### ISSUE TITLE
Invoking `super` should automatically add splat arguments

### ISSUE THREAD

**Issue by asterite** [manastech/crystal#1001]
```crystal
class Foo
  def foo(name)
    name
  end
end

class Bar < Foo
  def foo(*args)
    super
  end
end

x = Bar.new.foo "hello"
p x
```

In Ruby it prints `"hello"` while in Crystal it prints `{"hello"}`. That's because the `super` call is rewritten as `super(args)` instead of `super(*args)`.

**Comment by vendethiel** [comment]
Couldn't we do away with this behavior? I've always found it confusing in Ruby. What's wrong with being consistent and using `super(*args)`?

**Comment by asterite** [comment]
I think `super` without args nor parens is pretty common, you usually want to invoke the parent method with exactly the same arguments that you receive... more like "forward this call to my base definition". So I think this convenience is worth it, but it also wouldn't hurt that much to remove this feature. But I wouldn't remove it just because we found a small bug in it (which is now fixed).

**Comment by vendethiel** [comment]
No, there is nothing related to the bug. I never liked this feature much, always preferring the explicit solution. I can hear it has its uses, though. It just seems to me like that's the kind of implicit-ish things in Ruby that Crystal does explicit.
