### ISSUE TITLE
Underscore variable (with name "_")

### ISSUE THREAD

**Issue by sergey-kucher** [manastech/crystal#1010]
While In Ruby such operation allowed, in Crystal it's produces error:
```crystal
_ = 1 # Syntax error in eval:1: unexpected token: UNDERSCORE
```
http://play.crystal-lang.org/#/r/7jb

It's useful when we have to assign variable, but don't want to use it. Like here:
```
char, _ = ['a', 1]
puts char
```

So maybe will be better to make special case instead of Ruby behavior. For example:

1. Allow to assign:  `_ = 1 # no error`
2. Make `_` to always returns nil: `puts _.inspect # => nil`

**Comment by kirbyfan64** [comment]
+1 for point 1, -1 for point 2. I *hate* Go, but I really like it's treatment of the underscore as a magic variable.

I just can't think of any real-world uses of point 2, though.

**Comment by sergey-kucher** [comment]
About point 2, maybe we can find useful application for underscore only for reading.

**Comment by ysbaddaden** [comment]
Same here. I really like the `_` to discard variables in method definitions and multiple assignments (as in Ruby or Erlang). But it shouldn't be allowed as a variavle name.

**Comment by ysbaddaden** [comment]
No need because it would alias `nil`, and one could believe that `_` is actually a variable, with a value, which its not.

**Comment by waterlink** [comment]
+1 for having `_`. This will allow to employ some Nice FP techiques in more
canonical way. About 2nd point, how about to just disallow reading from
this Variable?

**Comment by davydovanton** [comment]
+1 for first case. It's really necessary. Also I can produce other example. Underscore variable very useful for not used variables in block:

``` crystal
{ user1: "Joe", user2: "Den" }.each { |_, name| p name }
```

**Comment by ozra** [comment]
+1 as a "discard place holder", not a variable name.

**Comment by waterlink** [comment]
Black hole variable, whatever you put there you can never get back :-D

**Comment by bcardiff** [comment]
While parsing, each _ could be replaced by a fresh variable name. That way 1 is achieved without allowing _ to be read. After optimizations, write only vars might be dropped. And probably 2 will fail due to uninitialized local variable. 




I think this is the simpler approach to implement this and will allow _ on any place a var can appear. 




+1

**Comment by waterlink** [comment]
+1 to Brian's idea

**Comment by asterite** [comment]
Yes, the `_` should work and shouldn't be difficult to implement (without hacks).
