### ISSUE TITLE
support csv header ?

### ISSUE THREAD

**Issue by 404pnf** [manastech/crystal#1016]
Feature request: support csv header?

Feature request: add a method that mimics the ruby CSV.table behavior?

So I can do without these code

``` crystal

  s =  File.read "some.csv"
  csv = CSV.parse s
  header = csv[0]
  data = csv[1..csv.length]
  row_with_header = data.map { |e| header.zip e }
  puts row_with_header

````

**Comment by jhass** [comment]
Here's the code: https://github.com/manastech/crystal/blob/master/src/csv/csv.cr And here are the specs: https://github.com/manastech/crystal/tree/master/spec/std/csv

Why don't you see if you can throw up a couple PRs?

**Comment by 404pnf** [comment]
Initially I tried to port the ruby https://github.com/ruby/ruby/blob/trunk/lib/csv.rb , but decided to learn more about ]crystal and the community conduct.

Thanks for the encouragement!  I am still learning Crystal.  But I will make it a goal.

**Comment by hamin** [comment]
@jhass @404pnf I've made a pull request to add header support. Specs and docs and all. The pull request is backwards compatible to the existing api. All of the previous tests still pass :)
