### ISSUE TITLE
undefined method 'raise'

### ISSUE THREAD

**Issue by sardaukar** [manastech/crystal#1024]
Minimum code to replicate it:

<pre lang='crystal'>
class A
  def blow_up
    elem = B.new
    raise elem.thingy
  end

  class B
    def thingy
    end
  end
end

A.new.blow_up
</pre>

**Comment by bcardiff** [comment]
Slightly smaller. But this is the minimum example I reached.

```crystal
def thingy
end

class A
  def blow_up
    raise thingy
  end
end

A.new.blow_up
```

**Comment by asterite** [comment]
Further reduced to:

```crystal
def foo(ex : String)
end

class A
  def blow_up
    foo 1
  end
end

A.new.blow_up
```

("works" with `--prelude=empty`)

Gives incorrect error, should be easy to fix :-)

**Comment by sardaukar** [comment]
Is this the same issue? http://carc.in/#/r/9zk

If so, mind pointing me to where I can fix it? Really annoyed by it! :D

**Comment by asterite** [comment]
@sardaukar Don't worry, it was easy to fix, I just forgot about this bug :-)

**Comment by sardaukar** [comment]
Thanks!
