### ISSUE TITLE
else in method definition superfluous and confusing.  please remove

### ISSUE THREAD

**Issue by technorama** [manastech/crystal#1026]
Else breaks the body of a method in to 2 parts without a defined purpose and makes it harder to reason about control flow by dividing the body of a method in to the body and an else block generally at the bottom of the method.  Anything within the else block can be put in the body of the method.  The addition of raise/rescue does not appear to effect the outcome.

The 2 functions below are identical.   Else does not appear to add any value.
```
def foo
  a
  b
end
```

```
def foo
  a
else
  b
end
```

Else does not appear to add any value but does raise questions about the order of operations.
```
# Under what conditions do [a, b, c, d] run?  What is the order and most importantly why?
def foo
  a # first
rescue
 # does this rescue from a AND d?  why or why not? 
  b # ?
ensure
  c # probably last
else
  # does this run before or after ensure?  why or why not?
  # is the return value from the body of the method or else statement?  why or why not?
  d # 2nd?
end
```

```
# This method is identical to the one above and appears to run in the same order
# while being easier to visually inspect and reason about why the order is the way
# it is.
def foo
  a # first
  d # second and return value
rescue
  b # only when exception thrown within a or d
ensure
  c # last
end
```

If there is a use case I've missed the documentation should probably be updated with an explanation of how to use else correctly.

**Comment by kirbyfan64** [comment]
`else` does add value. It runs if no error occurred. It's just like Python.

**Comment by technorama** [comment]
The body of a method runs if no error occurs.  Else looks like a split body.  What is the purpose?

**Comment by asterite** [comment]
@technorama The code you are complaining about doesn't compile: http://play.crystal-lang.org/#/r/7xi

**Comment by ysbaddaden** [comment]
This is merely syntax sugar for `def; begin; ... else; ... end; end` to skip some useless indentation and visual noise (hey, Ruby syntax).

The else block will always run, unless an exception has been raised in the main block, in which case it won't. That being said, there usually are no else blocks without a rescue/ensure block.

**Comment by technorama** [comment]
Rescue was left out to give a simplified example of why both methods are identical.  Add a rescue statement to compile it.  The result of either method is the same but the syntax is different.  Why?   What purpose does the additional syntax serve?

**Comment by technorama** [comment]
@ysbaddaden begin/else is also not useful.  Any code in the else section can be put in the body of the method.  That's probably why it's almost never used in ruby code.

See the example below.  Both methods function identically regardless of missing rescue's.

```
begin
  a
  b
end
```

```
begin
  a
else
  b
end
```

**Comment by dziulius** [comment]
I don't really understand what is the problem?

```crystal
def m1
  puts 'a'
rescue
  puts 'b'
else
  puts 'c'
end

def m2
  puts 'a'
  raise 'ERROR'
rescue
  puts 'b'
else
  puts 'c'
end
```

`m1` will print `a` and `c`, while `m2` will print `a` and `b`.

**Comment by alex-fedorov** [comment]
@technorama they are not identical if `a` and/or `b` can raise an error. It is kind of useless without `rescue`, but when rescue is in place: `a` can safely raise error and in this case `b` will not be executed; `b` can't raise error (or if it does it will not be rescued and will be propagated).

Given `a` and `b` can raise error: When these two are the same:

```crystal
def x
  a
else
  b
end

def y
  a
  b
end
```

These are not:

```crystal
def x
  a  # if it fails, it is rescued
rescue
  // stuff
else
  b  # if it fails it is propagated (not rescued)
end

def y
  a  # if it fails it is rescued
  b  # rescued too
rescue
  // stuff
end
```

**Comment by asterite** [comment]
@technorama Can I close this? An `else` without a `rescue` is a syntax error. If there is at least one `rescue` then `else` can't be easily coded without that language construct.

**Comment by asterite** [comment]
I'll close this, `else` in exception handlers is useful (though honestly I never used it, so unless someone has a good use case for it we might consider removing it)

**Comment by strcmp** [comment]
what @waterlink said made the most sense to me, if there is an error in method call to 'a' which you want to rescue but you want errors to propagate from 'b' (not risk being rescued) then else seems like it fits the use case very well but the difference is subtle and i don't think i've ever had a need for that usecase to be accommodated.
