### ISSUE TITLE
Escaped macros and 'end'

### ISSUE THREAD

**Issue by Exilor** [manastech/crystal#1029]
In the code below some ```end```s have had to be replaced by ```{{"end".id}}``` or it wouldn't compile. In comments there's the error that the compiler gives if you switch the latter for the former.

```crystal
macro open_record(name)
  class {{name.id}}
    macro method_missing(name, args, block)
      \{% if name.split("").last == "=" %}
        @\{{name.id}} \{{args.argify}}
      \{% else %}
        @\{{name.id}}
      \{% end %}
    {{"end".id}} # expecting token 'EOF', not '%}'

    def to_h
      \{% if @type.instance_vars.any? { |var| var } %}
        {
        \{% for ivar in @type.instance_vars %}
          \{{ivar}}: @\{{ivar}},
        \{% end %}
        }
      \{% end %}
    {{"end".id}} # expecting token 'EOF', not 'end'
  {{"end".id}} # expecting token 'EOF', not 'end'
end
```
It appears that the more methods with escaped macros I add to the main macro, the more ```end```s need to be changed to ```{{"end".id}}```: If I add another method with an escaped macro it won't compile no matter how many ```end```s I change. And if I remove ```#to_h```, the ```end``` of the class doesn't need to be ```{{"end".id}}```.

This started to happen with the release of 0.7.1.

**Comment by asterite** [comment]
I think these are just macro parsing bugs. They will eventually be fixed.

As a side note, I wouldn't advice having macros inside macros. In your case you could use a module:

```crystal
module OpenRecord
  macro method_missing(name, args, block)
    {% if name.split("").last == "=" %}
      @{{name.id}} {{args.argify}}
    {% else %}
      @{{name.id}}
    {% end %}
  end

  def to_h
    {% if @type.instance_vars.any? { |var| var } %}
      {
        {% for ivar in @type.instance_vars %}
          {{ivar}}: @{{ivar}},
        {% end %}
      }
    {% end %}
  end
end

class Foo
  include OpenRecord
end

foo = Foo.new
foo.x = 1
foo.y = 2
p foo.to_h
```

However, I don't think that `to_h` method is a good choice. Why do you need that? Ruby tends to use arrays and hashes for everything, in Crystal that usually doesn't work because of the static types.

**Comment by asterite** [comment]
Ah, and note that that `to_h` method is broken, it should be a `macro def` but there's no way to know the return type. That's why I'm suggesting not having code like that.

**Comment by Exilor** [comment]
It's sample code to illustrate the bug. Of course it won't win any contests :stuck_out_tongue_closed_eyes:

**Comment by asterite** [comment]
@Exilor This if fixed in HEAD now, you can try it. The above snippet works with regular "end" now (it stops working with the hacky "end"). If you find more of these, please report them too :-)

**Comment by Exilor** [comment]
Nice :D
