### ISSUE TITLE
parentheses less method call with tuple in macro raises Syntax error

### ISSUE THREAD

**Issue by yui-knk** [manastech/crystal#1051]
```
{% p {"a", 'e', 1} %}

#=> Syntax error in ./crystal/three.cr:8: unexpected token: }
#=> {% p {"a", 'e', 1} %}
```

```
{% p({"a", 'e', 1}) %}
#=> {"a", 'e', 1} is printed
```

**Comment by jhass** [comment]
Outside a macro too ;)

This is because Crystal parses `method_call {` as passing a block to the method call, so it's expecting a block and not a tuple or a hash.

**Comment by asterite** [comment]
Yes, it's similar to Ruby:

```
$ irb
p irb(main):001:0> p {foo: bar}
SyntaxError: (irb):1: syntax error, unexpected ':', expecting '}'
p {foo: bar}
       ^
```

**Comment by jhass** [comment]
I think this comes up more often in Crystal than in Ruby because Ruby allows you to leave up the `{` for the hash literal if it's the last argument to a method. And thinking about it, it might very well the reason Ruby does allow that in the first place.
