### ISSUE TITLE
"if var" doesn't work with instance variables

### ISSUE THREAD

**Issue by hangyas** [manastech/crystal#1052]
```crystal
class Foo
  def initialize
    @a = 2 as Int32? 
    if @a
      p typeof(@a)
    else
      p typeof(@a)
    end
  end
end

Foo.new
```
will output `(Nil | Int32)` instead of `(Int32)`

**Comment by jhass** [comment]
Yes, that's intentional, see #477.

Any suggestions as to how we can better document this?

**Comment by hangyas** [comment]
At the end of the "Nilable instance variables" section the [docs](http://crystal-lang.org/docs/syntax_and_semantics/instance_variables_type_inference.html
) says:
>To deal with Nil, and generally with union types, you have several options: use an if var, if var.is_a?, case and is_a?.

That's why I tought it should work. Maybe it could mentoin that for this you have to use a local variable.

**Comment by will** [comment]
I wonder if the compiler could take care of rewriting
``` crystal
if @foo
  puts @foo
end
```

to 

``` crystal
if _uniquehiddenname = @foo
  puts _uniquehiddenname
end
```

I can't think of cases where you'd want the potential for the race.

**Comment by jhass** [comment]
I'm not sure, I think it makes the code a lot harder to judge. That `if value_expression` is actually `if assignment` is entirely non-obvious.

**Comment by asterite** [comment]
@will In fact in the early days this was working like what you suggest. But imagine you have:

```crystal
# @foo :: String | Nil 
if @foo
  some_method
  puts @foo.length
end
```

In that case `@foo` can't be assumed to be non-nil, maybe `some_method` changed it (and this isn't easy to analyse). So the rules for understanding when `@foo` is nil or not are more complex for the programmer. I think here it's better to be explicit.

**Comment by bcardiff** [comment]
Maybe when an `undefined method ... for Nil` compile error is found over an instance variable, and the instance variable was used in a `if @ivar` we can just tell this story to the user. The case will appear once and again. But doing auto code transformation is not a good way to go IMO.

I think that doint this for `if @ivar; @ivar.method; end` is enough, although the same case apply to other type unions.

**Comment by will** [comment]
Good points, thanks

**Comment by daviswahl** [comment]
I think being able to do multiple assignments within conditionals (making each assignment available to the next condition) would help a lot with this. eg:

```cr
if foo = @foo && bar = foo.bar && baz = bar.baz
   baz.dance
end
```
Absolutely no idea how reasonable this would be.

**Comment by asterite** [comment]
@daviswahl It works if you use parenthesis, otherwise there's ambiguity:

```crystal
if (foo = @foo) && (bar = foo.bar) && (baz = bar.baz)
   baz.dance
end
```

And in that particular case you can use the [try method](http://crystal-lang.org/api/Object.html#try%28%26block%29-instance-method):

```crystal
@foo.try &.bar.try &.baz
```

**Comment by daviswahl** [comment]
@asterite 

Oh hey, that's great. Totally solves my issues.

**Comment by asterite** [comment]
@daviswahl Great. I'll close this then.
