### ISSUE TITLE
HTTP:WebSocket::PacketInfo raises error on type HTTP:WebSocket::OPCODE_CLOSE

### ISSUE THREAD

**Issue by fkchang** [manastech/crystal#1054]
if a connected javascript client calls ```websocket.close()``` you will get 'Invalid packet type' error raised. The case statement in PacketInfo#initialize does not handle this opcode.  I think this needs to handle this, and changes propagate else where.  My guess on what needs to happen

* handle this opcode on PacketInfo
* update WebSocketHandler to now handle the close case in WebSocketSession and send back close frame to the client
* add a close method to TCPSocket, so that it can be closed

**Comment by asterite** [comment]
Yes, WebSocket is only partially implemented

**Comment by asterite** [comment]
This is working now thanks to #1264
