### ISSUE TITLE
JSON mapping, mixed type array

### ISSUE THREAD

**Issue by rpierreye** [manastech/crystal#1061]
created mapping to parse JSON. This works fine. http://play.crystal-lang.org/#/r/930
```ruby
require "json"

class Response
  json_mapping({
    datasets: Array(Hash(String, Array(Float32)))
   })
end

response = Response.from_json("{\"datasets\":[{\"series1\":[1.4,2.1,2.1]}]}")
a = response
puts a.datasets #=> [{"series1" => [1.4, 2.1, 2.1]}]
```
However, when I have a mixed type array, it doesn't work... even when I specify the array is mixed type. http://play.crystal-lang.org/#/r/931

```ruby
require "json"

class Response
  json_mapping({
    datasets: Array(Hash(String, Array(Float32 | Nil)))
   })
end

response = Response.from_json("{\"datasets\":[{\"series1\":[1.4,2.1,2.1, null]}]}")
a = response
puts a.datasets #=> expected null but was float at 1:29 (JSON::ParseException)
```

**Comment by asterite** [comment]
Not a bug, it works because of some rule in the language which seems not to be pretty nice (invoking a method on a union type).

What JSON are you trying to parse?

**Comment by rpierreye** [comment]
I am simply trying to parse something similar to sample data in the example.  
```ruby
"{\"datasets\":[{\"series1\":[1.4,2.1,2.1, null]}]}"
```
do you want me to provide something else, or is this sufficient?

**Comment by asterite** [comment]
I'm not exactly sure how we can allow union types for JSON mapping. Imagine you can have unions like `Int32 | Nil` or `Float64 | Nil` or `String | Float64` or `String | Float64 | Nil`. In the case of a union the pull parser would have to ask if any if the types can parse the next token. That might work, but it will stop working if you try to do for example `MyObj1 | MyObj2` where both are objects but there's some rule in the JSON object (`{...}`) itself to know which one to instantiate.

This is definitely something we have to think more to get it right.

For now I can offer this solution:

```crystal
http://carc.in/#/r/93b
```

**Comment by rpierreye** [comment]
Thanks, this should help me keep going...
