### ISSUE TITLE
"read before definition" when argument used as default also has a default

### ISSUE THREAD

**Issue by wconrad** [manastech/crystal#1062]
Having an argument use a previous argument as a default works as expected:

```
def foo(a, b = a)
  p [a, b]
end

foo(1)    # => [1, 1]
```

But if the previous argument itself has a default:

```
def bar(a, b = a, c = b)
end

bar(1)
```

then a "read before definition" error results:

```
Error in ./foo.cr:11: instantiating 'bar(Int32)'

bar(1)
^~~

in ./foo.cr:7: read before definition of 'b'

def bar(a, b = a, c = b)
```

Version: `Crystal 0.7.4 [42efdbf] (Wed Jun 24 01:08:36 UTC 2015)`

**Comment by asterite** [comment]
@wconrad Good catch! The way default arguments were handled didn't take into account your case.
