### ISSUE TITLE
html escape code in docs

### ISSUE THREAD

**Issue by bcardiff** [manastech/crystal#1067]
We need to html escape the comments probably.

![screen shot 2015-07-31 at 11 35 24 am](https://cloud.githubusercontent.com/assets/459923/9009557/74fdae52-3778-11e5-96d5-8edef4a3440c.png)

![screen shot 2015-07-31 at 11 36 23 am](https://cloud.githubusercontent.com/assets/459923/9009559/76cff3ca-3778-11e5-8eeb-56015c10a854.png)

But ~~everything~~ crystal is awesome

**Comment by davydovanton** [comment]
I'll fix this

**Comment by asterite** [comment]
@davydovanton Great! I think the issue might be [here](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/tools/doc/markdown_doc_renderer.cr). Unfortunately that class has no specs, but you could try writing some for it.

**Comment by davydovanton** [comment]
@asterite I escape html tags in doc, but your solution is better

**Comment by asterite** [comment]
@davydovanton Yes, I've been writing `&quot;` manually in some places but I should fix it in the html renderer :-)

**Comment by bcardiff** [comment]
@davydovanton you will/want try to implement @asterite 's proposal?

**Comment by davydovanton** [comment]
@bcardiff yes
