### ISSUE TITLE
Some String#split inconsistencies (vs ruby)

### ISSUE THREAD

**Issue by dbackeus** [manastech/crystal#1070]
In Ruby:
```ruby
"=".split("=") => []
"=".split("=", 2) => ["", ""]
```

In Crystal
```crystal
"=".split("=") => [""]
"=".split("=", 2) => [""]
```

Since the methods are not documented I'm not sure what you're going for here but if you haven't considered this already I guess principle of least surprise would be to stick to the Ruby spec.

**Comment by asterite** [comment]
I think we should define once and for all the behaviour of split, regardless of how Ruby does it. Based on the snippet above, I found Ruby is being inconsistent: how come I split without a limit and I get an empty array, but when I apply a limit I get **more** results? At least in Crystal it always gives the same (maybe incorrect) result.

The logic Ruby seems to use (I checked the [source code](https://github.com/ruby/ruby/blob/trunk/string.c#L6725-L6730)) is: if there's no limit specified, remove empty results. But if there's a limit, return the result as is.

So:

```
irb(main):007:0> ",,,,".split(",")
=> []
irb(main):008:0> ",,,,".split(",", 1)
=> [",,,,"]
irb(main):009:0> ",,,,".split(",", 2)
=> ["", ",,,"]
irb(main):010:0> ",,,,".split(",", 3)
=> ["", "", ",,"]
irb(main):011:0> ",,,,".split(",", 4)
=> ["", "", "", ","]
irb(main):012:0> ",,,,".split(",", 5)
=> ["", "", "", "", ""]
irb(main):013:0> ",,,,".split(",", 6)
=> ["", "", "", "", ""]
```

Maybe `",,,,".split(",")` should give `["", "", "", "", ""]` so it's consistent with "unlimited". But removing empty results might be useful so then if you iterate these you don't have to check that. So maybe we can add another option to split that's "ignore_empty" or something like that. Or we never ignore empty and are consistent.

**Comment by dbackeus** [comment]
I can't think of a time I have wanted to get empty strings back from a split so I'd definitely be for `",".split(",") => []` being the default.

The limit in Ruby indeed adds some inconsistency. Gut feeling is that that it's by design. Optimised for programmer happiness rather than stringency. Maybe even `"=".split("=", 2) => ["", ""]` which is indeed fairly odd... it apparently has a use case in Rack::Utils: https://github.com/rack/rack/blob/master/lib/rack/query_parser.rb#L39

But agree good api design could make everything clearer. The Ruby docs clarifies the behaviour of empty matches with and without limit parameter (except for the weird nil case). But `ignore_empty` would make things very clear cut indeed.

**Comment by asterite** [comment]
I think we should stop removing black results from split. That way we can consistent, expected results (but not the same results as in Ruby, but maybe Ruby is wrong here). Or we can add a named argument to specify if we want blank entries to be removed.

**Comment by technorama** [comment]
or use str.split().compact to remove empty elements

**Comment by dbackeus** [comment]
Yeah, worth noting that chaining on `compact` is probably less typing than sending an extra argument to `split`.

**Comment by asterite** [comment]
But compact eliminates nils, not empty strings. And an extra argument is more efficient, because you don't create an intermediate array.

**Comment by asterite** [comment]
I have a patch that "fixes" this by keeping all results from a split. For example:

```crystal
assert { "a=b".split('=').should eq(["a", "b"]) }
assert { "a=".split('=').should eq(["a", ""]) }
assert { "=b".split('=').should eq(["", "b"]) }
```

But also:

```crystal
assert { "hello world".split(/\b/).should eq(["hello", " ", "world", ""]) }
assert { "abc".split(//).should eq(["a", "b", "c", ""]) }
assert { "hello".split(/\w+/).should eq(["", ""]) }
assert { "foo".split(/o/).should eq(["f", "", ""]) }
```

I think this is consistent, although it might be annoying. What Ruby does is to [remove the last results if they are empty and no limit was specified](https://github.com/ruby/ruby/blob/trunk/string.c#L6699-L6704). Hm, it's even in the docs, it says "If the limit parameter is omitted, trailing null fields are suppressed".

So I'm not sure what would be the best thing to do:

1. Retain Ruby's semantic, but fix the case where a limit is supplied (and retain trailing "null fields" in that case)
2. Drop Ruby's semantic and maybe provide a flag to drop trailing null fields.

What do you think?

**Comment by jhass** [comment]
I vote for the flag, consistency wins over "guessing the right thing".

**Comment by technorama** [comment]
+1 for consistency with a flag.  or consistency with .split.reject &.empty?

**Comment by dbackeus** [comment]
Flag sounds good but having the default be to drop the empty strings since in my experience that's what I have wanted when splitting 99% of the time.

**Comment by technorama** [comment]
Keeping the empty string is what I need 99% of the time.  With ruby it didn't matter much but with crystal you may get Nil type errors when trying to access members of the array.

**Comment by dbackeus** [comment]
@technorama what do you mean? In Ruby you neither get empty strings nor nil when doing split.

**Comment by asterite** [comment]
@dbackeus It's because you can also do this:

```crystal
key, value = string.split "="
```

Now, if string is "a=" and we don't return ["a", ""], then you will get an IndexError because the above is rewritten to:

```crystal
temp = string.split "="
key = temp[0]
value = temp[0]
```

That's why it's sane to return empty strings by default.

**Comment by dbackeus** [comment]
Point taken :+1:

**Comment by yxhuvud** [comment]
@dbackeus : "I can't think of a time I have wanted to get empty strings back from a split so I'd definitely be for ",".split(",") => [] being the default."

The obvious one being when you are parsing a csv file or some other similarly structured format with a fix amount of comma-separated fields.
