### ISSUE TITLE
Math on arrays

### ISSUE THREAD

**Issue by kerkomen** [manastech/crystal#1071]
It might be nice to have some element-wise array methods defined in standard lib, like that:

```
x = [1, 2, 3]
y = [4, 5, 6]
x * y  # => [4, 10, 18]
```

I'm not sure about possible conflicts, but it seems to me a good topic to discuss.

P. S. I suppose there's a way to come up with an appropriate syntax for that. The product sign in the example may be misleading, since `+` defined for Array is not element-wise.

**Comment by asterite** [comment]
I'm not sure, Array doesn't have any math-related operations, it's just a container. Plus `*` could mean "product" or "dot product". And there's the `+` method which complicates things.

**Comment by asterite** [comment]
As a side note, there's `Enumerable#sum`, which I'm not sure should belong there because it's also math-related. But then there's `Enumerable#min` and `Enumerable#max`, so it's hard to draw a line.

**Comment by yui-knk** [comment]
I think this issue is equivalent to
`call a block with elements of some enums which have same index. In this case 1 and 4, 2 and 5, 3 and 6.`

How about `zip` method with block arg ?

```crystal
x = [1, 2, 3]
y = [4, 5, 6]
acc = []

x.zip(y) {|a, b| acc << a*b}
acc
# => [4, 10, 18]
```

this example is ruby code, I feel we can return "array of result of block" in crystal world :)

**Comment by jhass** [comment]
Note also that we got `Matrix` on which doing the arithmetic rather than the set operations makes more sense than on `Array`.

**Comment by jhass** [comment]
I'd like to close this with pointing towards `Matrix`.

**Comment by asterite** [comment]
Yes, array is an element container, not a math object. (which makes me wonder if Enumerable#sum belongs there, but it's so convenient)

**Comment by Nakilon** [comment]
I agree that `Array#*`, `Array#+`, etc. that already known for Ruby should work the same.

Maybe OP was looking not exactly for Matrix, but for feature, that is called `Listable` in Wolfram Mathematica. Here is example of it ported to Ruby: https://github.com/Nakilon/mll/blob/master/spec/_spec.rb#L154

**Comment by kerkomen** [comment]
Thanks everyone for the discussion!
