### ISSUE TITLE
C structs can't have fields beginning with an uppercase letter

### ISSUE THREAD

**Issue by boghison** [manastech/crystal#1082]
expecting identifier 'end', not 'Filename'
Filename, Contents : Void*

**Comment by jhass** [comment]
I'd say this is a won't fix. Note that the names don't need to match "the real thing" you're mapping, only the sizes do.

**Comment by asterite** [comment]
Yes, it's as jhass says, names don't matter for proper C bindings to work. And because C structs look like regular Crystal objects, accessing their fields look like method calls:

```crystal
str = SomeLib::Struct.new
str.field = 1
str.field
```

Method names in Crystal can only begin with lowercase, so that's why there's that restriction.
