### ISSUE TITLE
make doc fails through: argument 'size' of 'LibC#malloc' must be UInt64, not UInt32

### ISSUE THREAD

**Issue by jalyna** [manastech/crystal#1083]
```
$ make doc
Error in ./src/gc/null.cr:1: argument 'size' of 'LibC#malloc' must be UInt64, not UInt32

fun __crystal_malloc(size : UInt32) : Void*
^

in ./src/gc/null.cr:2: argument 'size' of 'LibC#malloc' must be UInt64, not UInt32

  LibC.malloc(size)
              ^~~~

make: *** [doc] Error 1
```

I have this issue since today. I could temporary fix it by changing `docs/main.cr` line 9 to `require "../src/gc/boehm"` so to not include the null.cr that seems also not be included somewhere else. But I don't know if this is the real fix here :)

**Comment by asterite** [comment]
@jalyna Thanks! https://github.com/manastech/crystal/commit/69c625469efbd8e5d1086a4f1f32b0eae13fb9cd broke it, it's not used in any code but `make doc` just requires it and couldn't compile it.
