### ISSUE TITLE
C structs can't be compared

### ISSUE THREAD

**Issue by boghison** [manastech/crystal#1092]
Error in macro 'macro_53020640' /home/boghison/Projects/crystal/src/struct.cr:66, line 2:

    1.     
    2.       return false unless @kind == other.@kind
    3.     
    4.       return false unless @xdata == other.@xdata
    5.     
    6.       return false unless @data == other.@data
    7.     
    8.     true
    9.   

      return false unless @kind == other.@kind
                                   ^

    LibClang::CXCursor doesn't have an instance var named '@kind'

The struct does, in fact have that field. Possibly caused by `child != LibClang.clang_getNullCursor()`, where both structs are LibClang::CXCursor. Any idea why this is happening?

**Comment by asterite** [comment]
@boghison What's the code to reproduce this?

**Comment by boghison** [comment]
@asterite https://gist.github.com/boghison/a881d4ed87087651974f

**Comment by asterite** [comment]
@boghison Thanks. The issue seems to be more general, C structs can't be compared:

```crystal
lib LibFoo
  struct Foo
    x : Int32
  end
end

f1 = LibFoo::Foo.new
f2 = f1
f1 == f2
```

Also the error trace is incomplete.

**Comment by boghison** [comment]
@asterite Turns out code duplication can lead to finding bugs :D
