### ISSUE TITLE
Compiler crashing if instantiating Logger class in main 

### ISSUE THREAD

**Issue by daphee** [manastech/crystal#1106]
This crashes the compiler 

```crystal
require "logger"

f = File.open("log","w")
l = Logger.new(f)
f.close()
```
Interesting is also that only version 0.7.5 seems affected: http://play.crystal-lang.org/#/r/9pv
While on version 0.7.4 the code is working: http://play.crystal-lang.org/#/r/9pw

Also the logger worked properly for me when used in class variable: http://play.crystal-lang.org/#/r/9q0
Which correctly writes "...Test" in a file.

**Comment by asterite** [comment]
Thanks!!

I was able to reduce it to this:

```crystal
class Foo
  BAR = 1 || 2

  def foo
    BAR
  end
end

->(x : Foo) { x.foo }
```
