### ISSUE TITLE
Definition sequence of macro included vs inherited

### ISSUE THREAD

**Issue by luislavena** [manastech/crystal#1109]
Hello folks,

While attempting to define a small class-level DSL, found that `inherited` does not work as expected compared to `included`:

The following is an example using `included` macro:

```crystal
module Notes
  macro included
    @@list = [] of String
  end

  macro add(item)
    @@list << {{item}}
  end

  def list
    @@list
  end
end

class Todo
  include Notes

  add "pen"
  add "paper"
end

a = Todo.new
pp a.list
# => a.list = ["pen", "paper"]
```

This works great for this scenario, but attempt to produce the same for inherited result in compilation error:

```crystal
class Notes
  macro included
    @@list = [] of String
  end

  macro add(item)
    @@list << {{item}}
  end

  def list
    @@list
  end
end

class Todo < Notes
  add "pen"
  add "paper"
end

a = Todo.new
pp a.list
# undefined method '<<' for Nil
```

I think this might be related to #1098 but I'm not sure.

The reason to the usage of class variables and the macros on it is because each class defined by it are not mutable on the defined elements.

There is a need to inherit instead of inclusion as the class that does the DSL implementation needs to be fed into another system that is expecting a particular class (example, inherit from `HTTP::Handler` to be used as part of the middleware stack of `HTTP::Server`).

Is this a bug or, like I'm thinking, using it wrong? :smiley: 

Thank you.

**Comment by asterite** [comment]
@luislavena You are totally right. This was a recurring issue so I decided to fix it once and for all. Behaviour should be similar to Ruby in this case.

If you try your second snippet with the new compiler (and use `inherited` instead of `included` :wink:) it should work now.

**Comment by luislavena** [comment]
Thank you @asterite, facepalm for the copy&paste error, but I can confirm that a fresh build does work!

```
$ uname -a
Darwin Nostromo.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64

$ bin/crystal --version
Using compiled compiler at .build/crystal
Crystal 0.7.5 [6c42520] (Thu Aug  6 19:31:01 UTC 2015)

$ git show 6c42520
commit 6c4252056c1f484efdd97434e4d764f67a6c2f14
Author: Brian J. Cardiff <bcardiff@manas.com.ar>
Date:   Thu Aug 6 16:28:11 2015 -0300

    add gh-pages branch to travis whitelist

$ bin/crystal 12.cr
Using compiled compiler at .build/crystal
a.list = ["pen", "paper"]
```

:heart: :heart: :heart:
