### ISSUE TITLE
Specifying block arguments in a Hash with lambdas for values

### ISSUE THREAD

**Issue by sardaukar** [manastech/crystal#1112]
Is there a way to do this that I'm not seeing?

```crystal
cli_filter = {
  "-f --file" => ->{ |e| false },
  "-i --interactive" => ->{ true },
  "-h --help" => ->{ :meh }
}
```

I always get "unterminated hash literal". But if I remove the block argument, it parses:

```crystal
cli_filter = {
  "-f --file" => ->{ false },
  "-i --interactive" => ->{ true },
  "-h --help" => ->{ :meh }
}
```

**Comment by asterite** [comment]
Seems like a parser bug.

**Comment by asterite** [comment]
Oh, it should give an error in the `|`, but your snippet should be written like this:

```crystal
cli_filter = {
  "-f --file" => ->(e : DontKnowWhatTypeYouExpectHere){ false },
  "-i --interactive" => ->{ true },
  "-h --help" => ->{ :meh }
}
```

That's because anonymous functions need a type specified for their arguments. I'll still leave this open because the error message is wrong.

**Comment by asterite** [comment]
And note that in Ruby this:

```ruby
->{ |x| x }
```

is also a syntax error, it should be written like this:

```ruby
->(x) { x }
```

**Comment by sardaukar** [comment]
Yeah, I thought it was weird, too. Saw it on clik's readme https://github.com/trans/clik
