### ISSUE TITLE
Parent process never receives SIGCHLD from child processes

### ISSUE THREAD

**Issue by ysbaddaden** [manastech/crystal#1114]
I'm trying to trap the SIGCHLD signal to clean up after they exit (and start fresh ones), but the parent process is either never signaled or the block is never invoked (Ubuntu Trusty 64bits). Killing the parent process manually with `kill -CHLD <pid>` will print the `Got SIGCHLD` message, thought.

```crystal
Signal::CHLD.trap do |value|
  puts "Got SIGCHLD"
end

pid = fork {}
loop { sleep 1 }
```

**Comment by waj** [comment]
@ysbaddaden The signal numbers were copied from OSX but in Linux the SIGCHLD have a different value. It should work now.

**Comment by ysbaddaden** [comment]
Thx! I should have thought about the values.
