### ISSUE TITLE
Begin/while body not read before condition?

### ISSUE THREAD

**Issue by sardaukar** [manastech/crystal#1118]
```crystal
def get_value
  42
end

begin
  a = get_value
end while a != 42
```

I get `Error in line 7: read before definition of 'a'`. Is this a bug?

**Comment by asterite** [comment]
Yes, but we'll probably remove the trailing `while`. I'll mark it as a bug for now.

**Comment by asterite** [comment]
The discussion is here: https://github.com/manastech/crystal/issues/549
