### ISSUE TITLE
Syntax sugar for hash arguments (rocket literal)

### ISSUE THREAD

**Issue by sergey-kucher** [manastech/crystal#1127]
While using named arguments so neaty (`obj.meth a: 1, b: 2`), using of hash arguments is not really nice.

Examples:
```crystal
Person.where({ "number_of_dependents" => 0 })

Person.create({ "first_name"           => "John",
                "last_name"            => "Smith",
                "number_of_dependents" => 3 })
# ...
collection.insert({"name" => "James Bond", "age" => 37})
```

So I think it's obvious improvement to omit curly brackets.

```crystal
class Obj
  def meth(first, second : Hash(Symbol, Int) , third, fourth : Hash(String, Int), fifth)
  end
end

# Expression
Obj.new.meth "first", :a => 1, :b => 2, "third", "d" => 3, "e" => 4, "fifth"

# Can be the same as
Obj.new.meth "first", { :a => 1, :b => 2 }, "third", { "d" => 3, "e" => 4 }, "fifth"
```

Or reformatted
```crystal
Obj.new.meth "first", :a => 1,
                      :b => 2,
             "third", "d" => 3,
                      "e" => 4,
             "fifth"

# Instead of
Obj.new.meth "first", {:a => 1,
                       :b => 2},
             "third", {"d" => 3,
                       "e" => 4},
             "fifth"

```

It looks like good way to do thing.

**Comment by MakeNowJust** [comment]
:+1:

**Comment by jhass** [comment]
One thing to point out is that it allows to disambiguate passing a hash from passing a block without using parens in the method call:

```
foo { i_am_a_block }
foo i_am => a_hash
```

**Comment by strcmp** [comment]
I often try to use the same syntax you propose in Ruby, and have a "oh yeah" moment every time ruby tells me about a syntax error. I am :+1: for omission of {} in method calls when using rocket syntax. I wonder why ruby doesn't allow for it, maybe because of what @jhass said or something else.

**Comment by waterlink** [comment]
What if you had two hash args in row? Like this:

```crystal
def meth(first, second : Hash(Symbol, Int), third : Hash(Symbol, Int))
```

--
Best Regards,
Alexey Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

2015-08-09 0:59 GMT+03:00 strcmp <notifications@github.com>:

**Comment by sergey-kucher** [comment]
You just have to use curly brackets for this case

```crystal
Obj.new.meth "first", { :a => 1, :b => 2 }, { "c" => 3, "d" => 4 }
```
But I think such situations will be rare.

**Comment by asterite** [comment]
I think using hashes is pretty common in Ruby. For example they are used, a lot, for a kind of named arguments.

In Crystal this is not so common, so in my opinion it doesn't hurt to write the parentheses. Plus you have ambiguities in Ruby, like @waterlink says.

And there's the thing that `{foo: 1}` is a Hash of Symbol => Int32, but if you do:

```crystal
call foo: 1
```

that's a named argument, not a Hash, so users would wonder why it works with `=>` but not with `:`.

Finally, using a hash as an intermediate way to pass arguments to a method isn't good because of performance reasons. I'd prefer having this for the above examples:

```crystal
Person.where("number_of_dependents", 0).where(...)

person = Person.new
person.first_name = "John"
person.last_name = "Smith"
person.create
```

Specially for the second case, I can't see how you would type-check that hash with mixed types and keys that are not known at compile time.

**Comment by waterlink** [comment]
BTW, `Person.where(criteria("number_of_dependents") == 0)` is nicer. (Query Object Pattern)

**Comment by sergey-kucher** [comment]
I still can't see flexible way to deal with optional arguments without using hashes. I mean the following:

```crystal
def method1(options)
  options[:arg1] = do_something options[:arg1]
  method2 options
end

def method2(options) 
  ...
  method3 options
end
```

But I think performance reason is the good one. Also I like the idea of query object pattern. So probably I can close this.

Thanks for explanations, Ary!
