### ISSUE TITLE
Improve error message for non-existant postfix increment

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#1128]
Looking through carc.in submissions again, the error message could be better here: http://carc.in/#/r/a8o

**Comment by asterite** [comment]
Good idea, `++` and `--` are pretty common in other languages but are not available here and will always give some kind of error, so it's better if we give a nice error :-)

**Comment by stellarpower** [comment]
Is there a particular design reason why prefix- and postfix-incremenet aren't supported? I know they're missing from Ruby, but with a background in C++, I do miss them (hell, we don't have a name for the language without them!!). This is fixed now of course, and I like how readable a lot of Crystal's compiler errors are - it's a real gold standard at times in how to communicate what's wrong and what needs fixing. But, the fact there's an improved message presumably means that the compiler can parse ++/-- correctly, so I'm guessing it's not the case that it couldn't be parsed with Ruby-like syntax. Out of interest, is there a specific reason why they're not supported? I know it's just syntactic sugar* for `x += 1`, but again, I do miss them, they look prettier on the page to me.

* although in C++ they're different operators, so if we're talking non random-access iterators for example, we may not be able to provide a += or + operator; IDK if this would ever really surface in Crystal, but as a language that can be used for systems programming, I imagine it might be possible. I'd certainly argue that in C++ this condition means they're not just syntactic sugar in every case and are needed in the language.

**Comment by straight-shoota** [comment]
Please let's not revive zombie discussions. 
This probably fits best in the Crystal contrib section on the forums: https://forum.crystal-lang.org/c/crystal-contrib/6
