### ISSUE TITLE
Multiple assignments in single expression

### ISSUE THREAD

**Issue by sergey-kucher** [manastech/crystal#1135]
Example
```crystal
ary = %w(a b c d)
hash = {"b" => 2, "c" => 3}

while char = ary.pop? && num = hash[char]?
  puts num
end
```
Raises `Syntax error in eval:4: unexpected token: =` (http://carc.in/#/r/alf)

First problem is second assignment in expression (http://carc.in/#/r/aln)
```crystal
a = 1 && b = a + 1 # Syntax error in eval:1: unexpected token: =
```

Second problem is accessibility of `a` (http://carc.in/#/r/alo)
```crystal
a = 1 && a + 1 # Error in line 1: undefined local variable or method 'a'
```

**Comment by kirbyfan64** [comment]
I think Crystal is correct here. Operator precedence says that `=` binds less tightly than `&&`.

**Comment by jhass** [comment]
`&&` binds stronger than `=` does. That's intentional. http://carc.in/#/r/alu

**Comment by kirbyfan64** [comment]
So you're basically doing

```ruby
char = (ary.pop? && (num = hash[char]?))
```

**Comment by sergey-kucher** [comment]
Thanks
