### ISSUE TITLE
Improve error message for documentation build if gitbook-cli is not present

### ISSUE THREAD

**Issue by PragTob** [manastech/crystal#1139]
When you don't have `gitbook-cli` installed and run `rake build` the following happens:

```
tobi@airship ~/github/crystal $ rake build
Parsed haml layout files
Parsed haml include files
Parsed haml index files
Parsed main.sass
mv: cannot stat ‘./_gitbook/_book’: No such file or directory
```

That is rather unspecific, you can fix it by installing the `gitbook-cli` and I already took a stab at improving the docs there in #1137 - but I still think it might be nice if a helpful error message would pop up saying that gitbook-cli isn't installed or something :)

**Comment by asterite** [comment]
@PragTob Thanks, good idea!
