### ISSUE TITLE
Iterator: skip vs. drop

### ISSUE THREAD

**Issue by PragTob** [manastech/crystal#1144]
I noticed that Iterator is missing an implementation of `drop` - but it has an implementation of `skip` which does the same.

What do we want to use, `skip` or `drop`? `drop` is the ruby name and goes well with `take` I believe, but maybe crystal wants to move in another direction.

I'll happily do a PR once this is decided (plus other generalization things like raising if n is negative and that n is an Int).

edit: little side tracking question that doesn't deserve an own ticket, is it cool for me to alphabetically reorder methods (and implementations) in Iterator? I like things to be orderly :smile:

**Comment by asterite** [comment]
Yes, I also noticed these conflicting names, so thanks for bringing this up :-)

Maybe we should use `skip` for both, because neither of them really drop (remove) anything, they just skip a number of elements and then return the rest, either eagerly or lazily.

**Comment by PragTob** [comment]
Okay I'll do a rename to skip then in the coming days... or maybe now. :)

Do you want an alias to drop to be added for ruby compatibility or will crystal rather stay away from away from the flood of aliases in ruby?

**Comment by asterite** [comment]
Let's stay away from aliases :-)
