### ISSUE TITLE
What to expect of require within a module?

### ISSUE THREAD

**Issue by luislavena** [manastech/crystal#1146]
Hello folks,

Lurking around some code in some projects I found cases where `require` is being used inside a module/class.

In theory, that works similar to Ruby's `load` with an anonymous module:

```crystal
# b1.cr

module B
  VERSION = "1.0.0"
end
```

```crystal
# b2.cr

module B
  VERSION = "2.0.0"
end
```

```crystal
# main.cr

module V1
  require "./b1"
end

module V2
  require "./b2"
end

pp V1::B::VERSION
pp V2::B::VERSION
```

```
$ crystal main.cr

V1::B::VERSION = "1.0.0"
V2::B::VERSION = "2.0.0"
```

This is great if you want to sandbox two versions of the same library, however, it becomes a problem when you require a common file between the two that is relative to the location of those:

```crystal
# z.cr

module Z
  VERSION = "1.0.0"
end
```

```crystal
# b1.cr

require "./z"

module B
  VERSION = "1.0.0"
end

pp Z::VERSION
```

```crystal
# b2.cr

require "./z"

module B
  VERSION = "2.0.0"
end

pp Z::VERSION
```

```
$ crystal main.cr
Error in macro 'pp' /usr/local/Cellar/crystal-lang/0.7.5/src/macros.cr:16, line 2:

  1.
  2.     ::puts "#{ "Z::VERSION" } = #{ (Z::VERSION).inspect }"
  3.

    ::puts "#{ "Z::VERSION" } = #{ (Z::VERSION).inspect }"
                                    ^~~~~~~~~~

undefined constant Z::VERSION (did you mean 'B'?)
```

This is not triggered by the `require`, but actually by the attempt to access `Z`. Leaving just the require works.

Of course, if only version of B required `z`, it worked as expected **but** attempt to access `Z` from `main` results also in error (`undefined constant Z::VERSION`)

This problem goes away when `b1.cr` and `b2.cr` are on their own directories, each with their own copy of `z.cr`, and everything works:

```
$ crystal main.cr
Z::VERSION = "1.0.0-b1"
Z::VERSION = "1.0.0-b2"
V1::B::VERSION = "1.0.0"
V2::B::VERSION = "2.0.0"
```

This indicates the problem is not with require within a module/class, but actually a require of a shared file that has been already required.

Either way, since there is no documentation about this behavior, wanted to check first :smile: 

Looking forward your comments.

Thank you.

**Comment by jhass** [comment]
Related #140 #265

I still dislike that module level require and thought we decided to drop it but can't find the discussion right now.

**Comment by luislavena** [comment]
Thank you @jhass for the comment. Definitely this indicates there are still issues with `require`.

Removing that functionality will also break things like Amethyst, which is -- ahem -- *abusing* of this approach.

I was not able to find any prior conversation about this specific require (perhaps was on IRC?) so decided to create this issue.

Cheers.

**Comment by asterite** [comment]
I'd make `require` be an error unless used at the top-level. I have to talk about this with @waj, but I think he'll agree.

**Comment by asterite** [comment]
Given that `require` remembers the absolute path of the file, it doesn't make sense to use it inside types, defs or other expressions. This will lead to less confusion and a simpler language :-)
