### ISSUE TITLE
Iterator implementation duplication reloaded (rewind and getting next value)

### ISSUE THREAD

**Issue by PragTob** [manastech/crystal#1155]
#1132 was about the duplication in `rewind` and got rejected and I said if I found more I'd be back. I implemented something in Iterator and noticed more duplication - so I'm back! I want to discuss here if a refactoring to remove duplication is wanted and if so, how it should roughly look like so that I can go do a refactoring :)

As a summary:

* almost every `rewind` implementation does 

```
@iterator.rewind
self
```

* almost every `next` implementation has some form of:

```
value = @iter.next
return stop if value.is_a?(Stop)
```

Those are the same concepts being repeated imo. With the latter it also lead to a bug - `Skip` does not check for a stop value:

```
    def next
      while @n > 0
        @iter.next
        @n -= 1
      end
      @iter.next
    end
```

So I think a parent class/module like `WrappingIterator` ( copyright @asterite ) would be in place providing a `rewind` implementation and a method to get the next item from the internal iterator. I'm thinking of something like:

```
with_next_value do |value| 
  # ...
end
```

Which yields the next item if present or returns `stop` if not present. Some helper like that (likely to evolve once refactored/implemented). There may be other possibilities like template methods or something else that I haven't yet thought of.

Is a refactoring like this desired? 

Thanks for your time and patience!
Tobi

PS: It's perfectly fine with me if this is not desired for some reason. Just checking + I'm a bit of a refactoring junkie and perhaps a bit too adverse to duplication. :)

**Comment by PragTob** [comment]
Thanks! :) Cool use of macro - wouldn't have thought of that :)

**Comment by asterite** [comment]
:-)

I was originally going to reply to you that the `with_next_value { ... }` wouldn't work because you'd still have to return early, but then I remembered that macros allow you to do just that. I don't think many languages allow that.

**Comment by PragTob** [comment]
Yes macros are quite amazing and I'm not really used to them... but they are so powerful allowing to you to do things that would normally require you to resort to hardcore meta programming. Looks much nicer as well - excited to write nice macros myself :+1:
