### ISSUE TITLE
StringIO (and IO in general) needs a pos function

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#1163]
There is currently no way to query the current position in a ```StringIO```, open file, or any other form of IO. Ruby's IO classes have a ```pos``` member, and I have need of similar functionality in Crystal.

For that matter, there is also no way to seek within an IO object. That's kinda a big deal, in my opinion.

**Comment by stugol** [comment]
It needs an ```eof?``` function as well. How else am I supposed to know if I've reached the end of the stream!!!??

```undefined method 'eof?' for StringIO```

**Comment by waj** [comment]
@stugol it might happen sometimes you find missing pieces in the language and the libraries. That's because the language is very young and far from being complete. Please, feel free to fill the gaps and send PR anytime. We'll be more than happy to merge your contributions!

**Comment by stugol** [comment]
But I don't know how to do that!

**Comment by waj** [comment]
You can also know you're at the end of the stream when `read` returns `nil`. Actually in many cases is not possible to figure out the eof condition without trying to read first, so I'm not sure if we want to have an `eof?` method in IO.

**Comment by stugol** [comment]
Ruby's streams all have ```pos```, ```length``` and ```eof?``` methods. They're very useful.
Granted, there are cases where the length of a stream of data may be unknown, but usually that is not the case.

In any event, the length of a ```StreamIO``` and a ```FileDescriptorIO``` *is* known, and my code will be a lot easier to write if I don't have to be psychic!

**Comment by technorama** [comment]
FileDescriptorIO has seek(), there is no need to rewind.
File could use a pos method but we would need to track it manually.  Most other forms of IO (other than StringIO) are streams and can't support pos.

eof? support in ruby comes from stdio in c.  The feof() function works by setting a flag when a read fails.  You can do the same thing when read returns nil in crystal.

I don't see a length provided in IO.  Maybe you are thinking of file.stat.size?  It works in crystal also.

**Comment by asterite** [comment]
https://github.com/manastech/crystal/commit/5207425cf807a92c9fc98868ef2ffc95e23fe865 and https://github.com/manastech/crystal/commit/8f9a5b206bc2d2395e57d60876deaa8520553898 give `StringIO` and `File` `pos` and `pos=` methods. For others IOs (like sockets and pipes) those don't make sense.
