### ISSUE TITLE
Will there be a REPL?

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#1165]
Will there ever be a REPL for Crystal? And if so, how soon?

**Comment by bcardiff** [comment]
There is desire, yes, but quoting @asterite from https://github.com/manastech/crystal/issues/681#issuecomment-106538018 "I think it's possible, just hard."

I will close this as duplicate. Feel free to follow the topic on the other issue or in the mailing list.

Regarding when, it is no in the short/mid goals as in https://github.com/manastech/crystal/wiki/Roadmap or https://salt.bountysource.com/teams/crystal-lang
