### ISSUE TITLE
No enumerable.reduce() ?

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#1167]
In Ruby, ```reduce``` is an alias for ```map```, and - notably! - can accept an accumulator argument, whereupon the behaviour of the method is altered. For example:
```
mask = range.reduce(0) { |acc, n| acc + (1 << n) }
```

Why does Crystal support only the no-args version of ```map```?

Arguably, ```reduce``` is a better name when the method takes an accumulator value; so if you don't want to alias it, why not just implement a separate ```reduce``` method that works like the above?

**Comment by bcardiff** [comment]
In ruby `reduce` is equivalent for `inject` (aka `fold`). http://ruby-doc.org/core-2.1.0/Enumerable.html#method-i-reduce

In crystal we use `inject` and try to avoid aliases. The working code of you example can be found at http://play.crystal-lang.org/#/r/b5h

**Comment by stugol** [comment]
Damn, I could'a *sworn* it was map that was aliased with reduce. Seriously, I'm kinda nonplussed to find out that I was mistaken ;)

**Comment by bcardiff** [comment]
Hopefully in this 15 min you don't stop playing around the bits :-).

Happy coding!

**Comment by kostya** [comment]
reduce seems better name instead of inject. also map().reduce readed nicer ...

**Comment by asterite** [comment]
Yes, `reduce` is also known from functional languages, but it seems `inject` is used more in Ruby. But I wouldn't mind keeping `reduce` instead of `inject`.

**Comment by bcardiff** [comment]
Well, I would prefer `map`/`fold`/`filter` since Haskell is wired in that part of my brain. But I know it's a lost battle :-P. 

Since C# `select`/`aggregate`/`where` and later Ruby using `map`/`inject`|`reduce`/`select` my brain keeps going to Haskell and saying ... which was the `map`, the `fold`, and the `filter`? Yeah, specially because of the `select` ambiguity... :-(

**Comment by mverzilli** [comment]
+1 for map, fold and filter. The underlying ops come from the functional world and that's the most widely used nomenclature. I also struggle a lot with Ruby's inject and select. C#'s names are heavily influenced by SQL. If I was to write a SQL DSL on Crystal I'd probably borrow from SQL, but not in the general case.

**Comment by stugol** [comment]
+1 for ```reduce``` instead of ```inject```. It just makes more sense. You're reducing a sequence of values to some single answer; whereas ```inject``` is just a meaningless verb.

**Comment by jwaldrip** [comment]
:+1: for reduce.

**Comment by Nakilon** [comment]
I vote for:
`map` because it's shorter
`select` because there is `reject` that sounds similar
`fold` to later implement `rfold`!

**Comment by ysbaddaden** [comment]
I'd vote for `map`, `select` and `reject`. As for `inject` I'd prefer `reduce` over `fold`, but the latter would allow `foldr` so I have mixed feelings. Does anybody has some examples about `foldr` usages?

**Comment by asterite** [comment]
I also for for `reduce` instead of `inject`. However, if there's a good use case for `foldr` we might want to choose that. But note that `foldr` will obviously not be defined by Enumerable, only by Array (and maybe some other custom containers).

**Comment by Nakilon** [comment]
Not sure if there is a kind of `.reverse_each` in Crystal, but sometimes folding from right to left helped me if I had a break condition inside the loop.
The chapter "Rules of Thumb for Folds" here https://wiki.haskell.org/Foldr_Foldl_Foldl%27 has this point and some others.

Also people say that "foldr can handle infinite lists and foldl can't", but I don't fully understand it and not sure how much it's applicable to our compiler.

**Comment by bcardiff** [comment]
@Nakilon  Handling infinite lists in haskell is possible due to lazy evaluation together with the structure of the list. The most similar to concept here would be consuming iterators and just drop them when you don't need them. And yes, there is a [reverse_each](https://github.com/manastech/crystal/blob/master/src/array.cr#L1180-L1208) :-)

**Comment by ysbaddaden** [comment]
Actually it makes an argument against `foldr` in Crystal (which is the opposite assumption): `foldr` doesn't play nicely with Iterator which may lazily iterate from the first to the last element, but `foldr` would mean reaching the last element of the iterable, which is impossible with infinite iterators.

BTW: there are no `Enumerable#reverse_each` nor `Iterable#reverse_each` in Crystal but `Array#reverse_each`, thought there is `Enumerable#reverse_each` in Ruby.
