### ISSUE TITLE
Strange static typing error

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#1175]
The following code doesn't work - complaining that "int32 doesn't have a length method" - presumably due to static typing rules. How *should* I do this? Some kind of cast, perhaps?
```
class Array(T)
	def fn
		if self[0].responds_to?(:length)
			self[0].length
		end
	end
end
[0].fn
[""].fn
```
What I'm actually trying to do, is make ```array.join``` work differently for arrays of hashes and of ranges. My actual code:
```
class Array(T)
	def join(*args)
		if !empty? && args.none? && first.is_a?(Hash)
			inject(&.merge) # this line fails for other types of array,
			# even though it should never be executed
		elsif count > 1 && args.none? && first.is_a?(Range)
			first + self[1..-1]
		else
			previous_def(*args)
		end
	end
```

**Comment by bjmllr** [comment]
Seems the `.length` call is failing the type check even though it's impossible for the surrounding condition to be true for `T == Int32`. You can satisfy it by using a local variable, as you might need to do if `T` were a union.

```ruby
if (e = self[0]).responds_to?(:length)
    e.length
end
```

**Comment by stugol** [comment]
That won't work in the second code snipped I quoted, however.

**Comment by bjmllr** [comment]
Yes, I see your point. Perhaps you could replace that `if` structure with a helper method that has 3 overloads?

**Comment by asterite** [comment]
I think [my answer](https://github.com/manastech/crystal/issues/1176#issuecomment-131061686) in #1175 answers your question, and @bjmllr shows a way to use `responds_to?` after an `if` check (you have to assign the expression to a local variable). This wasn't explained in the docs (it was explained for `is_a?`) but I just [added that note](https://github.com/manastech/crystal/commit/da723ec17add045574bc0533996e99ee67908187).

**Comment by bjmllr** [comment]
@asterite, I understand the reason for the local variable technique when dealing with a union-typed expression, where the branch selected by `if` can vary at runtime based on the runtime type of the union, but I'm confused by this situation where there's no union.

After reading the explanations in https://github.com/manastech/crystal/issues/989, I would expect this

```crystal
class Array(T)
  def foo
    if first.responds_to?(:length)
      first.length
    end
  end
end

[1].foo
```

to instantiate `Array(Int32)#foo`, and rewrite it to be essentially

```crystal
def foo
end
```

before doing the type check. Instead, the compiler reports `undefined method 'length' for Int32`, which suggests that it is trying to type check `Array(Int32)#foo` without removing the dead branch, or before it's removed. Is this correct?
