### ISSUE TITLE
previous_def is broken

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#1177]
```puts [1, 2, 3].join``` works. However:
```
class Array(T)
	def join(separator = "")
		previous_def
	end
end
puts [1, 2, 3].join
```
fails to compile, declaring ```there is no previous definition of 'join'```. This is clearly bogus, since ```Array(T)``` inherits ```join``` from ```Enumerable(T)```. And if I can't call the previous definition, how am I supposed to delegate?
```
class Array(T)
	def join(separator = "")
		(self as Enumerable(T)).join(separator)
	end
end
```
causes the error ```Enumerable(T) is not a generic class, it's a generic module```.

**Comment by bjmllr** [comment]
I think you want to use `super` when a method has been overridden via inheritance. `previous_def` is used when the original and the override were both defined in the same class.

**Comment by stugol** [comment]
@bjmllr Yes, you may be right. Thank you.

**Comment by jhass** [comment]
So this issue can be closed?
