### ISSUE TITLE
Wrong type inference for (at least) hash class variables

### ISSUE THREAD

**Issue by sergey-kucher** [manastech/crystal#1188]
This code works fine:
```crystal
class Foo
  def self.foo
    return @@foo if @@foo
    @@foo = "123"
  end
end

puts Foo.foo.to_i + 5
puts Foo.foo.to_i + 10
```
http://play.crystal-lang.org/#/r/bem

But this, gives the error:
```crystal
class Foo
  def self.foo
    return @@foo if @@foo
    @@foo = {a: 1, b: 2}
  end
end

puts Foo.foo[:a] + 5
puts Foo.foo[:b] + 10
```
http://play.crystal-lang.org/#/r/beq

```
Error in line 8: undefined method '[]' for Nil (compile-time type is Hash(Symbol, Int32)?)

================================================================================

Nil trace:

  eval:2



  eval:3
```

**Comment by jhass** [comment]
That's not a bug, the first example works because there's both, `Nil#to_i` and `String#to_i`. But if you'll check `typeof(Foo.foo)` it still says `String?`, which is `String|Nil`. This is because `@@foo` might change between the `return` and the `if` and it is nilable.

Use

```cr
class Foo
  def self.foo
    @@foo ||= {a: 1, b: 2}
  end
end
```

**Comment by sergey-kucher** [comment]
> This is because `@@foo` might change between the `return` and the `if` and it is nilable.

I don't see any way how `@@foo` can be changed here (unless we talk about concurrency, of course)
For me is there only two ways to return from method. And for both, returned value can't be nil.

Actually this works as expected
```crystal
class Foo
  def self.foo
    if foo = @@foo
      return foo
    end

    @@foo = {a: 1, b: 2}
  end
end

puts Foo.foo[:a] + 5
puts Foo.foo[:b] + 10
```
http://play.crystal-lang.org/#/r/bf4

But since it can't be used as `return foo if foo = @@foo`. It looks not well.
BTW, example kind of crashing here: http://play.crystal-lang.org/#/r/bf3

**Comment by jhass** [comment]
Concurrency is exactly the reason, since concurrency can come from external sources (signal handlers, event loops etc.) it's almost impossible for the compiler to analyse if there's concurrent access to a variable or not, at least not with reasonable effort.

The segfault is a stackoverflow. In the first invocation `foo = @@foo` is `nil`, thus `return foo` isn't executed. In the second call the expression becomes truthy, but the assignment is not visible to `return foo`, thus it falls back to the method call which recuses endlessly. Compare http://play.crystal-lang.org/#/r/bfi

What's wrong with my variant?

**Comment by asterite** [comment]
This reminds me: maybe we should remove `Nil#to_i`. I don't know why `nil` should be a zero as an integer. Maybe it's OK in Ruby, but if we try to catch nils at compile-time I don't think it makes sense for `nil` to respond to these methods.

I just tried removing it and the compiler still compiles, so at least the compiler doesn't rely on that behaviour :-)

**Comment by sergey-kucher** [comment]
> What's wrong with my variant?

Your variant is good for cases when expression is short enough (as `@@foo ||= {a: 1, b: 2}`). But if for long logic I have to use `begin ... end`

```crystal
@@foo ||= begin
  ...
  new_foo_value
end
```

Which undesirable because involves additional nesting level into code. I think ability to do this, will be better:

```crystal
def self.foo
  return foo if foo = @@foo # early return

  ... # code without redundant nesting
  @@foo = new_foo_value
end
```

**Comment by asterite** [comment]
@sergey-kucher For `return foo if foo = @@foo` to parse the way you want the parser would have to have a huge look-ahead, making things more complex and slower. Try it in Ruby and you'll get the same error (Ruby works that way too).

You can change it to:

```crystal
def self.foo
  # early return
  if foo = @@foo
    return foo
  end

  ... # code without redundant nesting
  @@foo = new_foo_value
end
```

but the `@foo ||= begin` variant is also OK, and we use it [in](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/compiler.cr#L253-L256) [quite](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/compiler.cr#L253-L256) [a](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/compiler.cr#L253-L256) [few](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/compiler.cr#L253-L256) [places](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/compiler.cr#L253-L256).

**Comment by sergey-kucher** [comment]
To resume, I think crystal ability to catch potential concurrency problems (like `return @@foo if @@foo`) is great!
And because implementation of `return foo if foo = @@foo` is shady and maybe not worth efforts I'll close the issue.

Thanks!

**Comment by jhass** [comment]
For more complex expressions I often end up with something like

```cr
class Foo
  def foo
    @foo ||= build_foo
  end

  private  def build_foo
     # yada yada
  end
end
```

Having a method to always compute a "fresh" one is often useful anyways, eg. to reset the value.
