### ISSUE TITLE
Array#product

### ISSUE THREAD

**Issue by And3s** [manastech/crystal#1193]
```
[1, 2].product([3, 4]) do |x|
    p x
end

# ruby
# [1, 3]
# [1, 4]
# [2, 3]
# [2, 4]

# crystal
# 1
# 1
# 2
# 2

[1, 2].product([3, 4], [5, 6]) do |x|
    p x
end

# ruby

# [1, 3, 5]
# [1, 3, 6]
# [1, 4, 5]
# [1, 4, 6]
# [2, 3, 5]
# [2, 3, 6]
# [2, 4, 5]
# [2, 4, 6]


# crystal
# wrong number of arguments for 'Array(Int32)#product' (2 for 1)
```

**Comment by asterite** [comment]
In Crystal Array#product yields two elements, [like this](http://play.crystal-lang.org/#/r/bi8).

For the multi-array variant you can use `Array.each_product`, just added by kostya (so it's in HEAD):

```crystal
Array.each_product([[1, 2], [3, 4], [5, 6]]) do |x|
  p x
end
```

I wouldn't like `Array#product` with a block to create intermediary arrays, as you almost always want the individual elements, and doing the product of two arrays is the most common case.

Also see [this comment](https://github.com/manastech/crystal/issues/105#issuecomment-131547103).
