### ISSUE TITLE
index out of bounds for tuple

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#1195]
The code at http://play.crystal-lang.org/#/r/bk5 causes error ```index out of bounds for tuple {Int32}```. How can I reference tuple arguments that might not exist? Apparently an ```if``` isn't enough.

**Comment by asterite** [comment]
You define a method overloads with two or more arguments

**Comment by stugol** [comment]
In this particular case, sure - and I have since done so. But in general, there may be cases where, say, a function returns a tuple, and we need to extract values from it. There ought to be a way to handle tuples whose number of elements is not necessarily known at compile-time, don't you think?

**Comment by jwaldrip** [comment]
There is a special operator for that. See http://play.crystal-lang.org/#/r/bmo


- Jason

—

Jason Waldrip
Chief Technology Officer
brandfolder.com
<email| jason.waldrip@brandfolder.com>
<office | 720-744-0311>
<mobile | 646-460-5959>

**Comment by bjmllr** [comment]
Example using method overloads to find the length of a tuple at compile time: http://play.crystal-lang.org/#/r/bmy

**Comment by stugol** [comment]
@jwaldrip I didn't know the '?' Would fix this particular problem. Thanks.

**Comment by stugol** [comment]
@bjmllr Interesting solution.
