### ISSUE TITLE
String.split different from ruby and possible bug

### ISSUE THREAD

**Issue by technorama** [manastech/crystal#1197]
ruby:
```
"a=".split("=", 2)
=> ["a", ""]
```

crystal:
```
"a=".split("=", 2)
=> ["a"]
```

 I believe the crystal result is incorrect since the delimiter exists.  The 2nd value should be a blank string.  Otherwise it is impossible to differentiate between "a=".split... and "a".split....

**Comment by jhass** [comment]
`"a=".split("=")` returns `["a"]` in Ruby, which is inconsistent to specifying a limit. I guess we just went the wrong path towards consistency here and should make both cases return `["a", ""]`

**Comment by asterite** [comment]
This is a duplicate of #1070
