### ISSUE TITLE
feature request: connection.cr

### ISSUE THREAD

**Issue by kostya** [manastech/crystal#1198]
Connection class like: http://eventmachine.rubyforge.org/EventMachine/Connection.html

**Comment by waj** [comment]
In Ruby, eventmachine is useful to handle many network connections within the same thread. Crystal already can do that, without all the hassle of handling the connections in callbacks and state machines. So the question is, why would you want to have something like that in Crystal? Can you describe a scenario where an EventMachine's like connections is better that using linear code in separate fibers?

**Comment by kostya** [comment]
may be not understand something, but how can i get event when client or server disconnected? (in em it was unbind)
