### ISSUE TITLE
No overload matches, but it clearly does

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#1201]
The code at http://play.crystal-lang.org/#/r/bl3 causes the following self-contradictory error:
```
Error in line 10: no overload matches 'Array(Int32)#[]'
Overloads are:
 - Array(Int32)#[](start : Int, count : Int)
 - Array(Int32)#[](index : Int)
 - Array(Int32)#[](range : Range)
 - Array(Int32)#[]()
```

The error does not occur if I implement the method directly in ```Array(T)```.

**Comment by asterite** [comment]
Yep, seems like a bug in the method lookup.
