### ISSUE TITLE
Int32 is not a Number

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#1204]
In line with your recent fix concerning Hashes and ```is_a?```, shouldn't the following code print ```true```?
```
puts Int32.is_a?(Number)
```
It'd really be helpful to have some way of type-checking these things.

**Comment by jwaldrip** [comment]
You can't type check a type.


- Jason

—

Jason Waldrip
Chief Technology Officer
brandfolder.com
<email| jason.waldrip@brandfolder.com>
<office | 720-744-0311>
<mobile | 646-460-5959>

**Comment by bjmllr** [comment]
`Int32` just isn't an instance of `Number`. This does work:

```crystal
Int32.is_a?(Class) #=> true
```

Ruby gives the same result for `Fixnum` and `Numeric`, so I think this is pretty solidly expected behavior. You might be able to use this instead:

```crystal
Int32.is_a?(Number.class) #=> true
```

**Comment by stugol** [comment]
@bjmllr Your suggestion works, but I really didn't expect it to. I figured 'Int32.class' would return 'class', and therefore ALL classes would match. I mean, a subclass isn't an "instance of" its parent, really. I guess it's a special case in the compiler somewhere. Thanks for the help.

**Comment by stugol** [comment]
@jwaldrip Apparently you can ;)

**Comment by bjmllr** [comment]
@stugol True, in a normal method call, it would behave as you say. I was able to guess at this usage based on the knowledge that `Foo.class` works this way in type restrictions in method signatures also, so there is a sort of consistency.

**Comment by asterite** [comment]
I'm closing this. `Int32.is_a?(Number)` is false and `Int32.is_a?(Number.class)` is true.
