### ISSUE TITLE
Casting error using *args on 0.7.6

### ISSUE THREAD

**Issue by dbackeus** [manastech/crystal#1208]
http://play.crystal-lang.org/#/r/bpk

Works in 0.7.5 but not in 0.7.6.

**Comment by asterite** [comment]
I have no idea why it compiled in 0.7.5, but it shouldn't.

Crystal has method overloads, there's no need to define a method with `*args` and then do check at runtime.

But in your case, I would do it the way @jhass replied to you in IRC (assigning to a temporary variable and then using `is_a?`).

**Comment by jhass** [comment]
@asterite actually it is a bug or otherwise http://carc.in/#/r/byv should be an error too

**Comment by dbackeus** [comment]
@asterite I didn't realize *args could be put in any position in conjunction with other variables. I'm definitely very happy with this approach: http://play.crystal-lang.org/#/r/bzm

A similar example could be helpful to have available at: http://crystal-lang.org/docs/syntax_and_semantics/splats_and_tuples.html

However I still don't see why my original example couldn't compile while still being able to work around it by assigning local variables basically forcing the same logic to happen using more verbose code.
