### ISSUE TITLE
Array.flatten

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#1211]
Ruby arrays have a 'flatten' method to consolidate nested arrays into a single array. Crystal does not, and attempts to write my own using 'inject' or recursion have failed due to issues with the unioning type system.

How would I go about implementing such a method, please?

**Comment by jhass** [comment]
See #1009 for some discussion around a similar issue.

**Comment by stugol** [comment]
Awesome, thank you!

Although I have no idea why it works, when my attempts all failed.
