### ISSUE TITLE
missing "initialize super" call in unreferenced class causes error message for some other class

### ISSUE THREAD

**Issue by ervumlens** [manastech/crystal#1222]
The Crystal compiler is reporting a "not initialized in all 'initialize' methods" error in a class that appears to be initializing things correctly. It turns out that the cause of the problem was in a separate, not-directly-referenced class (that is, the class was not mentioned again in the program but was referenced indirectly in a Ruby-esque sense). The error made no mention of this other class, so it took some tracking to figure out. 

I'm hoping the error message for this case could be improved.

(I couldn't find a similar report here or on the forum, but sorry if this has already been discussed.)
 

Here is the simplest form of the problem I could come up with.

```ruby

class Base
  property x

  def initialize()
	@x = 0
  end
end

#No (direct) references to this class in the code
class Unreferenced < Base
  def initialize()
	#forgot the super call
  end
end

class Derived < Base
  def initialize()
	super()
  end

  def print_x()
	print @x + 100
  end
end

b = Derived.new
b.print_x
```

Crystal 0.7.6 [produces the following error](http://play.crystal-lang.org/#/r/bv2):

```
Error in line 28: instantiating 'Derived#print_x()'

in line 23: undefined method '+' for Nil (compile-time type is (Nil | Int32))

================================================================================

Error: instance variable '@x' of Derived was not initialized in all of the 'initialize' methods, rendering it nilable.

Specifically in this one:

  eval:18
```

I have found three ways to fix the error:
1. Remove the `Unreferenced` class.
2. Change `Unreferenced < Base` to just `Unreferenced`.
3. Add a `super` call to `Unreferenced`'s `initialize`.

I get the general idea that the definition of `Unreferenced` affects the definition of `Base`. However, the error message only mentions my `Derived` class, and mentions of `Nil` and `nilable` reinforce (in mind mind, at least) the notion that something is wrong in `Derived` rather than in `Base` or `Unreferenced`. These factors made an otherwise simple problem difficult to track down.

I'm certainly more conscious of this type of error now, but I'm wondering if there is room for improvement somewhere.

* Is it possible to provide a more specific error message for this case? Or maybe provide more information when running with `--verbose`? I would not have thought to look down to `Base` and then back up to `Unreferenced`, so something along these lines would have been helpful.

* Is it possible (and advisable) to change the way I define classes to prevent this type of error from occurring?

Thanks.

**Comment by asterite** [comment]
The error message is wrong, it should point to the `initialize` without `super`. It could also suggest "did you forget to call super?", maybe.

**Comment by ervumlens** [comment]
Great, thanks. I was afraid it was one of those things that makes sense to everyone but me. :smiley:

**Comment by asterite** [comment]
Now for your example it says:

```
Error in ./foo.cr:27: instantiating 'Derived#print_x()'

b.print_x
  ^~~~~~~

in ./foo.cr:22: undefined method '+' for Nil (compile-time type is (Nil | Int32))

    print @x + 100
             ^

================================================================================

Error: instance variable '@x' of Unreferenced was not initialized in all of the 'initialize' methods, rendering '@x' of Derived nilable (Base is the common supertype that defines it)

Specifically in this one:

  ./foo.cr:11

      def initialize()
          ^~~~~~~~~~
```

**Comment by ervumlens** [comment]
That looks fantastic, thanks a lot.
