### ISSUE TITLE
String % operator doesn't support symbols

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#1224]
The following code works in Ruby but fails in Crystal. Please make the % operator (and therefore ```sprintf```) support symbolic hash access:
```
puts "%{a}" % {a:1}
```
Ruby output: ```1```
Crystal output: ```Missing hash value: "a" (KeyError)```

**Comment by stugol** [comment]
I was going to fork it and have a go myself, but according to the docs:
```
You can't dynamically create symbols
```
So my intended fix of ```@io << arg[Symbol.new(key)]``` isn't an option.

**Comment by asterite** [comment]
Yes, that's basically the reason. Note that you have a short syntax for strings in hashes:

```crystal
puts "%{a}" % {"a":1}
```

so at least it's not that painful :-)

**Comment by stugol** [comment]
Yeah, but it'd be well handy to be able to refer to symbols...

**Comment by waterlink** [comment]
@stugol How symbols are better than strings in that regard?
