### ISSUE TITLE
Macro variable issue

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#1225]
The code at http://play.crystal-lang.org/#/r/bxb causes the error ```undefined local variable or method```.

As there appears to be no way to explicitly constrain a variable's type (```a :: Int32```) and also provide an initialisation value (```a = 4```) at the same time, I figured this macro would help.

It works for instance variables, but not locals, and I don't understand why.

**Comment by bjmllr** [comment]
You can put a cast in the body of a method to further restrict the type: http://play.crystal-lang.org/#/r/bxc

**Comment by stugol** [comment]
@bjmllr Quite possibly, but I don't see how that relates to my situation. I'm trying to do this:
```
def fn
  a :: Int32 = 4
  ...do something with a...
end
```
Alternatively - or additionally - it would be helpful to be able to constrain the return type of a method:
```
def fn(a) : String
  a.to_s
end
```

**Comment by kirbyfan64** [comment]
@stugol You can: http://play.crystal-lang.org/#/r/bxg. ??

**Comment by stugol** [comment]
....oh ;)

I tried ```::``` and ```as```, and I was sure I'd tried ```:``` as well. Guess not.

Follow-up question: Why ```typeof(Range(Int64,Int64).new(0, 10).begin) == Int32``` ?

**Comment by bjmllr** [comment]
I get `no overload matches 'Range(Int64, Int64)#initialize' with types Int32, Int32` when I try to run that on 0.7.6.

**Comment by stugol** [comment]
@bjmllr I'll grant you that. I didn't specify ```_i64``` in the call. Also, it appears that when run online (e.g. http://play.crystal-lang.org/#/r/bxm) I don't get this issue. But I seriously have this code in my project:
```
struct Range(B,E)
	# ...code elided...
	def -(ranges : Array(Range(B,E)))
		puts typeof(self), typeof(self.begin)
		# ...code elided...
	end
end
```
And it seriously prints:
```
Range(Int64, Int64)
(Int32 | Int64)
```

**Comment by asterite** [comment]
Macros can't define variables that will be visible outside of them. This is because the parser knows that something is a variable when you assign something to it:

```crystal
a = 1
a # varaible
b # method call
```

So in your example:

```crystal
var a, Int32, 4
puts a # a wasn't assigned something, so it's a method call
```

This is because first the program is parsed, then macros are expanded. Macros can't be expanded during the parsing because then you'll have to do syntax and semantic at the same time. Plus I think it would be pretty confusing if macros could define variables.

**Comment by stugol** [comment]
Then would it not be helpful to be able to constrain the type of a variable and assign to it at the same time?

Sometimes we don't want automatic type-unioning. Sometimes we want the compiler to warn us if we try to change the type. Why? Because (Array(Int32) | Array(Int64)) != Array(Int32 | Int64). 

Incidentally, it would be well useful to be able to compress types like that. For example, when subtracting ranges of different types. Indeed, in my project, I've had to specifically use Range(Int64,Int64) everywhere, disallowing type unioning, because it simply won't compile otherwise.

**Comment by bjmllr** [comment]
@stugol Why can't you put the constraint and the assignment on different lines?

```crystal
a :: Int32
a = 2_147_483_648 #=> compile error, type must be Int32, not (Int32 | Int64)
```

**Comment by stugol** [comment]
I can. But it's a bit long winded.

**Comment by bjmllr** [comment]
Then what about a cast? `a = 2_147_483_648 as Int32` has pretty much the same effect as far as I can tell.

**Comment by stugol** [comment]
Nope. Because you can then say ```a = "cheese"``` later on.

**Comment by kirbyfan64** [comment]
@stugol Crystal's static typing would still prevent you from doing anything stupid, though, right?

**Comment by stugol** [comment]
Sure. But try writing ```Array#flatten``` or ```Range#-``` when you end up with types like ```(Range(Int32 | Int64 | Int32 | Int64) | Range(Int32, Int32 | Int64) | Range(UInt64, UInt64))```, or ```(Array(Array(Int32) | Int32) | Array(UInt64) | Array(UInt64 | Int32))```. Argh!!

Tracking down where exactly the array was populated with an Int32, when you expect it to contain only UInt64s, is almost impossible with automatic unioning.

**Comment by kirbyfan64** [comment]
@stugol Hahaha, I can agree there. See #861.

**Comment by asterite** [comment]
I'm closing this in favour of #919
