### ISSUE TITLE
Undefined constant B

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#1226]
The code at http://play.crystal-lang.org/#/r/bxk throws an ```undefined constant B``` error, when that makes no sense.

**Comment by waterlink** [comment]
Error is strange. In your case you still can use `self` there:
http://play.crystal-lang.org/#/r/bxo

--
Best Regards,
Alexey Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

2015-08-19 5:05 GMT+03:00 stugol <notifications@github.com>:

**Comment by stugol** [comment]
Very true. Thanks.

Still needs fixing though, don't you think? ;)

**Comment by waterlink** [comment]
Yeah. Don't know if it should compile here or not, though. And if not, how
error should sound.

--
Best Regards,
Alexey Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

2015-08-19 5:27 GMT+03:00 stugol <notifications@github.com>:

**Comment by bjmllr** [comment]
I tried to reduce it, seems to apply to any nested generic with a free variable in a return type restriction: http://play.crystal-lang.org/#/r/by6
