### ISSUE TITLE
Constrain to Map type?

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#1227]
Can someone tell me what I'm doing wrong here?
```
def fn(args : {Int32 => Int32} )
end
```

**Comment by bjmllr** [comment]
You have to write it as `Hash(Int32, Int32)` in a type restriction.

I think only `Proc` has special syntax inside type restrictions (where it is `Arg1, Arg2 -> Ret`), `[] of` and `{} of` only apply to literals.

**Comment by stugol** [comment]
Ah, of course. Thanks.
