### ISSUE TITLE
FIle permission issue

### ISSUE THREAD

**Issue by rishavs** [manastech/crystal#1230]
Hi

I was trying run the simple `puts "hello World"` program on my Lubuntu 32 bit with Clang as the compiler and I am getting the following issue:

    rishav@rishav-VirtualBox:~/Workspace$ ls -l
    total 4
    -rwxrwxrwx 1 rishav rishav 18 Aug 19 12:55 test.cr

    rishav@rishav-VirtualBox:~/Workspace$ crystal run test.cr 
    Error opening file '/home/rishav/Workspace/.crystal/home/rishav/Workspace/test.cr/bc_flags' with 
    mode 'w': Permission denied

    *Errno::new<String>:Errno +305 [0]
    *File::new<String, String>:File +787 [0]
    *Crystal::Compiler#codegen<Crystal::Compiler, Crystal::Program, Crystal::Expressions,     Array(Crystal::Compiler::Source), String>:(Nil | Int32 | Bool) +4475 [0]
    *Crystal::Compiler#compile<Crystal::Compiler, Array(Crystal::Compiler::Source),     String>:Crystal::Compiler::Result +5008 [0]
    *Crystal::Command::run_command<Array(String)>:Nil +132 [0]
    *Crystal::Command::run<Array(String)>:(Nil | Bool | FileDescriptorIO+ | Crystal::Compiler::Result | Array(Crystal::Init::View+:Class)) +17811 [0]
    main +17803 [0]
    __libc_start_main +222 [0]
    _start +33 [0]

    Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/manastech/crystal/issues

**Comment by jhass** [comment]
That is strange, did you create `/home/rishav/Workspace` with a different user or ran `crystal run test.cr` with a different user prior? You can try `chown -R rishav /home/rishav/Workspace/.crystal`, as root if you get permission errors on that one too.

**Comment by rishavs** [comment]
I have only 1 user on the system. Its a fresh VM which i just installed today.

So this is the sequence of things as they happened:

I installed Crystal using the shell script and apt-get command.
when I tried to run it, i got a missing cc exception.

Thinking that it is because lubuntu is very minimalistic and may not have a c compiler installed, i installed clang.

then i tried to run by test program.

it ran fine and i got the output in the console. but it also gave me some `warning: sigreturn is not implemented and will always fail`

I ignored that as the output came on the console.

then i shut down my VM. I made some changes to the VM. increased memory to 786 mb.
changed chipset to ICH9 and enabled i/o APIC.

This was because my VM was acting sluggish.

then i restarted.

i tried to run the program again and now I am getting this error.

all operations were done using the same user `rishav`

**Comment by jhass** [comment]
Did you try the fix anyway? Does it work after `rm -rf`ing `.crystal`? What are the permissions of the files and folders (`ls -l`)?

**Comment by rishavs** [comment]
chown worked. it compiled and my console now shows Hello World.
so, what happened there? some random OS issue where the folder permission changed for reason?

**Comment by jhass** [comment]
I guess so, I doubt it's a Crystal issue.

**Comment by rishavs** [comment]
Thanks. Shall i close the issue now?

**Comment by jhass** [comment]
Feel free to reopen if you find a reliable way to reproduce it :)
