### ISSUE TITLE
Parsing HTML with libxml2 and xpath

### ISSUE THREAD

**Issue by ryanworl** [manastech/crystal#1240]
I'm interested in parsing HTML with libxml2, but the XML module doesn't currently support it. I would be happy to contribute the code to interface with the html functions from libxml2, but before I do, should it go under the HTML module or the XML module?

The HTML and XML interfaces share a lot and one could conceivably swap out `xmlReadMemory` for `htmlReadMemory` and be on their way (which I have done locally to make sure it works).

I'm open to suggestions on where to put this integration. Personally I'm on the side of adding a `parseHTML` method to the XML module and being done with it.

**Comment by asterite** [comment]
@ryanworl That would be a very welcome addition!

You mean `parseHTML` would return an `XML::Node` and you would interface to it just like you interface with an XML document? If so, I'd prefer this option.

**Comment by ryanworl** [comment]
@asterite That is correct. `htmlReadMemory` and `xmlReadMemory` have the same C function signature and the return value interoperates with the rest of the XML functions. This is how many HTML/XML parsing libraries are implemented in Swift and Objective-C, [for example](https://github.com/stklieme/HTMLDocument/blob/master/HTMLDocument.m). 

It would also make sense to create an XML::HTMLParserOptions enum to encapsulate the few differences from XML::ParserOptions.

**Comment by asterite** [comment]
@ryanworl Sounds good :-)

**Comment by asterite** [comment]
Fixed by #1244
