### ISSUE TITLE
Compiler bug: Assertion failed: (getOperand(0)->getType() == cast(getOperand(1)...

### ISSUE THREAD

**Issue by technorama** [manastech/crystal#1243]
This error shows up on linux llvm 1.5 & 1.6.2 and macos llvm 3.6.2 when using the following branch:
* https://github.com/technorama/crystal/tree/f/io_timeout

Assertion failed: (getOperand(0)->getType() == cast<PointerType>(getOperand(1)->getType())->getElementType() && "Ptr must be a pointer to Val type!"), function AssertOK, file Instructions.cpp, line 1083.

Try running the socket spec.

Modifying Event.add and putting the to_timeval call inside or outside of the if statement changes the error depending on what other code is commented or not.   The error still occurs even after all calls to Event.add are removed.

**Comment by jhass** [comment]
You mean 3.5 / 3.6.2 ?

```
(master) $ git pull; make;
$ git fetch technorama; git checkout f/io_timeout; git reset --hard technorama/f/io_timeout
(f/io_timeot) $  bin/crystal spec/std/socket_spec.cr                     
Using compiled compiler at .build/crystal
.......

Finished in 53.59 milliseconds
7 examples, 0 failures, 0 errors, 0 pending
(f/io_timeout) $ git rebase master;  bin/crystal spec/std/socket_spec.cr                     
Using compiled compiler at .build/crystal
.......

Finished in 53.59 milliseconds
7 examples, 0 failures, 0 errors, 0 pending
(f/io_timeout) $ make spec
./bin/crystal build  -o .build/all_spec spec/all_spec.cr
Using compiled compiler at .build/crystal
Error in ./spec/compiler/compiler_spec.cr:4: instantiating 'describe(String)'
describe "Compiler" do
^~~~~~~~
in ./src/spec/dsl.cr:3: instantiating 'Spec::RootContext:Class#describe(String, String, Int32)'
    Spec::RootContext.describe(description.to_s, file, line) do |context|
                      ^~~~~~~~
in ./src/spec/dsl.cr:3: instantiating 'Spec::RootContext:Class#describe(String, String, Int32)'
    Spec::RootContext.describe(description.to_s, file, line) do |context|
                      ^~~~~~~~
in ./spec/compiler/compiler_spec.cr:4: instantiating 'describe(String)'
describe "Compiler" do
^~~~~~~~
in ./spec/compiler/compiler_spec.cr:5: instantiating 'it(String)'
  it "compiles a file" do
  ^~
in ./spec/compiler/compiler_spec.cr:5: instantiating 'it(String)'
  it "compiles a file" do
  ^~
in ./spec/compiler/compiler_spec.cr:9: instantiating 'Crystal::Command:Class#run(Array(String))'
    Crystal::Command.run ["build", "#{__DIR__}/data/compiler_sample", "-o", tempfile.path]
                     ^~~
in ./src/compiler/crystal/command.cr:41: instantiating 'init(Array(String))'
          init options
          ^~~~
in ./src/compiler/crystal/command.cr:97: instantiating 'Crystal::Init:Class#run(Array(String))'
    Init.run(options)
         ^~~
in ./src/compiler/crystal/tools/init.cr:37: instantiating 'Crystal::Init::InitProject#run()'
      InitProject.new(config).run
                              ^~~
in ./src/compiler/crystal/tools/init.cr:123: instantiating 'Array(Crystal::Init::View+:Class)#each()'
        views.each do |view|
              ^~~~
in ./src/array.cr:636: instantiating 'each_index()'
    each_index do |i|
    ^~~~~~~~~~
in ./src/array.cr:636: instantiating 'each_index()'
    each_index do |i|
    ^~~~~~~~~~
in ./src/compiler/crystal/tools/init.cr:123: instantiating 'Array(Crystal::Init::View+:Class)#each()'
        views.each do |view|
              ^~~~
in ./src/compiler/crystal/tools/init.cr:124: instantiating 'Crystal::Init::View+#render()'
          view.new(config).render
                           ^~~~~~
in ./src/compiler/crystal/tools/init.cr:101: instantiating 'to_s()'
        File.write(full_path, to_s)
                              ^~~~
in ./src/object.cr:85: instantiating 'String:Class#build()'
    String.build do |io|
           ^~~~~
in ./src/string.cr:217: instantiating 'String::Builder:Class#build(Int32)'
    String::Builder.build(capacity) do |builder|
                    ^~~~~

in ./src/string.cr:217: instantiating 'String::Builder:Class#build(Int32)'

    String::Builder.build(capacity) do |builder|
                    ^~~~~

in ./src/object.cr:85: instantiating 'String:Class#build()'

    String.build do |io|
           ^~~~~

in ./src/object.cr:86: instantiating 'to_s(String::Builder)'

      to_s io
      ^~~~

in macro 'embed_ecr' /home/jhass/projects/crystal/code/src/ecr/macros.cr:1, line 1:

  1.   {{ run("ecr/process", "/home/jhass/projects/crystal/code/src/compiler/crystal/tools/init/template/example_spec.cr.ecr", "__io__") }}

  {{ run("ecr/process", "/home/jhass/projects/crystal/code/src/compiler/crystal/tools/init/template/example_spec.cr.ecr", "__io__") }}
  ^

expanding macro
in macro 'embed_ecr' /home/jhass/projects/crystal/code/src/ecr/macros.cr:1, line 1:

  1.   {{ run("ecr/process", "/home/jhass/projects/crystal/code/src/compiler/crystal/tools/init/template/example_spec.cr.ecr", "__io__") }}

  {{ run("ecr/process", "/home/jhass/projects/crystal/code/src/compiler/crystal/tools/init/template/example_spec.cr.ecr", "__io__") }}
     ^~~

Error executing run: ecr/process "/home/jhass/projects/crystal/code/src/compiler/crystal/tools/init/template/example_spec.cr.ecr" "__io__"

Got:

Nil assertion failed (Exception)
Nil assertion failed (Exception)
Could not raise

Makefile:21: recipe for target '.build/all_spec' failed
make: *** [.build/all_spec] Error 1
$ llvm-config --version
3.6.2

**Comment by asterite** [comment]
I'm getting @technorama 's error if I use a compiled compiler, so I must have broken something in these last commits.

**Comment by asterite** [comment]
So, this was an obscure one. The problem was that the compiler defines "printf" [internally](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/primitives.cr#L104-L106). But then [io.cr also defines it](https://github.com/manastech/crystal/blob/60e797442591189fa1ba220928a6e5a3cd40d628/src/io.cr#L51), but it returns Char. Now, Char is 32 bits, like what printf returns, so it seems that would be OK. However, we are inside `LibC` and now there's a `Char` alias to `UInt8`, so we get a different return type for printf. If `LibC.printf` return value was used somehow (and it being the last expression in a method is a case), the code would explode.

The solution was to change printf's return type. So change it in your branch and it'll hopefully compile again.

In the future we'll remove those hardcoded definitions of printf, sprintf, etc. In the early days we used them for debugging, but now we don't need those anymore.

**Comment by technorama** [comment]
I used printf because of 2 other problems in the compiler.
1. puts sometimes causes the compiler to explode from circular dependencies (especially in FileDescriptorIO)
2. puts sometimes prints NOTHING.  switching to printf is a workaround

**Comment by asterite** [comment]
@technorama We use 1 too when coding some basic stuff. The problem is that when coding FileDescriptorIO you can't puts because that uses STDOUT, which is a FileDescriptorIO, which is what we are trying to define. And because that class depends on LibEvent, debugging scheduler code must be done with printf. But that's OK.

As for 2, it never happened to me. Do you have a way to reproduce it?

**Comment by technorama** [comment]
It's happened several times on this branch.  After compiling maybe I can find an example, but there's another problem.  There's different compiler error after rebasing.

Assertion failed: (isa<X>(Val) && "cast<Ty>() argument of incompatible type!"), function cast, file /private/tmp/llvm3620150726-85865-1nple2r/llvm-3.6.2.src/include/llvm/Support/Casting.h, line 237.

**Comment by asterite** [comment]
@technorama How can I reproduce it? I checkout out that branch. If I do `crystal spec/std/socket_spec.cr` it works fine. I also tried with a compiled compiler (not from that branch because that doesn't compile).
