### ISSUE TITLE
Weird bug on Mac OS Dir operations

### ISSUE THREAD

**Issue by sardaukar** [manastech/crystal#1245]
The following code works on Linux:

```crystal
Dir.open("/") do |dir|
  dir.each do |file|
    puts file.inspect
  end
end
```

But on Mac OS X (10.10.5) I get:

```
Error: File / does not exist
```

**Comment by ryanworl** [comment]
I'm also running 10.10.5 with crystal 0.7.6 and that code does successfully print out my root directory, dotfiles included. What version of crystal are you using?

**Comment by sardaukar** [comment]
`Crystal 0.7.6 [eb13f75] (Thu Aug 13 22:00:15 UTC 2015)`

**Comment by sardaukar** [comment]
Well, it's not a bug - I was just running this with an extra argument "/", due to a previous test with ARGV being passed, and that's why I got a Crystal error... :cry:

**Comment by ryanworl** [comment]
Hmm, that's interesting. I'm no expert, so hopefully someone more familiar with that part of the standard library can chime in. Just wanted to share that I was on same OS version and your code worked. Sorry! :smiley:
