### ISSUE TITLE
Compile and run STDIN or inline code

### ISSUE THREAD

**Issue by igneus** [manastech/crystal#1263]
I suggest adding a way to compile contents of the standard input and an option to compile and run a one-liner from the command line (like ruby's `-e`).

Both would be nice to have for quickly exploring ideas and occasional shell magic.

**Comment by jhass** [comment]
The second is already possible, check `crystal eval`

**Comment by igneus** [comment]
Now I see - actually both are already possible using `crystal eval`. Shame on me. I should have studied the available subcommands and options more carefully.

**Comment by asterite** [comment]
@igneus Definitely not your fault, that command was under-documented.

You can actually do `echo puts 1 + 2 | crystal eval` :-)
