### ISSUE TITLE
Private macros cannot call other private macros

### ISSUE THREAD

**Issue by RX14** [manastech/crystal#1265]
```crystal
private macro x
end

private macro y
	x
end

y
```

Produces error message:

```
Error in macro 'y' eval:4, line 1:

  1. 	x

 x
 ^

undefined local variable or method 'x'
```

**Comment by asterite** [comment]
Right you are!

**Comment by jhass** [comment]
Slightly related,

```cr
class Foo
  private macro test
  end
end

class Bar < Foo
  test
end
```

probably shouldn't work but does.

**Comment by asterite** [comment]
Right now private macros are file-private, so the above should probably give a compile-error saying "can't mark this macro as private" or something like that (until we really want to support that).
