### ISSUE TITLE
[RFC] Interpolate to IO

### ISSUE THREAD

**Issue by asterite** [manastech/crystal#1267]
This is an idea I had for some time.

Crystal has `to_s(io)` in addition to `to_s` (from Ruby) because we want to write directly to an IO and avoid intermediate strings.

In Ruby you can write for example:

```ruby
class Point
  def initialize(x, y) 
    @x = x
    @y = y
  end

  def to_s
    "Point(#{@x}, #{@y})"
  end
end

point = Point.new 1, 2
puts point # prints "Point(1, 2)"
```

To do the same in Crystal you'd have to overwite `to_s(io)`, like this:

```crystal
class Point
  def to_s(io)
    io << "Point(" << @x << ", " << @y << ")"
  end
end
```

The code isn't as nice now. We could do:

```crystal
io << "Point(#{@x}, #{@y})"
```

but that defeats the point, because the interpolation creates an intermediate string.

So, I propose to add this extra syntax:

```crystal
"Point(#{@x}, #{@y})"(io)
```

It's basically a string interpolation followed by a call and a single argument. The above would be syntax sugar for:

```crystal
io << "Point(" << @x << ", " << @y << ")"
```

but it retains the readability of string interpolations. 

This is backwards compatible because right now `"string"(io)` gives a parse error.

The only drawback I see is that it's something new to learn, but it's an easy concept.

An alternative would be for the compiler to recognize `obj << interpolation` and rewrite that, but that's more dangerous and unexpected, so that's what a new syntax is better.

Thoughts?

**Comment by jhass** [comment]
I like the concept but I'm not sure about the syntax tbh, it looks too much like a call to me. I have to think a bit about it for a while, but a quick idea would be alternate interpolation syntax, `io << "foo #<<{bar} baz"` or something like that.

**Comment by jhass** [comment]
Or borrow a bit from shell? `io <("foo #{bar} baz")`, parenthesis mandatory.

**Comment by jhass** [comment]
Third idea: The IO percent literal: `io << %io{foo #{bar} baz}`

**Comment by waterlink** [comment]
Shouldn't it be possible to detect `something << "string #{@with}
interpolation"` automatically and just use more effective version under the
hood? Or is it a subject to too many edgecases? Or wrong parsing/lexing
phase?

--
Best Regards,
Alexey Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

2015-08-24 3:10 GMT+03:00 Jonne Haß <notifications@github.com>:

**Comment by jhass** [comment]
@waterlink That would need to make the compiler aware of what an IO is, no? Thinking about `["foo"] << "bar #{baz} quux" for example.

**Comment by kostya** [comment]
why compiler can't replace 

```ruby
a = "Point(#{@x}, #{@y})"
```

with 
```ruby
a = "Point(" << @x << ", " << @y << ")"
```

then 
```ruby
io << "Point(#{@x}, #{@y})"
```

would be replaced as 
```ruby
io << "Point(" << @x << ", " << @y << ")"
```

**Comment by stugol** [comment]
I'm in favour of pretty much all proposals to add syntactic sugar ;)

@jhass's io percent literal looks to be the best idea so far. The delimiter could be arbitrary, like existing percent literals: ```%r(regex)```

**Comment by bjmllr** [comment]
+1 for a percent literal. Percent literals are a familiar way to rewrite string literals into other constructs at compile time.

> ```ruby
> a = "Point(" << @x << ", " << @y << ")"
> ```

@kostya how would this expansion behave differently from regular interpolation? There's no `String#<<` so far.

**Comment by jhass** [comment]
@kostya `["a"] << "foo #{bar} baz"` -> `["a"] << "foo " << bar << " baz"` is most likely not what you intended.

**Comment by Exilor** [comment]
On occasion I've wondered why is it so important that ```#to_s```` and ```#inspect``` be *that* efficient. Does it happen often that sending the string representation of a class through an IO is a bottleneck?

**Comment by kostya** [comment]
ok
`["a"] << "foo #{bar} baz" -> ["a"] << ("foo " << (bar << " baz"))`

**Comment by waj** [comment]
Another option that doesn't require a new syntax could be:
```crystal
"foo #{bar} baz" >> io
```
However, I'm not sure I would put many votes on my own idea ;-)

So far, I am more convinced with the `%io` syntax.

@Exilor it's probably not a bottleneck (sending bytes through an IO often takes much more time) but as an example, if you profile almost any Java application, you'll find that the most common class that the GC has to deal with is strings. Allocate a new string just to concatenate some values before sending the result through the IO is really fast, but then it's more work for the GC.

**Comment by bcardiff** [comment]
I though of `"foo #{bar} baz" >> io` also. I was searching for something like  interpolate "in this context".
But if we can deal with `>> io` we should be able to deal with `io <<` which is clearly a winner for me regarding the syntax.

I think `>> io` should have the same issues of `io <<`, but since it is not so widely used, we don't care too much (?).

Regarding `%io`, it will be `io << %io{...}` which is not so nice. 
Something like `io << %<<{...}` hurts even more, but it is kind of clear that will interpolate using `<<` instead of generating a string.

**Comment by technorama** [comment]
+1 For making the compiler smarter.  It's a common pattern to io << "str#{i}ng" regardless of to_s/inspect.  
Every new language concept makes the language harder to use, especially for new developers.  Crystal should focus on expressiveness and not performance annotations.  Do we want a complex language that's impossible to learn all of like c++ or an expressive language that's easy to use?

http://cpprocks.com/cpp-ruby-coffeescript-language-complexity/

Compilers already change strings to constants, instructions are reordered, structs are packed or realigned, etc for performance without requiring the programmer to specify anything.   << "str{i}ng" should be automatically optimized.

**Comment by stugol** [comment]
+1 for maybe making this automatic.

-1 for the suggestion that the language be made simple at the expense of performance. Sure, expressiveness is awesome, but if you're prepared to sacrifice run-time performance, why use a statically-typed language in the first place?

Admittedly, I have previously requested dynamic dispatch on an ```any``` type, but the difference is that I would be able to choose when, and where, to employ it.

**Comment by asterite** [comment]
I'll close this. Everyone seems to have a different opinion, and the current `io << ... << ...` works well and there's no magic.
