### ISSUE TITLE
Disallow def definitions inside conditions

### ISSUE THREAD

**Issue by asterite** [manastech/crystal#1271]
This currently compiles but shouldn't:

```crystal
if 1 == 2
  def foo
    1
  end
end

foo #=> 1
```

Seen [here](http://www.slideshare.net/tmtm/crystal-51973486)

**Comment by jhass** [comment]
Can we allow

```cr
begin
  def foo
  end
#rescue
end
````

while disallowing

```cr
def foo
  begin
    def bar
    end
  #rescue
  end
end
```
etc.?

**Comment by asterite** [comment]
Well...

```crystal
begin
  raise "oops" if some_condition

  def foo
  end
rescue
end
```

I understand this change broke carc.in. A solution is to rewrite the program to put a begin/rescue around the first expressions, and then another one around the last expression, the one you'll print. I actually had to make a change in our [spec_helper](https://github.com/manastech/crystal/commit/fde74a09fd3f49b55287bc69d4e5e037f1780fef#diff-906deee07fd614ba421ecd7a4a66ffd1R163) because I was basically assigning the whole expression to a value and printing it, but now that's illegal.

**Comment by jhass** [comment]
MMh, that gets really hairy really quickly. Can't just split on `;`, since it would break things like `"foo;bar".split(',')"`.
