### ISSUE TITLE
URI.parse failures with URL encoded characters in pathname

### ISSUE THREAD

**Issue by ysbaddaden** [manastech/crystal#1289]
URI.parse raises whenever the pathname of a URI contains an urlencoded character (like `%3A` or `%20`).

```crystal
URI.parse("http://test.dev/a%3Ab")
# => bad URI(is not URI?): http://test.dev/a%3Ab (Exception)
```

Whereas in Ruby:
```ruby
URI("http://test.dev/a%3Ab").path
# => "/a%3Ab"
```

This doesn't affect the query string, thought:
```crystal
URI.parse("http://test.dev/search?q=a%3Ab")
# => #<URI:0x2094e40 @scheme="http", @host="test.dev", @port=nil, @path="/search", @query="q=a%20b", @user=nil, @password=nil, @fragment=nil, @opaque=nil>
```

**Comment by will** [comment]
It might be a difference between pcre and oniguruma. I pulled the regexs from ruby, and they're the same except for lowercase group names.

**Comment by asterite** [comment]
The problem was that `\h` doesn't exist in PCRE.

**Comment by will** [comment]
Good to know, thanks!
