### ISSUE TITLE
responds_to? not working properly in Modules

### ISSUE THREAD

**Issue by alanwillms** [manastech/crystal#1308]
The following code will fail, unless I call `self.responds_to?` instead of `responds_to?`:

```ruby
module SomeLength
  def responds
    responds_to?(:foobar) # fails here
  end
end

class Items
  extend SomeLength

  def self.foobar
    "Any return"
  end
end

puts Items.responds.to_s
```

* Bug: http://carc.in/#/r/d1k
* Workaround: http://carc.in/#/r/d1j

**Comment by alanwillms** [comment]
I am not sure if this is related, but `responds_to?` does not accept `Symbol` in this way. I tried to use `Macros::SymbolLiteral` as well, but it still fails:

```ruby
module SomeLength
  def responds(method_name : Symbol)
    self.responds_to?(method_name) # Syntax error: 'responds_to?' argument must be a Symbol literal
  end
end

class Items
  extend SomeLength

  def self.foobar
    "Any return"
  end
end

p Items.responds(:foobar)
```

**Comment by lbguilherme** [comment]
@alanwillms It's because `responds_to?` is a compile-time method, it is not evaluated at runtime. So the compiler must have a literal there to work with. This is a feature™ .

**Comment by alanwillms** [comment]
Thank you @lbguilherme :smile: 

What about the first issue, is it a bug or a newbieness?

**Comment by asterite** [comment]
@alanwillms Yes, after some though I classify this as a bug. Right now the parser just checks for `is_a?` and `responds_to?` with a receiver (like in `obj.is_a?`), but never without one. But it should work.
