### ISSUE TITLE
Bug: Macro expansion in comment

### ISSUE THREAD

**Issue by MakeNowJust** [manastech/crystal#1318]
http://carc.in/#/r/d44

```crystal
macro m
  # {{ not_defined }}
  10
end

m
```

```
Error in line 5: expanding macro

in line 2: undefined macro variable 'not_defined'
```

Macro expansion in comment doesn't need expand!

(Note: By same problem, #1317's code can't execute)

**Comment by jhass** [comment]
Well, it's not a bug it's a feature. Doing the expansion in the comments too allows you to generate docs for your generated code alongside.

Maybe we can find a special comment syntax for macros, either one where expansion is explicitly disabled or explicitly enabled.

**Comment by MakeNowJust** [comment]
Thanks @jhass, I'll fix #1317 code and close this issue.

**Comment by MakeNowJust** [comment]
@jhass By the way, where is this function used? Please teach me!

**Comment by asterite** [comment]
For example in [HTML::Builder](https://github.com/manastech/crystal/blob/master/src/html/builder.cr#L73-L89) (a class which started as an experimento with `with ... yield`, I'm not sure it belongs in the std). But I plan to use that feature in HTTP::Client, where we generate methods for each of the HTTP verbs.

But we could, for example, automatically document `getter` to say "Returns the {{name}}", although it would be redundant.

**Comment by MakeNowJust** [comment]
I see.

If I use macro expansions as comment in macros, it may be good to use HTML character entity reference.
