### ISSUE TITLE
Regression in parsing responds_to?

### ISSUE THREAD

**Issue by BlaXpirit** [manastech/crystal#1320]
After commit https://github.com/manastech/crystal/commit/7c72b83b36bbef5ff353ed6708a129a3213e0030 this does not compile anymore

```crystal
a = [1, 2]
if a.responds_to? :[]
  x, y = a
end
```

```
Syntax error in ./test.cr:3: unexpected token: x

  x, y = a
  ^
```

**Comment by asterite** [comment]
It's so good that you guys are constantly testing against HEAD :-)

I introduced this when fixing #1308
