### ISSUE TITLE
Wrong error message when trying to instanciate a Module

### ISSUE THREAD

**Issue by ysbaddaden** [manastech/crystal#1323]
```crystal
module A; end
A.new

# => Error in line 2: undefined method 'new' for A:Class
```

The error states that A is a Class when it's actually a Module.

**Comment by jhass** [comment]
Well, `A:Class` is sort of the meta class of `A`.

**Comment by jhass** [comment]
@ysbaddaden do you stand the message is wrong? What should it say instead?

**Comment by bjmllr** [comment]
It could say `A:Module` instead of `A:Class`, as in Ruby.

```
[1] pry(main)> module A; end
[2] pry(main)> A.new
NoMethodError: undefined method `new' for A:Module
```

**Comment by jhass** [comment]
Granted but probably in the scope of #1150

**Comment by asterite** [comment]
I fixed it because it was pretty simple and it's true that it provides a bit more information about the type that doesn't have the method.

It's still related to #1150, which shouldn't be that hard to do.
