### ISSUE TITLE
how to make crystal from src ? 

### ISSUE THREAD

**Issue by sevk** [manastech/crystal#1331]
```
▶  make
CRYSTAL_CONFIG_PATH=`pwd`/src ./bin/crystal build  -o .build/crystal src/compiler/crystal.cr
You need to have a crystal executable in your path!

```

there is no  crystal executable in my system , how to do this ? it is impossible ...

thanks

**Comment by jhass** [comment]
Please [install](http://crystal-lang.org/docs/installation/index.html) a released version of crystal first.

**Comment by rdp** [comment]
I guess the problem/concern here is that the install instructions don't mention you need crystal already installed.  My current problem being that I'm on cygwin which has no previous install of crystal possible, I'm going to assume I'm supposed to go back to crystal "pre crystal being written in crystal" to build a crystal to (build crystal)...are there any instructions for that anywhere?

**Comment by asterite** [comment]
@rdp We use [cross compilation](https://crystal-lang.org/docs/syntax_and_semantics/cross-compilation.html) to bootstrap the compiler into other platforms

**Comment by rdp** [comment]
for followers, this appears to mean compiling crystal itself a la 

$ crystal build -o ./build/cross_crystal src/compiler/crystal.cr  --target x86_64-macosx-darwin

where the target options are the directories in ./src/lib_c
