### ISSUE TITLE
Debugging runtime segfaults when interfacing with library, that allocates memory itself?

### ISSUE THREAD

**Issue by waterlink** [manastech/crystal#1342]
I thought the problem might be related to `structs` I define in `lib` declaration. For my purposes I need only one of three, that is why:

- first, mapped out fully, and its `sizeof(typeof(T))` is equal to `sizeof` result in analogous C program;
- second (`U`) and third (`V`) are aliased as `Void` (and used only as pointers, ie: `U*` and `V*`).

Is my assumption about `U` and `V` correct, that they can be safely aliased as `Void` in that case?

Segfaults happen in random places depending on different circumstances (passed `-v` to specs for example). Running under `valgrind` and `gdb` makes a difference too. But these segfaults always start as a string manipulation (builder or regexp scanning) and end up in `GC_generic_malloc_many`.

Additionally, if I run only couple of specs (with `-e` option) including segfaulting spec, it just successfully passes.

Here is the example output from `valgrind`:

https://gist.github.com/waterlink/d5cc21c32b4cc3197469

---

Is there any tips on how to debug such issues?

---

This happens only on linux (my machine + travis), but works without problems on Mac OS X (might be different platforms or library implementations).

My environment:

```bash
 ⇒ crystal --version   
Crystal 0.7.6 [eb13f75] (Thu Aug 13 21:51:12 UTC 2015)

 ⇒ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"

 ⇒ uname -a
Linux home-laptop 3.19.0-031900-generic #201502091451 SMP Mon Feb 9 14:52:52 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

# Version of the lilbrary I use bindings for:
 ⇒ mysql --version                      
mysql  Ver 14.14 Distrib 5.5.40, for debian-linux-gnu (x86_64) using readline 6.3
# libmysqlclient-dev version is the same `5.5.40`
```

**Comment by waj** [comment]
I read many times that Valgrind doesn't play nice with the GC and raises many false alarms. I found this thread for example: http://www.hpl.hp.com/hosted/linux/mail-archives/gc/2006-May/001286.html

Can you share some output from gdb?

The kind of issues that you're chasing really sucks, because the place where the problem really is could be far from where it explodes.

If the problem disappears while running with GC_DONT_GC=1, then it might be possible that one of the pointers to structs allocated by the GC is not reachable by the GC anymore. This might happen for example if you pass a pointer to a Crystal object to a external library, but then the native library holds the reference inside a block of memory not handled by the GC.

**Comment by waterlink** [comment]
This is the output from `gdb`: https://gist.github.com/waterlink/03240d38ecdd03f2b817 - to me looks pretty the same.

**Comment by waterlink** [comment]
Both with `GC.disable` inside of crystal code or with `GC_DONT_GC=1` as an environment variable, it works without problems: https://gist.github.com/waterlink/e0a49243a11e4159028c

That is the script I use to build and run my integration specs `./bin/test`:

```bash
#!/usr/bin/env bash

set -e

crystal spec
crystal build integration/integration_spec.cr -o integration/integration_spec -D active_record_adapter
./integration/integration_spec --fail-fast -v $*
```

**Comment by waterlink** [comment]
Hmm, about references passed to external library. I might as well re-read all this code tomorrow and see if there is a possibility like that.

**Comment by waj** [comment]
Does it happen if you run just the failing test? Start trying to comment out some of the other tests to narrow down the problem. Can you share some code so I can reproduce the problem?

**Comment by waterlink** [comment]
Here is the code: https://github.com/waterlink/mysql_adapter.cr, to repro: run `./bin/test` after `crystal deps`.

If I run just segfaulting test (or 2-3 more) tests they succeed. But if I run more of them, they segfault.

**Comment by waterlink** [comment]
Integration tests themselves are here: https://github.com/waterlink/active_record.cr/blob/master/spec/active_record_spec.cr - they are run in `mysql_adapter.cr` with different substituted adapter.

**Comment by waterlink** [comment]
https://github.com/waterlink/mysql_adapter.cr/blob/master/script/setup-test-db.sh - this re-creates required mysql database structure for test. You may want to provide it `$MYSQL_USER` and/or `$MYSQL_ASK_PASS` environment variables before running it. PS: see `.travis.yml` too.

**Comment by waterlink** [comment]
Forget about that: the library itself that probably causing problems is here https://github.com/waterlink/crystal-mysql/tree/small-lib-ext-fixes (yes, it is a feature branch for now, since I was trying to fix this issue already for quite some time)

**Comment by waterlink** [comment]
BTW: travis build fails, because of some troubles with `apt-get update`: https://travis-ci.org/waterlink/crystal-mysql/builds/78145832

**Comment by waj** [comment]
So... did you manage to find the problem? Can we close this issue then?

**Comment by waterlink** [comment]
I haven't taken a look since yesterday. I will look into it soon (tomorrow) (I decided to take a little context-switch from this frustrating segfault and do something different).

On the other hand, if you consider this issue a Question. Then my questions I have raised are answered. Though my problem is not fixed yet. So I think it is safe to close issue. If needed I can always ask to re-open or create new one in case of new findings.

**Comment by asterite** [comment]
@waterlink I can help you find the segfault. I tried running the specs in https://github.com/waterlink/crystal-mysql/tree/small-lib-ext-fixes and they pass. I also try the ones in mysql_adapter and they all pass except one (I get "Error: Unknown column 'number_of_dependents' in 'field list',"). But no segfaults.

**Comment by waterlink** [comment]
For `mysql_adapter.cr` you first need to run script that creates correct
tables. It doesn't have failures currently (should be fully green on mac os
x, but segfault on linux).

--
Best Regards,
Alexey Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

2015-09-02 0:56 GMT+02:00 Ary Borenszweig <notifications@github.com>:

**Comment by waterlink** [comment]
@asterite forgot to mention which exactly script to run, look into `.travis.yml` for that: https://github.com/waterlink/mysql_adapter.cr/blob/master/.travis.yml

**Comment by waterlink** [comment]
Finally I have found the problem!

**Comment by waterlink** [comment]
Was able to find it because of suggestion from @waj about "passing GC-controlled pointer to the library".

I have just looked up each call to `LibMySQL` and tried to explain what is happening there and what gets passed to library.

Found this and was shocked: https://github.com/waterlink/crystal-mysql/blob/21c1518e320e1398ca2aa04d79aee0eb181ef362/src/mysql/support.cr#L5-L9

Specifically:

```crystal
new = Pointer(UInt8).malloc(0)
```

Which reads as allocate `0` elements of `UInt8`. And then write there a string from library. Super safe operation :D

Fix is simple, is to allocate enough. Thankfully mysql docs say how much exactly is required in the worst case scenario - `length*2+1`.

Problem was not about passing in `GC-controlled` pointer, but more about doing very dumb `malloc` call..

**Comment by waterlink** [comment]
Yay!: https://travis-ci.org/waterlink/mysql_adapter.cr/builds/78491581

Closing the issue as resolved.

**Comment by waterlink** [comment]
BTW, should it even be a valid `malloc` with `0` elements in any situation? Could it be that it is possible to forbid `0` value there? Currently it forbids only negative ones.

**Comment by asterite** [comment]
Malloc with 0 should raise in my opinion. I think we "knew" this issue at one point but then forgot about it.

**Comment by waterlink** [comment]
+1

**Comment by kirbyfan64** [comment]
+1. The C standard doesn't define what malloc with 0 returns, provided it can be freed, so this is something that really should be done.

**Comment by asterite** [comment]
Mmm... given that `Pointer.malloc` allocates memory from the GC and is automatically freed, or you can free it with `GC.free`, I wonder if maybe it's better if `Pointer.malloc(0)` returns a valid pointer. If you ask for 0 bytes than you can't put/get anything from there anywhere, but that shouldn't mean it should raise.

I'm saying because right now you can do:

```crystal
Slice.new(10, 3)
```

and that allocates a 10 integers initialized to 3, and gives you a slice. Slice does bound checking so you can't access beyond those 10 elements. Now, maybe this should work:

```crystal
Slice.new(0, 3)
```

I ask for 0 elements, and I should get a slice anyway. I won't be able to read/write it, but I can ask it's length, if it's empty, etc., but maybe that operation shouldn't fail. And since `Slice.new` uses `Pointer.malloc`, maybe `Pointer.malloc(0)` shouldn't fail.

Of course, the mysql code above will still fail, but I think that was a wrong usage of the API.

**Comment by waterlink** [comment]
Sounds fair to me.

**Comment by technorama** [comment]
The Open Group does define what malloc(0) can return:  
> If size is 0, either a null pointer or a unique pointer that can be successfully passed to free() shall be returned.

free(NULL) is undefined and implementation specific.  So the return of malloc(0) depends on what free() can handle.  A pointer than can be freed is always safe.  NULL is only valid if free() handles NULL.

**Comment by kirbyfan64** [comment]
@technorama If you can call that *defining* it...

**Comment by jhass** [comment]
And I'm not sure we should abide it here, both behaviours hide bugs. I can imagine a case or two where an empty Slice makes sense since you can treat it like an empty collection. But an empty pointer not so much. Creating one will be a logic bug more often than not, disallowing it seems sane. Likewise freeing a nullpointer is an application bug and shouldn't be swallowed.

**Comment by waj** [comment]
Please, let's continue the discussion in #1355
