### ISSUE TITLE
Wrong full type name in types contained in generic class

### ISSUE THREAD

**Issue by bcardiff** [manastech/crystal#1358]
http://play.crystal-lang.org/#/r/dmu

```crystal
class Bar(T)
  class Foo
  end
end

puts Bar::Foo.to_s # => Bar(T)::Foo
```

expected
```
puts Bar::Foo.to_s # => Bar::Foo
```

**Comment by kirbyfan64** [comment]
I'm guessing someone just needs to change [this line](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/macros/methods.cr#L742) to:

```crystal
interpret_argless_method(method, args) { MacroId.new(type.to_s.gsub(/\(.*?\)/g, '') }
```

?

**Comment by asterite** [comment]
@kirbyfan64 Almost. `type.to_s` is the one giving the incorrect result, and might be called from other places. This should be fixed somewhere [here](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/types.cr).

**Comment by kirbyfan64** [comment]
@asterite [`types.cr`, line 1515](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/types.cr#L1515)? I can do a PR if wanted.

**Comment by kirbyfan64** [comment]
@asterite Wait, that can't be changed. That's what the compiler uses to give error messages.

**Comment by bcardiff** [comment]
There should be no problem changing that. 

When using a GenericClass as a container we should skip the type args. An additional flag to skip type_args is probably needed in [line 482](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/types.cr#L482) something as skip_union_parens.

**Comment by bcardiff** [comment]
Yet I would prefer not to be able to instantiate a `Bar::Foo` but `Bar(Int32)::Foo`. But that's a different discussion. With the current semantics this issue is a bug.
