### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by devdazed** [manastech/crystal#1361]
Hi, I am looking to contribute and wanted to get my feet wet by creating the `#select` method from Ruby's `Hash`. The following code works in the playground

```
class Hash
  def select(&block : K, V -> U)
    hash = {} of K => V
    each do |k, v|
      hash[k] = v if yield k, v
    end
    hash
  end
end

a = {a: 1, b: 2, c: 3}; puts a.select{|k, v| k == :a}
```

However when I add that method directly to `hash.cr` and compile then try to run using

```
$ ./.build/crystal eval "a = {a: 1, b: 2, c: 3}; puts a.select{|k, v| k == :a}"
```

I get the following output:

>ld: library not found for -levent
>clang: error: linker command failed with exit code 1 (use -v to see invocation)
>Error: execution of command failed with code: 1: `cc -o /Users/rbradberry/Projects/open_source/crystal/.crystal/crystal-run-eval.tmp "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/main.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Array40Int3241.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/String5858Builder.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/GC.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/String.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Slice40T41.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Slice40UInt841.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Math.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Int32.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Pointer40UInt841.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/IndexError.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/ArgumentError.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Pointer40LibABI5858UnwindException41.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/UInt64.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Array40String41.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Exception.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/StaticArray40UInt844326541.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/DivisionByZero.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Pointer40String41.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Pointer40Int3241.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Array40Pointer40Void4141.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Pointer40Pointer40Void4141.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Fiber.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Pointer40Void41.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Array40Fiber41.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Pointer40Fiber41.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Event5858Base.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Int64.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Scheduler.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/FileDescriptorIO.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Bool.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Errno.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/LibEvent25858EventFlags.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Event5858Event.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/IO5858Timeout.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Signal.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/40Int3232456232Void41.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Event5858SignalHandler.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/AtExitHandlers.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Array404032456232Void4141.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Pointer404032456232Void4141.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/StaticArray40UInt84432441.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/UInt8.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Exception43.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/ChannelClosed.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/TimeFormat5858Error.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/GlobError.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/IO5858EOFError.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/IO5858Error.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/KeyError.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/InvalidByteSequenceError.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/DomainError.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/EmptyEnumerable.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Hash40Symbol4432Int3241.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Pointer40Hash5858Entry40Symbol4432Int32416341.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Hash5858Entry40Symbol4432Int3241.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Hash5858StandardComparator.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Hash40123UInt644432Symbol1254432Bool41.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Pointer40Hash5858-87b25e50fb3d0d3b5c5052fe12251c97.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/123UInt644432Symbol125.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Hash5858Entry40123UInt644432Symbol1254432Bool41.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Symbol.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Range40B4432E41.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Range40Char4432Char41.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/Char.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/CharReader.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/UInt32.o" "/Users/rbradberry/Projects/open_source/crystal/.crystal/eval/LEBReader.o"   -levent -lpcl -lpcre -lgc -lpthread

Any advice?

Thanks

**Comment by kirbyfan64** [comment]
You need to install libevent first.

**Comment by devdazed** [comment]
Thanks, is there a list of other required libraries I need to install? 






On Thu, Sep 3, 2015 at 3:13 PM -0700, "Ryan Gonzalez" <notifications@github.com> wrote:












You need to install libevent first.

**Comment by bcardiff** [comment]
Yes https://github.com/manastech/crystal/wiki/All-required-libraries

Happy crystalling!

On Thu, Sep 3, 2015 at 7:16 PM, Russ Bradberry <notifications@github.com>
wrote:

> Thanks, is there a list of other required libraries I need to install?
>
>
>
>
>
>
> On Thu, Sep 3, 2015 at 3:13 PM -0700, "Ryan Gonzalez" <
> notifications@github.com> wrote:
>
>
>
>
>
>
>
>
>
>
>
>
> You need to install libevent first.
>
>
>
> —
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/manastech/crystal/issues/1361#issuecomment-137588917>.
>



-- 
Brian J. Cardiff - Manas Technology Solutions
[ar.phone] 4796.0232 #BCR(227)
[us.phone] 312.612.1050  #BCR(227)
[email] bcardiff@manas.com.ar
[web] www.manas.com.ar
[weblog] http://weblogs.manas.com.ar/bcardiff/

**Comment by kirbyfan64** [comment]
@bcardiff 

> Happy crystalling!

That one's new. :O

**Comment by devdazed** [comment]
Thanks! I appreciate the help!






On Thu, Sep 3, 2015 at 3:20 PM -0700, "Ryan Gonzalez" <notifications@github.com> wrote:












@bcardiff 




Happy crystalling!




That one's new. :O

**Comment by asterite** [comment]
@devdazed Note that the block signature in the method is not needed, so this also works: http://play.crystal-lang.org/#/r/dn4 (the compiler knows the method receives a block because it yields). Or, if you want to say that there's a block, you can simply do so but, again, there's no real need to specify types (you can always do so to verify that you are yielding the correct types, though): http://play.crystal-lang.org/#/r/dn5

I'm closing this because I suppose installing the required libraries fixed your problem, but if not please reopen.

**Comment by waj** [comment]
@devdazed: I noticed you are invoking the compiled compiler directly. Instead use the "bin/crystal" wrapper and the error should go away without installing any library. The reason is when you install the binary package of Crystal it already comes with some binary dependencies. But these are not in the build path by default and the wrapper script will do just that for you.

**Comment by devdazed** [comment]
I tried `bin/crystal` and got the same error, but after installing all the dependencies in the wiki things are working now.

Thanks
