### ISSUE TITLE
`-f` Parameter for Build

### ISSUE THREAD

**Issue by k2b6s9j** [manastech/crystal#1384]
I love the new tooling stuff in 0.7.7, thanks @bcardiff, but one of my favorite parts of this might have to be the ability to choose between Plain Text and JSON for Result Format. Could this extend to the results of the build command?

**Comment by jhass** [comment]
You mean you'd like any error output in a parsable format/JSON?

**Comment by k2b6s9j** [comment]
Yeah, so that compilation errors and warnings are parseable in JSON.

**Comment by bcardiff** [comment]
Thanks @k2b6s9j :-) Any atom related feedback (in the appropriate repo ;-) ) is welcome since I installed it only for the crystal-tools package.

Usually crystal error outputs aim for a nice console display, colors, ^^^^ indicators, etc.

Is there anything in particular you would benefit from by adding json output? Something painful for the linter package maybe?

I don't know any compiler that use that for errors and lots of editors/IDE are highlight the locations of errors.

**Comment by k2b6s9j** [comment]
How'd you know it was for Linter? :smile: But yes, in all seriousness, it would allow me to move away from parsing the information, using RegExp, I need from the console, to pulling the information I need right from JSON fields. Finding line position of an issue as a numeric value in a JSON field would be incredibly helpful. I can think of a couple other uses cases as well, but that is the first one to come to mind.

IIRC the [Hack](https://github.com/facebook/hhvm) "compiler" allows for JSON output for it's compilation issues.

**Comment by asterite** [comment]
I think JSON output should be fairly easy to do. All the logic to convert an error into a human-readable string is [here](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/exception.cr). We would only need to implement a `to_json` method. Then parsing this info becomes trivial :-) (and more in Atom ;-))

**Comment by k2b6s9j** [comment]
Awesome! This will let me clean up and optimize `linter-crystal` and move on to better Crystal IDE things I have in mind. The new tool commands will be very helpful in that regard. :wink:

**Comment by asterite** [comment]
I'm thinking the JSON output will be something like:

```json
[
  {
    "file": "foo.cr",
    "line": 1,
    "column": 2,
    "length": 3,
    "message": "undefined method 'x'"
  },
  {
    "file": "bar.cr",
    "line": 1,
    "column": 2,
    "length": 3,
    "message": "undefined method 'x'"
  }
]
```

"length" will allow you to show squiggles, if your editor supports that. Sounds good?

**Comment by k2b6s9j** [comment]
I like it. I'm trying to decide if the file field should be relative or absolute though.

**Comment by kirbyfan64** [comment]
So, I've been looking for some way to contribute to Crystal. Could I try to tackle this?

**Comment by bcardiff** [comment]
+1 Absolute paths. Errors might come from crystal sources or libs. the editor should make them relative if possible.

**Comment by k2b6s9j** [comment]
Linter will make all file relative when viewed in it's panel, but for this providers must provide it with absolute paths, so I guess I'll :+1: absolute paths as well.

**Comment by asterite** [comment]
@kirbyfan64 Absolutely! And if you get stuck, ask for help :-)

My only doubt is the `-f` name for the flag, could we use something longer like `--error-format`? In case we want to reserve `-f` to mean something else and more common... the long flag doesn't matter because a machine will be using it :-P

**Comment by k2b6s9j** [comment]
`--console-format`?

**Comment by k2b6s9j** [comment]
Oh! Maybe an optional type field? That way there can be different types of errors, like `Syntax Error`, but still default to `Error` if nothing is supplied.

**Comment by asterite** [comment]
But this will be used for errors, the compiler doesn't speak anything else. Well, if you pass `--verbose` it will output the linker command, but you wouldn't want `--console-format` to affect that.

As for the error type, I guess we could make it be:

```json
{
  "type": "syntax",
  "errors": [ 
  ]
} 
```

"type" can be "syntax" or "semantic".

**Comment by kirbyfan64** [comment]
Isn't `-f` already used for controlling [output format](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/command.cr#L375)?

**Comment by k2b6s9j** [comment]
@asterite I guess differing types doesn't really make sense for this. Let's just stick with the scheme we already had, no types. Everything will be an error.

@kirbyfan64 That's for @bcardiff's Tool Commands. Which inspired this.

**Comment by asterite** [comment]
Right, but if it's just for the tools I'd prefer those names to be longer. Or we can change them later, along with the tools, so you can use `-f` and `--format` for now.
