### ISSUE TITLE
[RFC] Feature proposal: allow HTTP::Request/Response to work with parameters and cookies

### ISSUE THREAD

**Issue by waterlink** [manastech/crystal#1392]
```crystal
class Request
  # Returns query parameters as hash parsed from url like:
  # "/api/v3/users?since=12-07-2014&trusted=false"
  # Operates lazily: should not parse anything unless called
  def query_parameters : Hash(String, String) ... end

  # Returns request parameters as hash parsed from body like:
  # "since=12-07-2014&trusted=false"
  # valid only if "Content-Type: application/x-www-form-urlencoded"
  # Operates lazily: should not parse anything unless called
  def request_parameters : Hash(String, String) ... end

  # Returns request cookies as hash parsed from "Cookie" header
  # Operates lazily: should not parse anything unless called
  def cookies : Hash(String, String) ... end
end

class Response
  # Sets cookie for response
  def set_cookie(key, value, secure=false, http_only=false, path="", domain="", expires="") ... end
end
```

WDYT? Is it a valid point that such methods should be in language's stdlib?

**Comment by jhass** [comment]
See #1252

**Comment by waterlink** [comment]
@jhass WDYT, should such methods return raw hashes (`Hash(String, String)`) or some kind of object, i.e. `HTTP::Params` and `HTTP::Cookies` ?

**Comment by waterlink** [comment]
#1252 Unfortunately Looks stalled to me :( Would love to see it fixed in terms of CR and accepted as a PR, of course :)

**Comment by jhass** [comment]
I think I see no real benefit in custom types here. Keep in mind the more types you add the more you have to know, "a X? What's that? Okay I can treat it as a Hash" is a significant overhead over "okay looks like a hash".

**Comment by waterlink** [comment]
Makes sense. Application/Library code may always wrap it in its own class if needed.
