### ISSUE TITLE
Encapsulated Require System

### ISSUE THREAD

**Issue by trans** [manastech/crystal#140]
While Ruby's require system is nice for it simplicity, it is seriously lacking for encapsulation. It would be nice to see a system that supported this.

To clarify what I am talking about, instead of loading code at the top level, one would assign the required code and then access it via a variable or constant. To differentiate this from require, lets call it "acquire". e.g.

```
 MyFoo = acquire('foo')
 MyFoo::Foo.new
```

This is like the require systems used by Lua and Node.js and such.

**Comment by jhass** [comment]
-1

I think it just doesn't fit the semantics of the language as #767 and similar show, disambiguating which monkey patch should affect what, how which constant should be looked up after namespacing etc while not damaging the open class system is just too hard, for both the compiler but also the user of the language.

I therefore vote to reject this, drop the existing namespacing behaviour that `require` has and to disallow `require` anywhere outside the toplevel.

**Comment by ysbaddaden** [comment]
-1 for me too.

I stand with @jhass. I vote for require to always be global, to avoid confusion and inconsistencies. When I open a file, I want to see the actual namespaces and classes when I'll require it, either directly or throught another require. Non global requires may only make sense within ifdef or maybe inside macros.

BTW: refinements in Ruby have been there for 2 years. I feel that nobody uses them, and everybody forgot about them...

**Comment by deathbeam** [comment]
+1 I second this as I am coming here from Lua background, which had this system for globals from requires before, but now it is deprecated. What about syntax like this:

```
require(`foo`) as Bar
```

So it will require it as alias but it will still have Ruby-styled principe for globals from requires.

**Comment by jhass** [comment]
Side note: Refinements do change the global view but localize that change to a single file, that's vastly different from changing the namespace of things and something I wouldn't oppose.

**Comment by asterite** [comment]
I'm closing this, we won't change the require system. We might introduce a concept similar to refinements if we later find the need for it.

**Comment by trans** [comment]
:disappointed:

**Comment by rdp** [comment]
(I guess the proposal here is to do what python does, which is everything is defined in a "file local" namespace, except vars declared global, +1 here):

Hmm it seems to me like monkey patching can still work 

```
require "a/b", "B"

def B.my_new_method

end

```

ref: https://groups.google.com/d/msg/crystal-lang/Yid3gQnlKyI/oS4eLDh2AAAJ

**Comment by ozra** [comment]
This is a very good thing (TM) - but it should _allow_ flexibility.

**Some propositions**
- Requiring a module is "assigned" to a module/namespace reference which is by default _local to the file_
- The module can be "opened" via the usual `include`/`extend` - _local to file_ to avoid prefixing.
- The module can _also_ be explicitly exposed program wide, and of course "opened" program wide, if one really wants too (working the Ruby-way).
- Any _decent_ library _should_ require modules into _local space_ - thereby not leaking deps in to global space for discriminating users (with the obvious exception of libs one _definitely_ want super accessible in more DSL'ish scenarios - specs or so)
- Monkey patching works just as well as before (any module required is re-used over and over, if required again in the same program, so any patches done to it, even though through a local "namespace/module reference", is accessible in all units requiring it.)
   - this is how monkeypatching is done in Lua and NodeJS (_even though "modules" in them are of course just common table/hash-values - in Crystal it is resolved on a compile time "level"_).
- A `using` ("with") clause which I've proposed before, it also very useful: "opening" modules in an explicit lexical `using` scope.

**Motivations**
- Making sure every file specifies its' requirements is very healthy for dependency and program integrity and quickly reveals structural problems.
- Makes it much easier to ensure separation of concerns and refactoring code into packages
   - Continually refactoring large codebases into sub-packages is a very desirable process
   - we want to avoid large monolith sourcebases with interdependencies to-and-fro all over the place
   - improves testability, narrows range of possible erroneous combinations of invocation
   - makes it easier to share distinct functionalities _increasing usage exposure and thereby also contributions_ - speeding up evolvment of the entire lib/program.
- For those who don't like it, or for prototyping / whipping up a quick "just need it to do its' shit"-cli-command one can simply have a "main-include" or directly in a main-file, all requirements program-globally exposed.
- _Alternatively - though loosing a lot of promise of security would be to have it work like now by default and add a require-modifier to make the references file-local._
   - Any unwanted "leaks" would then have to be identified with a flag to the compiler (`--hints`, `--warnings` or such)

**I see only pros to _extending Crystal_ with this stabilizing feature.**

**Comment by chocolateboy** [comment]
Almost all of the comments here (including, confusingly, later comments by the OP) are (negative) responses to a proposal to *change the semantics of `require`*, which are understandable, but **not** what this issue initially proposed:

> To **differentiate this from require**, lets call it "acquire".

Since this discussion has wandered away from this topic, I've opened a new one [here](4439) to discuss implementing a *new method* which complements `require` rather than replacing it.
