### ISSUE TITLE
XML module does not support HTML5

### ISSUE THREAD

**Issue by dimparf** [manastech/crystal#1404]
When parse HTML document with HTML5 tags this error occuried: 
Test code:
```crystal
 html5 = "<html><body><nav>Test</nav></body></html>"
 XML.parse_html(html5)
```
<pre>
Error:
Tag nav invalid
       *Exception@Exception#initialize<XML::Error, String>:Array(String) +56 [0]
       *XML::Error#initialize<XML::Error, String, Int32>:Array(String) +46 [0]
       *XML::Error::new<String, Int32>:XML::Error +155 [0]
       *XML::Error::new<Pointer(LibXML::Error)>:XML::Error +76 [0]
</pre>

**Comment by jhass** [comment]
Since Nokogiri is fine with it and both use libxml2 we're probably just missing a flag or something.

**Comment by dimparf** [comment]
I installed a crystal 0.7.7 according to the official instructions for Ubuntu (http://crystal-lang.org/docs/installation/on_debian_and_ubuntu.html).

**Comment by asterite** [comment]
Nokogiri seems to relax all errors, but still produce a node tree:

```ruby
require "nokogiri"

doc = Nokogiri::HTML("<html><body><nav>Test</nav></body></html>")
p doc.errors #=> [#<Nokogiri::XML::SyntaxError: Tag nav invalid>]
```

Maybe we should do the same. My "problem" with this approach is that you need to explicitly check for errors. The "nav" tag is here in not an error, but other "real" errors would go into this property. But at least it's better than not being able to parse these things.

**Comment by asterite** [comment]
I just fixed this. Now it doesn't raise and you can get the errors with the `errors` property. Check the specs in the above commit.

**Comment by dimparf** [comment]
Thanks, asterite!

**Comment by dylandy** [comment]
How do I install the nokogiri module within crystal lang?
I have no idea about it.

**Comment by ysbaddaden** [comment]
You don't. Use the XML module from stdlib.
