### ISSUE TITLE
File name / command ambiguity

### ISSUE THREAD

**Issue by beno** [manastech/crystal#1412]
Currently (0.7.7) filenames are preferred over subcommands and this leads to name clashes. For instance, having a shell script named `build` prevents the subcommand `crystal build` from being called. Instead, Crystal will try to compile the shell script.

**Comment by vyp** [comment]
+1. I think this should be the other way, i.e. subcommand > files. And if we really want to compile and run a crystal file called build, `crystal ./build`.

**Comment by MakeNowJust** [comment]
Is it like git? (for example, `git pull` calls `git-pull` shell script)

**Comment by beno** [comment]
The fix is actually quite simple, but I don't have everything set up to compile and run the tests.

https://github.com/manastech/crystal/blob/master/src/compiler/crystal/command.cr 

@MakeNowJust no, there are none of these shortcuts in place as far as I can tell.

**Comment by MakeNowJust** [comment]
@beno I understand your sense.

**Comment by asterite** [comment]
Fixed by #1414
