### ISSUE TITLE
Feature request: tuple expansion in blocks

### ISSUE THREAD

**Issue by colinmarc** [manastech/crystal#1415]
Sorry if this has already been brought up somewhere.

In ruby, all of the following three snippets of code produce the same output:

```ruby
arr = (0..10).each_cons(2)
arr.each { |a, b| puts "from #{a} to #{b}" }
```

```ruby
(0..10).each_cons(2) { |a, b| puts "from #{a} to #{b}" }
```

```ruby
(0..10).each_cons(2) { |tuple| puts "from #{tuple[0]} to #{tuple[1]}" }
```

Crystal, however, is missing some functionality. The first and third work, but not the second; and the first works only because there's a separate implementation for `each_cons` (and `each_with_index`, `Hash#each`, etc) in order to `yield` two values.

I'm not sure what exactly the right solution is; but since we automatically _compact_ multiple yield values, as in the third example above, I think it would be a reasonable feature to automatically expand them to the right arity, as well.

**Comment by bcardiff** [comment]
Hi,

The issue in github is this one
https://github.com/manastech/crystal/issues/392
Splat a tuple when yielding is not supported yet.

Feel free to +1 it ;-)



On Tue, Sep 8, 2015 at 10:07 AM, Colin Marc <notifications@github.com>
wrote:

> Sorry if this has already been brought up somewhere.
>
> In ruby, all of the following three snippets of code produce the same
> output:
>
> a = (0..10).each_cons(2)
> a.each { |a, b| puts "from #{a} to #{b}" }
>
> (0..10).each_cons(2) { |a, b| puts "from #{a} to #{b}" }
>
> (0..10).each_cons(2) { |tuple| puts "from #{tuple[0]} to #{tuple[1]}" }
>
> Crystal, however, is missing some functionality. The first and third work,
> but not the second; and the first works only because there's a separate
> implementation for each_cons (and each_with_index, Hash#each, etc) in
> order to yield two values.
>
> I'm not sure what exactly the right solution is; but since we
> automatically *compact* multiple yield values, as in the third example
> above, I think it would be a reasonable feature to automatically expand
> them to the right arity, as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/manastech/crystal/issues/1415>.
>



-- 
Brian J. Cardiff - Manas Technology Solutions
[ar.phone] 4796.0232 #BCR(227)
[us.phone] 312.612.1050  #BCR(227)
[email] bcardiff@manas.com.ar
[web] www.manas.com.ar
[weblog] http://weblogs.manas.com.ar/bcardiff/

**Comment by jhass** [comment]
Closing as a duplicate.

**Comment by colinmarc** [comment]
Cool, I will +1 that one =). FWIW, though, that's not exactly the same as what I'm describing - this would work without splatting anything (as it does in ruby).

**Comment by jhass** [comment]
Well, we're pretty aware of autosplat and the lack thereof, just undecided on whether to do that or explicit destructing (#132) ;)

**Comment by colinmarc** [comment]
Ah, that's much more what I was getting at. Thanks for the link! =)
