### ISSUE TITLE
As ruby, crystal has open class?

### ISSUE THREAD

**Issue by xdougx** [manastech/crystal#1417]
Im studying this lang, and I'm wondering the possibility to do something like this:
```crystal
class Foo
end

bar = Foo.new
def bar.bar foo_bar
  puts "this is a '#{foo_bar}'"
end

bar.bar "Foo Bar"
=> this is a 'Foo Bar'
```

is this possible?

**Comment by asterite** [comment]
This is a duplicate of #238. You can read/continue the discussion there :-)

**Comment by asterite** [comment]
But the short answer is that for now we have no plans to implement this.

**Comment by jhass** [comment]
Note the related concept in Ruby is called singleton class. The open class model is what allows

```cr
class Foo
  def foo
  end
end

class Foo
  def bar
  end 
end

**Comment by xdougx** [comment]
Yeah, I was wondering about this feature because i was studying the Crystal `active_record.cr`, with this feature, work with schema is going to be more clean then define `field` on class as `MongoID` on ruby.
But looking for this feature as I said https://github.com/manastech/crystal/issues/238#issuecomment-138600185, Singleton Class Concept and Open Class is very useful, but i don't know if is viable to sacrifice performance for it.
