### ISSUE TITLE
segfault on spec/std

### ISSUE THREAD

**Issue by will** [manastech/crystal#1419]
I was trying to just run std lib specs, and ran into this.

```
crystal ➤ bin/crystal spec spec/std -v
Using compiled compiler at .build/crystal
Array
... 
StringIO
  writes
  writes big
  reads byte
  appends to another buffer
  reads single line content
  reads each line
  gets with char as delimiter
  does gets with char and limit
  does gets with limit
  raises if invoking gets with negative limitProgram exited because of a segmentation fault: 11
```

Unfortunately, running just the stringio spec does not reproduce, nor does running all specs.

Also unfortunately, building `require "spec"; require "./spec/std/**" and running through lldb stops at the Signal specs
```
(lldb) run -v
Process 72069 launched: './sp' (x86_64)
Signal
  runs a signal handlerProcess 72152 stopped
* thread #1: tid = 0x12a0be, 0x00007fff8ca97c82 libsystem_kernel.dylib`__kill + 10, queue = 'com.apple.main-thread', stop reason = signal SIGUSR1
    frame #0: 0x00007fff8ca97c82 libsystem_kernel.dylib`__kill + 10
libsystem_kernel.dylib`__kill:
```

So I removed signal_spec, and the segfault went away. "Ah hah!" I thought, signal_spec must be causing problems for string_io_spec. I made a program that was just require "spec" and those two to try and reproduce. No luck, no segfault.

I made a program that manually listed all spec/std/** specs, and it did segfault. My plan was to remove inconsequential specs in a binary-searchish way in order to find the minimal set of specs that cause the segfault. However after a bit of poking, removing _any_ spec, even those after string_io_spec, removed the segfault.

I'm at a loss on how to investigate more, so I'm opening the issue.

**Comment by waterlink** [comment]
I think it would be worth having a link to a gist with smallest list of requires that causes segfault.

**Comment by will** [comment]
@waterlink that's the problem, from the several I tried, removing any file from spec/std no longer segfaults.

**Comment by waterlink** [comment]
Ah, I see. I misunderstood an initial comment a bit, I thought that you had succeed in removing at least some of them..

**Comment by waj** [comment]
@will are you still able to reproduce this issue using HEAD? do you know in which revision this happened?

Because the segfault happened in a spec raising exceptions I suspect this might be related with 7711879a7c568d25686a73c38456234ab94fd375

**Comment by will** [comment]
Things are working on HEAD right now fc87725, so your patch probably did fix it. Thanks!
