### ISSUE TITLE
question: why #inject instead of #reduce?

### ISSUE THREAD

**Issue by jwaldrip** [manastech/crystal#1420]
Question. Why use #inject instead of reduce. I think the common vernacular for users today is reduce. It is confusing to have:

`#map` and `#inject`

it should be one of the following:

`#map` and `#reduce` << my vote

OR

`#collect` and `#inject`

**Comment by bjmllr** [comment]
This was discussed briefly in https://github.com/manastech/crystal/issues/1167

I would prefer that Crystal continues to use `map` instead of `collect`. I'd also prefer `reduce` over `inject`, but I'd like `fold` even better.

**Comment by stugol** [comment]
+1 for `#map` and `#reduce`

`inject` makes no goddamn sense. And I can't even alias it, because there's no `alias_method` keyword in Crystal. Grr.
