### ISSUE TITLE
Specific Exception for "cast to {type} failed" errors

### ISSUE THREAD

**Issue by ysbaddaden** [manastech/crystal#1427]
While traversing a parsed YAML (or JSON, TOML, ...) file, we always have to cast types. The `value as Type` syntax makes it nice to write and read, but in case the cast fails, it raises a generic Exception which makes it hard to rescue to print a nice "Error: invalid file.yml message" instead of the cryptic "cast to Type failed".

I would have propose a pull request, but I'm not exactly sure how to specify the class. See https://github.com/manastech/crystal/blob/master/src/compiler/crystal/codegen/codegen.cr#L876

**Comment by will** [comment]
I took a stab at this, but ran into some problems with the specs.
