### ISSUE TITLE
whether 'abstract' must to guarantee the method implementation?

### ISSUE THREAD

**Issue by OlegTsyba** [manastech/crystal#1429]
Example

    abstract class AbstractClass
        abstract def meth_name
    end
    
    class Someone < AbstractClass
        def some_meth
            puts "i can do it"
        end
    end
    
    Someone.new.some_meth

So, `abstract class AbstractClass` means that this class defines abstract interface and should not be used as the some concrete class, but, what is the meaning of `abstract def meth_name`? Maybe it should guarantee that all descendants must implement this meth_name, but it didn't happen, since  code example has been compiled, or we write `abstract def meth_name` just to explicitly define interface?

**Comment by jhass** [comment]
This is a duplicate of #835.

**Comment by OlegTsyba** [comment]
ok, I didn't find it before start this issue.

**Comment by jhass** [comment]
No worries, this way there's one more way to find it ;)
