### ISSUE TITLE
Dir.glob doesn't support recursive matching using double star ("**") wildcard

### ISSUE THREAD

**Issue by 5t111111** [manastech/crystal#1433]
Although I don't know whether this is intended or not, `Dir.glob` doesn't support recursive matching using double star ("**") wildcard.

when the below directory tree and the program are given:

```text
.
├── dir_b
│   ├── dir_c
│   │   ├── file_c_1
│   │   └── file_c_2
│   ├── file_b_1
│   └── file_b_2
├── file_a_1
├── file_a_2
└── glob_check.cr
```

```crystal
Dir.glob("**/*") do |file|
  puts file
end
```

while when I run this code as Ruby I get:

```bash
$ ruby glob_check.cr 
dir_b
dir_b/dir_c
dir_b/dir_c/file_c_1
dir_b/dir_c/file_c_2
dir_b/file_b_1
dir_b/file_b_2
file_a_1
file_a_2
glob_check.cr
```

as Crystal I get:

```bash
$ crystal glob_check.cr 
dir_b/dir_c
dir_b/file_b_1
dir_b/file_b_2
```

Crystal 0.7.7 on OS X.

**Comment by jhass** [comment]
Yes, unfortunately the backing libc call glob(3) doesn't support it and everybody seems to reimplement it all the time.

**Comment by 5t111111** [comment]
thanks, i see the point.

**Comment by jhass** [comment]
To clarify, we totally want this, it's just that nobody had time or motivation yet to do a full Crystal glob implementation.

**Comment by asterite** [comment]
Yes! We know this now for a long time but it's not a simple thing to do. As @jhass says, we would **really** love having this functionality, though. If somebody want's to tackle this, please let us know! It should be a fun little project, plus it's very easy to test.

**Comment by pgkos** [comment]
I suppose that any glob pattern can be translated into a regex? If yes, then the implementation should be quite easy. We will just match the paths using the regex. Later, we might implement a hand-written glob matcher for efficiency.

If there is a `**` in the pattern, we will recurse infinitely into the subdirectories. If there is no `**`, we can optimize the traversal by counting the depth of the pattern and not recursing too deeply.

**Comment by ysbaddaden** [comment]
Or maybe keep using LibC.glob to match individual files/folders but manually traverse directories on **.
