### ISSUE TITLE
whether the compiler can restrict an argument of several types to the usage of only the common methods?

### ISSUE THREAD

**Issue by OlegTsyba** [manastech/crystal#1437]
First Example:

     def another_meth(b)
         a = 1
         a = "text" if b # => a is (Int32 | String)
         a.length    #  here we can use only the methods defined for both Int32 and String
     end

Second Example:

    class One
        def common
            puts "One#common"
        end
    
        def one
            puts "one"
        end
    end
    
    class Two
        def common
            puts "Two#common"
        end
    
        def two
            puts "two"
        end
    end
    
    def some_meth(o : (One | Two))
        o.common
        o.one
    end

So, when I will write later:

    some_meth(One.new)

All is correct, but later when I write:

    some_meth(Two.new)

then, of course, program is not being compiled.

So, whether the compiler can immediately(at the first method call or right after definition) to understand that argument can be of any types(that is declared for this argument)? and because of this restrict an argument to use only methods what is common for both classes(types).

**Comment by asterite** [comment]
I'm sorry, but I don't understand what's the question.

If it's "can the compiler give a compile error right away in the case of `some_meth`?" the answer is no: before invoking that method someone might reopen `Two` and add a `one` method to it.

**Comment by OlegTsyba** [comment]
@asterite, Ok, this exactly what I mean, I didn't take into account the case with reopening Two.
