### ISSUE TITLE
Document passing nil as C function callback passes null

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#1439]
```cr
lib LibFoo
  alias Function = (Int32 -> Int32)
  fun fake(cb : Function) : Int32
end

LibFoo.fake(Pointer(LibFoo::Function).null)
```
```
Error in line 6: argument 'cb' of 'LibFoo#fake' must be (Int32 -> Int32), not Pointer((Int32 -> Int32))
```
http://carc.in/#/r/eo9

**Comment by asterite** [comment]
You can pass `nil` though. I don't think a pointer should pass.

**Comment by jhass** [comment]
Ah damn, I knew I forgot something. I'll turn this into a doc bug then :P

**Comment by asterite** [comment]
Hm, right, it's not documented. It should probably go [here](http://crystal-lang.org/docs/syntax_and_semantics/c_bindings/callbacks.html). I also see that passing `nil` where a pointer is expected is also not documented.
