### ISSUE TITLE
An example code in the docs' "Generics" doesn't work 

### ISSUE THREAD

**Issue by 5t111111** [manastech/crystal#1453]
In the docs' "Generics" section, there is described the uses of generic types for improving run-time performance along with an example code.

> Although generic types are usually associated with containers, they can also be used to improve execution performance at the cost of a larger executable size. The main trick is to use a generic type to avoid runtime method dispatch. For example there's the standard library's BufferedIO(T):

```crystal
file = File.open("myfile.txt")
io = BufferedIO.new(file) #:: BufferedIO(File)
io.gets
```

https://github.com/manastech/crystal/blob/ebfdafa49d4f67074c54ad8542f6f858b734106e/_gitbook/syntax_and_semantics/generics.md#other-uses-for-generic-types

However, `BufferedIO` is no longer a class, so the above code does not work, and the description isn't correct for the latest Crystal either.

At first I've tried to find an alternative generic class in the standard library, but I have no idea which one is appropriate for the purpose of explaining this kind of uses of generics.

**Comment by asterite** [comment]
I decided to remove that section from the docs ([here](https://github.com/manastech/crystal/commit/a3d264dc499e8f7257b41b42ac2c8c276f95459c)). You can use that "trick" if you understand how generic works, but maybe it's not something to put in the docs and most of the time there won't be a noticeable performance difference.
