### ISSUE TITLE
Allow Proc#call to take splatted array

### ISSUE THREAD

**Issue by trans** [manastech/crystal#1464]
An example to clarify:

```crystal
x = Proc(Int32, Int32, Int32).new { |x,y| x + y }
a = [1,2]
x.call(*a)
```

This give the error: `argument to splat must be a tuple, not Array(Int32)`.

I think it severely limits the usefulness of lambdas if splatted arrays can't be passed in as arguments. Having to use tuples makes many use cases difficult (if not impossible).

**Comment by jhass** [comment]
Could you elaborate on how the compiler should guess the right types from an array? Let's take this example:

```cr
def add(a : Int32, b: Int32)
  a + b
end

def add(a : String, b : String)
  "#{a} #{b}"
end

a = [[1, 2], ["foo", "bar"]].sample
add(*a)
```

**Comment by trans** [comment]
Doesn't the compiler know the type of the array (e.g. `[] of String` or `[] of Int32`)? Can't it use that?

In your example, of course, the sample causes a union type which isn't supported even if they are tuples. (`splatting a union ({Int32, Int32} | {String, String}) is not yet supported`).

**Comment by asterite** [comment]
The compiler knows the type of the array at compile-time, but not it's size.

What happens if you do this?

```crystal
x = Proc(Int32, Int32, Int32).new { |x,y| x + y }
x.call(*ARGV.map(&.to_i))
```

One answer is that the compiler transforms the above to this:

```crystal
x = Proc(Int32, Int32, Int32).new { |x,y| x + y }
temp = ARGV.map(&.to_i)
if temp.length == 2 && (first = temp[0]).is_a?(Int32) && (second = temp[1]).is_a?(Int32)
  x.call(first, second)
else
  raise "wrong number of arguments/incorrect types for proc call"
end
```

However, right now in the language there are no hidden raises when issuing method calls: they either compile and succeed, or don't compile at all. I mean, there's no "undefined method" nor "wrong number of arguments" errors at runtime, only at compile-time. We don't want to break that rule. So in this case you'll have to manually do the above checks.

**Comment by kirbyfan64** [comment]
What if it's explicit, like:

```crystal
unpack_call myfunc, [1, 2, 3]
```

**Comment by jhass** [comment]
@trans so if we support it for methods/procs with uniform argument types, don't you think people will be even more disappointed about being unable to splat to `def foo(a : String, b : Int32)`?

**Comment by trans** [comment]
Since arrays can only be of one type, it is clear why that is not possible. 

However maybe it would be better to back up, and instead of worrying about Proc taking a splatted array, is it possible to allow tuples to be created from arrays? That would take care of this without changing the way Procs work.

**Comment by jhass** [comment]
@will has a trick for that, see #1466

**Comment by jhass** [comment]
Oh and `foo = [] of String|Int32` is perfectly valid.

**Comment by trans** [comment]
@jhass 

> Oh and foo = [] of String|Int32 is perfectly valid.

I realize that but I consider it one type -- a union type.

> @will has a trick for that, see #1466

Unfortunately I don't understand this. Could you break it down into it's most essential form?

**Comment by kirbyfan64** [comment]
Can't you do something like http://play.crystal-lang.org/#/r/f99?

**Comment by jhass** [comment]
@kirbyfan64  yes but notice http://play.crystal-lang.org/#/r/f9w

@trans this is only useful for the cases where you really need it, so it will still involve some metaprogramming boilerplate, but http://carc.in/#/r/f9t

**Comment by trans** [comment]
@jhass Thanks for the break down. It makes sense to me now. But it doesn't work in this case b/c the size has to be given explicitly -- it can't come from a variable.

Consider my use case, which is basically popping arguments off a stack and passing them to a Proc. The number of arguments to pop off and pass depends on the arity of the Proc. I do not know the arity of the Proc b/c it is provided by the library's user.

Now I could do something like:

```crystal
a = a0.shift(aproc.arity)
case aproc.arity
when 0:
    aproc.call
when 1:
    aproc.call(*a2t(a,1))
when 2:
    aproc.call(*a2t(a,2))
...
```

And so on all the way up to some arbitrary maximum that I decide. But doesn't that seem rather silly to have to do that?

**Comment by trans** [comment]
Hmm... I tried to use the "trick" and I am getting a strange error:

```
macro didn't expand to a valid program, it expanded to:

================================================================================
--------------------------------------------------------------------------------
  1.  String.as_cast(a[0]),  String.as_cast(a[1]), 
--------------------------------------------------------------------------------
Syntax error in expanded macro: macro_74729888:1: unexpected token: EOF

 String.as_cast(a[0]),  String.as_cast(a[1]), 
                                              ^

================================================================================

      { {% for i in (0..1) %} String.as_cast(a[{{i}}]), {% end %} }
```

Why `EOF`? That line is not the end of the program.

**Comment by jhass** [comment]
You missed the `{% if true %}` wrapper to enter the macro language so that the opening `{` and `}` of the tuple literal are considered part of the macro expansion and thus interpreted together with the elements.

**Comment by jhass** [comment]
I'm not sure if your library design is possible with Crystal, I'd certainly go as far and call it not idiomatic Crystal tbh. Did you consider ways to unify the signature of the procs? Like passing a value object similar to how one passes a request object to a HTTP server handler?

**Comment by waterlink** [comment]
@7rans Can you provide a link to the code on github (if you have already
pushed it), or at least README.md file with your public API. We might be
able to come up with solution here together, once we understand what kind
of public API you want to provide to the user of a library. I'm pretty
sure, clever macro can do the trick.

--
Best Regards,
Alexey Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

2015-09-14 21:18 GMT+02:00 Jonne Haß <notifications@github.com>:

**Comment by trans** [comment]
@jhass It would be a shame if so b/c it would mean Crystal support for lambdas is very limited.

@waterlink https://github.com/trans/clik/blob/master/src/clik.cr

So I added the `{% if true %}` and LOL :laughing: this compiler is *too* damn smart!

```
splatting a union ({String, String, String, String} | {String, String, String} | {String, String} | {}) is not yet supported

        flag.call(*argt)
```

**Comment by kirbyfan64** [comment]
http://play.crystal-lang.org/#/r/fd0

It's pretty freaking hackish, since I can't figure out how to get the number of arguments a proc literal takes.

**Comment by waterlink** [comment]
I already have almost working version ;) will publish once it compiles.

--
Best Regards,
Alexey Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

2015-09-14 23:11 GMT+02:00 Ryan Gonzalez <notifications@github.com>:

**Comment by kirbyfan64** [comment]
@waterlink Dang!

Another semi-working version: http://play.crystal-lang.org/#/r/fe5. It doesn't actually compile yet either...

**Comment by kirbyfan64** [comment]
GOT IT!!! http://play.crystal-lang.org/#/r/fep

**Comment by kirbyfan64** [comment]
Yeah, it uses blocks instead of procs, but that's arguably better for the intended use case. It basically constructs a temporary proc, so that this:

```crystal
puts call_block(array) { |a, b| a+b }
```

Is compiled to:

```crystal
->() {
    a = array[0]
    b = array[1]
    # Block body is inserted here
    a+b
}
```

:)

**Comment by waterlink** [comment]
So, here you go: http://carc.in/#/r/fex

Quite a long one, almost the same public API that @7rans tries to achieve

--
Best Regards,
Alexey Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

2015-09-14 23:44 GMT+02:00 Ryan Gonzalez <notifications@github.com>:

**Comment by waterlink** [comment]
Cleaned up a bit and added comments: http://carc.in/#/r/fey

--
Best Regards,
Alexey Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

2015-09-14 23:58 GMT+02:00 Alex Fedorov <waterlink000@gmail.com>:

**Comment by waterlink** [comment]
This has small problem, that current scope of blocks is in entirely
different module/class.

I am trying now to mitigate it by defining macro on the fly instead of
classes

--
Best Regards,
Alexey Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

2015-09-15 0:11 GMT+02:00 Alex Fedorov <waterlink000@gmail.com>:

**Comment by waterlink** [comment]
Did it without changing scope: http://carc.in/#/r/ff3

--
Best Regards,
Alexey Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

2015-09-15 0:13 GMT+02:00 Alex Fedorov <waterlink000@gmail.com>:

**Comment by waterlink** [comment]
Another interesting way to do that:
https://github.com/waterlink/clik-playground/commit/226e0f32e5b7cbab6630d6e716145fe11188af68#diff-ccc79beaefc85505f35940c3a2377411L92
- this shows you even more how powerful AST macro can be ;)

--
Best Regards,
Alexey Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

2015-09-15 0:41 GMT+02:00 Alex Fedorov <waterlink000@gmail.com>:

**Comment by trans** [comment]
Those are very clever and full props for being able to devise such intricate macros, but to me it isn't really a solution to this issue. I feel the problem is more fundamental. If we can't freely pass parameters to lambdas then Crystal really has no support for lambdas, and this will greatly limit it DSL abilities. 

@waterlink This macro warps my mind. Where is the ">>" ever mentioned in the code? It doesn't make sense to me that you can reference the receiver and the block without any mention of the method -- in such a case wouldn't any method name work? e.g. what prevents me from doing `cli "-f --file" .wtfever{ |f| @@file = f }`?

**Comment by waterlink** [comment]
Nothing prevents you currently from doing that. Though you definitely can
add a check in the loop in the macro and raise error at compile time if
call.name is not >>

**Comment by trans** [comment]
I think the conversation has gotten off track a bit about my particular use case. I think the general case is more important b/c I have a number of Ruby programs that I'd like to port to Crystal, but in many cases I can foresee it probably won't be possible because of this. 

@asterite 
> However, right now in the language there are no hidden raises when issuing method calls: they either compile and succeed, or don't compile at all. I mean, there's no "undefined method" nor "wrong number of arguments" errors at runtime, only at compile-time. We don't want to break that rule. So in this case you'll have to manually do the above checks.

I think in the case of lambda's that rule might need to be bent. At the very least maybe there can be a separate class that has the additional flexibility?

**Comment by asterite** [comment]
I'll close this, we have no plans of supporting this.

**Comment by trans** [comment]
:-1: [Good luck](https://github.com/rails/rails/search?utf8=%E2%9C%93&q=args&type=Code) Rails. This is just too limiting for too many of my Ruby project to consider porting.

**Comment by kirbyfan64** [comment]
@trans Almost all of those cases can be replaced by tuples/macros, though...

**Comment by jhass** [comment]
I don't think anyone (should) attempt truly porting Rails. Crystal is a different language, it has different limitations but also different (DSL) opportunities than Ruby.

**Comment by ysbaddaden** [comment]
I don't understand how the "can't splat array" would prevent a Rails port?

The big differences are: the metaprogramming that make porting the DSL complicated —but they can be replaced with more straightforward solutions— and of course the static typing that make some features a bit more convoluted (params in controller, types in model, etc).

**Comment by kliuless** [comment]
@kirbyfan64 I tried writing a macro for splatting but got stuck. Your play link (http://play.crystal-lang.org/#/r/fep) helped me finally get it.
I'd like to suggest an improvement. In the current version, the macro may overwrite the values of local variables in the same scope, e.g.: https://play.crystal-lang.org/#/r/wfu

The improved version: https://play.crystal-lang.org/#/r/wfx
