### ISSUE TITLE
Trying to create a lib called First

### ISSUE THREAD

**Issue by andywenk** [manastech/crystal#1472]
Hi dear folks,

first of all - this is a very promising project. Thanks for keeping us from writing C code ;-).

This error occurred on my very first shoots. I already created a file called `first.cr` and compiled it. Then later I tried to create a lib called `First` (uppercase!)

    ~/p/crystal ❯❯❯ ls -l                                                                                                    ⏎
    total 632
    drwxr-xr-x   5 andwen  staff     170 14 Sep 20:28 .
    drwxr-xr-x  72 andwen  staff    2448 14 Sep 20:24 ..
    drwxr-xr-x   3 andwen  staff     102 14 Sep 20:27 .crystal
    -rwxr-xr-x   1 andwen  staff  318692 14 Sep 20:28 first
    -rw-r--r--   1 andwen  staff      74 14 Sep 20:26 first.cr
    ~/p/crystal ❯❯❯ crystal init lib First
    Unable to create directory './First': File exists
    *Errno::new<String>:Errno +284 [4445832476]
    *Dir::mkdir_p<String>:Int32 +536 [4448080536]
    *Crystal::Command::run<Array(String)>:(Nil | Bool | FileDescriptorIO+ | Crystal::Compiler::Result | Array(Crystal::ImplementationTrace) | Array(Crystal::Init::View+:Class)) +2272 [4451654224]
    main +17325 [4451651277]

    Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/manastech/crystal/issues
    
I hope this helps a bit ...

Cheers

Andy

**Comment by jhass** [comment]
Yeah it should check these cases and print a nicer error message.

**Comment by waterlink** [comment]
Hi. I can take care of this :)

**Comment by andywenk** [comment]
cool ;-) +1 Thanks!

**Comment by vjdhama** [comment]
What's the expectation here? Should the lib be created or not?

**Comment by alex-fedorov** [comment]
It should provide meaningful error message, so that user knows what exactly is wrong and how to fix it. It is impossible to create the folder if such a file already exists.

**Comment by alex-fedorov** [comment]
Filesystem that is used here is (probably) case insensitive, that is why `./first` clashes with `./First/`

**Comment by vjdhama** [comment]
I think there's another related issue. I created a directory `foo` with a file `foo.txt`. Then i tried running `crystal init lib foo`. I think this should have failed, but it did not. It adds `foo.txt` inside `foo` directory with all other lib files. You can see `foo.txt` inside foo.

```
$ mkdir foo

$ touch foo/foo.txt

$ crystal init lib Foo
      create  Foo/.gitignore
      create  Foo/LICENSE
      create  Foo/README.md
      create  Foo/.travis.yml
      create  Foo/shard.yml
      create  Foo/src/Foo.cr
      create  Foo/src/Foo/version.cr
      create  Foo/spec/spec_helper.cr
      create  Foo/spec/Foo_spec.cr
Initialized empty Git repository in /Users/vjdhama/Work/crystal/foo/.git/

$ ls
first.cr       foo            issue_1522.cr  roman_numerals rubyvscrystal  testing

$ ls foo
LICENSE   README.md foo.txt   shard.yml spec      src

```

**Comment by alex-fedorov** [comment]
Yeah, those 2 are related. Ideally it should be smart enough to ask if it needs to overwrite files per each conflicting file being generated. But I think at this point, error message should be enough. WDYT?

**Comment by vjdhama** [comment]
For now I think printing a error message when there's already a directory with same name with some files should suffice. If directory is empty, it should work as it is.

**Comment by jhass** [comment]
I'd even accept an error on an empty directory ;)
