### ISSUE TITLE
[Documentation] Reword code example in 'Local Variables'

### ISSUE THREAD

**Issue by andywenk** [manastech/crystal#1474]
While reading the section http://crystal-lang.org/docs/syntax_and_semantics/local_variables.html I stumbled about the second code example:

    var = "Hello"

I first thought "oh it's like in JavaScript" where you declare a variable with the keyword `var` (see [MDN - var](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var) ). So imho it's a bit misleading (although I understood it ;-) ) and I suggest to change the word `var` to sth. else (and please NOT foo or bar ... that's verboten! :D) 

P.S.: If you like, I send a PR

**Comment by jhass** [comment]
Yes, please send a PR to the gh-pages branch! Since I have no good idea what to replace it with, perhaps just `some_variable` or `greeting`?

**Comment by andywenk** [comment]
will do ... and find sth. nice ;-)
