### ISSUE TITLE
Make `crystal spec` only run files that end with `_spec.cr`

### ISSUE THREAD

**Issue by asterite** [manastech/crystal#1479]
Extracted from #966

Right now if you use the `run` macro inside specs, and the run program is defined inside the `spec` directory, when doing `crystal spec` it also gets compiled. `crystal spec` should only compile/run files that end with `_spec.cr`.

As a workaround for now, define your run programs with a different extension, say `.cr.run`, so `crystal spec` doesn't pick it up. In fact, we could have this convention so that `crystal doc` and others don't pick up these files.

**Comment by jhass** [comment]
Mmmh, something like `_run.cr` or even `.run.cr` would be okay, but we shouldn't introduce more file extensions that editors would have to be configured for as containing Crystal code. And especially don't use `.run` since that's a popular extension for self extracting installer scripts on linux.

**Comment by luislavena** [comment]
@asterite @jhass now that #1487 has been merged perhaps `crystal spec` can use it?

**Comment by MakeNowJust** [comment]
Thanks @asterite !
