### ISSUE TITLE
[Library enhancement] (De)serialise from/to `IO` using specified endian-ness

### ISSUE THREAD

**Issue by js-ojus** [manastech/crystal#1488]
When writing/reading signed and unsigned integers of different sizes to/from `IO` instances, we sometimes need specific byte ordering.  An encoder/decoder that can perform the necessary conversions on the fly helps in such scenarios.

Such a class can be independent, working with any `IO`.

**Comment by jhass** [comment]
I think we shouldn't directly bind them to IO, rather have the equivalent to Ruby's `Array#pack` and `String#unpack`  converting to and from `Slice(UInt8)`

**Comment by asterite** [comment]
Mmm... no, pack and unpack requires the code to parse the format each time. I believe we can go a bit more low level than Ruby and provides methods to read and write these data in a fast way.

**Comment by asterite** [comment]
We could, however, later define a macro that would generate writing/parsing code based on a format.

**Comment by jhass** [comment]
I meant for the level of functionality and usecases really, not the specific interface.

**Comment by asterite** [comment]
I'll close this because now we have `IO#read_bytes` and `IO#write_bytes` (and I just [documented them](https://github.com/manastech/crystal/commit/38795eeadada5030eba60c09fe9851572dbb43e4)) so the original request is fulfilled.
