### ISSUE TITLE
Add an alternative to {% if true %}

### ISSUE THREAD

**Issue by kirbyfan64** [manastech/crystal#1490]
Because it looks ugly as heck. :)

Maybe something like:

```crystal
{% do %}
...
{% end %}
```

instead of:

```crystal
{% if true %}
...
{% end %}
```

**Comment by asterite** [comment]
Hehe, waj told me the same, he suggested begin / end :)

**Comment by Nakilon** [comment]
`begin end` looks good.
But could you explain to me what is this at all? I don't see an example in docs.

**Comment by jhass** [comment]
+1 for begin end
