### ISSUE TITLE
string interpolation for symbols in macro context

### ISSUE THREAD

**Issue by jreinert** [manastech/crystal#1496]
I'd like to be able to do

``` crystal
macro foo(bar)
  {% FOO = "foo_#{bar}" %}
end
```

**Comment by asterite** [comment]
It works: http://play.crystal-lang.org/#/r/fmu

Without saying what output you expect or how `foo(bar)` is used, we can't guess what you want.

**Comment by jreinert** [comment]
ah i see. It's only for symbols where it doesn't work: http://play.crystal-lang.org/#/r/fmv

**Comment by asterite** [comment]
You can do it: http://play.crystal-lang.org/#/r/fmw

String interpolation doesn't exist for symbols. Does the above work for you?

**Comment by jreinert** [comment]
sure, this works, but it won't allow me to assign the result to a constant in macro context

**Comment by asterite** [comment]
With the new `symbolize` macro method you can do this. See #1501. For example:

```crystal
SYMBOLS = [] of Symbol

macro add(piece)
  {% SYMBOLS << "piece_#{piece.id}".id.symbolize %}
end

add 123
add foo

puts SYMBOLS #=> [:piece_123, :piece_foo]
```
