### ISSUE TITLE
Add `symbolize` macro method to create symbols

### ISSUE THREAD

**Issue by jreinert** [manastech/crystal#1497]
I'd like to be able to do something like

``` crystal
macro foo
  def %fresh_var
  end

  {% FOO = :%fresh_var %}
```

**Comment by jreinert** [comment]
see also #1496

**Comment by asterite** [comment]
Please show desired behaviour and some usage. Otherwise we don't understand what you mean.

**Comment by jreinert** [comment]
``` crystal
module Model
  VALIDATORS = [] of Symbol

  macro validate(field, message)
    def validator_{{VALIDATORS.size}}
      valid = begin
        {{yield}}
      end

      unless valid
        @errors[{{field}}] << {{message}}
      end
    end

    {% VALIDATORS << :"validator_#{VALIDATORS.size}" %}
  end
end
```

**Comment by jreinert** [comment]
this can of course be done with strings also which i'm doing now, but if string interpolation works, why not for symbols too? :)

**Comment by asterite** [comment]
Because symbols can't be created dynamically. What we need is a `symbolize` macro method, similar to `stringify`.

**Comment by kirbyfan64** [comment]
@asterite  Should it only work on strings, or on all types?

**Comment by asterite** [comment]
I guess on all AST nodes, just like [stringify](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/macros/methods.cr#L15-L16)

**Comment by jreinert** [comment]
thought it was merged already
