### ISSUE TITLE
hierarchy option not in homebrew tap (Mac OS X)

### ISSUE THREAD

**Issue by andywenk** [manastech/crystal#1502]
I am not sure what is wrong exactly but the documentation at http://crystal-lang.org/docs/using_the_compiler/index.html says, there is a `hierarchy` command. But I don't see it:

    ~/p/crystal ❯❯❯ crystal -v
    Crystal 0.7.7 [170f859] (Sat Sep  5 02:46:31 UTC 2015)
    ~/p/crystal ❯❯❯ crystal
    Usage: crystal [command] [switches] [program file] [--] [arguments]

    Command:
        init                     generate new crystal project
        build                    compile program file
        deps                     install project dependencies
        docs                     generate documentation
        eval                     eval code from args or standard input
        run (default)            compile and run program file
        spec                     compile and run specs (in spec directory)
        tool                     run a tool
        --help, -h               show this help
        --version, -v            show version

I scanned the change log quickly but could not find the change. Is this a bug? Happy to update the docs with a PR (this time at the correct location ;-) )

**Comment by jhass** [comment]
Ah yes, it moved to tool, the docs need to be updated ;)

**Comment by andywenk** [comment]
there we have it ;-):

    ~/p/crystal ❯❯❯ crystal tool --help
    Usage: crystal tool [tool] [switches] [program file] [--] [arguments]

    Tool:
        browser                  open an http server to browse program file
        context                  show context for given location
        hierarchy                show type hierarchy
        implementations          show implementations for given call in location
        types                    show type of main variables
        --help, -h               show this help

I try to find time to prepare a PR ...
