### ISSUE TITLE
Functional Programming Support?

### ISSUE THREAD

**Issue by ahmadseleem** [manastech/crystal#1512]
Hi,

I am glade to see this project... but, I hope you guys put priority to add FP style more than Ruby Does...
Immutability by default, Pattern matching and so on...

**Comment by jhass** [comment]
Please see the discussions in #263, #728, #1388

**Comment by ahmadseleem** [comment]
Okay, thanks @jhass

**Comment by ahmadseleem** [comment]
@asterite  @jhass Here's a link I like: http://yager.io/programming/go.html

**Comment by alanwillms** [comment]
@ahmadseleem if you want Ruby-like syntax + functional programming, take a look at Elixir programming language

**Comment by ahmadseleem** [comment]
Yea, but Elixir isn't statically typed and depends on the Erlang and its libs. that's the problem.
In my little opinion, I think Crystal has a better chance if it gets a better deep design.
