### ISSUE TITLE
'Array(T)#count' is expected to be invoked with a block, but no block was given

### ISSUE THREAD

**Issue by sdogruyol** [manastech/crystal#1525]
Just updated my Crystal version to 0.8.0 and my specs broke.

```
in ./src/cryload/stats.cr:26: 'Array(Cryload::Request)#count' is expected to be invoked with a block, but no block was given

      total_request_time / @requests.count
```

The related code: https://github.com/sdogruyol/cryload/blob/master/src/cryload/stats.cr#L25-L27

Do i have to specifiy a block for count even if i don't have to?

**Comment by jhass** [comment]
Use `size`

**Comment by sdogruyol** [comment]
So this is intentional?

**Comment by jhass** [comment]
Yes

**Comment by sdogruyol** [comment]
OK. Thanks @jhass :+1:

**Comment by sdogruyol** [comment]
Btw i forgot to ask what's the motivation for this?

**Comment by asterite** [comment]
https://github.com/manastech/crystal/issues/1363

**Comment by sdogruyol** [comment]
Thanks @asterite
