### ISSUE TITLE
Improve error message for undefined type vars in generics (Was: Possible Bug in Hash)

### ISSUE THREAD

**Issue by trans** [manastech/crystal#1526]
```
in ./example.cr:1: instantiating 'Hash(K, V):Class#new(Int32)'

    letters = Hash.new(0)
                   ^~~

instantiating 'new(Int32, Hash::StandardComparator:Module)'

in /opt/crystal/src/hash.cr:44: instantiating 'new(Hash::StandardComparator:Module)'

    new(comp) { default_value }
    ^~~

in /opt/crystal/src/hash.cr:39: undefined constant K

  def self.new(comp = StandardComparator, &block : (Hash(K, V), K -> V))
```

**Comment by asterite** [comment]
Ah, I think this will be impossible to solve because of the recursiveness of the issue. We need to document this. You can do this:

```crystal
letters = Hash(String, Int32).new(0)
```

**Comment by asterite** [comment]
Well, mmm, not recursiveness (there was a similar issue with generic types recently), but if you just give the value there's no way for the compiler to infer the key type. So the error it gives you is correct ("I don't know the key type K").

**Comment by waj** [comment]
Maybe when the undefined constant is one of the type parameters the compiler can give a different error message?

**Comment by asterite** [comment]
@waj Oh, that's a **great** idea! I didn't know how to solve this. It also happens when you do:

```crystal
Array.new # Error: undefined constant T
```

**Comment by asterite** [comment]
Ideas of what the error message should be? You can use the two examples above.

**Comment by jhass** [comment]
Maybe just "Couldn't infer generic type argument T/K, please specify it."?

**Comment by waj** [comment]
"Could not infer the type parameter V for the class Hash(K, V). Please provide it explicitly"

Now I remember the idea about adding an unique code to each compile error so we can have a dedicated page for each with more clear explanation and examples.

**Comment by trans** [comment]
Can there be more specific messages depending on the type of object? If so then,

    "Could not infer type of hash key. Use `Hash(<key type>, <value type>).new()`."

Something like that. And like wise for Array.

    "Could not infer type of array elements. Use `Array(<type>).new()`."

Providing the example code really helps make it clear.
