### ISSUE TITLE
Question methods doesn't work correctly for enums with only capital letters

### ISSUE THREAD

**Issue by radarek** [manastech/crystal#1534]
Last release brings to us automatic question methods for enums. I see that it tries to generate method name based on capital letters in enum. For `HTTPResponse` it will generate method `http_response`. Apparently it doesn't work for enums with all capital letters.

```crystal
enum Color
  RED
  BLACK
end

color = Color::RED

# puts color.red?   # Error in ./enums.cr:8: undefined method 'red?' for Color (did you mean 're?'?)
# puts color.black? # Error in ./enums.cr:9: undefined method 'black?' for Color (did you mean 'blac?'?)

puts color.re?
puts color.blac?
```

I would suggest that for enums with all capial letters it should generate downcased names.

**Comment by asterite** [comment]
Oops, seems like a bug in [String#underscore](https://github.com/manastech/crystal/blob/master/src/string.cr#L1818-L1878)

http://play.crystal-lang.org/#/r/g76

**Comment by radarek** [comment]
Yes, I was able to narrow it. Here is quick fix, but I don't know if this is sufficient.

```diff
diff --git a/spec/std/string_spec.cr b/spec/std/string_spec.cr
index 91025e4..ec81027 100644
--- a/spec/std/string_spec.cr
+++ b/spec/std/string_spec.cr
@@ -1156,6 +1156,7 @@ describe "String" do
     "Char_S".underscore.should eq("char_s")
     "Char_".underscore.should eq("char_")
     "C_".underscore.should eq("c_")
+    "HTTP".underscore.should eq("http")
   end

   it "does camelcase" do
diff --git a/src/string.cr b/src/string.cr
index 4b934da..97f6154 100644
--- a/src/string.cr
+++ b/src/string.cr
@@ -1874,6 +1874,10 @@ class String
         first = false

       end
+
+      if mem
+        str << mem.downcase
+      end
     end
   end
```

**Comment by asterite** [comment]
Thanks @radarek ! I used your fix and also found I could simplify more things :-)
