### ISSUE TITLE
Syntax error in macro used for generic type parameter

### ISSUE THREAD

**Issue by Ragmaanir** [manastech/crystal#1535]
```crystal
class Base
end

class Gen(T)
end

macro ident(x)
  {{x}}
end

macro xxx(cls)
  {{cls}}(ident(Base))
end

xxx(Gen)
```

Error: `ERROR: Syntax error in expanded macro: xxx:1: expecting token 'CONST', not 'ident'`
Crystal 0.7.7

**Comment by asterite** [comment]
You can't invoke a macro as a type parameter.

Basically boils down to this:

```crystal
class Gen(T)
end

Gen(macro_call(foo)) # after Gen a type must come, some like Foo::Bar, T, or typeof(...)
```

What do you want to do?

**Comment by asterite** [comment]
No answer in days, I'm closing this. Please reopen if you need it.
