### ISSUE TITLE
ARGV Tuple 

### ISSUE THREAD

**Issue by trans** [manastech/crystal#1536]
If ARGV were a Tuple instead of an Array, it would be more useful. A Tuple can be converted to an Array without a problem but not vice-verse. And slices of a Tuple can be passed to a Proc, but not so Array's.

**Comment by bcardiff** [comment]
Tuples have compile time size. It won't work having a tuple for ARGV. You just don't know how many args the user will pass to the program.

**Comment by trans** [comment]
Ah, right.
