### ISSUE TITLE
Better error message when output file is directory (Was: Hello World build error)

### ISSUE THREAD

**Issue by ahmetabdi** [manastech/crystal#1540]
OSX 10.9.5

`` hello.cr``

```
puts "Hello World"
```

``crystal build hello.cr``

```
ld: can't open output file for writing: hello, errno=21 for architecture x86_64
collect2: ld returned 1 exit status
Error: execution of command failed with code: 1: `/usr/local/Cellar/apple-gcc42/4.2.1-5666.3/bin/gcc-4.2 -o "hello" "${@}"  -rdynamic  -levent -lpcl -lpcre -lgc -lpthread -ldl`
```

**Comment by jhass** [comment]
You resolved the issue? If so how?

**Comment by ahmetabdi** [comment]
The problem was related to having a folder named hello and a crystal file called hello.cr. Deleting the hello folder fixes the problem. Fix found here: https://github.com/manastech/crystal/issues/650

**Comment by jhass** [comment]
Ah, that error message should definitely be improved. (Even though I get a quite clear `/usr/bin/ld: cannot open output file hello: Is a directory` on Linux).

**Comment by asterite** [comment]
I just tried `clang c.c -o src`, where a `src` directory exists, and got this:

```
ld: can't open output file for writing: src, errno=21 for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

So, same error. But we can definitely improve this. If the output file is directory we should say so, right?

**Comment by jhass** [comment]
Yes.
