### ISSUE TITLE
`crystal init lib foo` creates a dir even when `foo` directory already exits

### ISSUE THREAD

**Issue by vjdhama** [manastech/crystal#1555]
I created a directory `foo` with a file `foo.txt`. Then i tried running `crystal init lib foo`. I think this should have failed, but it did not. It adds `foo.txt` inside `foo` directory with all other lib files. You can see `foo.txt` inside foo.

```
$ mkdir foo

$ touch foo/foo.txt

$ crystal init lib Foo
      create  Foo/.gitignore
      create  Foo/LICENSE
      create  Foo/README.md
      create  Foo/.travis.yml
      create  Foo/shard.yml
      create  Foo/src/Foo.cr
      create  Foo/src/Foo/version.cr
      create  Foo/spec/spec_helper.cr
      create  Foo/spec/Foo_spec.cr
Initialized empty Git repository in /Users/vjdhama/Work/crystal/foo/.git/

$ ls
first.cr       foo 

$ ls foo
LICENSE   README.md foo.txt   shard.yml spec      src

```

**Comment by jhass** [comment]
As already discussed on IRC, I think it should print an error message for that case too, yes. This is so strongly related to #1472 that I'm close to saying it's a duplicate. In any case both issues should be resolved together.

**Comment by vjdhama** [comment]
@jhass I also think they should be resolved together. The other issue didn't have info about this issue. That's why I referenced it.

**Comment by vjdhama** [comment]
And I created new issue because in this issue there was no error thrown. Issue #1472  was about printing better error message. That's not the case with this issue.
