### ISSUE TITLE
Shorter entry for nilable json mappings

### ISSUE THREAD

**Issue by ahmetabdi** [manastech/crystal#1556]
using ``JSON::Mapping``

```ruby
class Movie

  json_mapping({
    id: Int32,
    title: { type: String, nilable: true },
    description: { type: String, nilable: true }
  })

end
```

Would be nice if we could shorten the type check down to just ``String?`` .. ``Int32?`` which checks for ``Nil`` also

**Comment by jhass** [comment]
The question is whether it also should set `emit_null: true`, I'd say yes.

**Comment by jhass** [comment]
On second thought this is actually not possible, since `String?` etc is only valid in  the type grammar, which is not active in a hash literals value. We could in theory support something like

```cr
json_mapping([
  foo :: String?
])
```

but that would disallow to mix shorthand and long form, eg. this

```cr
json_mapping([
  foo :: String?,
  bar: {type: Time, converter: Time::Format.new("%h")}
])
```

wouldn't parse.

**Comment by bjmllr** [comment]
Could `String?` be given the same meaning outside the type grammar? It doesn't seem to be syntactically valid anywhere else: I checked `def String?`, `class String?`, `String? = 1`.

**Comment by asterite** [comment]
I think the current approach is fine and works well too. Let's keep things simple.
