### ISSUE TITLE
Incorrect line numbers in compile error trace

### ISSUE THREAD

**Issue by trapped** [manastech/crystal#1558]
The compiler reports incorrect line numbers and text when code (probably containing macros) fails to compile.
For example [this line](https://github.com/trapped/fs_adapter/blob/ff1cada95bd25b0ac6e60b37953122340af88368/src/fs_adapter/driver.cr#L144) using Crystal at 5e53fb1 prints:
```
in ./src/fs_adapter/driver.cr:164: undefined method 'table_path' (if you declared 'table_path' in a suffix if, declare it in a regular if for this to work)

      tables_.not_nil!.map(&.[2])
                        ^~~~~~~~~~
```
I believe it's due to the line references being collected before expanding macros, but take my word with a grain of salt as I don't know almost anything about the compiler's internals.

**Comment by asterite** [comment]
@trapped I almost went crazy with this one! Are you developing in Windows or something like that? Your newlines are `\r\n` instead of `\n`.

**Comment by trapped** [comment]
I do too develop through Windows (actually, using a buggy sshfs driver) occasionally, but it's actually because I have git configured to convert to CRLF line endings.
