### ISSUE TITLE
File length should be size? 

### ISSUE THREAD

**Issue by trans** [manastech/crystal#1575]
in /opt/crystal/src/file.cr:37: undefined method 'length' for Char

    if mode.length == 0
            ^~~~~~

**Comment by jhass** [comment]
Hit a bad revision? https://github.com/manastech/crystal/blob/master/src/file.cr#L37

**Comment by trans** [comment]
Hmm... I have 0.7.7 installed.

**Comment by jhass** [comment]
That should still have length though. 0.8.0 dropped it.

**Comment by trans** [comment]
Odd. But in any case it appears to be fixed. So I will close.
