### ISSUE TITLE
Hosting Homebrew formula on the official Homebrew repository

### ISSUE THREAD

**Issue by 5t111111** [manastech/crystal#1597]
As of version 0.8.0, you maybe want to install Shards along with a Crystal compiler, but Shards cannot be installed via Homebrew. If you generally think, Shards should be able to be installed with Homebrew too.

Although there was already a PR proposed, it was rejected because of cross-tap dependency on Crystal. 
https://github.com/Homebrew/homebrew/pull/44151

As the issue is that cross-tap dependency is not accepted in Homebrew core, adding another Homebrew repo for Shards is one possibility. However, the best thing is that you can have both Crystal and Shards from Homebrew without tapping external repositories.

I have read the thread below as well.
https://github.com/Homebrew/homebrew/pull/40530

That's way too bad, but since you have already adopt **crystal-lang** as the package name, adding **crystal-lang** to Homebrew core has no problem, doesn't it?

Please consider to add a Formula to Homebrew core repository.

**Comment by asterite** [comment]
The main issue is that you'd ideally like `brew install crystal-lang` to also install `shards`. But `shards` depends on crystal! :-(

That's why I'd **really** like crystal to include shards, automatically. Then everything (for programmers, travis, etc.) will work out of the box. But I know many don't agree with this.

**Comment by ysbaddaden** [comment]
I do agree with distributing a Shards binary along with Crystal. Especially when running `crystal shards`. We can still have a newer `shards` installed and run it directly as `shards`. That would simplify CI configurations for example.

**Comment by 5t111111** [comment]
> you'd ideally like brew install crystal-lang to also install shards

Agreed. In the old days of RubyGems you had to install it separately, that was sort of tiresome job :sleepy:

Sorry but I have seen discussions about including shards in crystal, anyway, please feel free to close this issue if there is already appropriate place to discuss this topic.

**Comment by ysbaddaden** [comment]
There could still be a formula for installing newer Shards versions until the next Crystal release (because, you know, bugs).

**Comment by asterite** [comment]
But how do we deal with the recursiveness of crystal depending on shards and shards depending on crystal?

**Comment by jhass** [comment]
We should definitely also propose to rename the crystal package to crystal-generator or something, that's possible as of recently, somebody just has to do and argue it.

**Comment by will** [comment]
> But how do we deal with the recursiveness of crystal depending on shards and shards depending on crystal? 

Precompiled shards binaries for the released versions?

**Comment by jhass** [comment]
https://github.com/Homebrew/homebrew/pull/44742 was merged, so I turned this into a doc bug.

**Comment by asterite** [comment]
And apparently the docs were changed in https://github.com/manastech/crystal/commit/c8c45ea9b76d9de472e9d8eed7b7dfcee70050de so all is done here :-)
