### ISSUE TITLE
Case-insensitive comparison function for strings

### ISSUE THREAD

**Issue by Papierkorb** [manastech/crystal#1604]
It's about time we don't clutter our code with `downcase` anymore when one needs to do a case-insensitive comparison.

That's why I propose to add `String#compare(other : String, case_mode = String::CaseSensitivity::Sensitive) : Int32`

It's basically `String#<=>` in a case-(in)sensitive manner.

**Complete definition**
````crystal
class String
  enum CaseSensitivity
    Sensitive
    Insensitive
  end

  def compare(other : String, case_mode = String::CaseSensitivity::Sensitive) : Int32
    #TODO
  end
end
````

**Example documentation**

#compare takes a string +other+ as first argument, which +self+ is compared to. The optional second argument can be used to define whether the string comparison shall be done case-sensitively (the default), or case-insensitively.

#compare returns a Int32. Is the result `0`, the two compared strings were detected to be equal. Is the result `-1`, so comes +other+ lexicographically *before* +self+. Is the result `1`, so is +other+ lexicographically *after* +self+.

**Example usage**
````crystal
# Case-sensitive comparison
puts "is the same!" if "foo".compare("FOO") == 0
puts "is different!" if "foo".compare("FOO") != 0

# Case-INsensitive comparison
puts "is the same!" if "foo".compare("FOO", String::CaseSensitivity::Insensitive) == 0
puts "is different!" if "foo".compare("FOO", String::CaseSensitivity::Insensitive) != 0

# Sort an array of strings case-insensitively
["one", "TWO", "Three"].sort { |a, b| a.compare(b, String::CaseSensitivity::Insensitive) }
````

**Note on Unicode**

The case-sensitive comparison can work the same as C's `strcmp(3)` and does not need to be Unicode aware. The case-insensitive comparison however has to be Unicode aware on the long run, IMO, before Crystal hits version 1.0.

**Comment by jhass** [comment]
I think this depends on adding methods for Unicode normalization according to https://en.wikipedia.org/wiki/Unicode_equivalence#Normalization

**Comment by spajus** [comment]
Why not use `"foo".compare("FOO", :case_insensitive)` to keep things simple?

**Comment by radarek** [comment]
@spajus Using symbol is not a bad idea but you would get runtime error if you will misspell it. I don't like `String::CaseSensitivity::Sensitive` because it's too verbose for such a simple thing. It reminds me of java... I would use optional keyword argument:

```
def compare(other : String, casecmp = false)
end

"Foo".compare("foo")
"Foo".compare("foo", casecmp: true)
```

It's better because it is checked at compile time and it isn't verbose.

**Comment by spajus** [comment]
> It reminds me of java

Same here.

+1 for optional keyword boolean argument.

**Comment by Nakilon** [comment]
I would be ok with if `==` had optional parameter. Like `str1.==(str2, case_sensitive = true)`
