### ISSUE TITLE
Feature request: Add more magic constants

### ISSUE THREAD

**Issue by DougEverly** [manastech/crystal#1605]
In addition to `__LINE__`, `__FILE__`, `__DIR__` (from https://github.com/manastech/crystal/blob/fad1793e3171ab611d8723746664fb8c9acf65cd/src/compiler/crystal/codegen/call.cr#L98),

add:
`__METHOD__` - return current method name/signature (`upcase`)
`__MODULE__` - return fully qualified module, struct, or class name (`HTTP::Client`)

**Comment by jhass** [comment]
Related to #1582

**Comment by ozra** [comment]
@DougEverly - commented in #1582 as @jhass pointed to - seems this issue would be better of as a comment there? Same things - different style..

**Comment by DougEverly** [comment]
Yes, the end goal seem to be the same. I'll close this one for #1582.
