### ISSUE TITLE
Feature request: Enforce code convention.

### ISSUE THREAD

**Issue by tioteath** [manastech/crystal#1616]
Digging the Internet for Crystal code examples I found [this project](https://github.com/kostya/crystal-benchmarks-game). Despite that fact, the overall code quality is nice, there's some major drawback: author extensively uses camelCase for variable names, and I see the dangerous sign in it. I mean, if it continue in that way, Crystal would became a mess like Python, but not a beautiful  tool like Ruby. This would be a big fat minus in the list of program languages consideration, as there is absolutely no sane reason to break code convention, but it happens all the time anyway. Apparently, people are not good in following rules, especially if they are too lazy to learn some (I'm talking about newbies). 
So my proposal is: Mark a camelCase usage in variable names as a syntax error. 
Actually, this is not the only limitation I would like to see in the modern programming language. I would also expect enforcement on 80-character line length limit, extensive space usage (i.e. `2   + 3`, instead of `2 + 3`), and empty brackets in function calls (i.e. `test()`).  In other words, let's make tools like `rubocop` useless by building-in its functionality in the compiler.

**Comment by kumpelblase2** [comment]
I've looked through it and, apart from one instance, couldn't find the "extensive use of camelCase" you were talking about. But I'll stick with you for the sake of argument.

I do think sticking to coding conventions should be considered a 'must'. However, I disagree with the fact that there should be _one_ style everyone _has to_ follow. Everyone has his/her own views and comes from different backgrounds (I would consider 80-character old and outdated) which leads to different tastes as to how code should look like. The compiler itself shouldn't have to care what my conventions are, its job it is to check if I didn't make any _actual_ mistakes, like misspelling a method name when I call it. Missing code conventions isn't an error or a bug, the application will run the same, no matter what convention you have.

If such a system should be made it should first be optional by default and secondly be configurable to use a different convention set by the user. Code no longer working because you missed a convention somewhere is just not an option. A separate command for the crystal executable which reads from a local config (or uses a default if it doesn't exist) would in my eyes be a good solution for everyone.

I would be totally in support for creating a standard code convention for the crystal language that the main crystal codebase would abide to. As a result, this would be the convention new people would follow when joining the language and could give a good reference point. But I would dislike it to just force this convention on everyone.

**Comment by jhass** [comment]
I'm fully seconding @kumpelblase2 here. Having an official style is good, forcing it upon everybody in every situation is a very bad idea.

**Comment by ysbaddaden** [comment]
I usually don't like enforcements, but I second @tioteah for methods/variables. Seeing camelBack methods in a Ruby-like language is an heresy. Apart from that, the other enforcements would be too much dogma, an be a stop to others adopting the language.

I live with tmux + vim in a fullscreen terminal and split like crazy, so anything larger than 80 chars is a pain. but I won't enforce anybody else to it.

**Comment by kirbyfan64** [comment]
Woah, I'd be *really* irritated if this were forced. I frequently will use single-character variables when the types are obvious, put lines over 80 characters while still toying with code, and use underscores in CSS/JavaScript. Now, a separate compiler command (`crystal style`?) would be nice, but nothing forced. Let the people use camelCase. Even though I hate it.

**Comment by sdogruyol** [comment]
This #309

**Comment by ozra** [comment]
A configurable styling tool (like, say astyle for C++) would be good to reformat code to an - within project team - agreed upon standard. Enforcing? Hell no! I use dashes in identifiers ("the right way TM" ;-) in all my own code - wouldn't dream of using archaic underscores or hump less I have too.

**Comment by agatan** [comment]
Some modern languages (like `Rust`, `go`) have very strict compiler checks and warnings.
I think it is nice, but overdo also. 
I want some linter tools and use them with `crystal` command (seconding @kirbyfan64).
If there's an official linter tool, many programmers may follow its default conventions. If someone dislikes some of default conventions, he/she don't use the tool or configure its convention.

**Comment by rhysd** [comment]
@tioteath 

I think it's the work of linter.  You can make a linter with Crystal's powerful AST API.

**Comment by tioteath** [comment]
> Everyone has his/her own views and comes from different backgrounds

Exactly, and the everyone, as new comer starts a development of new cool library that would be published later without changes (code re-factoring is some sort of ideal that rarely happens in the real world). Multiply one person by overall community number and you'll get a mess. This is not a fantasy, this is what I can see in real world over and over again.

As for this "compiler job" statement, this is very subjective, I'd like to see actual prove of it. Which paper defines what compiler should do and what shouldn't?

**Comment by kirbyfan64** [comment]
@tioteath I don't get it. The compiler's job should be to compile the source and check for *logic* errors. If I want a linter, I can use it myself.

BTW, that's another thing I hate about Go: forced style. I hate capitalized method names.

-1000000000000e200000000 from me.

**Comment by asterite** [comment]
The benchmark code works well. For kostya it was easier for porting it from python code. The purpose of the benchmark code is to show how fast the language is. He shouldn't be bothered with style, conventions and so on.

Imagine I want to do some quick test in Crystal and copy the code from another language. Now the compiler starts bothering me with style and other things that I really don't care right now. Like how Go forces you to remove `import` declaration or comment unused variables. It's a pain. Let me program and play.

I think only newbies in a language don't follow code conventions. Once they gain some experience they follow them. And if they don't have experience they'll probably won't write good libraries, or someone will tell them to fix their style. But if the library works well but has some minor style issues, why the programmer should be bothered with this?

I think Go is pretty simple that it can allow strong code rules. Crystal is much more liberal, features like different string literals, string interpolation, methods with or without parenthesis. Should a code enforcer always force parenthesis or non-parenthesis? Using always the same kind of string literals? I think in the end it will just check 2 space indentation and maybe disallowing two consecutive newlines. If that's it, I don't see the point in it.

So it's a -1 for me :-)

**Comment by kumpelblase2** [comment]
> Multiply one person by overall community number and you'll get a mess. This is not a fantasy, this is what I can see in real world over and over again.

Java doesn't enforce it and I don't see the mess you're talking about. I might not have used every ever so small library out there, but I have yet to encounter one that has a "different" coding style that is visible to the outside world (like method name format, argument names, etc.).  Also, this is why I've said to make a default convention for the crystal core (compiler, std, ...) so if you'd then run a lint everyone would be on the same page. If you REALLY don't like the default style, you should be able to change it. This means that you make actual decision to differ explicitly from the default convention, so you probably have a good reason to do so.

> As for this "compiler job" statement, this is very subjective, I'd like to see actual prove of it. Which paper defines what compiler should do and what shouldn't?

A "formal" description of a compiler would be that it turns code from one language (e.g. crystal, ruby, java) to another language (e.g. assembly, bytecode, java-bytecode). So it should work on every code that is valid in the source language, which includes code that has different coding conventions. Forcing code convention would mean that the language is defined that way and code that differs from the convention would be considered invalid. Using empty brackets or leaving them away produces equally valid source code. Using `{` or `do` for blocks is also equally valid. It's just what you prefer that makes one code valid and the other invalid.

**Comment by vyp** [comment]
I agree with kumpelblase2, ozra, kirbyfan64, enforcing *some* sort of code convention among *a* project is clearly beneficial, and it could be argue it's needed. But enforcing it for the language as a whole I think too dogmatic. Don't get me wrong, I don't particularly prefer camel case either, and also always try to keep it to 80 columns, but forcing these things just does not seem to have much benefit, at the cost of a lot more flexibility, especially when we want Crystal to be a relatively easy language to pick up (I think?). I know some larger projects like to have a convention of 100 or 120 columns even (albeit not Crystal projects).

So -1 from me too.

**Comment by jreinert** [comment]
i agree that an official style guide is much needed. But that being that: a style guide. Breaking it is not and should never be a syntax error. What I would very very very awesome is if someone took the time and wrote a linter which checks and enforces the styleguide if necessary. This could then be used by crystal projects (such as crystal itself) by travis to keep the codestyle clean.

**Comment by tioteath** [comment]
> Java doesn't enforce it and I don't see the mess you're talking about. 
Yes it does. At least for `javaBeans`. Not in the compiler, of course, but still.  

> Imagine I want to do some quick test in Crystal and copy the code from another language. Now the compiler starts bothering me with style and other things that I really don't care right now. Like how Go forces you to remove import declaration or comment unused variables. It's a pain. Let me program and play.
Use code convertor or something. It is very easy to complete the task even by regexp search-and-replace dialog, which is in place in any programmers editor. I cannot see how it cannot be solution for you. In-deed,  if you're OK with external tool for code validation for overall the platform, how can you not be OK with some tool for code conversion for the rare case scenario?

> So it should work on every code that is valid in the source language, which includes code that has different coding conventions. Forcing code convention would mean that the language is defined that way and code that differs from the convention would be considered invalid. 
Exactly, by enforcing code convention we postulate that code which is not conforms the convention is not syntactically valid, hence it's compilers job to handle that.

**Comment by kumpelblase2** [comment]
> Yes it does. At least for javaBeans. Not in the compiler, of course, but still.

That's different from enforcing coding conventions for the whole language. If we'd force coding conventions for things like Records only, fine, no problem at all. But you're talking about two different scales. This again boils down to one thing: if you enforce it in the main codebase many or most people will abide to it for general use, unless they make the honest decision to not do it.

> Exactly, by enforcing code convention we postulate that code which is not conforms the convention is not syntactically valid, hence it's compiler's job to handle that.

This would make the language even harder to grasp and get into it for new people, because there's so many definitions as to how things have to look in order for them to work. It's one thing what is considered "good" and "bad", however "correct" and "wrong" is a whole different story.

If we'd make it an optional tool, it would not be the job of the compiler, as the code is still valid either way.

**Comment by tioteath** [comment]
> That's different from enforcing coding conventions for the whole language. If we'd force coding conventions for things like Records only, fine, no problem at all. But you're talking about two different scales.

javaBeans are kind of key component for overall Java platform. I wouldn't say it some how close to the scale of Record. It's much bigger. I would say, enforcing naming convention on javaBeans is equivalent to enforcing the convention over the whole platform.

> This again boils down to one thing: if you enforce it in the main codebase many or most people will abide to it for general use, unless they make the honest decision to not do it.

Well, have you ever heard of anyone, who chose to not to accept the job, because he didn't like the code convention established in the company?


> It's one thing what is considered "good" and "bad", however "correct" and "wrong" is a whole different story.

From my point of view referring as "good" and "bad" toward the syntax and punctuation is lame. "Good" equals "the same manner" and "bad" equals "as I like it".

**Comment by kirbyfan64** [comment]
@tioteath 

> Use code convertor

Code conversion is insanely freaking hard when you're trying to output idiomatic code. Just look at everything that happened when the Go compiler was automatically ported to Go.

> very easy to complete the task even by regexp search-and-replace dialog,

Regexes don't solve everything. *Really*, they're kind of useless for the task of auto-formatting and will break more than they fix.

> I would say, enforcing naming convention on javaBeans is equivalent to enforcing the convention over the whole platform.

You've got to be kidding. I code Java (mostly Kotlin, actually) with underscores. It's not wrong, and I really don't care about the established conventions at all.

My lines of text frequently go over 80 characters. I would get really upset if the compiler tried to force me to do that.

Google uses camelCase, so almost everything written by employees in any language is camelCase. If the language mandated underscores...it'd be kind of stupid, IMO.

**Comment by Nakilon** [comment]
80 chars is a pointless 18th century religious madness. A lot of other PEP-like rules are smelling the same.

**Comment by asterite** [comment]
Now that we have a formatter (the next version will come with many fixes to it), can we close this? We won't enforce name patterns or stuff like that.

**Comment by jhass** [comment]
My vote stands against it too.

**Comment by asterite** [comment]
I'll close this, we don't want to force code conventions for names, and we have a formatter if you want to have at least some uniformity. But making it mandatory just gets in the user's way if she wants to try something quickly or just play with the language.
