### ISSUE TITLE
Unsupported operation given in Arch Linux installation documentation.

### ISSUE THREAD

**Issue by Earnestly** [manastech/crystal#1633]
The official documentation [describes](http://crystal-lang.org/docs/installation/on_arch_linux.html) using `-Sy` when upgrading on Arch Linux but this kind of operation is [not supported](https://wiki.archlinux.org/index.php/Pacman#Partial_upgrades_are_unsupported) for that distrubtion.

Please consider removing the entire "Upgrade" section as it's pretty unnecessary.  Even if this was changed to the correct `-Syu` innvocation the options `--needed` and `crystal` would be redundant.  Essentially you'd end up with `pacman -Syu` which is not what you mean.  Other distributions using pacman (such as msys2) do support partial upgrades. (afaik)

**Comment by vyp** [comment]
+1. This bites people sometimes. A good example right now of this would be people (partially) upgrading just the ncurses library, usually rendering the system unbootable.
