### ISSUE TITLE
Lexer fails to parse "!~" operator

### ISSUE THREAD

**Issue by ysbaddaden** [manastech/crystal#1637]
Crystal 0.8.0 can no longer parse the `!~` operator (doesn't match regexp). It seems to lex `!` alone then tries to lex `~` which fails:

```
$ crystal eval '"test" !~ /test/'
Syntax error in eval:1: unexpected token: !

$ crystal eval 'if "test" !~ /test/; end'                                           
Error undefined method '~' for Regex
```

**Comment by jhass** [comment]
It's ugly anyway :P scnr

**Comment by asterite** [comment]
I think `!~` was [never](http://play.crystal-lang.org/#/r/hdv) supported (that's against 0.6.1), even though I see it in the lexer/parser source code. Strange. I'll fix this. I think `!==` is also missing.

**Comment by asterite** [comment]
Oh, well, it seems `!==` doesn't exist in Ruby, I don't know where did I get that from (java, cough, script, cough, cough)
