### ISSUE TITLE
Whitespace between colon and argument type

### ISSUE THREAD

**Issue by veelenga** [manastech/crystal#1640]
Method argument:
```crystal
def meth(x:Int32)
  puts x
end
```
```sh
Syntax error in eval:1: unexpected token: Int32 (expected ',' or ')')

def meth(x:Int32)
          ^
```
Or proc argument:
```crystal
proc = ->(x:Int32) {}
```

```sh
Syntax error in eval:1: expecting token 'IDENT', not 'Int32'

proc = ->(x:Int32) {}
           ^
```

Why whitespace between `:` and type definition is required ?

**Note**: `expected ',' or ')'` in first case is also wrong as there at least could be an 'IDENT' token.

**Comment by asterite** [comment]
Hehe, we'll actually change it to always be `x : Int32`. `x: ...` looks like a named argument. And `x :Int32` looks like `:Int32` is a symbol. So we'll actually change the parser to require spaces in both sides of the colon.

I don't think this is what you wanted, though...

**Comment by veelenga** [comment]
:+1:
