### ISSUE TITLE
discussion: should there be IO#write_fully and IO.copy_fully

### ISSUE THREAD

**Issue by jreinert** [manastech/crystal#1652]
we already discussed what should be done if `#write` writes less than given in #1641 

I'd like to propose a method `#write_fully` which would raise if it writes less than `slice.size` bytes. I think a `IO.copy_fully` method would be also appropriate. This would utilize both the `#read_fully` and `#write_fully` methods of the source and dest.

If this is generally wanted and @asterite and @waj agree, I'd make a PR for this.

**Comment by jhass** [comment]
Related to #1276

**Comment by waj** [comment]
I think `write` should already do that, try to write all the given data or raise otherwise.

**Comment by jreinert** [comment]
@waj you think? what if i choose a very large slice size? say 1024 and the IO "fits" only 1023? I'm thinking about stuff like SliceIO and PointerIO which have a limited capacity. Shouldn't they be filled completely?

**Comment by waj** [comment]
In that case I'd raise because there is no enough space to write all the data.
I think it's generally much easier to work with an IO that asures it will write all the given data. The current behavior is actually a bug, because I didn't realized that LibC.write could write less data than given :)

**Comment by jreinert** [comment]
ok. this should be a different concern though. leaves us with `copy_fully` which would utilize read_fully instead of read.

**Comment by bcardiff** [comment]
@waj regarding https://github.com/manastech/crystal/issues/1652#issuecomment-144204902 we said something in https://github.com/manastech/crystal/pull/1641#issuecomment-144152350 . Yet, I am not sure if there is an actual scenario where a write operation can't be completed fully but it will in the next call, but the description I linked is inspired in having a dual contract mainly.

**Comment by waj** [comment]
From `write` man page:
> When using non-blocking I/O on objects, such as sockets, that are subject to flow control, write() and writev() may write fewer bytes than requested; the return value must be noted, and the remainder of the operation should be retried when possible.

Crystal uses non-blocking I/O internally, but we expose a blocking API, so I think the IO#write should loop until all the data has ben sent instead of exposing this implementation detail to the outside.

**Comment by waj** [comment]
That was actually from OSX man page. In Linux it says:
> The number of bytes written may be less than count if, for example, there is insufficient space on the underlying physical medium, or the RLIMIT_FSIZE resource limit is encountered (see setrlimit(2)), or the call was interrupted by a signal handler after having written less than count bytes

If the call was interrupted by a signal we need to make sure it continues writing after handling the signal. Regarding RLIMIT_FSIZE, we need to somehow raise an exception because no more data could be written without failing.

**Comment by waj** [comment]
@jreinert BTW, I don't see why we need a `copy_fully` method. `IO#copy` will read and write all the bytes until it reaches the EOF. If the destination doesn't accept all the data, an error must be raised.

**Comment by technorama** [comment]
`BufferedIO#write` is also not safe to resume.  There may be data loss as `flush` may fail and there is no way to resume where it left off.

**Comment by asterite** [comment]
These don't make sense anymore after #1639
