### ISSUE TITLE
HTTP::Client.head is slower than HTTP::Client.get

### ISSUE THREAD

**Issue by berfarah** [manastech/crystal#1659]
I've noticed that Crystal's HEAD requests are actually _slower_ than its GET requests. This seems like a bug.

Benchmarks:

With my own domain:
```crystal
Benchmark.ips do |x|
  x.report("GET request") { puts HTTP::Client.get("bernardo.me") }
  x.report("HEAD request") { puts HTTP::Client.head("bernardo.me") }
end
```

```
 GET request    2.9  (±34.10%)       fastest
HEAD request   0.19  (± 0.00%) 15.57× slower
```

With Google.com (both http and https) I ended up giving up because nothing happened after a few minutes.

With an internal company link to an image:
```
 GET request   6.99  (±35.89%)       fastest
HEAD request    6.7  (±32.75%)  1.04× slower

 GET request   7.47  (±27.64%)       fastest
HEAD request   6.28  (±36.80%)  1.19× slower
```

With a company CDN:
```
 GET request   5.81  (±31.04%)       fastest
HEAD request   0.25  (± 0.13%) 23.25× slower

 GET request   6.03  (±24.68%)       fastest
HEAD request    0.2  (±26.80%) 30.69× slower
```

With these last two, I know that HEAD requests are *significantly* faster in Go. Here's a comparison in Ruby using `rest-client` and `benchmark-ips`

```
Calculating -------------------------------------
         GET request     2.000  i/100ms
        HEAD request     1.000  i/100ms
-------------------------------------------------
         GET request     21.539  (±23.2%) i/s -     80.000
        HEAD request     37.666  (±13.3%) i/s -    147.000

Comparison:
        HEAD request:       37.7 i/s
         GET request:       21.5 i/s - 1.75x slower
```

**Comment by waj** [comment]
I guess this is because during a HEAD request the server doesn't send any body contents, but still the HTTP::Client is waiting for it. So it finishes when the server closes the connection.

**Comment by berfarah** [comment]
It looks to me like the offenders are here (I may very well be misinterpreting what things are doing and I don't know what `#try` does on IOs)

In [`crystal/client.cr`](https://github.com/manastech/crystal/blob/master/src/http/client/client.cr#L306)
```crystal

def exec(request : HTTP::Request, &block)
  request.headers["User-agent"] ||= "Crystal"
  request.to_io(socket)
  socket.flush
  HTTP::Response.from_io(socket) do |response|
    value = yield response
    response.body_io.try &.close # <= This line
    close unless response.keep_alive?
    value
  end
end
```

which calls [`crystal/request.cr .from_io`](https://github.com/manastech/crystal/blob/master/src/http/request.cr#L45)
```crystal
def self.from_io(io)
  request_line = io.gets
  return unless request_line

  method, resource, http_version = request_line.split
  HTTP.parse_headers_and_body(io) do |headers, body| # <= This line
  return new method, resource, headers, body.try &.gets_to_end, http_version
  end

  # Unexpected end of http request
  nil
end
```

which then calls [`crystal/common.cr .parse_headers_and_body`](https://github.com/manastech/crystal/blob/4889495a0ddd11065cddb4a5e4cf61637adc0723/src/http/common.cr#L4). and waits using [`&.gets_to_end`](https://github.com/manastech/crystal/blob/4889495a0ddd11065cddb4a5e4cf61637adc0723/src/io.cr#L462)

**Comment by bcardiff** [comment]
@berfarah [Object#try](http://crystal-lang.org/api/Object.html#try%28%26block%29-instance-method) performs de block if the receiver is not nil. Nothing trickier than that.

**Comment by berfarah** [comment]
Thanks, @jhass!
