### ISSUE TITLE
Wrong size (for mask key) used in WebSocket

### ISSUE THREAD

**Issue by jreinert** [manastech/crystal#1664]
see #1663 for frame structure

**Comment by kumpelblase2** [comment]
https://github.com/manastech/crystal/blob/master/src/http/web_socket.cr#L39 The masking key is 4 bytes or 0, so it is correct as it is right now.

**Comment by jreinert** [comment]
I'm confused. Maybe I changed something in #1656 that caused the spec to fail. Anyway, It's working now.
