### ISSUE TITLE
Change OSX bin destination from /usr/bin to /usr/local/bin

### ISSUE THREAD

**Issue by cielavenir** [manastech/crystal#1671]
Due to OSX El Capitan's **rootless**, `/usr/bin/crystal` cannot be created anymore. Hence, bin symlinks need to created in /usr/local/bin instead.

**Comment by jhass** [comment]
Please open this issue at https://github.com/manastech/homebrew-crystal/

**Comment by waj** [comment]
homebrew-crystal actually installs the symlink in /usr/local/bin/crystal. I guess @cielavenir is installing the .pkg so this is an issue for https://github.com/manastech/omnibus-crystal

**Comment by cielavenir** [comment]
@waj Reopened at https://github.com/manastech/omnibus-crystal/issues/6. Thank you for the help!

**Comment by cielavenir** [comment]
Finally this issue has been closed **properly.** https://github.com/crystal-lang/omnibus-crystal/pull/7
