### ISSUE TITLE
TCPSocket and Channels

### ISSUE THREAD

**Issue by Chalant** [manastech/crystal#1675]
Encountered this today, and I'm not sure whether it's by fault of implementation or just something strange happening with the compiler.

```crystal
require "socket"

channel = Channel(TCPSocket).new
server = TCPServer.new(1234)

loop do
    socket = server.accept
    channel.send socket
end
```

Produces the following error:
>  Bug: trying to downcast TCPSocket+ <- TCPSocket
> Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/manastech/crystal/issues

Am I misunderstanding the concept of channels? Still very new to this language, and never touched Ruby before.

**Comment by jhass** [comment]
No you're not, this is a compiler bug, most likely unrelated to Channels and TCPSockets, it just happens with those types.

**Comment by asterite** [comment]
Reduced:

```crystal
class Foo
end

class Bar < Foo
end

class Generic(T)
  def initialize
    @value :: T
  end

  def value=(@value)
  end
end

generic = Generic(Foo).new
generic.value = Foo.new
```
