### ISSUE TITLE
Macro-defs (and "method"-defs) inside method-defs

### ISSUE THREAD

**Issue by ozra** [manastech/crystal#1690]
Is there any particular reason for not allowing macro-defs inside method-defs?

I find it a good practise for DSL'ish helpers in certain methods (like setting up gui's or whatever, where you might repeat some similar constructs a lot) - without tainting the bigger namespace.

A related issue is to also be able to define "methods", or rather "functions" - call it what you will (no closuring) - inside methods. That would of course basically serve the exact same purpose (especially after inlining in release mode), and could also be done with procs (albeit with sucky call syntax). 
Still - I would find it very usable. It's a practise I'm used to that also _avoids polluting bigger scopes than necessary_.

**Comment by jhass** [comment]
@asterite You tagged this as a question but never replied.

**Comment by asterite** [comment]
Oh, I forgot.

You can use `private def` and maybe we can later add `private macro` inside modules. I don't think we need to make the language more complex.

**Comment by ozra** [comment]
ok
