### ISSUE TITLE
while loop never ends unless something is printed

### ISSUE THREAD

**Issue by feifanzhou** [manastech/crystal#1694]
```cr
  it "works as a multi-threaded queue" do
    q = ThreadsafeQueue.new
    t1_done = false
    t2_done = false
    spawn do
      (1..10).each { |i| q.push(i) }
      t1_done = true
    end
    spawn do
      (11..20).each { |i| q.push(i) }
      t2_done = true
    end

    while !t1_done || !t2_done
      # p "Hello"
      next
    end

    # … more code below
```

The `while` loop never finishes. However, if I uncomment the `p "Hello"`, then "Hello" prints and the code finishes. 

$ crystal -v
Crystal 0.8.0 [e363b63] (Sat Sep 19 12:00:17 UTC 2015) (installed via Homebrew)
OS X 10.11 (15A279b)

**Comment by jhass** [comment]
That's expected, other coroutines/fibers are only scheduled if the current one blocks or explicitly yields. Printing something does block and thus gives the stuff you spawn a chance to run, not doing it keeps your main coroutine in a busy loop.

Why don't you use a channel?

**Comment by feifanzhou** [comment]
Hmm I didn't know about channels and how it differs from fibers. Is there documentation on Crystal's multi-threading capability and how to use it? I've been trying to figure this out by reading through source

**Comment by asterite** [comment]
There aren't any docs right now because the design is in flux, but if you learn about Go channels and the `go` statement (which is similar to `spawn`) you'll understand both languages.

**Comment by feifanzhou** [comment]
:+1: 

where is the source (or examples) for the `go` statement?

**Comment by ozra** [comment]
@feifanzhou - `spawn` that is: http://crystal-lang.org/api/toplevel.html#spawn-macro
Source: https://github.com/manastech/crystal/blob/e363b63c05abc63fc11c407c23507ff144900c45/src/concurrent/concurrent.cr#L16
Channels: http://crystal-lang.org/api/Channel.html

**Comment by feifanzhou** [comment]
I am using `spawn` above … does using a Channel fix the issue (a channel will block until sender and receiver finishes)? How can I use Channels with Fibers?

**Comment by jhass** [comment]
I suppose you could do something like

```cr
  it "works as a multi-threaded queue" do
    q = ThreadsafeQueue.new
    channel = Channel(Nil).new
    spawn do
      (1..10).each { |i| q.push(i) }
      channel.send nil
    end
    spawn do
      (11..20).each { |i| q.push(i) }
      channel.send nil
    end
   
    channel.receive
    channel.receive

    # … more code below
```

But that's just as good as

```cr
  it "works as a multi-threaded queue" do
    q = ThreadsafeQueue.new
    (1..10).each { |i| q.push(i) }
    (11..20).each { |i| q.push(i) }
    # … more code below
```

since nothing is done in parallel yet. Besides `ThreadsafeQueue` is probably duplicating most usecases you would use a channel for.

**Comment by ozra** [comment]
Even though nothing is done in parallel _now_, it might be good to write code so that it's prepared when it does :)

**Comment by feifanzhou** [comment]
> Besides ThreadsafeQueue is probably duplicating most usecases you would use a channel for

Hmm didn't know that. Does a channel guarantee order as a queue would?

**Comment by jhass** [comment]
Just the same, yes. With a single consumer and producer you have a guaranteed order, if you have more than a single consumer or producer at a time, the order guarantee boils down to whatever got in first will get out first.

**Comment by feifanzhou** [comment]
Perfect. Would a channel's performance be significantly different (worse?) than a Deque?

**Comment by jhass** [comment]
There's `Channel::Unbuffered` and `Channel::Buffered` which are used depending on the invocation of `Channel.new` and `Channel.new(64)` respectively. `Channel::Unbuffered` basically acts like an exchanger, blocking on `send` and `receive` until both operations converge and the value is exchanged. `Channel::Buffered` acts like a sized queue, blocking when the limit is reached. *Currently* `Channel::Buffered` is backed by an `Array`.

**Comment by feifanzhou** [comment]
Ok — so `Channel::Unbuffered` behaves like a buffered channel of size 1? Can a buffered channel's capacity be changed at runtime?

**Comment by waj** [comment]
> Channel::Unbuffered behaves like a buffered channel of size 1?

No, because an unbuffered channel blocks the sender fiber until another fiber receives the message. It can be used as a synchronization point.

On the other hand, a buffered channel wont block unless the channel is full.

> Can a buffered channel's capacity be changed at runtime?

No, do you have a scenario where that could be necessary?

**Comment by feifanzhou** [comment]
> do you have a scenario where that could be necessary

I'm working on an auto-scaling system that spawns more upstream or downstream threads (relative to a particular queue) depending on how full the queue is. Would be nice to be able to adjust the size of the queue accordingly as well rather than having to fix it to an arbitrarily large value.

**Comment by jhass** [comment]
Seems like the question is answered, closing.
