### ISSUE TITLE
question: Formatting tool

### ISSUE THREAD

**Issue by ozra** [manastech/crystal#1701]
Will the formatting tool (branch "formatting") incorporate the AST; and then also put comment-nodes in AST so everything can be reproduced from it? (hoping)

**Comment by asterite** [comment]
I don't understand well your question, but comments will be preserved.

**Comment by ozra** [comment]
I just wonder if comments get a node in the AST - and aren't handled "on the side".

**Comment by asterite** [comment]
They don't get a node in the AST, but there's an option in the lexer to emit tokens for them. The formatter uses this. It parses the AST into an AST node and then traverses it while also lexing the source code.

**Comment by ozra** [comment]
alright.
