### ISSUE TITLE
`likely` and `unlikely` keywords for branching annotation

### ISSUE THREAD

**Issue by ozra** [manastech/crystal#1712]
It would be very nice to have the keywords `likely` and `unlikely` to use in conjunction with `if` and `when`. Their completely optional of course.

What now?

```crystal
if unlikely a == 42
  do_stuff
elsif likely a == 47
  do_other_stuff
else
  do_defaults
```

What purpose does this serve?

- Branches can still be ordered in a logical 'things that go together way'.
- While at the same time making intent and code reasoning clearer by showing that certain branches might be more unlikely / likely.
- This information can be passed on as meta-data to LLVM which can re-order generated binary code for optimum cache hit and performance.

- Win for the coder
- Win for the compiler / performance

As a worse case: if it could be annotated with pragma - but then it would be useful only for optimization.

**Comment by kirbyfan64** [comment]
Yeah, this makes sense, but it's a bit useless in the real world, IMO. Maybe LLVM or the compiler could reorder one or two statements, but it's not much of a perf. difference.

**Comment by ozra** [comment]
One re-ordering is all it takes in a loop and there can be pretty good gains. However, I consider that a bonus only to the semantics.

**Comment by jhass** [comment]
`def likely(c); c; end; def unlikey(c); c; end;`  done. Just saying.

I think this adds noise for little to no benefit. Ruby lives from its terseness and that terseness is where the expressiveness comes from IMO. I'd like to see as much as possible of that retained in Crystal.

**Comment by waj** [comment]
I don't think this kind of optimization hints matches with the kind of language we want to build.

**Comment by ozra** [comment]
cool
