### ISSUE TITLE
cast to Crystal::ClassVarContainer failed

### ISSUE THREAD

**Issue by waterlink** [manastech/crystal#1713]
So, I'm currently trying to rewrite my [spec2](https://github.com/waterlink/spec2.cr) to use class per context concept (a middleground between no-class-generation and class per example), because I hit some limits of not having any lexical scope.

And currently I'm encountering `cast to Crystal::ClassVarContainer failed` compile time exception. This is a branch I'm working on now: [browse `better_scoping`](https://github.com/waterlink/spec2.cr/tree/better-scoping) ([or compare](https://github.com/waterlink/spec2.cr/compare/better-scoping)) and this is the commit, where I try to enable one more test and it starts failing with this compile-time exception: https://github.com/waterlink/spec2.cr/commit/c0cb7eee1f2d05c4b8af2898a211f8a8e06739de

I have searched for places where exactly this error can occur and found only this place: https://github.com/manastech/crystal/blob/d6618972e5a4b6d04ebf124104565a394ba62915/src/compiler/crystal/semantic/type_inference.cr#L386-L404

Can somebody help me to understand in which case `scope` is not a `ClassVarContainer` in this case?

BTW, you can notice that I use only 2 class variables throughout the code and probably `Context::@@instance` is responsible for the problems, since I generate subclasses of this class on the fly (via macro).

/cc @waj @asterite @jhass

**Comment by trapped** [comment]
Getting this same [error](https://gist.github.com/trapped/56fd6ab22be92b9c3141) when trying to do this:
```crystal
require "active_record"
class User < ActiveRecord::Model
# ...
end

models = [User]
models.map(&.not_nil!.class as ActiveRecord::Model.class) as Array(ActiveRecord::Model.class)
```

**Comment by waterlink** [comment]
Ok I have added these lines to debug output into the place of cast:

```crystal
pp scope.class  
pp typeof(scope)                                                                                                           
class_var_owner = scope as ClassVarContainer
```

And the output right before cast exception:

```
scope.class = Crystal::NonGenericClassType
typeof(scope) = Crystal::Type
scope.class = Crystal::NonGenericClassType
typeof(scope) = Crystal::Type
scope.class = Crystal::VirtualMetaclassType
typeof(scope) = Crystal::Type
cast to Crystal::ClassVarContainer failed
```

**Comment by waterlink** [comment]
Any clue what is happening there and what is `VirtualMetaclassType` and how it is different from `NonGenericClassType` in the context of `ClassVarContainer` ?

**Comment by asterite** [comment]
@waterlink I think this is a duplicate of #1713 . Here's the [explanation](https://github.com/manastech/crystal/issues/916#issuecomment-129263016). We didn't have time to discuss how to solve this.

**Comment by waterlink** [comment]
I see. In that case at the moment I can workaround by defining this classvar in each subclass (because I control generated subclass).

I think the issue need to be resolved at some point.

Now it could at least throw a compile error with good explanation, that it is currently not supported. If you agree, I can create a PR for that.

**Comment by waterlink** [comment]
Oh, actually even defining it in each single class doesn't really help.. :( I will have to have some sort of `ContextRegistry` class that will hold all the instances then.

**Comment by waterlink** [comment]
Yep, this is a duplicate, so I am closing this.
