### ISSUE TITLE
Request for adding CNAME as ja.crystal.org

### ISSUE THREAD

**Issue by pine613** [manastech/crystal#1719]
Hello, everyone. We ([crystal-jp](https://github.com/crystal-jp)) are the activities that spread the Crystal in Japan.

We are translating official Crystal document now, so It is soon seems to end.

There are Crystal document in Japanese:

 - Web: http://gh-pages.crystal.pine.moe/docs/
 - GitHub: https://github.com/crystal-jp/gh-pages
 - Cite:
   - Google Group: https://groups.google.com/forum/?fromgroups#!topic/crystal-lang/YxvtmERLQOs
   - Issue: #1673

We would like to publish this translated document as subdomain in crystal.org.

We'll maintenance Japanese document, will track to original document,
and plan to support Japanese developer of Crystal. And, we'll host and publish this document in GitHub pages.

Would you add CNAME record (= ja.crystal.org) in crystal.org domain ? @waj  @asterite 

Example of DNS record:
> ja.crystal.org.  IN  CNAME  crystal-jp.github.io.

https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

Thank you.

**Comment by 5t111111** [comment]
As described in above and also in #1673, crystal-jp project is about to finish the translation of the document into japansese. Then, we want to publish it as soon as possible because (sorry but it's just because of our circumstances) we are going to hold a meetup for about 80 crystal users in japan next week, and we would like to introduce that there are docs available in japanese to participants.

Could you please consider to make `ja.crystal.org.` to be a CNAME for `crystal-jp.github.io.` ?

**Comment by waj** [comment]
I just added the CNAME. Note that the correct host name is `ja.crystal-lang.org`. Should we also set `jp.crystal-lang.org`?

**Comment by waj** [comment]
BTW... `crystal-lang.jp` seems to be available :wink:

**Comment by pine613** [comment]
Thank you!!!

> Note that the correct host name is ja.crystal-lang.org. Should we also set jp.crystal-lang.org?

oh... That's right! I had been mistaken.

> BTW... crystal-lang.jp seems to be available

I'll think about it :smiley:

**Comment by alanwillms** [comment]
Juan, could you create a br. or pt-br subdomain to point to
http://alanwillms.github.io/crystal-pt-br-docs ?

I'm working on the Brazilian Portuguese translations of the docs.

2015-10-13 14:25 GMT-03:00 Pine Mizune <notifications@github.com>:

**Comment by 5t111111** [comment]
> I just added the CNAME. Note that the correct host name is ja.crystal-lang.org. Should we also set jp.crystal-lang.org?

Thank you! we appreciate your kindness, and yes, please set jp.crystal-lang.org to point to our website as well.

**Comment by asterite** [comment]
I'm closing this since [ja.crystal-lang.org](http://ja.crystal-lang.org) already works. Please reopen if you need `jp` or create other issues if you need other subdomains.
