### ISSUE TITLE
Unable to return instance of subclass or Nil

### ISSUE THREAD

**Issue by Perelandric** [manastech/crystal#1735]
```crystal
class Foo
end

class Bar < Foo
end

def test() : Foo?
   if true
     Bar.new
   else 
     nil
  end
end

puts test()
```

>Error in line 14: instantiating 'test()'

>in line 6: type must be Foo?, not Bar?

Compiles if I only return the subclass...

```crystal
def test() : Foo
   Bar.new
end
```

...or if I don't statically define the return type.

```crystal
def test()
   if true
     Bar.new
   else 
     nil
  end
end
```

**Comment by kirbyfan64** [comment]
Changing `Foo?` to `Foo+?` or explicitly casting `Bar.new as Foo` fixes the issue. The problem seems to be that union types and polymorphism don't mix. A type in a union is *always* non-polymorphic. See http://play.crystal-lang.org/#/r/iyp.

**Comment by Perelandric** [comment]
@kirbyfan64 Thanks much. That's helpful.
