### ISSUE TITLE
Crystal format error

### ISSUE THREAD

**Issue by benoist** [manastech/crystal#1737]
Hi,

Really cool that the formatter is merged, I've put it in my Guardfile!

Got a format error trying to format this file

https://github.com/benoist/carbon-crystal/blob/466c2d807af625292f7ab0f5ab3b10b9c76fa54a/spec/carbon_support/log_subscriber_spec.cr

When I looked in the file I noticed that there was a comma at the end of line 39 that shouldn't have been there.

**Comment by kirbyfan64** [comment]
What was the actual error?

**Comment by benoist** [comment]
Error: couldn't format 'spec/carbon_support/log_subscriber_spec.cr', please report a bug including the contents of the file: https://github.com/manastech/crystal/issues

**Comment by asterite** [comment]
Good, thanks :-)

It should probably be a syntax error in the parser.

@kirbyfan64 The formatter doesn't report internal errors in a more detailed way, but the source file is enough to reproduce it and fix it.
