### ISSUE TITLE
carc.in (play.crystal-lang.org) lies about recursive macro crash

### ISSUE THREAD

**Issue by kirbyfan64** [manastech/crystal#1739]
http://carc.in/#/r/j0g

> There was no output.

Yeah, right...

I know [this is a wontfix](https://github.com/manastech/crystal/issues/849), but play.crystal-lang.org should give a better description.

**Comment by waj** [comment]
The compiler segfaults. Maybe this should be handled by carc.in and show an error message? Probably https://github.com/jhass/carc.in is a better place to add this issue. @jhass do you agree?

**Comment by kirbyfan64** [comment]
@waj I didn't realize it was a separate repo.

**Comment by jhass** [comment]
Well, at the end of the day it's a duplicate of #271

**Comment by kirbyfan64** [comment]
@jhass Not really. This is just so carc.in can show a message like "Segmentation fault" or something.

**Comment by jhass** [comment]
Still not an issue for this repo, so closing ;)
