### ISSUE TITLE
Logger requires mutex?

### ISSUE THREAD

**Issue by kostya** [manastech/crystal#1748]
when multiple spawns write to the same logger, 
output always looks like mixed trash.

**Comment by jhass** [comment]
I guess, or we keep we spawn a coroutine that writes the messages and use a shared unbuffered channel to submit messages.

**Comment by ysbaddaden** [comment]
That, or be sure to write atomically to the IO stream, instead of multiple writes in Logger as we do now.

**Comment by asterite** [comment]
@kostya Could you send a failing sample? We tried it in Mac and linux and couldn't reproduce it.

**Comment by asterite** [comment]
Nevermind, found it
