### ISSUE TITLE
StringIO is now known as MemoryIO, but there is no mention in changelog

### ISSUE THREAD

**Issue by luislavena** [manastech/crystal#1753]
Looking at 0.9.0 changelog, there is no mention of `StringIO` becoming `MemoryIO`, which was introduced in 9b8e6c7e5f35b62503cd1507b1097d6c20c398dd.

Please mention this in the release notes.

Thank you. :heart: :heart: :heart:

**Comment by asterite** [comment]
Oops! It's because we were about to release, doing a couple of things, and then forgot this change. We'll add it to the changelog and also include it in the release notes. Thanks for catching this!

**Comment by luislavena** [comment]
Thank you, saw the fix in bc0433062ccaae9e6ae84f0afe726f1acd8e2ad4, closing this now.
