### ISSUE TITLE
Glob with trailing slash should list directories

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#1754]
Ruby
```rb
Dir.glob("/*/") # => ["/boot/", "/var/", "/dev/", "/run/", "/etc/", "/tmp/", "/sys/", "/proc/", "/usr/", "/home/", "/mnt/", "/opt/", "/root/", "/srv/", "/bin/", "/lib/", "/lib64/", "/sbin/"]
```

Crystal
```cr
Dir.glob("/*/") # => []
```

**Comment by jhass** [comment]
Probably just another manifestation of the issue, thus as comment but `foo/*/bar` with bar being a directory works neither.

**Comment by jhass** [comment]
And actually not even `/*` lists any directories, only files.

**Comment by asterite** [comment]
I want to fix this, but there's a thing I don't understand (it also applies to Ruby). The `**` pattern matches directories recursively. But then I do:

```crystal
puts Dir["**"].join("\n")
```

and it just lists one level (in Ruby). Using `Dir["*"]` gives the same result.

So what's the logic? I believe the fix might involve changing how to map the pattern to a different regex, but I don't quite understand the `**` behaviour.

**Comment by jhass** [comment]
Ruby documents it at [File.fnmatch](http://ruby-doc.org/core-2.2.3/File.html#method-c-fnmatch), but that doesn't go into much detail either.

bash(1):
> \*      Matches  any  string,  including the null string.  When the globstar shell option is enabled, and \* is used in a pathname expansion context, two
                     adjacent \*s used as a single pattern will match all files and zero or more directories and subdirectories.  If followed by a /, two adjacent  \*s
                     will match only directories and subdirectories.

zshexpn(1):
> Recursive Globbing
       A pathname component of the form `(foo/)#' matches a path consisting of zero or more directories matching the pattern foo.

>  As a shorthand, `**/` is equivalent to `(*/)#`; note that this therefore matches files in the current directory as well as subdirectories.  Thus:

>              ls (*/)#bar

> or

>             ls **/bar

>   does  a  recursive directory search for files named `bar` (potentially including the file `bar` in the current directory).  This form does not follow symbolic
       links; the alternative form `***/` does, but is otherwise identical.  Neither of these can be combined with other forms of globbing within the same path  seg‐
       ment; in that case, the `*' operators revert to their usual effect.


From observed behaviour, `**` degrades to `*`, while `**/` lists all directories recursively.
