### ISSUE TITLE
Formatter: Adds empty space to empty comments in code blocks

### ISSUE THREAD

**Issue by luislavena** [manastech/crystal#1755]
The following example:

```crystal
# Here is the doc of a method, and contains an example:
#
# ```
# result = foo
#
# puts result
# ```
def foo
  # ...
end
```

There is no space after `#` between `result = foo` and `puts result` line, however the format tool adds one.

This result in some trailing spaces warning when merging branches with Git.

Thank you. :heart: :heart: :heart:

**Comment by jhass** [comment]
It probably should just make a final pass to strip trailing whitespace

**Comment by asterite** [comment]
@jhass Great idea, I was going to fix this particular case. Doing that I found that there are more cases where trailing spaces are left. I'll fix it soon :-)

**Comment by asterite** [comment]
I hope that now that the formatter is in the wild we'll fix these details and some bugs once and for all :-)
