### ISSUE TITLE
Formatter: questions about alignment of assignations

### ISSUE THREAD

**Issue by luislavena** [manastech/crystal#1757]
Hello,

This is the 3rd report I submit about the formatter and forgot to say something: thank you for the formatter! :heart: :heart: :heart:

Really appreciate the work put towards it and definitely will iron some details aiming to provide a unified usage of the language.

This is a question about alignment of assignations. Right now constant definitions get aligned:

From:

```crystal
module X
  A = 1
  ABC = 10
end
```

To:

```crystal
module X
  A   =  1
  ABC = 10
end
```

Which is great.

However, this seems only to apply to constants.

From my time dealing with Ruby and several projects and coding styles, I found quite useful align LHS (shorter or larger) to the equal sign:

```crystal
a   = 1
abc = 10
```

Will that be possible? (actually, will that be desired?)

Thank you :heart: :heart: :heart:

**Comment by kirbyfan64** [comment]
> assignations

Well, I accidentally read this as "assassinations", which made the sentence sound...*weird*...

**Comment by asterite** [comment]
Yes, it's possible and we've considered this. However, if it's applied to every series of consecutive assignments it becomes tedious very quickly.

**Comment by adlerhsieh** [comment]
I think this issue has been concluded with not going with it and can be closed?

**Comment by asterite** [comment]
Yes, thanks
