### ISSUE TITLE
error formatting file

### ISSUE THREAD

**Issue by will** [manastech/crystal#1766]
```
crystal-pg ➤ crystal tool format .
Error: couldn't format './src/pg/libpq.cr', please report a bug including the contents of the file: https://github.com/manastech/crystal/issues

crystal-pg ➤ crystal --version
Crystal 0.9.0 (Sat Oct 17 15:59:36 UTC 2015)
```

File ancored to last release (no change since then and current master): https://raw.githubusercontent.com/will/crystal-pg/v0.4.2/src/pg/libpq.cr

**Comment by asterite** [comment]
It's already fixed in HEAD with https://github.com/manastech/crystal/commit/eaa3263bbdf12bd0842cebb0a3cee3cb2ff38d17, the formatter didn't know that enum members could be separated with commas. But thanks anyway!

**Comment by will** [comment]
Thanks
