### ISSUE TITLE
Formatter assignment alignment decisions

### ISSUE THREAD

**Issue by asterite** [manastech/crystal#1773]
Right now the formatter aligns the right hand-side of an assignment. For example:

```crystal
a = if 1
      2
    else
      3
    end
```

It does this with every kind of expression:

```crystal
a = String.build do |str|
      str << "hello"
    end
```

This quickly becomes tedious of the right-hand side expression is long, or if the variable name is long.

This is done because it's maybe more readable, and it's also in the [Ruby style guide](https://github.com/bbatsov/ruby-style-guide#indent-conditional-assignment). But in those examples only `if` and `case` are mentioned. A separate issue is that the editors don't know about this special alignment and when you enter a newline the cursor is placed in a wrong position.

Maybe we can format assignments this way but only for `if`, `unless`, `case`, array, tuple and hash literals. A call then would be formatted like this:

```crystal
a = String.build do |str|
  str << "hello"
end
```

which, I think, is the most usual way to write this.

What do you think?

**Comment by luislavena** [comment]
@asterite I encounter this kinda weird, specially when doing assignment like constructing an array:

```crystal
stack = [
  HTTP::LogHandler.new  
  HTTP::ErrorHandler.new
]
```

Which then is weirdly aligned to the right side :disappointed:

**Comment by ysbaddaden** [comment]
My Ruby VIM plugin only aligns assignments of conditionals, but block calls, arrays and hashes literals are not.
