### ISSUE TITLE
Generic constraints?

### ISSUE THREAD

**Issue by azazeal** [manastech/crystal#1774]
Hey, the docs aren't really clear on this but how can someone declare constraints on generic classes?

Take a look at the following example:

```crystal
abstract class Context
  abstract def bootstrap : Void
end

class App(C) # C should only allow for sub-classes of Context
end
```

Furthermore, the single letter (plus maybe one digit) naming rule for type variables seems a bit restrictive.

Any ideas on this?

**Comment by jhass** [comment]
Duplicate of #934
