### ISSUE TITLE
http_server breaks ab on osx

### ISSUE THREAD

**Issue by kostya** [manastech/crystal#1779]
```
crystal build samples/http_server.cr --release
./http_server 
Listening on http://0.0.0.0:8080
```

```
~$ ab -n 50000 -c 20 http://localhost:8080/
This is ApacheBench, Version 2.3 <$Revision: 655654 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 5000 requests
Completed 10000 requests
Completed 15000 requests
apr_socket_recv: Operation timed out (60)
Total of 16368 requests completed
```

if i rerun ab, and not restarted http_server, it again failed at 16377 requests.

osx 10.9.5
on linux all is ok.

or maybe ab problem?

**Comment by waj** [comment]
I found that OSX normally throttles network connections. Please check if this is your case. You can see system logs using Console.app

**Comment by kostya** [comment]
errors like:

19.10.15 13:29:15,000 kernel[0]: Limiting closed port RST response from 12098 to 250 packets per second
