### ISSUE TITLE
Logger in coroutine won't log anything

### ISSUE THREAD

**Issue by ysbaddaden** [manastech/crystal#1781]
[Logger now uses a coroutine](https://github.com/manastech/crystal/commit/ad47e983e615a3abe1f129af52c1db643c13f809) to write messages, so writing to the output IO is atomic, and we can avoid garbage. This causes some problems:

- If the program doesn't use coroutines, the Logger coroutine will never be invoked, nothing will be written to the log (ie. all log messages are lost).
- Messages written just before the program exits are likely to not be written (ie. most error messages are lost).
- Less problematic, but still: logs are desynchronized to whatever is actually happening, making it a poor friend when analyzing a program behavior.

I already had all these issues when the output IO was buffered, until #1442.

**Comment by technorama** [comment]
Writing single message/line without a coroutine doesn't fix message corruption when writing to a pipe or socket.  It may also be possible to corrupt a file base logger depending on the operating system but I'm not sure.

* Fiber1: writes to log socket but the buffer is full.  Only half the message went out. Waits on event loop.
* Log Process: reads buffer.
* Fiber2: writes to log socket mixing it's message with Fiber1's.
* Fiber1: writes the remaining half of it's message to log socket.

The coroutine problem is fixable by closing the log channel and waiting for the logger using atexit or similar.

**Comment by ysbaddaden** [comment]
I understand this more as `write(2)` and `send(2)` being non atomic. As long as we use a String buffer as in #1783 instead of many writes/sends, we shouldn't hit the libevent loop... or do we? I'd love to learn here, I'm a bit lost :)

**Comment by technorama** [comment]
You can hit the libevent loop with a single write.  The above list with Fiber1/Fiber2 was meant to illustrate that.

**Comment by sdogruyol** [comment]
Is there any update on this :pray:

**Comment by asterite** [comment]
@ysbaddaden @jhass As a compromise, what if we use a Mutex for now? It won't work with multiple threads, but that's not supported anywhere else either, and it's better if this works well but a bit slow than working in a wrong way. I ask because there will be a release soon.

**Comment by sdogruyol** [comment]
:+1: for Mutex

**Comment by ysbaddaden** [comment]
Can we really use a mutex? As far as I recall it locked or crashed. But maybe that was fixed? Or we have a nice lock structure?

I think the coroutine and channel was a good idea... as long as there is some IO or scheduler involved, there is a log and it's up to date. The only problem is when there really isn't any IO happening (pure CPU), in which case, maybe a logger.sync option could be interesting (using a mutex).

BTW, performance can be improved a lot by buffering each message into a String.build and pushing a single call to @io.
