### ISSUE TITLE
crystal failed to compile on OSX(10.11 El Capitan) (version: 0.9.0)

### ISSUE THREAD

**Issue by conflikt** [manastech/crystal#1798]
Recently got crystal upgraded via homebrew from 0.8.x to 0.9.0. Earlier everything was working fine, but suddenly with this upgrade, crystal started to fail to compile with error

~~~
crystal eval 'puts "Hello world!"'
ld: library not found for -levent
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc -o "/Users/konflikt/.crystal/crystal-run-eval.tmp" "${@}"  -rdynamic  -levent -lpcl -lpcre -lgc -lpthread -ldl`
~~~

All the required crystal dependencies are install 
~~~
brew install \
  bdw-gc \
  gmp \
  libevent \
  libpcl \
  libxml2 \
  libyaml \
  llvm
Warning: bdw-gc-7.4.2 already installed
Warning: gmp-6.0.0a already installed
Warning: libevent-2.0.22 already installed
Warning: libpcl-1.12 already installed
Warning: libxml2-2.9.2 already installed
Warning: libyaml-0.1.6_1 already installed
Warning: llvm-3.6.2 already installed
~~~

Seems like an issue with current upgrade.
System: Mac OSX (10.11 El Capitan), Crystal: 0.9.0, LLVM: 3.6.2

**Comment by TBD** [comment]
```export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/lib"```

this fixed for me, but if there are problems check http://stackoverflow.com/questions/3146274/is-it-ok-to-use-dyld-library-path-on-mac-os-x-and-whats-the-dynamic-library-s

**Comment by conflikt** [comment]
@TBD yes, thanks. 
This solve the issue for me too. But that should be handled internally. no?

**Comment by ysbaddaden** [comment]
Not really, this is a homebrew configuration. It could be installed in `/opt` instead of `/usr/local/lib` for example.

**Comment by waj** [comment]
I also had this problem after upgrading to 10.11 but I solved it reinstalling the command line tools: `xcode-select --install` and selecting as the default active toolchain: `xcode-select --switch /Library/Developer/CommandLineTools`

Seems like XCode doesn't look by default for libraries at /usr/local/lib anymore. My understanding is that Homebrew should at least warn about this when running `brew doctor`.

**Comment by asterite** [comment]
@conflikt I just upgraded to El Capitan, had the same issue, did what @waj suggested and I'm having everything working again. Can you confirm this fixed it for you too?

**Comment by squarism** [comment]
Same problem (levent not found despite having deps installed).  Same situation (upgraded to 10.11).  @waj fix worked for me.  Thanks!  :cake:

**Comment by conflikt** [comment]
@asterite, I already mentioned the same thing worked for me too in my last comment <tt>`conflikt commented on Oct 22, 2015`</tt>. I guess you missed that :smiley:

**Comment by gottlike** [comment]
@asterite Maybe this should be mentioned in the Mac OS install docs. I was having the same problem and was lucky enough to find this Github issue..

**Comment by asterite** [comment]
Yeah, it's just so frequent that I think it's worth it. Just did so: http://crystal-lang.org/docs/installation/on_mac_osx_using_homebrew.html

**Comment by gottlike** [comment]
:+1:
