### ISSUE TITLE
Syntax to provide a default to_s value for enum variants

### ISSUE THREAD

**Issue by Perelandric** [manastech/crystal#1799]
It would be nice to be able to provide a default `to_s` value for `enum` variants, perhaps as a Symbol. When #1329 is fixed, overriding `to_s` will be able to handle this for some cases, but it would be nice to be able to do it without runtime cost. The Nim language has something similar using a String.

```cr
enum Foo
  Bar = :BAR
  Baz = :bazzz
end
```

This would interfere with the ability to set a number manually, so it would require syntax to handle both.

```cr
enum Foo
  Bar = 21, :BAR
  Baz = 42, :bazzz
end
```

We could also then create a value from its Symbol.

```cr
puts Foo.new(:bazzz)
```

And could possibly also retrieve its Symbol using a method, though I don't know what the value would be when there's no Symbol defined. Maybe `nil`.

```cr
puts Foo::Bar.symbol == :BAR
```

Does this enhancement sound useful?

**Comment by asterite** [comment]
You can override `to_s(io)` for your enum and define your logic there, doing a case over the enum value. The default implementation is just a convenient one, but you can override it in whatever way you want.

http://play.crystal-lang.org/#/r/jry

**Comment by Perelandric** [comment]
@asterite Yes but this can lead to problems when you have an enum with a large number of variants. You now have to keep two large lists in sync. Having the side-by-side is much more convenient.

When `super()` works in `to_s`, you can provide an override when there's a uniform translation but that doesn't work for all cases.
