### ISSUE TITLE
& for a member function

### ISSUE THREAD

**Issue by kirbyfan64** [manastech/crystal#1801]
Ruby seemingly has this weird thing where `&x.y` doesn't seem to do anything useful. What if, in Crystal, `&x.y` was equivalent to `{|v| x.y v }`? Basically, it takes a reference to the `y` method of `x`. Kind of like `&.+`?

**Comment by asterite** [comment]
In Ruby, and in Crystal, `&` is for forwarding a captured block or Proc:

http://play.crystal-lang.org/#/r/jt3
http://play.crystal-lang.org/#/r/jt4

What you are looking for is fun pointers (should be named proc pointers, actually):

http://play.crystal-lang.org/#/r/jt5

**Comment by kirbyfan64** [comment]
@asterite I didn't know about proc pointers. Thanks!
