### ISSUE TITLE
Variable compile time is Nil ?

### ISSUE THREAD

**Issue by adlerhsieh** [manastech/crystal#1802]
The following code runs into compile error, saying that I use `nil` for calculation.

```ruby
class Foo
  def initialize(path)
    index     = path.index("directory/")
    @pwd      = path[0..(index+9)]
    @filename = path[(index+10)..-1]
  end
end

Foo.new("/user/directory/foo.cr")
```

It says the `index` value is `nil`:

```
Error in line 9: instantiating 'Foo:Class#new(String)'
instantiating 'Foo#initialize(String)'
in line 4: undefined method '+' for Nil (compile-time type is (Nil | Int32))
======================================================================

Nil trace:
  eval:3
  /usr/lib/crystal/string.cr:1599
      def index(search : String, offset = 0)
  /usr/lib/crystal/string.cr:1599
      def index(search : String, offset = 0)
          ^~~~~
  /usr/lib/crystal/string.cr:1616
        nil
        ^
```
[source code](http://play.crystal-lang.org/#/r/jt0)

But I did pass the string `"/user/directory/foo.cr"` as the argument. Don't know how does that happen. However, I changed the approach to `split` and it works fine.

```ruby
class Bar
  def initialize(path)
    @pwd      = path.split("/")[0..-2].join("/")
    @filename = path.split("/")[-1]
  end
end

Bar.new("/user/directory/bar.cr")
```

[source code](http://play.crystal-lang.org/#/r/jt2)

Am I missing something or is that a bug? Thanks in advance!

**Comment by asterite** [comment]
The compiler analyzes methods independently of the actual values used to invoke them. The compiler sees this:

```crystal
  def initialize(path)
    index     = path.index("directory/")
    @pwd      = path[0..(index+9)]
    @filename = path[(index+10)..-1]
  end
```

Without knowing the value of `path`, `path.index("directory/")` might be `nil`, and that's why you are getting the error.

**Comment by adlerhsieh** [comment]
I see. But in the second example, `path` might be `nil` too. 

```ruby
path.split("/")[0..-2].join("/")
```

How does the compiler know that it responds to `split` method without an error?

**Comment by adlerhsieh** [comment]
I see. Thanks for clarification!
