### ISSUE TITLE
'llvm-c/Core.h' not found error

### ISSUE THREAD

**Issue by adlerhsieh** [manastech/crystal#1818]
I was trying to rebuild the compiler by running `make clean crystal spec` commands and saw this error message:

```
c++ -c -o src/llvm/ext/llvm_ext.o src/llvm/ext/llvm_ext.cc ` --cxxflags`
/bin/bash: --cxxflags: command not found
src/llvm/ext/llvm_ext.cc:1:10: fatal error: 'llvm-c/Core.h' file not found
#include <llvm-c/Core.h>
         ^
1 error generated.
make: *** [src/llvm/ext/llvm_ext.o] Error 1
```

I was trying to make some change in the compiler but even I reverse all the changes this still didn't work. Am I missing something?

**Comment by jhass** [comment]
You seem to miss the  development headers/tools for LLVM.

**Comment by asterite** [comment]
@adlerhsieh Can I close this?

**Comment by adlerhsieh** [comment]
Yeap sure, I'm still trying to get my llvm working but I got the idea.
