### ISSUE TITLE
enum .parse? method case insensitivity

### ISSUE THREAD

**Issue by Perelandric** [manastech/crystal#1831]
Seems this is either a documentation bug or code bug. Not sure.

The docs for `.parse?` state: "*Returns the enum member that has the given name, or nil if no such member exists. __The lookup is case-insensitive__*."

However it seems that the only case insensitivity comes with a character after an underscore because the macro uses `.camelcase` instead of something like `.downcase`.

So is full case insensitivity intended or is it meant to be limited?

Side question: If full case insensitivity is intended, would it make sense for hyphens to be converted to underscores as well?

**Comment by asterite** [comment]
Oh, the last commit changed the behaviour but didn't update the docs :-(

The comparison is camelcase.

https://github.com/manastech/crystal/commit/87a2788f2bf47b273e7f33b9bce8d45881fd60e2

**Comment by Perelandric** [comment]
Thanks @asterite .

**Comment by asterite** [comment]
I'll change the docs :-)

In your case, does this bring any problem? Or it's just that the behaviour was unexpected related to the docs?

**Comment by Perelandric** [comment]
There was no problem except in its expected behavior. 

For my case, `MyEnum.parse?(my_str.downcase.gsub('-', '_'))` works fine, though I'll eventually write my own parser so that it isn't using 3 passes over the string.

I do think it could cause problems for those weird cases where it actually makes some sense to have two enum variants distinguished only by an underscore, but as with case insensitivity, those issues are  going to be inevitable.
