### ISSUE TITLE
Bus error: 10 when `.to_s` isn't defined in a subclass

### ISSUE THREAD

**Issue by Perelandric** [manastech/crystal#1833]
This is half question, half bug report because I'm unable to make a reduced code example at the moment and it will take more  time than I have available right now.

The crux of the problem is that if I don't include a `.to_s` method on a subclass definition, I get the `Bus error: 10` at runtime. If I define `to_s` and merely have it call `super()`, the problem is fixed.

I've tried a simplified version of the code, but it doesn't reproduce the error. The code is fairly complicated and since I have a workaround, picking away at this issue is going to have to wait a little while. 

So is there any idea what could cause this, or is the breadth of possibilities just too great?

**Comment by jhass** [comment]
I'm afraid without a way to reproduce, no one will be able to help much. A 1 minute google indicates trying to modify a constant value of the binary.

**Comment by Perelandric** [comment]
@jhass Yeah, I did the 1 minute Google diagnostic. Thought maybe someone had some Crystal-specific insight.

Anyway, I'd like to keep this open as a reminder to go back and figure this out. I doubt it's anything directly with my code since the fix is just  to manually do what I would expect to be done via inheritance.

It'll nag at me while it's still open, so I should get to it before too terribly long. :smile:

**Comment by Perelandric** [comment]
Closing since I'm no longer able to reproduce this issue.
