### ISSUE TITLE
Sugestion about aplication template

### ISSUE THREAD

**Issue by xdougx** [manastech/crystal#1843]
How can i build (suggest)  my own crystal projects structures, i've done an application and i builded an application structure like this:
![screen shot 2015-10-30 at 3 07 18 pm](https://cloud.githubusercontent.com/assets/1920415/10852554/6f459ece-7f18-11e5-8210-75a962a16f94.png)

if it has an application template  like:
```
my_application_folder
--| .crystal
--| .shards
--| app
--| config
---- setup.cr
---- requirements.cr
--| libs
--| log
--| spec
--| tmp
----| pids 
.gitignore
.travis.yml
boot.cr
```

when i run my application:
`$ crystal run boot.cr -- my args here`
or
`$ crystal run /path/to/my/app/boot.cr -- my args here`

**Comment by kostya** [comment]
i also think about this, you forgot:
+ environments
+ config/environtments/
+ config/initializers
+ bin/
+ Makefile (to compile binary, specs)

**Comment by xdougx** [comment]
Yeah, also it shold include those folders too

**Comment by asterite** [comment]
A Crystal project structure is the one given by `crystal init`. If you app's name is `foo` you can provide `foo init` that will generate a specific template. That program could invoke `crystal init`, but it's not necessary.

**Comment by xdougx** [comment]
This is my boot.cr
``` crystal
ROOT = __DIR__
SHARED_ROOT = -> { __DIR__.gsub(/releases\/[0-9]+/, "shared") }.call

require "./config/setup"
require "./config/requirements"

# Module::Application.run
#run your application
```crystal
This is my setup.cr its define some Contants
```
# lang
require "colorize"
require "logger"
require "http/server"
require "yaml"
require "json"

AVAILABLE_ENVS = %w(test development production staging)

APPLICATION_ENV = -> {
  current = "development"
  AVAILABLE_ENVS.each do |env|
    current = env if ARGV.includes?(env)
  end
  current
}.call

$logger = Logger.new(File.open("#{ROOT}/log/#{APPLICATION_ENV}.log", "a+"))

def putsl(message, level = :info, label = "", logger = $logger)
  severity = {
    debug: Logger::Severity::DEBUG,
    info: Logger::Severity::INFO,
    warn: Logger::Severity::WARN,
    error: Logger::Severity::ERROR,
    fatal: Logger::Severity::FATAL,
    unknown: Logger::Severity::UNKNOWN
  }
  logger.log(severity.fetch(level), message, label)
end

```

**Comment by kostya** [comment]
for light projects in ruby, i use my https://github.com/kostya/ruby-app, i think the same in crystal would be nice.

**Comment by xdougx** [comment]
@asterite is that possible to have more then one project template for crystal?

**Comment by asterite** [comment]
@xdougx No, the template provided by `crystal init` is just a useful template for any kind of application or library. If you need different templates, provide them in a separate app. There's also [this](https://github.com/generate-cr) but I don't know if it's still ongoing.

**Comment by jhass** [comment]
I don't get whether this issue is a question or a proposal.

**Comment by xdougx** [comment]
Both, a question and a proposal.
To be available other templates, atm has two: app and lib.
App template is a 'lil bit poor, and for more complex applications with configurations, environments, deployments and anything else, i think is needed to has this option available.

**Comment by jhass** [comment]
It's hard to work on issues that mix and mash such things. Is the issue solved when the question is answered? When the issue looks like a question on first glance, why is it still open after a long time? One has to reread the whole thing all the time to get a picture. Please try to open specific and focused issues.

**Comment by asterite** [comment]
@xdougx Configuration, deployments, environments, etc: if you are making a game, or a console app, such things don't make much sense. Or maybe yes, but I think you are thinking about web applications here.

For example Rails has `rails init` and it lets you choose a lot of things that don't make sense for any kind of Ruby application. Then bundler has `bundler init` to create any kind of gem. So think of `crystal init` as `bundler init`. If you want other templates, provide them in your specific application.

**Comment by waterlink** [comment]
I think this should be handled by framework, not a language.

Currently, language provides 2 simplest templates:
- lib - minimal possible library
- app - minimal possible application

And I think this it is doing its best job now in that regard.

Anything more complex should come from respective frameworks, i.e.:
- web app template from some web framework
- cli app template from some cli framework
- game app template from some game engine framework
- .. and so on ..

`generate-cr` is my creation. It is currently frozen in probably even
broken state. I had no real need in generating boilerplates so far, that is
why I stopped development for it. Though I mostly build tools and libraries
in Crystal, not full-blown apps. If you are really eager to see it mature
and become actually usable with some solid library of boilerplate templates
- please create an issue here: https://github.com/generate-cr/generate - so
we can continue discussion there, maybe it would even make sense to create
some chat for it (like gitter or slack) to make feedback faster.

Cheers!



--
Best Regards,
Alexey Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476
