### ISSUE TITLE
Question about order of evaluation of nested expressions

### ISSUE THREAD

**Issue by Perelandric** [manastech/crystal#1844]
```crystal
@foo = [bar(), baz()]
```

Given the above code, is it guaranteed that the Array literal syntax `[]` will not assign a new Array to `@foo` until after both `bar()` and `baz()` have returned?

And if `bar()` or `baz()` raises an exception, is it guaranteed that `@foo` will remain at its former value? *(Assuming `bar()` and `baz()` didn't modify it before raising, and no multi-threading, etc.)*

TIA

**Comment by asterite** [comment]
Yes to all questions. An array literal is just syntax sugar for array creation and adding values to it:

```crystal
@foo = Array(typeof(bar(), baz())).build(2) do |buffer|
  buffer[0] = bar()
  buffer[1] = baz()
end
```

**Comment by jhass** [comment]
You can use `crystal tool browser` to look to the expanded code:
```cr
foo = ::Array(typeof(bar, baz)).build(2) do |__temp_111|
  __temp_111[0] = bar
  __temp_111[1] = baz
  2
end
```

See also

**Comment by Perelandric** [comment]
Thanks @asterite  and @jhass . Just wanted to make sure this was officially the order of expressions before taking too much advantage of it.
