### ISSUE TITLE
Segmentation fault when class assigned to instance variable raises in its initializer

### ISSUE THREAD

**Issue by Perelandric** [manastech/crystal#1845]
When a class's initializer invokes the `initialize` of a different class to assign it to an instance variable, and this is done inside a `begin`, if the different class raises during initialization, the instance variable will not get `nil`, leading to a seg fault.

```cr
class Foo
	def initialize
		begin
			@bar = Bar.new   # `Bar.new` will raise
		rescue
		end
	end

	def to_s : String
		(b = @bar) ? b.to_s : "DEFAULT"   # `@bar` has invalid memory
	end
end

class Bar
	def initialize
		raise "error"
	end
end

f = Foo.new
puts f.to_s
```

If we merely acknowledge the existence of `@bar` in the `rescue`, it works.

```cr
class Foo
	def initialize
		begin
			@bar = Bar.new
		rescue
			@bar   # adding this line makes it work
		end
	end

	def to_s : String
		(b = @bar) ? b.to_s : "DEFAULT"
	end
end
```

Naturally, adding a default initialization of `@bar` also fixes it.

My expectation was that `@bar` would either get `nil` or more generally would be in such a state as though it was never created.

>Crystal 0.9.1 (Fri Oct 30 16:14:17 UTC 2015)

**Comment by asterite** [comment]
The compiler is making `@bar` of type `NoReturn`, but it's true, it should be `Nil` as it can never be assigned a value.
