### ISSUE TITLE
Return type restriction ignored when whitespace is missing

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#1848]
This shouldn't compile:
```cr
def encode():String
 1
end

encode() 
```
http://carc.in/#/r/lgx

**Comment by asterite** [comment]
Good catch. In Ruby this is valid:

```ruby
def foo():Bar
end

p foo #=> :Bar
```

That is, `:Bar` is part of the body. In our case I just made it a syntax error because it can be really confusing if we retain Ruby's behaviour.
