### ISSUE TITLE
Nilable type when rescue in initialize merely wraps the exception

### ISSUE THREAD

**Issue by ysbaddaden** [manastech/crystal#1857]
Since #1845 was fixed, a rescue makes all class variables be nilable, but that shouldn't be the case if all the rescue does is raising again. For example the following will print `Int32` with Crystal 0.9.1 but `Int32?` with current master:

```crystal
class Error < Exception
end

class Foo
  def initialize
    @x = 1
  rescue ex
    raise Error.new(ex.message)
  end

  def bar
    typeof(@x)
  end
end

puts Foo.new.bar
```

My use case is to return a generic ConnectionError exception when trying to connect to different services that raise their own specific exceptions. I can get away with it using `getter! x` but I would prefer to avoid it, so I can catch if it actually becomes nilable by other means.

**Comment by asterite** [comment]
I'll try to fix it.

As a workaround you can assign to a local `x` and then to `@x = x` after the begin/rescue.

**Comment by ysbaddaden** [comment]
It's not high priority anyway. I'm just reporting an edge-case.

**Comment by asterite** [comment]
@jhass The case you mentioned (`begin; @bar = 1; rescue; @bar = 2; end`) is also covered by this fix \o/

**Comment by jhass** [comment]
Good job!

**Comment by ysbaddaden** [comment]
Oh thanks!
