### ISSUE TITLE
How to get class children?

### ISSUE THREAD

**Issue by kostya** [manastech/crystal#1860]
i trying this, but no luck:
http://play.crystal-lang.org/#/r/lp2

**Comment by kirbyfan64** [comment]
What's your use case? I don't it's really possible to type check this normally, and I'm not even sure if the resulting hash would even be usable.

**Comment by kostya** [comment]
http://play.crystal-lang.org/#/r/lp3

**Comment by kirbyfan64** [comment]
@kostya How about something like http://play.crystal-lang.org/#/r/lpn?

**Comment by kostya** [comment]
nice, but output should be 2

**Comment by jhass** [comment]
http://play.crystal-lang.org/#/r/lpp

**Comment by jhass** [comment]
Or http://play.crystal-lang.org/#/r/lpt

**Comment by kostya** [comment]
super, thanks

**Comment by kostya** [comment]
find little bug while playing with it http://play.crystal-lang.org/#/r/lq4
then problem in `@@my_name ||= `

**Comment by kostya** [comment]
why not to add to every class this methods?
```
  macro def self.subclasses : Array(self.class)
    {{ self.subclasses }}
  end
```

and others like, methods, private_methods, ...

**Comment by jhass** [comment]
The first call would set it in stone, classes defined afterwards won't be included.

**Comment by kostya** [comment]
? http://play.crystal-lang.org/#/r/lq7

**Comment by jhass** [comment]
Mh okay, maybe that changed.

**Comment by omninonsense** [comment]
Isn't that executed at compile time, so whenever you call it, it would just return all subclasses?
