### ISSUE TITLE
Question, macro wrapper with various args

### ISSUE THREAD

**Issue by kostya** [manastech/crystal#1861]
i need generate wrapper around methods with different arity and with options, how to do it?
i trying it:

http://play.crystal-lang.org/#/r/ls9

**Comment by kirbyfan64** [comment]
More generic thing: Crystal should have keyword-only (named-only, in Ruby lingo ;) arguments? In Python, this could be:

```python
def wrapper(*args, *, a=1, b=2):
    wrapper(*args) + a + b
```

**Comment by asterite** [comment]
Without keyword-only arguments this is kind of impossible to do. You can try it with Ruby and see that it doesn't work with default values, but does work with keyword arguments.

It would be nice to know why you need such wrappers.

**Comment by jhass** [comment]
It would be possible if we would have a way to fetch a `Def` for a given signature, akin to Ruby's `Object#method`. Then one could enumerate the arguments of the method and generate the right signature for the wrapper.

**Comment by kostya** [comment]
i rethink this to http://play.crystal-lang.org/#/r/m3v
but macro seems not allowed default params, and keyword params

**Comment by kostya** [comment]
http://play.crystal-lang.org/#/r/m3x
