### ISSUE TITLE
Union type problem with complex hash

### ISSUE THREAD

**Issue by sdogruyol** [manastech/crystal#1868]
This is a bit complex but i'll try to explain.

I have a JSON Api which returns an array of objects (union types) which may contain an array of objects and other types.

```json
[{
  "name": "HAMBURGER M",
  "possible_items": [
    {
      "seq": 350114,
      "display_name_tr": "SPRITE B\u00dcY\u00dcK",
      "display_name_en": "SPRITE LARGE"
    },
    {
      "seq": 350137,
      "display_name_tr": "HOT CHOCOLATE",
      "display_name_en": "HOT CHOCOLATE"
    }
  ]
}]

```

Here's the code that produces the output

```crystal
require "kemal"
require "json"
require "pg"

PG_URL = "postgres://serdardogruyol@localhost:5432/kiosk"
DB     = PG.connect PG_URL

alias ReturnType = String | Int32

get "/" do |env|
  env.content_type = "application/json"
  combo_menus = DB.exec("SELECT * FROM combo_menus")
  combo_menus.to_hash.map do |cm|
    combo_menu_hash = {} of String => ReturnType | Array(Hash(String | Symbol, ReturnType))
    possible_items_sql = <<-SQL
      SELECT DISTINCT(mi.seq), micmgm.price, micmgm.is_default,
             its.display_name_tr, its.display_name_en
      FROM combo_menus cm
      INNER JOIN combo_menu_side_group_mappings cmsgm
      ON cm.seq=cmsgm.combo_menu_seq
      INNER JOIN combo_menu_groups cmg
      ON cmg.seq=cmsgm.combo_menu_group_seq
      INNER JOIN menu_item_combo_menu_group_mappings micmgm
      ON micmgm.combo_menu_group_seq=cmsgm.combo_menu_group_seq
      INNER JOIN menu_items mi
      ON mi.seq=micmgm.menu_item_seq
      INNER JOIN item_settings its
      ON mi.seq=its.item_seq
      WHERE cm.seq=#{cm["seq"]}
    SQL
    combo_menu_hash["name"] = cm["name"] as String
    possible_items = DB.exec(possible_items_sql)
    combo_menu_hash["possible_items"] = possible_items.to_hash.map do |pi|
      {"seq": pi["seq"] as Int32, "display_name_tr": pi["display_name_tr"] as String, display_name_en: pi["display_name_en"] as String}
    end
    combo_menu_hash
  end.to_json
end

```

This works but the database result contains price which is ```Float32``` . That's why i want to use ```ReturnType``` as below

```crystal
alias ReturnType = String | Int32 | Float32
```

But this fails to compile with

```
no overload matches 'Hash(String, String | Int32 | Float32 | Array(Hash(String | Symbol, String | Int32 | Float32)))#[]=' with types String, Array(Hash(String | Symbol, String | Int32))
Overloads are:
 - Hash(String, String | Int32 | Float32 | Array(Hash(String | Symbol, String | Int32 | Float32)))#[]=(key : String, value : (String | Int32 | Float32 | Array(Hash(String | Symbol, String | Int32 | Float32))))

    combo_menu_hash["possible_items"] = possible_items.to_hash.map do |pi|
```
Do i have to explicitly return a ```Float32```value to do this?

**Comment by asterite** [comment]
I know this won't answer your question, but I wouldn't generate a huge object in memory only to later dump it as json. I would use a [JSON::Builder](http://crystal-lang.org/api/JSON/Builder.html). For example:

```crystal
require "json"

possible_items = [1, 2, 3]

string = String.build do |io|
  io.json_object do |obj|
    obj.field "name", "name"
    obj.field "possible_items" do
      io.json_array do |array|
        possible_items.each do |item|
          array.push do
            io.json_object do |obj|
              obj.field "seq", item
            end
          end
        end
      end
    end
  end
end
puts string
```

http://play.crystal-lang.org/#/r/lyb

That's way more efficient and you won't have to deal with types.

**Comment by asterite** [comment]
I also wouldn't use `to_hash` (I guess it transforms an sql result set into a hash). That's another memory transformation that you can avoid and by traversing those objects just once you won't have issues with types and it'll be more efficient.

**Comment by asterite** [comment]
The main issue is that in Ruby we use Hash for everything, and in Crystal it's painful to do that. And that's kind of good, because you'll avoid Hash unless necessary (like, for representing a mapping, not any kind of object) and in the meantime you'll end up with more efficient code.

**Comment by sdogruyol** [comment]
@asterite Thanks for the good answers but like you said it doesnt directly answer the question.

Apart from JSON, my main question is mostly about union types and i think this is a good case. Do i really have to explicitly return a ```Float32```to satisfy the union?

**Comment by asterite** [comment]
Oh, I now understand the issue, I think. The problem is that `possible_items.to_hash.map { ... }` returns an Array(U) where U isn't **exactly the same** type you said was the key of `combo_menu_hash`. I reduced the code:

```crystal
alias ReturnType = String | Int32

combo_menu_hash = {} of String => ReturnType | Array(ReturnType)
combo_menu_hash["foo"] = "bar"
combo_menu_hash["possible_items"] = ["a"] # This is Array(String), not Array(ReturnType)
```

The solution is to do:

```crystal
alias ReturnType = String | Int32

combo_menu_hash = {} of String => ReturnType | Array(ReturnType)
combo_menu_hash["foo"] = "bar"

# Now possible items is Array(ReturnType), so we can assign it as a value of combo_menu_hash
possible_items = [] of ReturnType
possible_items << "a"
combo_menu_hash["possible_items"] = possible_items
```

Alternatively, cast each element to the type you need:

```crystal
alias ReturnType = String | Int32

combo_menu_hash = {} of String => ReturnType | Array(ReturnType)
combo_menu_hash["foo"] = "bar"

combo_menu_hash["possible_items"] = ["a" as ReturnType] # Now it's an Array(ReturnType)
```

In your case you'll have to do the same. I guess doing:

```crystal
combo_menu_hash["possible_items"] = possible_items.to_hash.map do |pi|
  {
    "seq":             pi["seq"] as ReturnType,
    "display_name_tr": pi["display_name_tr"] as ReturnType,
    display_name_en:   pi["display_name_en"] as ReturnType,
  } # Now compiler knows this is Hash(String | Symbol, ReturnType)
end
```

If the above doesn't work (it might not work because I'm not sure casting a union to another union type works yet) you might need to to `(pi["seq"] as Int32) as ReturnType`.

**Comment by sdogruyol** [comment]
Yeah this is just what i needed :+1: 

Meanwhile do you think of any better way to handle this kind of situations? Or will there be any improvements in the future ala Crystal 1.0.0 ( I mean lots of casting)

**Comment by asterite** [comment]
We'll have `Array(Object), Hash(String, Object)`, etc., so you can put any type without any restriction. But when you get a value from there you'll probably have to cast it too. In the case of building a big object and then invoking `to_json` on it I think there won't be any casts.
