### ISSUE TITLE
Channel close doesn't work

### ISSUE THREAD

**Issue by askn** [manastech/crystal#1869]
After closing the channel should give an error message if `receive` is call. It doesn't work but the spec is passing https://github.com/manastech/crystal/blob/master/spec/std/channel_spec.cr#L195

```crystal
jobs = Channel(Int32).new 3

3.times do |j|
  jobs.send j
end

puts "closed? #{jobs.closed?}"
jobs.close
puts "closed? #{jobs.closed?}"

puts jobs.receive
puts jobs.receive
puts jobs.receive
```

output

```
closed? false
closed? true
0
1
2
```

**Comment by jhass** [comment]
A buffered channel still allows to receive the items pending, that is intentional. The next receive call after it ran empty will no longer block but raise instead on a closed channel.

**Comment by askn** [comment]
thanks :+1:
