### ISSUE TITLE
function doesn't accept lambda as a parameter

### ISSUE THREAD

**Issue by Nakilon** [manastech/crystal#1875]
http://carc.in/#/r/m2l

    def f y
    end

    f ->{
      ([] of Int32).flat_map do
        [] of Int32
      end
    }

```Syntax error in eval:5: expecting token '}', not 'do'```

**Comment by waterlink** [comment]
Parser is confused at this point. To disambiguate, use parenthesis:
http://carc.in/#/r/m2x

--
Best Regards,
Alexey Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476
