### ISSUE TITLE
Question, inspect code in macro

### ISSUE THREAD

**Issue by kostya** [manastech/crystal#1876]
how to do this?

http://play.crystal-lang.org/#/r/m36

**Comment by Perelandric** [comment]
I think you want `.stringify`.

http://play.crystal-lang.org/#/r/m3e

```
macro bla(code)
  res = {{code.id}}
  str = {{code.stringify}}
  puts "#{str} = #{res}"
end
```

**Comment by kostya** [comment]
hmm, i not think about this, thanks

**Comment by jhass** [comment]
Note that you reimplemented `pp`.

**Comment by kostya** [comment]
next question, how to inspect method param
http://play.crystal-lang.org/#/r/m4p

**Comment by Perelandric** [comment]
The [Macros::Call](http://crystal-lang.org/api/Macros/Call.html) docs show an `args` collection. 

I don't know if there's a better way, but this seems to do what you want, though it assumes there's a single argument passed...

http://play.crystal-lang.org/#/r/m53

```
macro bla(code)
  res = {{code}}
  name = {{code.name.stringify}}
  args = {{code.args[0]}}
  puts "#{name}(#{args}) = #{res}"
end
```

**Comment by jhass** [comment]
* http://play.crystal-lang.org/#/r/m54
* http://crystal-lang.org/api/Macros/Call.html
* http://crystal-lang.org/api/Macros/Var.html

**Comment by kostya** [comment]
but here i calculate params twice: http://play.crystal-lang.org/#/r/m5a
how to calculate it once, and pass it to inspect and to method

**Comment by jhass** [comment]
http://play.crystal-lang.org/#/r/m5g ? Note this is still pretty much reimplementing `pp`. I think this would be much faster if you described what you're really trying to do.

**Comment by kostya** [comment]
@jhass no, i expect it output calculated arg, like in my example:
```
some_method([1]) = 2
some_method([2]) = 3
some_method([3]) = 4
some_method([4]) = 5
some_method([5]) = 6
```

but not to calculate it twice

**Comment by kostya** [comment]
user write some dsl functions:
```ruby
def calc_some1
  # ... some calculations
  "res1"
end

def calc_some2(x)
  # ... some calculations
  "res2"
end

def calc_arg(i)
  # ... some calculations
  "arg#{i}"
end
```

then he want to call it with some wrapper:
```ruby
wrapper calc_some1, options: { ... }
10.times do |i|
  wrapper calc_some2(calc_arg(i)), options: { ... }
end
```

wrapper itself doing some useful things: using options, calling method, and logging.

i want to see in log:
```
calling calc_some1: res1, ...
calling calc_some2(arg0): res2, ...
calling calc_some2(arg1): res2, ...
calling calc_some2(arg2): res2, ...

```

and not to call `calc_arg` extra times.

**Comment by Perelandric** [comment]
@kostya 

In your previous example, you're wondering why `ii(i)` is invoked twice per iteration instead of once?

**Comment by jhass** [comment]
http://play.crystal-lang.org/#/r/m5z

**Comment by kostya** [comment]
thanks final version: http://play.crystal-lang.org/#/r/m6l

**Comment by waterlink** [comment]
@kostya, better use `%arguments` instead of `arguments` in macro. Because
`%name` will generate temporary variable with unique name. On the other
hand just `name` will translate directly to `name` variable in resulting
code - this can lead to a trouble with types and overriding previously
defined variables.

--
Best Regards,
Oleksii Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476
