### ISSUE TITLE
[Help] gherkin3 parser using crystal-lang

### ISSUE THREAD

**Issue by anilreddy** [manastech/crystal#1893]
Hi,

I have recently heard about this language and it is fantastic and am currently learning this language and am basically a Tester. I want to make this language a bit more popular. Could any one please help me in writing a parser for gherkin3 for this issue: [#119](https://github.com/cucumber/gherkin3/issues/119)

I know this is not the correct place for asking this. But I didn't find a better place than this.

Thanks,
Anil

**Comment by kirbyfan64** [comment]
Try the mailing list... :)

**Comment by omninonsense** [comment]
Have you looked at the [Ruby gherkin3 parser](https://github.com/cucumber/gherkin-ruby) yet? Porting it shouldn't be an issue. Also, it would give you an excellent opportunity to familiarise yourself some more with the languages (both gherkin3, and Crystal)!

**Comment by anilreddy** [comment]
@omninonsense I have already started building a parser by referring Ruby's. But reason am asking help is familiar with Ruby but not much fluent. I shall push the code soon. Then some body can review it and help me out.

**Comment by asterite** [comment]
@anilreddy Please use the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/crystal-lang) for this so the issue tracker doesn't end up with open issues which are just questions. Thanks!
