### ISSUE TITLE
Nightly builds stuck at 235f134?

### ISSUE THREAD

**Issue by luislavena** [manastech/crystal#1898]
Hello @jhass,

I'm trying to install latest nightly but seems last build is from November 8 (from commit 235f134)

Is there no newer build?

Thank you.

**Comment by kirbyfan64** [comment]
*cough* Build it yourself *cough*

;)

**Comment by luislavena** [comment]
@kirbyfan64 :trollface: 

Wanted to know if there was a problem and if so, perhaps how can we help to get it up and running again. I'm quite capable of building myself, but nightly is also used in Travis, so what is the purpose of testings against nightly if no new build is actually available? :smile:

**Comment by jhass** [comment]
Thanks for notifying, something messed up adding the built package to the repository, should be fixed.

**Comment by luislavena** [comment]
Thank you @jhass !!! :heart: :heart: :heart:
