### ISSUE TITLE
Error for HTTP::Cookie#to_json

### ISSUE THREAD

**Issue by Thyra** [manastech/crystal#1905]
I get an error when I try to convert an innocent little HTTP::Cookie to json:
```
require "http"
require "json"
puts HTTP::Cookie.new("name", "value").to_json
```
This is the error message:
```
Error in ./bug.cr:4: instantiating 'HTTP::Cookie#to_json()'

puts HTTP::Cookie.new("name", "value").to_json
                                       ^~~~~~~

in /opt/crystal/src/json/to_json.cr:3: instantiating 'String:Class#build()'

    String.build do |str|
           ^~~~~

in /opt/crystal/src/string.cr:220: instantiating 'String::Builder:Class#build(Int32)'

    String::Builder.build(capacity) do |builder|
                    ^~~~~

in /opt/crystal/src/string.cr:220: instantiating 'String::Builder:Class#build(Int32)'

    String::Builder.build(capacity) do |builder|
                    ^~~~~

in /opt/crystal/src/json/to_json.cr:3: instantiating 'String:Class#build()'

    String.build do |str|
           ^~~~~

in /opt/crystal/src/json/to_json.cr:4: wrong number of arguments for 'HTTP::Cookie#to_json' (1 for 0)
Overloads are:
 - HTTP::Cookie#to_json()

      to_json str
      ^~~~~~~
```
I am using Crystal 0.9.1 [b3b1223] (Fri Oct 30 03:48:35 UTC 2015) on Ubuntu 14.04 LTS (3.13.0-68-generic x86_64). I think this is a bug but maybe I'm just stupid ;-)

**Comment by jhass** [comment]
That's because there's no `to_json` method defined for `HTTP::Cookie`. I'm not sure what it would return anyway.

**Comment by Thyra** [comment]
Yes, I saw in the API doc that HTTP::Cookie inherits this method from Object. I expected to get a JSON representation of the cookies' properties (name, value, path etc.). Why does it inherit this method from Object if it doesn't work and isn't supposed to? I thought to_json would work on any object...

**Comment by jhass** [comment]
Well, the primary interface is `to_json(IO)`, `to_json : String` is merely a convenience wrapper around that.

**Comment by Thyra** [comment]
OK, I don't understand what that means. But would it make sense to define a ```to_json``` method for HTTP::Cookie?

**Comment by asterite** [comment]
@Thyra What would `to_json` for a cookie be? But more importantly, why do you need it?

**Comment by Thyra** [comment]
Well, I would expect a JSON representation of all the variables that I see with ```to_header```. For example ```{"name": "session_id", "value": "1234", "path":"/"}```. I don't have a specific scenario in mind, I was just surprised that it didn't work because I saw that the method is inherited from Object, so I thought the standard procedure would be to take all object properties and create a JSON string out of them.

**Comment by asterite** [comment]
As @jhass explained, [Object#to_json](https://github.com/manastech/crystal/blob/master/src/json/to_json.cr#L2-L6) [invokes](https://github.com/manastech/crystal/blob/master/src/json/to_json.cr#L4) `to_json(IO)`, and that method must be implemented for subclasses in order for `to_json` to work.

There's no default `to_json` for all objects. It doesn't work in Ruby either: http://carc.in/#/r/mw9 (well, it works but the output isn't what you'd expect).

**Comment by Thyra** [comment]
Ah, OK, I understand. Thank you for the explanation! So how come the ```to_json``` method is defined in the Object class? If it has to be implemented for each class individually, wouldn't it be better to not have it inherited from the Object class? At least to me an error message like *undefined method* would be much clearer than the ones I listed above; I really thought this was a bug.

**Comment by Thyra** [comment]
Ah, no, I think I got it now: You define the ```to_json(IO)``` method and then you don't have to define the ```to_json()``` method because it automatically uses your ```to_json(IO)```. Aha! That makes sense :-). Thank you both for your time!
