### ISSUE TITLE
Alias inside generic?

### ISSUE THREAD

**Issue by rmosolgo** [manastech/crystal#1920]
Hi, 

I'd like to use a generic's contained type for aliases, like this:

https://github.com/rmosolgo/data-structures-crystal/compare/alias-with-generic-type

But it seems that `T` is not valid for that case: 

```
~/projects/crystal-data $ crystal spec
Error in ./src/data/string_value_trie.cr:4: undefined constant T

    alias Entry = Tuple(String, T)
```

As you can see, that improves the readability of the code & decreases the chance for error.

- Does it make sense that it's not valid there? Maybe I don't understand how it's supposed to work.
- Is it _possible_ for it to work like that? If so, I think it would be an improvement :) 

Thanks again for your help! 

(ps. is there another issue for this? I googled around and didn't come up with one!)

**Comment by jhass** [comment]
I've seen this question before but can't find an existing issue for it either.

One tricky thing is that we would need to track whether an alias references a generic type argument and make it available as either `Foo::Alias` or `Foo(Bar)::Alias` depending on that.

**Comment by rmosolgo** [comment]
Oh yeah I didn't think of the complication when accessing the alias from _outside_ the class definition!

**Comment by asterite** [comment]
Yes, what @jhass says is the main issue with this. Instead of an alias, I'd recommend to use:

```crystal
struct Entry(T)
  getter key, value

  def initialize(@key : String, @value : T)
  end
end
```

That's also more readable when you access it: `.key` and `.value` instead of `[0]` and `[1]`. And creating it is also `Entry.new(key, value)`.

**Comment by rmosolgo** [comment]
Wow, that's perfect for this use case. Like you said, it's even better than a tuple since you access the values by name. 

Here's my application of that pattern: https://github.com/rmosolgo/data-structures-crystal/commit/5a995432fa0bba87ab9a067d2c653b2ece37835d

:heart:  thanks for your help!
