### ISSUE TITLE
Allow `respond_to?` work with Class methods?

### ISSUE THREAD

**Issue by luislavena** [manastech/crystal#1926]
Hello,

Right now is not possible to use `respond_to?` and check for class methods (`self.something`), only for instance ones.

I was if this was intentional (part of the design) and if not, any hint/guidance for implementation.

Thank you.

:heart: :heart: :heart:

**Comment by asterite** [comment]
Hi!

This works:

```crystal
class Foo
  def self.bar
  end
end

puts Foo.responds_to?(:bar) #=> true
puts Foo.responds_to?(:baz) #=> false
```

But maybe I'm not understanding your question.

**Comment by luislavena** [comment]
Hello,

Sorry, I should have provided the proper example. Is not that *does not work* but does not work when has been inherited and is used in an Array.

To simplify:

```crystal
class Foo
  def self.call
  end
end

klass = Foo
list = [Foo]

puts Foo.responds_to?(:call) # => true
puts klass.responds_to?(:call) # => true

list.each do |k|
  puts k.responds_to?(:call) # => true
end
```

With inheritance:

```crystal
class Foo
  def self.call
  end
end

class Bar < Foo
end

klass = Foo
list = [Foo, Bar]

puts Foo.responds_to?(:call)   # => true
puts Bar.responds_to?(:call)   # => true
puts klass.responds_to?(:call) # => true

list.each do |k|
  puts k.responds_to?(:call) # => false (both cases)
end
```

I know that the conditions are pretty weird, took me quite some time to figure out what was going on :stuck_out_tongue:

**Comment by asterite** [comment]
@luislavena Good find, incorrect behaviour is the worst bug :-)

**Comment by luislavena** [comment]
@asterite thank you! :heart: :heart: :heart:
