### ISSUE TITLE
Int32 as Parameter (ARGV)

### ISSUE THREAD

**Issue by davidak** [manastech/crystal#1953]
ARGV[0] is a `String`, how can i use the String "1" as an `Int32`?

i tried: `ARGV[0] as Int32`

Error: can't cast String to Int32

**Comment by MakeNowJust** [comment]
You can convert from string to integer value by `String#to_i`.

```crystal
ARGV[0].to_i
```

Documents:

- [String#to_i](http://crystal-lang.org/api/String.html#to_i%28base%3D%3Cspanclass%3D%22n%22%3E10%3C%2Fspan%3E%2Cwhitespace%3D%3Cspanclass%3D%22n%22%3Etrue%3C%2Fspan%3E%2Cunderscore%3D%3Cspanclass%3D%22n%22%3Efalse%3C%2Fspan%3E%2Cprefix%3D%3Cspanclass%3D%22n%22%3Efalse%3C%2Fspan%3E%2Cstrict%3D%3Cspanclass%3D%22n%22%3Etrue%3C%2Fspan%3E%29-instance-method).
- [`as` operator](http://crystal-lang.org/docs/syntax_and_semantics/as.html)

**Comment by davidak** [comment]
@MakeNowJust thanks!
