### ISSUE TITLE
Convert from Object to JSON::Type for dynamic nodes in json

### ISSUE THREAD

**Issue by qio-io** [manastech/crystal#1965]
With the code below:

```crystal
require "json"

module Test
  # TODO Put your code here
  class Test
    # JSON mapping
    JSON.mapping({
      name: {type: String, nilable: false},
      any: {type: JSON::Any, nilable: true}
    })
  end

  class SubTest
    # JSON mapping
    JSON.mapping({
      test: {type: String, nilable: false},
      test2: {type: String, nilable: false}
    })
  end

end

test = Test::Test.from_json(%(
  {
    "name": "test",
    "any": [
      {"hello": "new"}
    ]
  }
  ))

if test.any
  new_array = Array(Test::SubTest).new
  new_array << Test::SubTest.from_json(%(
      {"test": "1", "test2": "2"}
    )
    )

  test.any = new_array

end

puts test.to_json

```

How can i use the mapping macros for creating a new node with different object "schema"?.
This is the error i received when trying to cast/convert the object to JSON::Type.

```llvm

Error in ./src/test.cr:40: no overload matches 'Test::Test#any=' with types Array(Test::SubTest)
Overloads are:
 - Test::Test#any=(_any : JSON::Any | ::Nil)

  test.any = new_array
       ^~~

```

**Comment by asterite** [comment]
You can do this:

```crystal
new_array = Array(JSON::Type).new
new_array << JSON.parse(%({"test": "1", "test2": "2"})).raw
test.any = JSON::Any.new(new_array)
```

The thing is that `test.any` is of type `JSON::Any`, which is just a struct wrapping a `JSON::Type`, which is just a few types: `Nil | Bool | Int64 | Float64 | String | Array(Type) | Hash(String, Type)`. `Test::SubTest` is not part of that union.

Depending on what you want to do in your code maybe this can be modelled in a different way.

**Comment by qio-io** [comment]
Thanks @asterite:

The code above was a simple extraction from a bigger project. 
I couldn't find JSON.parse reading the source code and docs. 
Thanks for your help, the module in the project is working now.

**Comment by asterite** [comment]
@qio-io Great! :-) For cases where the JSON schema is kind of dynamic I would suggest just using `JSON.parse`, JSON mapping is pretty limited for that.

**Comment by qio-io** [comment]
@asterite is there any way to create a special hash operator for creating, reading dynamic nodes?:

Example:

```crystal
test = JSON::Type
test["field-a", "subfieldb", "subfieldc",  0, "subfield10"] = 10
var = test["field-a", "subfieldb", "subfieldc",  0, "subfield10"]
```

In nim there's an spacial operator {}= and {} for this case, based on dictionaries i believe.

**Comment by asterite** [comment]
We could actually define `[](first, *others)` and `[]=(first, *others, value)` for `JSON::Any`. In Ruby 2.3 they added `Array#dig` and `Hash#dig`, but I think in our case it's not very useful because of static type checking.

**Comment by qio-io** [comment]
I'll love to see this kind of operator, but i believe i don't have yet, the kind of knowledge for creating a PR. 
Anyway, i'm amazed by the language and i hope later, i could be more active developing new libraries for the community.
