### ISSUE TITLE
Catch CTRL+C interrupt?

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#1968]
Is there a way to intercept the CTRL+C interrupt and run clean shutdown logic?

**Comment by kirbyfan64** [comment]
```crystal
LibC.signal Signal::INT.value, ->(s : Int32) {
  puts "CTRL-C handler here!"
  exit
}

0.to 100000 { puts 123 }
```

In most cases, though, you should override [`finalize`](http://crystal-lang.org/docs/syntax_and_semantics/finalize.html) in the classes that need cleanup.

**Comment by will** [comment]
There is a bit nicer support without having to go to LibC manually

``` crystal
Signal::INT.trap do
  puts "CTRL-C handler here!"
  exit
end

1000000.times do
  print '.'
  sleep 0.01
end
```

**Comment by stugol** [comment]
@kirbyfan64: ```finalize``` is broken. See https://play.crystal-lang.org/#/r/oyd

**Comment by stugol** [comment]
@will Thank you.

**Comment by kirbyfan64** [comment]
I think that's a bug...

**Comment by stugol** [comment]
Unless it's only supposed to work if and when the GC does a cleanup, like in .NET. In other words, "sometime maybe never", which makes an utter mockery of the very idea of a finaliser.

.NET could have been so much better.

**Comment by stugol** [comment]
Rust got object lifetimes right. Shame it doesn't support function overloading. Also shame it replaced perfectly good symbolic notation with stupid words.

**Comment by asterite** [comment]
finalize runs when the GC collects an object. You should only use it to free resources, and never allocate memory there (so raising an exception is not good)

**Comment by stugol** [comment]
There are times when ```finalize``` is never called, though - e.g. on program exit. So why even bother having a finaliser? It's dumb to have a mechanism that only works "some of the time". Know how often I write a finaliser in .NET? _Never!_ Because they're pointless.

Can you give me one case when an unreliable finaliser is actually useful?

**Comment by will** [comment]
Calling a required memory-freeing function in a linked c library.

**Comment by stugol** [comment]
You can't rely on it actually being called though. So what's the point?

**Comment by stugol** [comment]
Granted, if you're only freeing memory, I guess it makes sense. If the GC doesn't run, presumably you have plenty of memory left. But there are loads of things _other than_ memory that might need releasing, and a sometime-maybe-never finaliser is utterly useless for all of them.

**Comment by kirbyfan64** [comment]
On most modern systems, all memory is automatically freed when the program terminates.

**Comment by ysbaddaden** [comment]
Lets keep calm. We almost never need to use the finalize method in regular code. It's only usage is to reclaim memory the GC can't know about, which usually means when creating a binding to an external C library.

For instance in the postgresql driver, the Result class keeps a reference to the libpq result, which is freed with `PQclear(result)` in the finalize method.

You can't expect finalize to be reliably called for anything that doesn't free memory, since this is only called by the GC, and the GC doesn't run at exit, since the OS will free the memory by itself.

You need something else, like `at_exit {}` and/or a coroutine that will regularly clear what you need to.

**Comment by stugol** [comment]
@kirbyfan64 I know. That's why nondeterminate finalisers are so pointless.

**Comment by asterite** [comment]
Closing this because the answer is answered (please use our Google Groups if you want to discuss these things, but finalizers work like that in Java, C#, D and many other languages and people do some really good programs in them, I don't think finalizers are broken).

**Comment by will** [comment]
I just went looking for how to do this because I forgot, and this Issue came up. It was surprising to see my own answer five and half years later 😂
