### ISSUE TITLE
Question: what was the reasoning to make def arguments always have a parenthesis on 0.10?

### ISSUE THREAD

**Issue by sardaukar** [manastech/crystal#1970]
I never use them, and it seems like a weird breaking change... :/

**Comment by kirbyfan64** [comment]
https://github.com/manastech/crystal/pull/1741

**Comment by robacarp** [comment]
Yeah, I was similarly surprised to see this change in this release.

If anything I expected to see ```::``` for method return types to resolve the ambiguity, but I'm still coming up to speed on the history and dogma of the project.

**Comment by PragTob** [comment]
It was also a lot about the style, so that this style was now removed. Crystal is a bit more... opinionated/restrictive whatever you want to call it for some things - meaning discouraging aliases for methods and things like this (more uniform code appearance). 

I think this should be closed :)
