### ISSUE TITLE
Hash#[] raising on missing keys?

### ISSUE THREAD

**Issue by robacarp** [manastech/crystal#1971]
Under the previous crystal release (installed by homebrew about 10 days ago), it was easy to do some conditional method calls based off of hash contents:

```crystal
h = {} of Symbol => Symbol

h[:a] = :b
h[:c] = :d
h[:h] = :i

puts "found :a #{h[:a]}" if h[:a]
puts "found :c #{h[:c]}" if h[:c]
puts "found :e #{h[:e]}" if h[:e]
puts "found :h #{h[:h]}" if h[:h]
```

Under 0.10, this throws an exception: Missing hash key: :e (KeyError)

The only reference I could find to this in current issues is [a comment on 1034](https://github.com/manastech/crystal/issues/1034#issuecomment-125019719) that makes it seem like this is the current behavior as of as far back as July.  I [had some code](https://github.com/robacarp/crystalized_migrations/blob/be55aeaa2458b4a68dbd19d2ab26a5225225b712/src/migrations/yaml_runner.cr#L23-L24) that was definitely running under the previous homebrew installed version.

I'll admit I'm new around here and to Crystal in general, but I'm betting this wasn't an on purpose change? Or it should be added to the changelog under breaking.

**Comment by kirbyfan64** [comment]
I think it was intentional, but I don't remember where the discussion was.

**Comment by robacarp** [comment]
I'm sure surprised to hear that. Given that exceptions are so comparatively slow, I'd like to read through the discussion to see why that choice was made.

**Comment by asterite** [comment]
That method worked like that since the beginning.

**Comment by robacarp** [comment]
hah. okay. well then I'll call my code some sort of heisenbug because I swear it worked yesterday...

**Comment by PragTob** [comment]
@robacarp imo `[]?` does what you want it to do (and will make the result a union type with Nil) - and I think this can be closed :)

**Comment by ysbaddaden** [comment]
`[]` always raises when the value can't be found, whereas `[]?` returns a nilable.

The reason methods like `[]` or `first` or `last` raise is to avoid having to deal with nilables all the time, and to have to specify when we want to ask whether a value is available or not, hence the added `?` in method names. For example:

```crystal
if value = hash[key]?
  # value existed and is defined (not nil)
end
```

This is a little different from Ruby, where a question mark means the method returns a boolean. In Crystal it's usually about returning a nilable.

**Comment by kostya** [comment]
what about, `[]?` rename to `[]` because used more often? and `[]` to `[]!`

**Comment by ysbaddaden** [comment]
Then `value = hash[key]` will always be a nilable. Won't it be a nightmare to deal with these nils, all the time, for any kind of collection?

**Comment by omninonsense** [comment]
I vote to keep `[]` and `[]?` *because* it is more used, and because of what @ysbaddaden pointed out.

**Comment by kostya** [comment]
yes, forget my question

**Comment by robacarp** [comment]
Yeah, it's worth mentioning that the discussion on []! Has already had some steam elsewhere in the issues. I'm not sure I really understand the trade off going on... Explicitly catching the nil vs explicitly catching an exception. 

I think it comes down to what the language wants to endorse as part of the style more than anything. Returning nils may very well have significant performance overhead in crystal -- I'll yield the decision to people with more experience in the language. 

My original comment was more about documentation, weather in the changelog or in the core docs for hash. Crystal advertises being ruby inspired. Since ruby has chosen to standardize on nils everywhere, this is a significant deviation from ruby. It should be highlighted and well documented to minimize confusion and transition friction. 

:Apple:

**Comment by gerrywastaken** [comment]
Here's how it's handled in Go

```go
statePopulations := map[string]int{
	"seattle": 744955,
	"boston":  694583,
}

fmt.Printf("Seattle population = %v\n", statePopulations["seatle"])
```

Output:
`Seattle population = 0`

If I want to catch mistakes I can just wrap everything:
```go
key = "seatle"
pop, ok := statePopulations[key]
if ok {
	fmt.Printf("seattle population = %v\n", pop)
} else {
	fmt.Printf("The key [%v] doesn't exist", key)
}
```

Maybe I want the default value to not be zero but 100000:
```go
pop, ok := statePopulations["Bisbee"]
if !ok {
  pop = 100000
}
fmt.Printf("Bisbee population = %v\n", pop)
```

In Crystal:
```cr
puts "Seattle population = #{state_populations[:seatle]}"
```

Output: `Unhandled exception: Missing hash key: :seatle (KeyError)`

For Bisbee default:
```cr
puts "Bisbee population = #{state_populations[:bisbee]? || 100000}"
```

Ruby has similar issues to Go where nobody uses fetch() when they definitely didn't want things to default to `nil` because they made a typo or a key was missing.

Thank you for choosing the sane option in Crystal.

**Comment by j8r** [comment]
@gerrywastaken Use this (idiomatic) syntax, which is similar to Go:
```cr
h = {"k" => "v"}
if value = h["key"]?
  puts value
else
  puts "Error"
end
```

**Comment by gerrywastaken** [comment]
@j8r I was actually suggesting it was a limitation in Go, that you have to write a special check around every access of an index just to make sure you haven't made a typo, like "seatle" instead of "seattle" in the above code. I guess my jesting wasn't very clear. :grin:

**Comment by asterite** [comment]
I understood it :-)

**Comment by j8r** [comment]
I meant, the thing is not really that Crystal chose the best option, but offers different ways which fits more for certain cases. Here, `#[]`, `#[]?` and `#fetch`.

We can say Crystal chose the option which was having several ones 😄
