### ISSUE TITLE
undefiled reference to GC_*_push_other_roots and GC_push_all_eager

### ISSUE THREAD

**Issue by MadBomber** [manastech/crystal#1976]
```bash
$ cat hello_world.cr
puts "Hello World"

$ crystal hello_world.cr
./.crystal/media/James/sandbox/git_repos/madbomber/crystal/samples/hello_world.cr/_main.o: In function `__crystal_main':
main_module:(.text+0x5a3): undefined reference to `GC_get_push_other_roots'
main_module:(.text+0x609): undefined reference to `GC_set_push_other_roots'
./.crystal/media/James/sandbox/git_repos/madbomber/crystal/samples/hello_world.cr/Fiber.o: In function `*Fiber#push_gc_roots<Fiber>:Void':
Fiber:(.text+0x17): undefined reference to `GC_push_all_eager'
Fiber:(.text+0x4c): undefined reference to `GC_push_all_eager'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o "/media/James/sandbox/git_repos/madbomber/crystal/samples/.crystal/crystal-run-hello_world.tmp" "${@}"  -rdynamic  -levent -lrt -lpcl -lpcre -lgc -lpthread -ldl`

$ crystal --version
Crystal 0.10.0 [9d59a34] (Wed Dec 23 17:24:02 UTC 2015)
```

OS: redhat FC20 (yea I'm a little out of date)
sudo yum repository-packages Crystal install

**Comment by kirbyfan64** [comment]
...I think this really needs an FAW entry or something...

You need to install newer version of the Boehm GC.

**Comment by ysbaddaden** [comment]
@MadBomber see #1964 (this is for Debian, but the problem is identical)

@kirbyfan64 maybe we should just provide updated deb/rpm packages :D

**Comment by MadBomber** [comment]
+1 of updated rpm :)

**Comment by rkeene** [comment]
I also had this problem with the pre-compiled distribution of Crystal, since it was using the LIBRARY_PATH environment variable to instruct the compiler on how to find libraries that it could not find in the system paths to search the "embedded/lib" directory.  However, I have several libraries in the system path that provided older versions of these libraries and were incompatible.

The solution I employed was to get rid of LIBRARY_PATH and replace it with an updated call to "CC", as follows

    #!/usr/bin/env bash
    INSTALL_DIR="$(readlink -f "$(dirname $(readlink -f "$0" || echo $0))/..")"
    export CRYSTAL_PATH=${CRYSTAL_PATH:-"libs:$INSTALL_DIR/src"}
    export PATH="$INSTALL_DIR/embedded/bin:$PATH"

    embeded_library_path="$INSTALL_DIR/embedded/lib"
    export CC="${CC:-cc} -L$(set | grep '^embeded_library_path=' | cut -f 2- -d '=')"
    
    "$INSTALL_DIR/embedded/bin/crystal" "$@"
