### ISSUE TITLE
Logger/Spec unexpectedly crashing

### ISSUE THREAD

**Issue by jessedoyle** [manastech/crystal#1982]
After upgrading to Crystal `v0.10.0`, my spec suite has been crashing without giving any usable error message.

You can see an example of the crash on the TravisCI build ([link](https://travis-ci.org/jessedoyle/duktape.cr)).

Alternatively, the issue should be able to be reproduced locally by cloning my project's repo ([link](https://github.com/jessedoyle/duktape.cr)), then running the following commands from the project directory: 
```bash
make libduktape && make spec
```

I believe the issue is related to the interaction between the `Logger` class and the spec framework - I can make the tests run successfully if I stub out the entire `Logger` class.

I have tried running the specs using the fixes from #1972, but the crashing still seems to occur.

Does anyone have any idea how I should go about debugging this issue, or is it likely a bug somewhere in the compiler?

**Comment by asterite** [comment]
@jessedoyle Could you try it with this change? The problem was that the logger's IO was being closed at exit, and in your case it was STDOUT, and that's wrong.

**Comment by jessedoyle** [comment]
@asterite - I just tried it and it looks like you squashed the bug! Thanks a lot!
