### ISSUE TITLE
LibC pipe with raw threads?

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#1991]
I know I can't call any IO functions (or sleep) from a raw operating system thread.

But could I create a "raw" pipe (that is, using the LibC API rather than Crystal's libraries) and use that to communicate with a raw thread? I see no reason why not.

**Comment by ysbaddaden** [comment]
You may try, but this is unsupported and you'll have to rely libc calls only.

**Comment by stugol** [comment]
I realise this. I didn't say it would be easy, I was asking if it would *work*.

**Comment by stugol** [comment]
I've had plenty of experience using API calls from another language (for example, WinAPI functions from VB.NET). My question is: is there any reason why using a raw pipe in Crystal to communicate with a raw thread would be problematic?
```
spawn_raw_thread {
   [...libc calls only...]
   [...libc raw pipe calls...]
}
[...Crystal calls...]
[...libc raw pipe calls...]
```

**Comment by ysbaddaden** [comment]
Well, it may work. But you must be sure to never call anything that triggers the event loop in the thread (not just IO). There is also no guaranty this will continue working weeks or months from now.

Ie. that should work, but you've been warned ;)

**Comment by stugol** [comment]
Is there some way I can check what calls use the event loop, so I know what to avoid?

Alternatively, I guess I could just trap the event loop exception, and if it happens I'll know what caused it. Presumably I can pretty much always replace a Crystal call with one or more LibC calls. I mean, that's what they're built on, after all.

Is there maybe any way to "give" a raw thread a Crystal event loop? That would solve everything, surely?

**Comment by ysbaddaden** [comment]
Crystal core and stdlib are written in Crystal, going bare metal is possible and you may even use `--prelude=empty` to skip the whole core lib (including the GC), so you're mostly on your own with LibC calls.

You may search the core/std lib for `event`, if anything creates an event on the Scheduler or EventBase then you can't use it, nor anything that depend on these functions (any IO, sleep, the Crystal PG driver, etc).

But again: this isn't supported and isn't the direction the language creators want for Crystal. I'm closing this discussion here. Use the Google group, for example, for further discussion.
