### ISSUE TITLE
&: syntax?

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#1993]
I'm sure this question has been answered before, but I can't for the life of me find it.

Does the &: or &. syntax support the passing of arguments? And if so, how?

**Comment by bcardiff** [comment]
https://play.crystal-lang.org/#/r/pcq

```crystal
puts [1,2,4].map &.+(10) # => [11, 12, 14]
```

**Comment by stugol** [comment]
Awesome, thanks.

Someone really should put that in the documentation. I could volunteer to help out with it if the guys in charge would like?

**Comment by bcardiff** [comment]
There is a [post](http://crystal-lang.org/2013/09/15/to-proc.html) about that, but there should be something inside http://crystal-lang.org/docs/syntax_and_semantics/blocks_and_procs.html IMO.

**Comment by vjdhama** [comment]
@bcardiff I agree. Since it differs a bit from ruby syntax, it would be good if it's documented.
