### ISSUE TITLE
0.10.1 Enforcement of abstract method does not allow super class parameter

### ISSUE THREAD

**Issue by Perelandric** [manastech/crystal#1998]
With the enforcement of abstract methods added in 0.10.1, a method that implements an abstract method but takes  a parameter that is the super class of the parameter defined by the `abstract` definition no longer compiles.

Not sure if this is intended or not.

```crystal
class Parent
end
class Child < Parent
end


abstract class ParentTest
  abstract def test(p : Child)     # Defined with `Child`
end

class ChildTest < ParentTest
  def test(p : Parent)             # Implemented with `Parent`
  end
end
``` 

>Error in ./tester.cr:8: abstract `def ParentTest#test(p : Child)` must be implemented by ChildTest

>$ crystal --version
>Crystal 0.10.1 [f364e3e] (Fri Jan  8 01:31:26 UTC 2016)

**Comment by asterite** [comment]
For now this is intended. The restrictions must match or not be present. We will improve this in the future, but it gets pretty tricky with union types, so it's better if we keep this simple.

**Comment by Perelandric** [comment]
Thanks @asterite. No problem at all.
