### ISSUE TITLE
Allow comment and escape for ecr tags

### ISSUE THREAD

**Issue by teodor-pripoae** [manastech/crystal#1999]
Hi,

Currently there is no option to escape a tag or to comment a tag.

In erb I can do the following:

```erb
<% a = b %>    # code, supported
<%= a %>       # embed value, supported
<%# comment %> # commented code, not supported
<%% a = b %>   # escaped code, not supported
```

If I want to generate a crystal template using ecr, it is not possible.

**Comment by ysbaddaden** [comment]
I'm working on that.

**Comment by asterite** [comment]
@ysbaddaden Excellent! :+1:

**Comment by arktisklada** [comment]
@ysbaddaden I was offline and started poking around at this.  Here's a wip towards what I was thinking.  let me know your thoughts https://github.com/manastech/crystal/pull/2002

**Comment by ysbaddaden** [comment]
Sweet!

I took another approach by having a local is_comment, then I eventually removed the locals is_local and is_output (and is_escape) to immediately define the type instead.

**Comment by arktisklada** [comment]
I see what you did with the types there.  Nice idea!  Anything I can do to support?
