### ISSUE TITLE
'^' does not match to a character after '\n'

### ISSUE THREAD

**Issue by rhysd** [manastech/crystal#2005]
```crystal
puts "   a\n   b\n   c".gsub(/^\s+/, "")
```

This code outputs below.

```
a
   b
   c
```

But `^` should match to all characters after `\n`.  So I expected below output.

```
a
b
c
```

I checked Ruby behavior and its output was expected one.

I know that Ruby uses [Onigmo](https://github.com/k-takata/Onigmo) and Crystal doesn't.  So this behavior difference may not be a bug.

- Environment
  - OS X 10.11.1
  - Crystal 0.10.1

**Comment by kumpelblase2** [comment]
https://carc.in/#/r/pin

You have to set the multiline mode (m)

**Comment by rhysd** [comment]
Hmm...  I didn't know Crystal's regex is not multiline mode by default.  Thanks.
