### ISSUE TITLE
Creating C binding for headers in same folder

### ISSUE THREAD

**Issue by sdogruyol** [manastech/crystal#2024]
Noob at C here. So pardon me if it's not a good question.

I'm trying to use https://github.com/manastech/crystal_lib for automatic C binding generation. But had no success.

This is how my folder looks like (apart from crystal_lib directories)

├── main.cr
├── multipart_parser.c
├── multipart_parser.cr
├── multipart_parser.h
└── multipart_parser.o

I'm trying to run the generator like 

`crystal main.cr -- multipart_parser.cr`

Here's multipart_parser.cr

```crystal
@[Link(ldflags: "-L#{__DIR__}/multipart_parser")]
@[Include("multipart_parser.h")]
lib LibMultipartParser
end
```

But seems like the `Link` command is not happy with the path

`input.c:1:10: error: 'multipart_parser.h' file not found with <angled> include; use "quotes" instead
@[Link(ldflags: "-L./multipart_parser")]
lib LibMultipartParser
end`

**Comment by ysbaddaden** [comment]
You must specify an include directory, otherwise clang won't find the header:

```crystal
@[Include("multipart_parser.h", flags: "-I.")]
@[Link(ldflags: "-L.")]
lib LibMultipartParser
end
```

**Comment by sdogruyol** [comment]
@ysbaddaden Thanks a lot :+1:

**Comment by sdogruyol** [comment]
@ysbaddaden why do i get this error?

My lib declaration

```crystal
@[Include("multipart_parser.h", prefix: %w(multipart_parser_ ), flags: "-I.")]
@[Link(ldflags: "-L.")]
lib LibMultipartParser
...
end
```

When trying to run

```
Error in ./src/multipart/lib_multipart_parser.cr:1: illegal attribute for lib, valid attributes are: Link
@[Include("multipart_parser.h", prefix: %w(multipart_parser_ ), flags: "-I.")]
```

**Comment by asterite** [comment]
@sdogruyol Check the [usage](https://github.com/manastech/crystal_lib#usage), that attribute is handled by the `crystal_lib` program, not by the compiler.

**Comment by sdogruyol** [comment]
Thanks @asterite
