### ISSUE TITLE
How to with-self-yield in initialize?

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#2026]
I don't seem to be able to ```with self yield``` in an ```initialize``` or ```new``` function...?

See https://play.crystal-lang.org/#/r/q4p and https://play.crystal-lang.org/#/r/q4q

**Comment by Exilor** [comment]
I don't know about the first one.
The second, though: https://play.crystal-lang.org/#/r/q50

**Comment by bcardiff** [comment]
It could be added, but it will force the type inference to quit some calculations because it will be exposing an object not "completely initialized"

https://play.crystal-lang.org/#/r/q4y

@Exilor workaround is better than the one I was going to post :+1:

**Comment by stugol** [comment]
@Exilor: Awesome, thank you! Although I'm not sure I understand how it works. Why doesn't the call to ```new``` cause an infinite recursion?

**Comment by Exilor** [comment]
Because all objects have a default ```new``` that doesn't yield, and the one I added does. Methods that yield are different from methods that have the same name, the same arguments but don't yield.

**Comment by stugol** [comment]
@Exilor: Oh, of course!

**Comment by vladfaust** [comment]
Bumping up. Is that somehow achievable?

```crystal
class Router
  def initialize(&block)
    with self yield
  end

  def get(path)
  end
end

Router.new do
  get "/"
end

# undefined method 'get'
```

I currently have to write

```crystal
Router.new do |r|
  r.get "/"
end
```

which is kinda overhead.

**Comment by asterite** [comment]
```crystal
class Router
  def self.new
    with Router.new yield
  end

  def initialize
  end

  def get(path)
  end
end

Router.new do
  get "/"
end
```
