### ISSUE TITLE
TCPServer.accept only accepting one connection at a time

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#2027]
```server.accept``` only accepts one incoming connection at a time. The second invocation of ```accept``` blocks until the first connection closes. Why is this?

```
server = TCPServer.new bind_address, port
loop {
	conn = server.accept
	spawn do				# connection fiber
		...receive loop...
	end
}
```

**Comment by asterite** [comment]
That doesn't seem to be true. Try this:

```crystal
require "socket"

server = TCPServer.new "0.0.0.0", 8080
i = 0
loop {
  conn = server.accept
  i += 1
  spawn do
    p "Got #{conn.gets} from #{i}"
  end
}
```

then `telnet localhost 8080` from two consoles, send data and it'll work.

**Comment by stugol** [comment]
Hmm. The problem seems to be with the ```IO.select``` call:
```
	server = TCPServer.new "0.0.0.0", 9000
	i = 0
	loop {
	  conn = server.accept
	  i += 1
	  spawn do
	    IO.select([conn], [] of Socket, [conn])
	    p "Got #{conn.gets} from #{i}"
	  end
	}
```

**Comment by stugol** [comment]
I need to call ```select```, because I'm using ```read```. ```gets``` won't do for receiving binary data.

**Comment by stugol** [comment]
The same problem occurs if, instead of calling ```IO.select```, I set ```socket.blocking = true```!

Surely this is wrong?

**Comment by waj** [comment]
Yup, don't use `IO.select` and don't set `socket.blocking = true`. Just use `conn.read(...)`.

`IO.select` might be improved in the near future so it doesn't block the entire thread, but right now it just makes a `select` syscall that blocks the process.

**Comment by stugol** [comment]
So I'm essentially supposed to spinwait on read? But that's dumb! And inefficient! This needs to be fixed, right away.

**Comment by waj** [comment]
No you don't... `read` will block until data is received. The underlying socket works in non-blocking mode but the Crystal API is blocking (it just blocks the fiber, not the entire process).

BTW... please watch your tone.

**Comment by stugol** [comment]
Alright, so ```read``` blocks in Crystal. Fair enough, I'll use that. Thanks.

Although ```select``` really needs to be fixed anyhow.

BTW... nothing wrong with my tone.

**Comment by rdp** [comment]
I believe select was removed now FWIW.
