### ISSUE TITLE
Compile time error on Tempfile rewind

### ISSUE THREAD

**Issue by willcosgrove** [manastech/crystal#2028]
I'm trying to rewind a tempfile, but at compile I'm getting this error:

```
in ./src/pdownload/download_thread.cr:18: instantiating 'Tempfile#rewind()'

      @tempfile.rewind
                ^~~~~~

in /usr/local/Cellar/crystal-lang/0.10.0/src/io/buffered.cr:267: instantiating 'unbuffered_rewind()'

    unbuffered_rewind
    ^~~~~~~~~~~~~~~~~

in /usr/local/Cellar/crystal-lang/0.10.0/src/io/file_descriptor.cr:246: undefined method 'seek'

    seek(0, IO::Seek::Set)
```

I'm not sure if it's my mistake, or a bug with the Tempfile implementation.  I can post the rest of my code if that would help.

**Comment by asterite** [comment]
It's a bug. I think `Tempfile` should inherit `File`, not `IO::FileDescriptor`.

**Comment by asterite** [comment]
I'm actually thinking `IO::FileDescriptor` should provide `seek`, even though it might fail for socket and other `IO`s. Since you can create an `IO::FileDescriptor` from a file descriptor, it makes sense that it could be seekable.
