### ISSUE TITLE
format macros

### ISSUE THREAD

**Issue by will** [manastech/crystal#2030]
Maybe it's intentional, but it looks like the formatter doesn't indent the code in macros.

``` crystal
class A
class B
macro mac(arg)
return arg
end
end
end
```

turns into 

``` crystal
class A
  class B
    macro mac(arg)
return arg
end
  end
end
```

**Comment by asterite** [comment]
Yes, there's no way to indent macros as their content is free text that's parsed after expanding it.

**Comment by will** [comment]
Makes sense, thanks

**Comment by luislavena** [comment]
@asterite so it ignores the macro...end part, correct? so we need to remember to indent that properly before?

**Comment by asterite** [comment]
Unfortunately, yes. I'd like to find a way to auto-indent macros, but it's hard. It's the price we have to pay to have free-text macros. For example you can do this:

```crystal
macro define(part, other)
  {{part.id}}
    def foo
      1
    end
  {{other.id}}
end

define("class Foo", "end")

puts Foo.new.foo
```

and the formatter has no clue that `def foo` should be indented. But other things should be easier to indent:

```crystal
macro record(name, *properties)
  struct {{name.id}}
    getter {{*properties}}

    def initialize({{ *properties.map { |field| "@#{field.id}".id } }})
    end

    {{yield}}

    def clone
      {{name.id}}.new({{ *properties.map { |field| "@#{field.id}.clone".id } }})
    end
  end
end
```

it's just that `struct {{name.id}}` isn't valid Crystal code so the current parser will choke on this. We would have to change the parser to understand this, somehow, in the context of macros. We could do this in the future, but right now it's low priority.

**Comment by luislavena** [comment]
@asterite got it, thank you for taking the time to provide an explanation. Indeed is not top priority but was more a curiosity question :smile:
