### ISSUE TITLE
Cast to Enumerable(T), or check if something is an Enumerable(T)

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#2036]
I am unable to cast to a module type, or test if an object is of that type:
```crystal
def fn2(data : Enumerable(Int32))
end
value :: Array(Int32) | String
fn2(value)

# Couldn't find overloads for these types:
# - fn2(data : String)
```
```crystal
def fn2(data : Enumerable(Int32))
end
value :: Array(Int32) | String
fn2(value as Enumerable(Int32))    # attempt a cast

# Enumerable(T) is not a generic class, it's a generic module
```
```crystal
def fn2(data : Enumerable(Int32))
end
value :: Array(Int32) | String
if value.is_a?(Enumerable(Int32))   # attempt a query
	fn2(value)
end

# Enumerable(T) is not a generic class, it's a generic module
```
The same problem occurs when using a ```case``` statement to check for ```Enumerable```.

Assuming a value may be of multiple types (i.e. it is of a unioned type), how can I constrain it to an ```Enumerable```, or test if it is an ```Enumerable```?

**Comment by asterite** [comment]
In the first case, you are missing an overload for String (as the error message tells you). If you add an overload [it works](https://play.crystal-lang.org/#/r/q6v).

In the second and third examples you are right, it's not currently possible to either use a generic module in a `is_a?` or `as` expression, but it will be possible in the future.

**Comment by stugol** [comment]
I know it's missing an overload for ```String```. That's the whole _point_. It was to demonstrate the need for type restriction by module.

**Comment by kumpelblase2** [comment]
But string doesn't implement any kind of `Enumerable`, so I don't see how this should ever work that way then. Right now, for me the type restriction is doing the right job as string is not an instance of `Enumerable(T)` for any type T and thus the compiler fails. This seems like the proper behavior to me

**Comment by stugol** [comment]
@kumpelblase2: You are confused.

**Comment by asterite** [comment]
No, he's right. String is not an Enumerable. That's why I said the compiler was doing the right thing in the first snippet.

**Comment by stugol** [comment]
Sigh. I _know_ it was! The first snippet was simply there to demonstrate that the other snippets were necessary.

**Comment by kumpelblase2** [comment]
Ah I get it now, so it's pretty much the same as #1900 , right?

**Comment by stugol** [comment]
Looks that way.

**Comment by asterite** [comment]
Closing as a duplicate then. Thank you!
