### ISSUE TITLE
Runtime error in HTTP library

### ISSUE THREAD

**Issue by willcosgrove** [manastech/crystal#2039]
When I use the HTTP library to get a response that has a very large Content-Length header, I'm getting a runtime error from `String#to_i`

I think it's stemming from here: https://github.com/manastech/crystal/blob/f364e3ec252a7384e401b1d3b4b04e21d469a91f/src/http/common.cr#L19

Here's my full runtime error:

```
invalid Int32: 2907279360 (ArgumentError)
[4415895506] *CallStack::unwind:Array(Pointer(Void)) +82
[4415895409] *CallStack#initialize<CallStack>:Array(Pointer(Void)) +17
[4415895368] *CallStack::new:CallStack +40
[4415895265] *Exception@Exception#initialize<ArgumentError, String>:CallStack +33
[4415895197] *ArgumentError#initialize<ArgumentError, String>:CallStack +29
[4415895132] *ArgumentError::new<String>:ArgumentError +92
[4415885747] *String#to_i32<String, Int32, Bool, Bool, Bool, Bool>:Int32 +435
[4415885301] *String#to_i<String, Int32, Bool, Bool, Bool, Bool>:Int32 +37
[4415885252] *String#to_i<String>:Int32 +84
[4415856844] ~fun_literal_48 +2508
[4415956084] *Fiber#run<Fiber>:Nil +212
[4415842137] ~fun_literal_4 +9
[4416792878] co_runner +43
```

Let me know what I can do to help fix/debug the issue

**Comment by waj** [comment]
Definitely the content length should be parsed as a 64 bit integer. I cannot test it right now, but you could try replacing the call in that line with `to_i64`.

**Comment by asterite** [comment]
Maybe `UInt64`, since it can't be negative and it will allow larger values.

If you do `HTTP::Client.get(...)` and don't pass a block, the whole response's body is read in a string. I guess loading 2.7GB of data to memory won't be good, I wonder how we should deal with this...

**Comment by willcosgrove** [comment]
I'm using the block method to deal with it as an IO and throwing it in a Tempfile, thus my Tempfile issue from yesterday :grin: 

I would definitely think you would want `UInt64` for the `content_length`.  But for the non-block method I don't think it's unreasonable for it to go into memory.  Alternatively, it could do what I'm currently doing, and drop it in a tempfile, and use that to store the response body.

**Comment by asterite** [comment]
I changed it to use `UInt64`. If you can check your program with master and let us know it worked, it would be nice. Thank you! :-)

**Comment by willcosgrove** [comment]
I'm sure this is an unrelated problem with my own environment, but using the `bin/crystal` from master to compile my code, I'm getting this error:

```
Error in /Users/will/Code/crystal-lang/src/fiber/fiber.cr:114: illegal attribute for def, valid attributes are: AlwaysInline, NoInline, Raises, ReturnsTwice

  @[Naked]
  ^
```

**Comment by asterite** [comment]
What's your crystal version? It should be `0.10.1 ` or `0.10.2`.

**Comment by willcosgrove** [comment]
Ah, sorry, I was on `0.10.0`.  Upgraded to `0.10.2` and built my program from master and everything seems to be working as expected!  Thanks!

I'm loving Crystal, looking forward to using it for a long time to come!

**Comment by asterite** [comment]
I guess we should have bumped the minor version there...
