### ISSUE TITLE
Compiler passes not initialized instance variable. And causes segfault.

### ISSUE THREAD

**Issue by kmdsbng** [manastech/crystal#2046]
version: Crystal 0.10.2 [b2b2d93] (Wed Jan 13 17:00:14 UTC 2016)

Compiler passes below code.

```
class Hoge
  def initialize
    @hoge :: String
  end

  def hoge
    @hoge.size
  end
end

p Hoge.new.hoge
```

And causes segfault.

```
% crystal instance_variable_test.cr
Program exited because of a segmentation fault (11)
```

If I  move instance variable definition from constructor to class context, compiler causes build error. (I expect this behavior)

```
class Hoge
  @hoge :: String

  def initialize
  end

  def hoge
    @hoge.size
  end
end

p Hoge.new.hoge
```

```
% crystal instance_variable_test.cr                                                                                                                 [~/work/crystal]
Error in ./instance_variable_test.cr:12: instantiating 'Hoge#hoge()'

p Hoge.new.hoge
           ^~~~

type must be String, not String?
...
```

**Comment by kirbyfan64** [comment]
The error is totally unrelated.

`::` is unsafe. It has no effect on the value's type, but it's uninitialized (as you already know).

I think the latter is an error because `@hoge` isn't initialized in `initialize`, so it is now nillable.

**Comment by asterite** [comment]
As @kirbyfan64 says, this is expected behaviour, although right now [the syntax is confusing](http://crystal-lang.org/docs/syntax_and_semantics/declare_var.html). In the next release the first code will become:

```crystal
class Hoge
  def initialize
    @hoge = uninitialized String
  end

  def hoge
    @hoge.size
  end
end
```

which is a bit more clear.
