### ISSUE TITLE
Segmentation fault under mysterious circumstances

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#2047]
I have managed to create code that segfaults. I have no idea why this is.
The code involves calling `Array#concat` with 32768 bytes of data.

At https://play.crystal-lang.org/#/r/q8z, you will find some code. This is _completely different_ code to what I'm using, but it segfaults also. It operates perfectly fine on the website, but segfaults on my machine every time.

Notably, if you remove one of the `infinite_sequence` calls, it does not segfault.
Also, if you add `to_a` after the call, it also does not segfault. This makes no sense whatsoever.

I am using Crystal 0.10.2 [b2b2d93] (Wed Jan 13 17:13:18 UTC 2016) on my machine.

**Comment by stugol** [comment]
Furthermore, if I replace `data.concat @buf[0, n]` with `data = data + @buf[0, n]` in my source (the original source, that is, not the source in the link), the segfault goes away.

I think there's something badly wrong with `Array#concat`.

FYI, `@buf` is a `Slice(Byte).new(32.kb)`, and `data` is a `[] of Byte`

**Comment by asterite** [comment]
Good catch, there was a bug with `concat` when the array was empty, `@capacity` wouldn't adjust properly.

**Comment by stugol** [comment]
But that doesn't explain why removing the redundant `infinite_sequence` line in my example code fixes the problem! Wtf?

**Comment by asterite** [comment]
There was a buffer overrun, so that could have written other variables in the stack. Effectively turning any code into a "wtf" state :-)

**Comment by stugol** [comment]
Ah, I see.
