### ISSUE TITLE
File read buffer not copied when reading a slice larger than the bytes in the buffer

### ISSUE THREAD

**Issue by benoist** [manastech/crystal#2049]
When you read bytes from a file that is less than the buffer size and you follow by reading bytes that exceed the remaining bytes in the buffer, then the bytes in the old buffer are not prepended to the new buffer

https://carc.in/#/r/qa8

**Comment by asterite** [comment]
The docs for [IO#read(Slice(UInt8))](http://crystal-lang.org/api/IO.html#read%28slice%3ASlice%28UInt8%29%29-instance-method) say:

> Reads at most slice.size bytes from this IO into slice. Returns the number of bytes read.

That means that less bytes could be read, even if there is more data available. You should always check `read`'s return value.

In this case, [IO::Buffered#read](https://github.com/manastech/crystal/blob/master/src/io/buffered.cr#L154-L173) only reads once from the underlying IO. I guess we could change it to read as much as possible to fill the given slice (maybe more intuitive).

**Comment by waj** [comment]
If you are waiting that many bytes to be read from the IO, then just use [IO#read_fully](http://crystal-lang.org/api/IO.html#read_fully%28slice%3ASlice%28UInt8%29%29-instance-method).

Let's say you're reading from a socket. If `IO::Buffered#read` continued reading until it filled as much data as possible, it might happen that the client doesn't have more data to send and is already waiting for a reply. In this case a deadlock would occur. We could make the second underlying read in `IO::Buffered` non blocking, but in any case you cannot trust that the `read` call will fill the entire buffer (maybe the next packed didn't arrive yet) and you always must check the returned number of bytes.

**Comment by benoist** [comment]
The reason I expected it to be filled was because the slice size is specified.
I see your point when reading from a socket and you don't know the size.
Would it be easier to have a method that fully fills the slice if you specifically ask for it? In my use case i do know the size of the bytes that should be read. It can raise if it can't be filled.

**Comment by waj** [comment]
That's what I said. Use [IO#read_fully](http://crystal-lang.org/api/IO.html#read_fully%28slice%3ASlice%28UInt8%29%29-instance-method) in that case :wink:

**Comment by benoist** [comment]
Haha I'm sorry. It's Friday and I'm in a pub having a beer trying to look smart ;-)

**Comment by asterite** [comment]
:beers:
