### ISSUE TITLE
module/class inheritance problems

### ISSUE THREAD

**Issue by shado23** [manastech/crystal#205]
When inheriting a constant it is accessible from inside the child class/module but not visible from the outside. Class variables are lost altogether. (Class instance variables are apparently not supported yet.)

Here is some sample code that show the issues. In ruby all of those cases work.

Using modules:
```ruby
module A
  CONSTANT   = true
  @@variable = true
end

module B
  include A

  def self.test
    pp CONSTANT
    pp @@variable # this fails
  end
end

B.test

pp A::CONSTANT
pp B::CONSTANT # this fails
```
Using classes:
```ruby
class A
  CONSTANT   = true
  @@variable = true
end

class B < A
  def self.test
    pp CONSTANT
    pp @@variable # this fails
  end
end

B.test

pp A::CONSTANT
pp B::CONSTANT # this fails
```

**Comment by asterite** [comment]
I'll close this, this is really old. Class variables work as expected, they are not shared by subtypes.

**Comment by kuraga** [comment]
Are class variables and constants not yet inheritable? Will be? Thanks.

**Comment by asterite** [comment]
@kuraga Class variables are not inheritable yet, but should be (and will be, but probably not in the next release)
