### ISSUE TITLE
Crystal Tool Format can't format Heredoc

### ISSUE THREAD

**Issue by sdogruyol** [manastech/crystal#2054]
Here's the source https://github.com/sdogruyol/kemal/blob/crystal-0.11.0/src/kemal/view.cr

`Error: couldn't format './src/kemal/view.cr', please report a bug including the contents of the file: https://github.com/manastech/crystal/issues`

**Comment by asterite** [comment]
Thanks for reporting this! :-)

**Comment by sdogruyol** [comment]
@asterite keep up the great work :heart_eyes:
