### ISSUE TITLE
Can someone explain `IO::FileDescriptor#wait_readable` to me please?

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#2056]
I'm trying to figure out `IO::FileDescriptor#wait_readable`, `IO::FileDescriptor#add_read_event` and `Scheduler::create_fd_read_event`. I don't understand why all these complicated functions are necessary. Surely `IO::FileDescriptor#unbuffered_read` could just be written like this?
```
private def unbuffered_read(slice : Slice(UInt8))
	count = slice.size
	loop do
		bytes_read = LibC.read(@fd, slice.pointer(count), count)
		return bytes_read if bytes_read != -1
		raise Errno.new "Error reading file" unless LibC.errno == Errno::EAGAIN
		Fiber.yield
	end
end
```

**Comment by ysbaddaden** [comment]
Wait readable is supposed to be called when a read call on the file descriptor would block, in order to not block but pass to another coroutine.

Ie. this is the event loop at work.

**Comment by ysbaddaden** [comment]
Your version would brute force the read until it passes, and would resume the coroutine for as long as we can't read. That would be very inefficient, spin the CPU for instance, ...

Wait readable tells libevent to notify when we can read, thus allowing to never return to the coroutine until we can read, allowing to run other coroutines that can be resumed in the meantime. Ie. it schedules coroutines efficiently.

**Comment by stugol** [comment]
Hm. I'm not familiar with libevent. It's some form of asynchronous callback-based version of `IO.select`?

**Comment by stugol** [comment]
What stops the fiber being resumed prior to a call from libevent? Is it something to do with the `Scheduler.reschedule` call?

**Comment by ysbaddaden** [comment]
I'm not familiar with libevent too, but it's a kind of cross platform wrapper for kernel systems like epoll,

**Comment by ysbaddaden** [comment]
Closing, since this is going into a talk and not an issue.
