### ISSUE TITLE
Class variable unconditionally assigned in initialize can be nil

### ISSUE THREAD

**Issue by shado23** [manastech/crystal#206]
It looks like the type interference doesn't know that initialize will have been called before instance methods can be called (or is there some circumstance where this isn't true?):
```ruby
class A
  @@a = 1

  def initialize
    @@b = 1
  end

  def test
    @@a + @@b
  end
end

A.new.test
```
Fails with:
```
in test_initialize.cr:11: no overload matches 'Int32#+' with types (Int32 | Nil)
```

**Comment by asterite** [comment]
I don't think we'll improve the logic for class variables, so I'll close this. You can always use the usual approach to deal with nil (try, not_nil!, if, etc.)
