### ISSUE TITLE
Compiler bug on dll call

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#2064]
The code [here](https://play.crystal-lang.org/#/r/qf1) throws a compiler bug.

**Comment by asterite** [comment]
Good catch. I reduced it to this:

```crystal
lib LibC
  fun foo(...)
end

LibC.foo(out x)
```

Basically, the use of `out` with variadic parameters. That shouldn't compile (because there's no way the compiler can figure out the type of `x`). As a workaround, you can use, in your case:

```crystal
  def self.get_terminal_size
    screen_size = uninitialized Int32
    C.ioctl(0, tIOCGWINSZ, pointerof(screen_size))
  end
```
