### ISSUE TITLE
"invalid character '\r' for heredoc identifier"

### ISSUE THREAD

**Issue by Arcovion** [manastech/crystal#2066]
```
Syntax error in ./libs/kemal/kemal/view.cr:3: invalid character '\r' for heredoc identifier

  template = <<-HTML
                    ^
```
Seems that the new heredoc syntax breaks on CRLF.
Quick fix was simply: `dos2unix ./libs/kemal/kemal/view.cr`

**Comment by asterite** [comment]
Yes, that should work.

In any case, you should be using `\n` for newlines, as specified in our [.editorconfig](https://github.com/manastech/crystal/blob/master/.editorconfig#L3).

**Comment by Arcovion** [comment]
Yea this was probably a Git issue with `autocrlf` when getting dependencies, not Kemal itself.

**Comment by Arcovion** [comment]
Found another bug:
```crystal
string = <<-EOS

1
2
3


EOS
p string
```
Ruby: `"\n1\n2\n3\n\n\n"`
Crystal: `"\n1\n2\n3\n\n"`

**Comment by asterite** [comment]
I think I prefer Crystal's output, otherwise you can't have a string without a trailing newline.

```crystal
string = <<-EOS
1
2
3
EOS
p string
```

Ruby: `"1\n2\n3\n"`
Crystal: `"1\n2\n3"`

So for me it's not a bug, just different from Ruby.

**Comment by Arcovion** [comment]
Ok, that makes sense.

**Comment by Arcovion** [comment]
Thanks!
