### ISSUE TITLE
check for nil failed in callback

### ISSUE THREAD

**Issue by kostya** [manastech/crystal#2075]
https://play.crystal-lang.org/#/r/qpi

y already should be not nil.

**Comment by kirbyfan64** [comment]
Not necessarily. Couldn't `y` be modified before you call the callback?

**Comment by asterite** [comment]
This is something to improve in the compiler, it could notice that `y` is never modified.

**Comment by asterite** [comment]
But right now every closured variable is considered like it could be modified.

The solution/workaround is to assign `y` to another variable inside the closure, and then use that one.
