### ISSUE TITLE
Segfault when running HTTP::Server in Thread

### ISSUE THREAD

**Issue by slava-vishnyakov** [manastech/crystal#2084]
First of all: thanks for Crystal! It's super-duper-awesome! :+1: 

I tried to make `HTTP::Server` saturate 4 CPU cores on Linux, but unsuccessfully, so I tried to run `HTTP::Server` inside 2 threads on different ports, but it segfaults.

```cr
# A very basic HTTP server
require "http/server"

(8080..8081).each do |port|
  Thread(Nil, Nil).new do
    server = HTTP::Server.new("0.0.0.0", port) do |context|
      context.response.print "Hello world"
    end
    puts "Listening on http://0.0.0.0:#{port}"
    server.listen
  end
end

puts "ok"
sleep(100000) // lazy way to to the join
```

The minimal case is:

```cr
require "http/server"

Thread(Nil, Nil).new do
  server = HTTP::Server.new("0.0.0.0", 8080) do |x| end
  server.listen
end.join
```

It results in segfault on both Mac and Linux on Crystal 0.11.1

Also, any plans (or an idea how to do it) for multi-threaded HTTP::Server that can saturate all CPUs?

I tried this:

```cr
server = HTTP::Server.new("0.0.0.0", 8080) do |context|
  Thread(Nil, Nil).new do
    context.response.print "Hello world"
  end.join
end
```

But it's slower and still doesn't saturate CPUs. (7k req/s instead of 40k/s without Thread)

Thanks!

**Comment by luislavena** [comment]
@slava-vishnyakov I believe the threading components of Crystal hasn't been updated (or work properly) right now.

In our end we spawn different processes with different ports and use nginx for reverse proxy, that way takes advantage of the cores of the system.

Cheers.

**Comment by asterite** [comment]
Yes, it's like what @luislavena says: you shouldn't be using `Thread` yourself, it will always break badly (that's why it's not exposed in the API). We are (well, @waj is) working on supporting multiple threads.

**Comment by slava-vishnyakov** [comment]
@asterite  @luislavena Thanks for the clarifications!
Does that mean that Crystal is supposed to be single-threaded or that's only for now?
Should I use `spawn` or Fiber?

Thanks for all you hard work, guys!

**Comment by ysbaddaden** [comment]
1. The event loop will eventually be multithreaded. Maybe we'll be able to manually start threads, but this is far from being guaranteed.
2. Use `spawn`, fibers are kind of an implementation detail.
