### ISSUE TITLE
Unable to use macro as the body of type alias

### ISSUE THREAD

**Issue by waterlink** [manastech/crystal#2085]
Lets imagine fictional case, that I have a macro that is supposed to produce some sort of concrete parametric/generic type, something like: `A(B, C(D), E(F(G)))`, and the type produced changes depending on macro arguments provided. Then to save keystrokes and de-dup, I would like to alias these complicated types to some meaningful names:

```crystal
alias AwesomeThing = my_macro(...)
```

I believe it results in a parsing error: `expecting token 'CONST', not 'my_macro'`.

If it is something that is easy to fix, great, if it is something that is hard to fix, don't bother, I am just playing around and experimenting with type system and will probably found a way around this problem at hand.

**Comment by waterlink** [comment]
Had to put an alias instead of macro, that constructs the result by recursively calling itself with ever-expanding result as an argument and only finally when it is completely expanded it puts it to the `alias`.

**Comment by waterlink** [comment]
s/instead/inside/

**Comment by waterlink** [comment]
To anyone wondering what I am doing, here is the snippet: https://carc.in/#/r/qrr

**Comment by waterlink** [comment]
And, of course, I have quickly hit a limitation: https://carc.in/#/r/qs5 - Hard limit of generic type nesting.

**Comment by waterlink** [comment]
Another interesting thing I have discovered, is that generating 1600 overloads of the same function, with different types, takes a lot of time. And it seems to have a quadratic time growth, which I can even imagine is pretty expected in this case.

**Comment by bcardiff** [comment]
I was going to suggest some other alternatives to play with information in generic classes, but I reach #2046 .
