### ISSUE TITLE
Script doesn't accept arguments

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#2087]
When running a script, command-line arguments are interpreted as additional filenames, rather than arguments; even if the script was run directly, using a shebang line:
```
#!/usr/bin/env crystal
puts ARGV
```
```
> ./test.cr hello
Error: File hello does not exist
```
This is unhelpful. By all means require the `--` separator when invoking a script via the `crystal` binary (`crystal test.cr -- hello`) but when running the script directly this is just silly and wrong.

**Comment by asterite** [comment]
Duplicate of #2087. I still don't know what's the best solution for this.

**Comment by stugol** [comment]
What, this is a duplicate of itself?

**Comment by asterite** [comment]
LOL, bad copy/paste, of #546
