### ISSUE TITLE
Import a module into the current namespace

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#2090]
Suppose I have a module declared in a file:
```
module IO
  def a; end
  def self.b; end
end
```
And I require it:
```
require "./io.cr"
```
I have two options. I can either `include IO` to import the instance method `a` into the current namespace; or call `b` by fully qualifying it (`IO::b`).

I would like to be able to use module methods fully qualified (`IO:b`), whilst also having the option to import the _same methods_ into the current namespace:
```
import IO
b()
```
In other words, how can I `import` the _class methods_ of `IO` into the current namespace as _instance methods_?

**Comment by ysbaddaden** [comment]
Just like in Ruby you need to extend a module. Yet, it won't extend the module methods (self.b) but the instance methods (a) as class/module methods (a becomes self.a).

Please ask such questions on stackoverflow with the `crystal-lang` tag. Thanks!

**Comment by stugol** [comment]
@ysbaddaden: You misunderstand me. This was less of a question, and more of a request for a missing feature.

It makes sense to wrap library code in a module. And yet, there is no way to import the contents of a module into the current namespace. Importing the instance methods as class methods doesn't cut it.

**Comment by asterite** [comment]
Is the section ["extend self" from the docs](http://crystal-lang.org/docs/syntax_and_semantics/modules.html) what you are looking for?

**Comment by stugol** [comment]
Ah, I wasn't aware of that. I would prefer something that I could invoke in the target namespace, rather than in the source module; but I guess it will suffice. Thank you.
