### ISSUE TITLE
Specific LIBC version dependancy

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#2092]
I compiled a Crystal executable on Debian 8, and tried to execute it on Debian 7. I get this error:
```
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found
```
How can I specify, during compilation, that an older version of GLIBC should be linked? ~~Alternatively, if I locate the correct version of `libc.so.6`, and place it in the same directory as the executable, will that fix it?~~ Apparently not.

**Comment by ysbaddaden** [comment]
This is a linking problem (LD). You better compile the executable on each different platform or build a static binary. There is nothing Crystal can do.

(Again: stackoverflow, thx).
