### ISSUE TITLE
Error: you've found a bug in the Crystal compiler

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#2097]
The following code crashes the compiler:
```cr
def dothing
	yield
end
dothing do
	spawn {
		next
	}
end
```
I can't use `return` in there, because Crystal complains if I do. If I'm not supposed to call `next` in a spawn, what should I do instead?

**Comment by ysbaddaden** [comment]
You can't. Coroutines live in their own world, there is nowhere to `return` to or `next` to.

`spawn` creates a coroutine that will run when the scheduler will tell it to run. In the meantime, the donothing block continues to run and thus terminates before the coroutine you created was given a change to run.

**Comment by asterite** [comment]
I think `next` should work, as we recently fixed the semantics of that ([here](https://github.com/manastech/crystal/issues/420)), it's just this bug that prevents you from doing it.

**Comment by asterite** [comment]
(probably because spawn is a macro)

**Comment by jhass** [comment]
@asterite what would it return from, the block passed to the macro? what would it return to?

**Comment by asterite** [comment]
It would return from the fiber. Just block is just pasted into the macro.

**Comment by stugol** [comment]
I just want a way to return early from a fiber. `return` doesn't work.

**Comment by ysbaddaden** [comment]
```crystal
def myroutime
  return
end

spawn :myroutine
```

**Comment by stugol** [comment]
That's not helpful.

**Comment by asterite** [comment]
Reduced:

```crystal
def foo
  yield
end

def bar(&block)
  block
end

foo do
  bar do
    next
  end
end
```
