### ISSUE TITLE
Error: execution of command failed with code:

### ISSUE THREAD

**Issue by greyblake** [manastech/crystal#2114]
Hi!
I am trying to build crystal from the source code. The build seems to pass, but crystal fails to run any program.

Build:
```
$ make
g++ -c -o src/llvm/ext/llvm_ext.o src/llvm/ext/llvm_ext.cc `/usr/bin/llvm-config-3.5 --cxxflags`
CRYSTAL_CONFIG_PATH=`pwd`/src ./bin/crystal build  -o .build/crystal src/compiler/crystal.cr
```

Attempt to run simple test.cr program:
```
$ ./.build/crystal test.cr 
./.crystal/home/blake/dev/open_source/crystal/test.cr/_main.o: In function `__crystal_main':
main_module:(.text+0x5fd): undefined reference to `GC_get_push_other_roots'
main_module:(.text+0x663): undefined reference to `GC_set_push_other_roots'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o "/home/blake/dev/open_source/crystal/.crystal/crystal-run-test.tmp" "${@}"  -rdynamic  -levent -lrt -lpcre -lgc -lpthread -ldl`
```

test.cr
```crystal
puts "Hello"
```

Environment:
```
$ uname -a
Linux susanne 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux
```

I've installed all the listed packages (in ubuntu section): https://github.com/manastech/crystal/wiki/All-required-libraries

```
$ llvm-link --version
LLVM (http://llvm.org/):
  LLVM version 3.5.0
```

**Comment by ysbaddaden** [comment]
I think the Crystal you built doesn't use the embedded `libgc.a` but another one that is present on your system but too old (it's missing symbols).

Please check the version of boehm GC you have installed. Upgrading it should fix your problem.

**Comment by greyblake** [comment]
Works!

So, what I had to do is to install `libmonoboehm-2.0-dev` package:
```
apt-get install libmonoboehm-2.0-dev
```

Thanks!

**Comment by greyblake** [comment]
@ysbaddaden I am on Debian. Shell we update the wiki page with list of dependecies?

**Comment by ysbaddaden** [comment]
The actual packages are `libgc` and `libgc-dev` but you need the ones from Debian Stretch or Ubuntu Xenial in order to install v7.4.0 or later.

I didn't know about the `libmonoboehm-2.0` packages. I don't understand how it solved the problem, since they install a library we don't link to (and they don't conflict with `libgc` so they didn't uninstall it)...

**Comment by ysbaddaden** [comment]
Actually GC 7.4.2 won't cut it either, we need `GC_push_all_eager` now which isn't in any release.

**Comment by codenoid** [comment]
how about this :/  , ubuntu 16.04, crystal 0.23.1, (working fine on my osx sierra)

```
root@toped:~/6000/crawler/shopee# crystal build --release --no-debug id.cr
/usr/bin/ld: /opt/crystal/embedded/lib/../lib/libgc.a(os_dep.o): undefined reference to symbol '_end'
//usr/lib/x86_64-linux-gnu/libsodium.so.18: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/root/6000/crawler/shopee/id'  -rdynamic  -lzmq -lz `command -v pkg-config > /dev/null && pkg-config --libs libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs libcrypto || printf %s '-lcrypto'` -lpcre -lm -lgc -lpthread /opt/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
```

**Comment by codenoid** [comment]
shards
```
dependencies:
  selenium:
    github: ysbaddaden/selenium-webdriver-crystal
    branch: master
  memcached:
    github: comandeo/crystal-memcached
  zeromq:
    github: benoist/zeromq-crystal
```

**Comment by codenoid** [comment]
manual compile with `gcc` from --cross-compile
https://pastebin.com/99Ts2tEL
