### ISSUE TITLE
"Nil assertion failed" in HTTP::Client.get

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#2117]
This code throws a "nil assertion failed":
```
require "http/client"
HTTP::Client.get("nas:8044")
```
Now granted, I'm not specifying the protocol here, but it's a reasonable assumption to make that it will default to `http://`.

Besides, a nil-exception is _never_ an error message, it's always a bug.

**Comment by waj** [comment]
I agree. The HTTP::Client should assume `http` scheme if not specified otherwise.

**Comment by waj** [comment]
Actually, this is a bug in the URI parsing (if you try the same without specifying the port you get a different error).

```crystal
URI.parse("nas:8044") # => #<URI @scheme="nas", @host=nil, @port=nil, @path=nil, @query=nil, @user=nil, @password=nil, @fragment=nil, @opaque="8044">
```

As you can see the URI is incorrectly parsed using "nas" as the scheme and "8044" as opaque data.

**Comment by waj** [comment]
Um... I should take more time before commenting, because it seems that Ruby's URI also parses the same way, so it either has the same bug or the behaviour is the expected. (I think is the last).

**Comment by stugol** [comment]
@waj You consider it better to emulate a Ruby bug (or bad decision) than to deviate from it and actually make the function useful?

**Comment by waj** [comment]
No... there is a whole specification about URI strings that we should obey and my guess is that Ruby is doing the right thing, because is much more mature and many more people is observing every detail.

Still I think the HTTP::Client could have a more friendly behaviour, but not changing the URI parser.

**Comment by waj** [comment]
For example, the excellent gem "rest-client" do this before parsing the URL:
https://github.com/rest-client/rest-client/blob/master/lib/restclient/request.rb#L357-L364

I think this is perfectly doable without using a regex. @asterite what do you think?
