### ISSUE TITLE
Surprising behavior of `Tuple` causing bug in `SimpleHash`

### ISSUE THREAD

**Issue by lucaong** [manastech/crystal#2121]
Hello,
I am not sure this can be considerevole a bug, but it is a surprising behavior that might deserve documentation, ad it can cause subtle bugs.

This code compiles without errors:

```crystal
Tuple(Int32, Int32).new("foo", "bar") # => {"foo", "bar"}
```

This is because of the way `Tuple.new` is implemented, that does not make use of type bounds:

```crystal
def self.new(*args)
  args
end
```

Sometimes this can lead to buggy behavior, like in `SimpleHash`, where this code does not compile:

```crystal
require " simple_hash"

h = SimpleHash(Symbol, Int32 | Book).new
h[:foo] = 42

# compilation error:
# no overload matches 'Array({Symbol, Int32 | Book})#[]=' with types Int32, {Symbol, Int32}
```

I can submit a pull request to fix `SimpleHash` by using a custom `Entry(K, V)` struct instead of a `Tuple(K, V)`, but I also wanted to let you know and possibly decide on this behavior of tuple. If you consider it a bug and have a fix in mind to make `Tuple.new` respect its type bounds, then the change in `SimpleHash` is unnecessary.

As always, let me know if I can help with this issue. Crystal is an amazing project and I want to help making it rock-solid.

**Comment by asterite** [comment]
This is a combination of two bugs: #1828 and #357.

For now we can use an `Entry` struct instead of a tuple until we solve these issues, but it's better if SimpleHash is usable.
