### ISSUE TITLE
NoReturn should be able to be casted to any type

### ISSUE THREAD

**Issue by bcardiff** [manastech/crystal#2132]
I recall we discussed this IRL and maybe we fixed some corner cases about NoReturn types acting as a bottom type.

NoReturn types (ie. exception raising code) should be able to be casted to any type.

For example https://play.crystal-lang.org/#/r/rvj runs (with the exception).
But https://play.crystal-lang.org/#/r/rvl does not compile avoiding for example partial/in-progress implementation of abstract classes sometimes. 

```crystal
abstract class Foo
  def n
    m as Int32
  end

  abstract def m : Int32
end

class Bar < Foo
  def m
    raise "not yet"
  end
end

Bar.new.n
```

`can't cast NoReturn to Int32`

**Comment by bcardiff** [comment]
:heart_eyes_cat: Yet, related to this in a formal way is the issue that when overriding a method there is not check that the type information is consistent. I was expecting the fix will be related to that.

Should we create a separate issue to handle proper subtyping in method overloads? 
https://play.crystal-lang.org/#/r/rvz (note that the compiler asumes that `#m` is an override due to https://play.crystal-lang.org/#/r/rw0)

With methods overloads and union I know the issue is hard to solve, but nevertheless is good to know that the compiler does not force some guarantees around this yet.

**Comment by asterite** [comment]
Return types are only checked for the current method, not for overriding methods, so yes, it's a separate issue.

**Comment by asterite** [comment]
It's #160
