### ISSUE TITLE
HTTP::Client body is empty

### ISSUE THREAD

**Issue by kostya** [manastech/crystal#2134]
0.11.1 is ok, but in master i get:

crystal eval 'require "http/client"; res = HTTP::Client.get("https://www.google.ru/"); p({res.status_code, res.body.size})'
{200, 0}

**Comment by kostya** [comment]
bisect it to 96c08295b047c2d2a2b0f08a3aa827eee48b15a8

**Comment by asterite** [comment]
@kostya Thank you! When I rewrote that class I totally missed that case. Can you confirm this fixes it?

**Comment by kostya** [comment]
fixed

**Comment by asterite** [comment]
I wanted to add a spec but I couldn't make it fail, it only failed when I did the http request...
