### ISSUE TITLE
More comprehensive printf/ String Formatter

### ISSUE THREAD

**Issue by gtramontina** [manastech/crystal#2137]
There are some format flags that are not recognized by the current implementation, here are some examples (perhaps to be added to the specs):

```crystal
it "does %" do
    ("%*s" % [10, "foo"]).should eq("       foo") # Dynamic width and/or precision for strings
    ("%5.5s…" % "abcdefghi").should eq("abcde…")  # String trimming (not only padding)
end
```

_PS: I'm still getting my environment setup in order to be able to play around with Crystal's source and contribute with code. I'm not really familiar with the things needed for compiling C and alike, so I'm facing some difficulties (like #1818) on OSX…_

**Comment by asterite** [comment]
Sure, those look useful.

Be sure to read [this](https://github.com/manastech/crystal/blob/master/Contributing.md#contributing-to-the-standard-library) in order to setup your environment.

**Comment by gtramontina** [comment]
Aha! RTFM! :smile:
