### ISSUE TITLE
Type for subclass of abstract class

### ISSUE THREAD

**Issue by Thyra** [manastech/crystal#2156]
I have an abstract class ``Engine``. Now I want to save several subclasses (classes that inherit from Engine) in a hash. How do I declare the type of this hash?
This is what I tried first:
```crystal
hash = {} of String => Class #-> can't use Class as generic type argument yet, use a more specific type
```
So I asked myself what a *more specific type* could be. So I tried:
```crystal
puts typeof({"a" => Int32}) #-> Hash(String, Int32:Class)
```
There obviously is a type ``Int32:Class``. Unfortunately I can't seem to use it:
```crystal
a : Int32:Class #-> unexpected token: Class
```
So how do I get methods and variables to use classes as their types?

**Comment by ysbaddaden** [comment]
If you want instances of Engine:

```crystal
{} of String => Engine.class
```

If you want Engine (sub)classes:

```crystal
{} of String => Engine.class
```

Int32 and alikes are actually primitive structs and not exactly classes, and the way the current compiler works, we can't use Reference or Class as generics. I'll let Asterite explain better.

**Comment by Thyra** [comment]
Thank you!
