### ISSUE TITLE
bug with ints

### ISSUE THREAD

**Issue by kostya** [manastech/crystal#2165]
```
crystal eval 'p Int64[0xFFFFFFFF, -0xFFFFFFFF]'
[4294967295, 1]
```

```
ruby -e 'p [0xFFFFFFFF, -0xFFFFFFFF]'
[4294967295, -4294967295]
```

**Comment by MakeNowJust** [comment]
It's mystery:

```console
$ crystal eval 'p -0xFFFFFFFF == -(0xFFFFFFFF)'
false
$ crystal eval 'p -0xFFFFFFFF'
1
$ crystal eval 'p -(0xFFFFFFFF)'
-4294967295
```

**Comment by asterite** [comment]
Seems there's a problem with hex numbers bigger than 0x80000000:

https://play.crystal-lang.org/#/r/siq

Must be a bug in the lexer (the lexer gives the type to these literals)

**Comment by asterite** [comment]
I think there are other (bigger) literals that might cause the same problem. If you find them, let me know :-)
