### ISSUE TITLE
Int16::MAX < UInt16::MAX == false

### ISSUE THREAD

**Issue by kostya** [manastech/crystal#2167]
```
crystal eval 'p({Int16::MAX, UInt16::MAX})'
{32767, 65535}
```

```
crystal eval 'p({Int16::MAX, UInt16::MAX}.min)'
32767
```

```
crystal eval 'p(Int16::MAX < UInt16::MAX)'
false
```

**Comment by kostya** [comment]
```
crystal eval 'p({UInt16::MAX, Int16::MAX}.min)'
65535
```

**Comment by asterite** [comment]
I think comparisons (or maybe even any operation) between signed and unsigned integers should be disallowed, we should make that change at some point.

**Comment by kostya** [comment]
noooooo, i fix by changing order or operators https://github.com/benoist/msgpack-crystal/pull/16/files#diff-d424809b29161176c5b252a646566ffdR71 (and converting between types can add slowdowns)
