### ISSUE TITLE
Markdown inner lists are broken

### ISSUE THREAD

**Issue by veelenga** [manastech/crystal#2169]
```crystal
require "markdown"

input = <<-MD
* Level1
   * Level2
   * Level2
MD

p Markdown.to_html input
```

Produces the following:

```html
<ul><li>Level1</li><ul><li>Level2</li></ul><li>Level2</li></ul>
```

Which looks like this:

* Level1
  * Level2
* Level2

But expected to be:

* Level1
  * Level2
  * Level2

I believe this is something related to #2149 

/cc @SebastianSzturo

**Comment by SebastianSzturo** [comment]
Sorry about that. I will look into it!

**Comment by asterite** [comment]
No need to say sorry, before your PR nested lists weren't supported at all :-)
