### ISSUE TITLE
File#truncate result when called by File object that is opened with "w" mode.

### ISSUE THREAD

**Issue by arcage** [manastech/crystal#2170]
The API reference shows the `File#truncate` requires a **write** file descriptor.

It seems to work when the receiver is opened with `"r+"` mode.

However, when the receiver is opened with `"w"` mode, all bytes in truncated file are set to null(`'\0'`).

```crystal
File.open("test.txt", "w") do |file|
  file.puts "1234567890"
end

File.open("test.txt", "r+") do |f|
  f.truncate(6)
end

p File.read("test.txt")
# => "123456"

File.open("test.txt", "w") do |f|
  f.truncate(3)
end

p File.read("test.txt")
# => "\u{0}\u{0}\u{0}"
```

I have encountered this behavior by using Crystal 0.12.0 on El Capitan and CentOS6.

Is this a normal function?

I wonder this result, because the `ftruncate` function in C lang works well even when the file descriptor is opened with `O_WRONRY`.

```c
/* test.c */

#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>

int main() {
  int fd;
  fd = open("test.txt", O_WRONLY);
  ftruncate(fd, 5);
  close(fd);
}
```

```shell
$ cat test.txt
1234567890
$ gcc test.c
$ ./a.out
$ cat test.txt
12345$
```

**Comment by jhass** [comment]
`w` opens with `O_TRUNC`, to mimic `fopen(3)`, see https://github.com/manastech/crystal/blob/master/src/file.cr#L59. You might be looking for `a`.

We're using `ftruncate(3)` underneath, the zero bytes come from there:

> If the file previously was smaller than this size, ftruncate() shall increase the size of the file. If the file size is increased, the extended area shall appear as if it were zero-filled.

**Comment by arcage** [comment]
Thank you for your comment.

My understanding of the mode flags was lacking.

**Comment by asterite** [comment]
Maybe the above can be added to the docs... somewhere, somehow :-)
