### ISSUE TITLE
Problems with block passing, inheritance and `with self yield`

### ISSUE THREAD

**Issue by waterlink** [manastech/crystal#2171]
I have very weird issues. Lets start with working code: https://carc.in/#/r/sjx

`Example` class is a required layer to delay the execution of `with-self-yielded` block.

Then next step is to define new class in inheritance hierarchy:

```diff
  class Something < Context
    def subject
      "hello world"
    end
+
+   class SomethingElse < Something
+     def subject
+       "overriden hello world"
+     end
+   end
  end
```

It results in this compile time bug: https://carc.in/#/r/sjy

After playing around with it, workaround to avoid this bug is:

```diff
 -class Context
+ module Context
```

```diff
 -class Something < Context
+ class Something
+   include Context
```

```diff
    class SomethingElse < Something
+     include Context
```

And the result can be seen here: https://carc.in/#/r/sk0

After adding more descendants and example output for all classes in hierarchy: https://carc.in/#/r/sk1

As you can see, leaf nodes of hierarchy seem to work properly, whereas `class Something` calls virtual method of last defined descendant - this is really weird.

I hope, you can spot an error in my code, or quickly recognize what this bug is and how to fix it.

**Comment by asterite** [comment]
Just a bug, I reduced it to this:

```crystal
class Foo
  def run
    with self yield
  end

  def method
    1
  end
end

class Bar < Foo
  def method
    2
  end
end

# So the type is Foo+
(Foo.new || Bar.new).run { method }
```

It seems the bug is with `with ... yield` and virtual types.

**Comment by asterite** [comment]
Or (a bit shorter):

```crystal
class Foo
  def method
    1
  end
end

class Bar < Foo
  def method
    2
  end
end

def foo
  with (Foo.new || Bar.new) yield
end

foo { method }
```

**Comment by waterlink** [comment]
@asterite Thanks for reducing it to smaller example. So, even if compiler knows for sure, that the type of `ctx` in question is the exact type (at least, that is what `typeof` shows), it still affected by being a virtual type kind of bug?

**Comment by asterite** [comment]
I think in your case you have a captured proc `T -> `. Since Proc is like a generic type, if you have Proc(T, Void) it's like Proc(T+, Void), so any T (same if you have Array(Foo), it's implicitly Array(Foo+) since you can store subclasses). That's why there's a virtual type.

Right now that part of the compiler is not very nice, maybe virtual types will be gone and a T will always mean "or it's subclasses".

**Comment by waterlink** [comment]
@asterite Oh I see. Thank you for the explanation. Any idea where to chase for the bug in compiler code?

**Comment by asterite** [comment]
Actually, the problem seems related to method dispatch, this also triggers the bug:

```crystal
class Foo
  def method(x : Int32)
  end

  def method(x : Float64)
  end
end

def foo
  with Foo.new yield
end

foo do
  method(1 || 1.5)
end
```

So probably the solution is simpler :-)

**Comment by asterite** [comment]
@waterlink Yes, it's around [here](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/codegen/call.cr#L262). I'll probably fix it in some minutes, must be something easy to find, and I'm also very curious :-P

**Comment by asterite** [comment]
Eventually we'll clean up the compiler's code so anyone can fix these things. Right now it's (just a bit) messy in a few places, and there aren't many comments.
