### ISSUE TITLE
Cannot store a Proc in a Hash or an Array

### ISSUE THREAD

**Issue by greyblake** [manastech/crystal#2176]
I am trying to store a Proc in hash:
```
rules = { :test => ->(x : Object) { true } }
```
And I get the following error:
```
cannot be used as a Proc argument type yet, use a more specific type

        rules = { :test => ->(x : Object) { true } }
```

Crystal version: 0.12.0

I see, the message means, it will be added in the future. So please consider this ticket as a feature request.
Thanks!

**Comment by greyblake** [comment]
Same with arrays:

```
icr(0.12.0) > arr = [ ->(x : Object) { true } ]
cannot be used as a Proc argument type yet, use a more specific type

  arr = [ ->(x : Object) { true } ]
```

**Comment by asterite** [comment]
You can actually store a Proc in a Hash, you just need a more specific type. What do your Procs do?

**Comment by greyblake** [comment]
Ah, I misunderstood the error message. `Object` is to generic type. This for exmaple works:

```
rules = { :test => ->(x : Int32) { true } }
```

Thanks, @asterite !
