### ISSUE TITLE
Addition of UInt32::MAX and Int

### ISSUE THREAD

**Issue by AlexWayfer** [manastech/crystal#2181]
```crystal
UInt32::MAX           #  => 4294967295
UInt32::MAX + 1       #  => 0
UInt32::MAX + 1_u32   #  => 0
UInt32::MAX + 5       #  => 4
UInt32::MAX - 10 + 5  #  => 4294967290
```
Some bug? How I can get `4294967296` through `UInt32::MAX`?

**Comment by kirbyfan64** [comment]
Is this really a bug? Seems just like integer overflow to me. I think you could do `UInt32::MAX.to_i + 1`. (I mean, maybe there's a bug involving integer promotions or something, but it just seems like overflow...)

**Comment by AlexWayfer** [comment]
@kirbyfan64 `UInt32::MAX.to_i + 1    #   => 0`

**Comment by kirbyfan64** [comment]
Haha, I'm stupid and misread the code. Try:

```crystal
puts UInt32::MAX.to_i64 + 1
```

That'll use `Int64`s, which should be big enough to hold that value.

**Comment by AlexWayfer** [comment]
Okay, @kirbyfan64 , thanks, it's working.
