### ISSUE TITLE
Named argument without default value

### ISSUE THREAD

**Issue by lepieru** [manastech/crystal#2184]
This is a valid Crystal code picked in the documentation:
```ruby
def some_method(x, y = 0, z = 0)
  # some code…
end

some_method 1
some_method 1, z: 3
some_method 1, y: 2, z: 3
```

Nice! But if we want to make explicit the first value like:

```ruby
some_method x: 1, y: 2, z: 3
```

It fails with:
```
wrong number of arguments for 'some_method' (0 for 1, 2, 3)
Overloads are:
 - some_method(x, y = 0, z = 0)

some_method x: 1, y: 2, z: 3
^~~~~~~~~~~
```

The documentation say:
> Note that in the above example you can't use x's name, as it doesn't have a default value.
> 
> In this way, default arguments and named arguments are related to each other: when you specify default arguments you are also allowing the caller to use their names. Be wise and choose good names.

I think it will be interesting to allow arguments without default value to be nameable. It may be helpful to write more explicit code. How about you?

**Comment by marceloboeira** [comment]
@lepieru I had this problem yesterday, I also would like to understand why this happens and if there is any initiatives to implement that :+1:

**Comment by asterite** [comment]
Yes, there are cases where the name might provide some good self documentation.

I'll close this as there's a more complete issue tracking this: https://github.com/manastech/crystal/issues/560#issuecomment-95357502 (#560)
