### ISSUE TITLE
Flags with underlying UInt8 to_s number instead of list

### ISSUE THREAD

**Issue by ozra** [manastech/crystal#2185]
```crystal
@[Flags]
enum SomeFacts : UInt8
   AppleLover
   PearLover
   CoolDude
end

some_facts = SomeFacts.flags AppleLover, CoolDude
puts "facts: #{some_facts}"
```

Prints it as its underlying value: `"facts: 5"`
Dropping the UInt8 gives the expected `"facts: AppleLover, CoolDude"`

**Comment by asterite** [comment]
Good catch. It seems that the `: UInt8` makes the enum not be Flags at all.
