### ISSUE TITLE
Mathematics fail

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#2197]
Can someone tell me how `a` is greater than `b`?
```
a = 1591627776_i32
b = 2147483648_u32
puts a > b
```
Surely this is a bug. And a serious one at that.

**Comment by rmosolgo** [comment]
Huh, apparently comparing signed and unsigned integers is similar in C: 

http://stackoverflow.com/questions/2084949/arithmetic-operations-on-unsigned-and-signed-integers

How do you think it should be handled?

**Comment by stugol** [comment]
In a word? Properly.

**Comment by kumpelblase2** [comment]
See #571
