### ISSUE TITLE
Alias generic type

### ISSUE THREAD

**Issue by jmoriau** [manastech/crystal#2198]
Hi,

So I tried to alias a type that would include a generic `T` like this https://carc.in/#/r/srv :

```ruby
class MyClass(T)
    alias BlockType = (T -> (Tuple(Bool, String) | Tuple(Bool, Nil)))
    def initialize(@block : BlockType)
      puts @block.call(10)
    end
end
b = MyClass(Int32).new(-> (a : Int32) { (a > 0) ? {true, nil} : {false, "failed because X"} })
```

But I get:
```
Error in ./test.cr:2: undefined constant T

  alias BlockType = (T -> (Tuple(Bool, String) | Tuple(Bool, Nil)))
```

I re-read the doc about `alias` and tried to find some examples, but no luck :confused: 
Do I have the wrong syntax ? Or is it simply not possible to alias it ?

I'm even more confused because if I use the type directly it works as expected https://carc.in/#/r/srt :

```ruby
class MyClass(T)
    def initialize(@block : (T -> (Tuple(Bool, String) | Tuple(Bool, Nil))))
      puts @block.call(10)
    end
end
b = MyClass(Int32).new(-> (a : Int32) { (a > 0) ? {true, nil} : {false, "failed because X"} })
```

What am I missing ?

**Comment by rmosolgo** [comment]
some reasons and workarounds here, too: https://github.com/manastech/crystal/issues/1920

**Comment by jmoriau** [comment]
Ah makes sense thanks!
