### ISSUE TITLE
"Particular" spelled incorrectly on docs page

### ISSUE THREAD

**Issue by jakebruemmer** [manastech/crystal#2200]
The header for the section about [command line options](http://crystal-lang.org/docs/using_the_compiler/index.html) for `crystal` has the word "particular" mispelled.

**Comment by jhass** [comment]
https://github.com/manastech/crystal/blob/master/Contributing.md#contributing-to-the-documentation Want to give it a try? ;)

**Comment by jakebruemmer** [comment]
I'll try it once I get home from work today :)

**Comment by jakebruemmer** [comment]
I fixed it on my own local branch but I don't have push permissions on the repository.

**Comment by bcardiff** [comment]
@jakebruemmer you need to fork it in your github account, perform the change in a branch and submit a pull request.

Alternative for some typos in the doc you can find the file and change it directly in github and will perform all this operations under the hood.

Next PR will be bigger for sure, so it's worth trying the process.

**Comment by jakebruemmer** [comment]
https://github.com/manastech/crystal/pull/2206

:)

?
