### ISSUE TITLE
Can't compile Crystal at all now

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#2203]
I'm doing exactly the same as I always do. And now:
```
# make
CRYSTAL_CONFIG_PATH=`pwd`/src ./bin/crystal build  -o .build/crystal src/compiler/crystal.cr
Using compiled compiler at .build/crystal
/tmp/crystalGB31tH/crystal/.crystal/crystal-run-macro-run-_opt_crystal_src_ecr_process.cr.tmp: symbol lookup error: /tmp/crystalGB31tH/crystal/.crystal/crystal-run-macro-run-_opt_crystal_src_ecr_process.cr.tmp: undefined symbol: GC_set_handle_fork
Error in ./src/compiler/crystal.cr:3: instantiating 'Crystal::Command:Class#run()'

Crystal::Command.run
                 ^~~

instantiating 'run(Array(String))'

in ./src/compiler/crystal/command.cr:42: instantiating 'Crystal::Command#run()'

    new(options).run
                 ^~~

in ./src/compiler/crystal/command.cr:58: instantiating 'init()'

        init
        ^~~~

in ./src/compiler/crystal/command.cr:146: instantiating 'Crystal::Init:Module#run(Array(String))'

    Init.run(options)
         ^~~

in ./src/compiler/crystal/tools/init.cr:41: instantiating 'Crystal::Init::InitProject#run()'

      InitProject.new(config).run
                              ^~~

in ./src/compiler/crystal/tools/init.cr:149: instantiating 'Array(Crystal::Init::View+:Class)#each()'

        views.each do |view|
              ^~~~

in /opt/crystal/src/array.cr:776: instantiating 'each_index()'

    each_index do |i|
    ^~~~~~~~~~

in /opt/crystal/src/array.cr:776: instantiating 'each_index()'

    each_index do |i|
    ^~~~~~~~~~

in ./src/compiler/crystal/tools/init.cr:149: instantiating 'Array(Crystal::Init::View+:Class)#each()'

        views.each do |view|
              ^~~~

in ./src/compiler/crystal/tools/init.cr:150: instantiating 'Crystal::Init::View+#render()'

          view.new(config).render
                           ^~~~~~

in ./src/compiler/crystal/tools/init.cr:127: instantiating 'to_s()'

        File.write(full_path, to_s)
                              ^~~~

in /opt/crystal/src/object.cr:78: instantiating 'String:Class#build()'

    String.build do |io|
           ^~~~~

in /opt/crystal/src/string.cr:238: instantiating 'String::Builder:Class#build(Int32)'

    String::Builder.build(capacity) do |builder|
                    ^~~~~

in /opt/crystal/src/string.cr:238: instantiating 'String::Builder:Class#build(Int32)'

    String::Builder.build(capacity) do |builder|
                    ^~~~~

in /opt/crystal/src/object.cr:78: instantiating 'String:Class#build()'

    String.build do |io|
           ^~~~~

in /opt/crystal/src/object.cr:79: instantiating 'to_s(String::Builder)'

      to_s io
      ^~~~

in macro 'embed' /opt/crystal/src/ecr/macros.cr:81, line 1:

  1.     {{ run("ecr/process", "/tmp/crystalGB31tH/crystal/src/compiler/crystal/tools/init/template/example_spec.cr.ecr", "__io__") }}
  2.

    {{ run("ecr/process", "/tmp/crystalGB31tH/crystal/src/compiler/crystal/tools/init/template/example_spec.cr.ecr", "__io__") }}
    ^

expanding macro
in macro 'embed' /opt/crystal/src/ecr/macros.cr:81, line 1:

  1.     {{ run("ecr/process", "/tmp/crystalGB31tH/crystal/src/compiler/crystal/tools/init/template/example_spec.cr.ecr", "__io__") }}
  2.

    {{ run("ecr/process", "/tmp/crystalGB31tH/crystal/src/compiler/crystal/tools/init/template/example_spec.cr.ecr", "__io__") }}
       ^~~

Error executing run: ecr/process "/tmp/crystalGB31tH/crystal/src/compiler/crystal/tools/init/template/example_spec.cr.ecr" "__io__"

Got:

make: *** [.build/crystal] Error 1
```

**Comment by asterite** [comment]
`undefined symbol: GC_set_handle_fork`

You need boehm GC 7.4.2.

**Comment by stugol** [comment]
And `git clone git://github.com/ivmai/bdwgc.git` is not sufficient for this???

**Comment by asterite** [comment]
Actually a duplicate of #1964

We should probably implement #251 at one point. I'm just not sure it's the correct solution.

**Comment by stugol** [comment]
How is this a duplicate? I already have the GC installed!

**Comment by kirbyfan64** [comment]
@stugol Is this on Debian or Ubuntu? [Debian's libgc is new enough](https://packages.debian.org/sid/libgc-dev).

**Comment by stugol** [comment]
Debian 7 32-bit.

**Comment by kirbyfan64** [comment]
@stugol [Not even Torvalds makes Linux binaries, though...](http://news.softpedia.com/news/Linus-Torvalds-Says-Linux-Binary-Packages-Are-Terrible-Valve-Might-Save-the-Desktop-458087.shtml) If you're trying to distribute binary versions of what you're making, your best bet would be to [wait for Musl support](https://github.com/manastech/crystal/pull/2124)...

**Comment by stugol** [comment]
It's for my own use. I've written a program to set up a fresh Debian system how I like it. Running it from source simply would not work here.

Else I'd just use Ruby.

**Comment by kirbyfan64** [comment]
> Running it from source simply would not work here.

Not to be rude or anything, but aren't there programs designed *exactly* for this task?

**Comment by stugol** [comment]
Such as?

**Comment by kirbyfan64** [comment]
Puppet. Just do:

```
$ sudo apt-get install puppet
$ puppet apply my-manifest.pp
```

See [here](http://www.example42.com/tutorials/PuppetTutorial/#slide-9) for info on how to write the manifests (just ignore the slide about "Node classification").

I think cfengine can also do this, but I couldn't find any info on running it locally, i.e. without a server.

Or you could just use shell scripts like I do...

**Comment by stugol** [comment]
Looks very complicated. And probably only works on systems that have a `puppet` package in the repo already. But sure, I'll take a look.

Writing shell scripts is like pulling teeth. It's honestly like the developers tried to make it as much of an arse as possible. For example, checking if a variable is empty. Or the horrible `then` keyword having to be on its own line. Gah.

**Comment by kirbyfan64** [comment]
> checking if a variable is empty

`[ -z "$VAR" ]`

> `then` keyword having to be on its own line

`if xyz; then`

**Comment by stugol** [comment]
But suppose I'm not "checking if it's empty", suppose I'm just checking if it's a specific value? If it turns out to be null, it'll be elided and cause an error.

I know about `; then`, it's just a pain. I keep forgetting, and it all goes to hell.

**Comment by kirbyfan64** [comment]
@stugol

> But suppose I'm not "checking if it's empty", suppose I'm just checking if it's a specific value? If it turns out to be null, it'll be elided and cause an error.

Just wrap it in quotes:

```
[ "$a" == "1" ]
```

> I know about `; then`, it's just a pain. I keep forgetting, and it all goes to hell.

Yeah, that kind of *is* a pain...you might want to check out a scripting shell like [rc](https://en.m.wikipedia.org/wiki/Rc).

But before this conversation completely derails...

You can set `LD_LIBRARY_PATH` in your `.profile`, or just uninstall your system `libgc` completely:

```
$ sudo apt-get purge --auto-remove libgc-dev libgc
```

Then install from Git. Just make sure you try it in a VM or something first, because I'm not sure if that would break anything (on Ubuntu, it doesn't, but I don't know about Debian).

@asterite I think there should probably be a "frequently encountered install issues" section in the docs, considering I think @stugol is the third person to encounter libgc issues on Linux since I started watching this repo. Maybe the install issues with El Captain (or however the heck it's spelled) could go there also?

**Comment by stugol** [comment]
If anything, `rc` looks even worse. Plus, whatever I use has to exist in the repo for any Linux I'm likely to use...

**Comment by ysbaddaden** [comment]
@kirbyfan64 I updated the wiki page to make it clear that BOEHM GC must always be compiled from source: https://github.com/manastech/crystal/wiki/All-required-libraries/_compare/7174996f9453d7ccf1952333477a015655e184be...1b7138638388ae561b859108fc7698ea5470f6f4

Please continue talking about the greatness of Bash and automated installs using Chef, Puppet, Salt or Ansible in better places :-)
