### ISSUE TITLE
Problem with comparison of Floats

### ISSUE THREAD

**Issue by AlexWayfer** [manastech/crystal#2209]
Help, please! It's blocking #2166 
How?!
```crystal
icr(0.12.0) > a = 9.99201e-14
 => 9.99201e-14
icr(0.12.0) > b = 9.98617e-14
 => 9.98617e-14
icr(0.12.0) > a > b
 => true
icr(0.12.0) > a == b
 => false
icr(0.12.0) > 1 + b < 1 + a
 => false
icr(0.12.0) > 1 + b == 1 + a
 => true
```
and even...
```crystal
icr(0.12.0) > (1.to_f64 + a.to_f64).to_f64 == (1.to_f64 + b.to_f64).to_f64
 => true
```
Out of Float64-memory?

**Comment by asterite** [comment]
That's the way floats work, they have a limited precision. If you add 1 to a very small float the result is 1, those decimal digitis way to the right don't fit in the representation.

Why is this blocking #2166 ?

**Comment by mverzilli** [comment]
Usually you end up having to define some comparison method that takes into account some sort of error tolerance. For example in Numpy they use:

http://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.isclose.html

Which we shamelessly stole in Crystalla: https://github.com/mverzilli/crystalla/blob/master/src/crystalla/comparisons.cr

**Comment by AlexWayfer** [comment]
@asterite Because writing precise tests for random of float-range with includes and excludes end-float (`rand(1.0..1.5)` and `rand(1.0...1.5)`) so hard :-) I tried to test with `rand(1.0..1.00000001)`. Okay, I will write it theoretical correct. Thanks.
