### ISSUE TITLE
Hashes with JSON::Any fails to to deserialize?

### ISSUE THREAD

**Issue by plukevdh** [manastech/crystal#2215]
This raises the following error: 

```crystal
require "json"

demo = "[{\"created_at\":1454961927000,\"id\":\"f9950bf1-8644-49a9-813a-a6543c91714e\",\"name\":\"library_public_api\",\"request_path\":\"/library\",\"strip_request_path\":true,\"upstream_url\":\"https://example.com/public_queries\"},{\"created_at\":1454447394000,\"id\":\"3a1aa4ff-edc1-48c9-82d1-4125bc9fbb46\",\"name\":\"products_docs\",\"request_path\":\"/docs/products\",\"strip_request_path\":true,\"upstream_url\":\"https://example.com/docs\"},{\"created_at\":1454102626000,\"id\":\"168d0fb3-cbe3-41da-a821-1dad41bafe06\",\"name\":\"products_admin_api\",\"request_path\":\"/admin/products\",\"strip_request_path\":true,\"upstream_url\":\"https://example.com/admin/products\"}]"
parsed = JSON.parse(demo).as_a

puts parsed.map(&.class)
# => [Hash(String, JSON::Type), Hash(String, JSON::Type), Hash(String, JSON::Type)]

puts parsed.map(&.nil?)
# => [false, false, false]

# This errors when I expect it to return an array of arrays 
# of the values of each Hash (which should be a JSON::Type),
# or in other words `Array(Array(JSON::Type))`
puts parsed.map(&.values)
```

```
Error in ./test.cr:15: undefined method 'values' for Nil (compile-time type is JSON::Type)

puts parsed.map(&.values)
                  ^~~~~~
```

There are no Nil values in the Hash and printing the Hash objects all return set values. Any idea why this is happening? The stack trace doesn't give me enough to see into the crystal runtime to understand why this is erroring.

**Comment by kirbyfan64** [comment]
In the `json/json.cr` source:

```crystal
module JSON
  ...
  # All valid JSON types
  alias Type = Nil | Bool | Int64 | Float64 | String | Array(Type) | Hash(String, Type)
end
```

**Comment by plukevdh** [comment]
@kirbyfan64 but I don't actually have any Nil type objects in the nested object...

**Comment by luislavena** [comment]
@plukevdh but `JSON::Type` is an alias that contains `Nil`, so it assumes `nil` is one of the possibilities, even when no value exist.

```crystal
a = [] of String | Nil
a.map &.size
```

```
Error in ./2.cr:2: undefined method 'size' for Nil (compile-time type is String?)

a.map &.size
        ^~~~
```

**Comment by asterite** [comment]
@plukevdh The method `.class` gives you the runtime type of something. Use [typeof](https://play.crystal-lang.org/#/r/sy0) to know the compile-time type. You can see it's `Array(JSON::Type)`.

Depending on what you need to do, we can give you an answer.

**Comment by asterite** [comment]
Maybe `to_a` and `to_h` should return an `Array(JSON::Any)` / `Hash(String, JSON::Any)` so they can be used more easily.

**Comment by plukevdh** [comment]
What I'm trying to get out of the array is `Array(Array(T))`, where T is the value of the leaf nodes, i.e. the values of `created_at`, `id`, etc, which will be differing types. Is this something a mapping can solve? I have no experience with mappings yet.

**Comment by plukevdh** [comment]
@luislavena that does help. I didn't realize it would make assumptions like that.

**Comment by asterite** [comment]
For your specific case, you can change the last line to:

```crystal
# Since `v` is a JSON::Any we need to cast it to the type we think sits there
puts parsed.map { |v| (v as Hash).values }
```

Alternatively, you can use [JSON.mapping](http://crystal-lang.org/api/JSON.html#mapping%28properties%2Cstrict%3Dfalse%29-macro), which should make these things much simpler to use, and I guess you could do that because those seem like ActiveRecord objects... or maybe Ember or a similar framework?

**Comment by plukevdh** [comment]
Ah okay, this works, I was trying to use `as_h` and getting the same nil errors. How does `as_<T>` differ from the `as Hash` casting?

**Comment by plukevdh** [comment]
@asterite it is a similar concept to AR models, I'm currently just fetching an external JSON api for parsing into `record`s

**Comment by asterite** [comment]
The method `as_h` is defined in `JSON::Any`, but in your case you had a `JSON::Type` which is just a union of some other types... and none of those define a `as_h` method.

If you can share the JSON "schema" of the objects you are dealing with, I can help with with your mapping and your code will be much easier to read/write and also faster :-)

**Comment by plukevdh** [comment]
The "schema" for a single object looks like:
```json
{
  "created_at":         1454961927000,
  "id":                 "f9950bf1-8644-49a9-813a-a6543c91714e",
  "name":               "library_public_api",
  "request_path":       "/library",
  "strip_request_path": true,
  "upstream_url":       "https://example.com/public_queries",
}
```

**Comment by asterite** [comment]
Then you can do something like [this](https://play.crystal-lang.org/#/r/szi).

I had to define a custom converter to go from millis to Time and back, maybe we can include such converter, and also for plain seconds, in the standard library.

Be sure to read the docs of JSON.mapping, if you have nilable properties (properties that might be missing in the JSON) you have to mark them as nilable.

**Comment by plukevdh** [comment]
Ah, that's pretty incredible. I really like that approach. Definitely works for my use-case as well. Many thanks @asterite
