### ISSUE TITLE
Referring to the self process

### ISSUE THREAD

**Issue by trizen** [manastech/crystal#2218]
I'm trying to implement the [Man or boy test](http://rosettacode.org/wiki/Man_or_boy_test) in Crystal, but I'm having some difficulties in telling the compiler that I want to refer to the self process in which I'm currently in.

Here is what I tried:
```crystal
def a(k, x1, x2, x3, x4, x5)
  b = ->() { k -= 1; a(k, b, x1, x2, x3, x4) }
  k <= 0 ? x4.call + x5.call : b.call
end

puts a(10, -> {1}, -> {-1}, -> {-1}, -> {1}, -> {0})
```

But, unfortunately, the code fails with the following error message:

```crystal
in ./mob.cr:3: undefined local variable or method 'b' (did you mean 'k'?)

  b = ->() { k -= 1; a(k, b, x1, x2, x3, x4) }
                          ^
```

Is there a special syntax, something like `__proc__` or alike, that can be used instead of variable `b` to refer to the current process?

**Comment by waterlink** [comment]
This code works if you create `b` variable before hand:

```crystal
def a(k, x1, x2, x3, x4, x5)
  b = uninitialized -> typeof(k)
  b = ->() { k -= 1; a(k, b, x1, x2, x3, x4) }
  k <= 0 ? x4.call + x5.call : b.call
end

puts a(10, -> {1}, -> {-1}, -> {-1}, -> {1}, -> {0})
```

see: https://carc.in/#/r/sym

**Comment by trizen** [comment]
It's good to know that this is possible. Thank you.

**Comment by asterite** [comment]
@waterlink Clever!

**Comment by ozra** [comment]
Neat indeed! :-)
Alternatively:
```crystal
def a(k T, x1, x2, x3, x4, x5)
  b = uninitialized -> T
  b = ->() { k -= 1; a(k, b, x1, x2, x3, x4) }
  k <= 0 ? x4.call + x5.call : b.call
end

puts a(10, -> {1}, -> {-1}, -> {-1}, -> {1}, -> {0})
```

**Comment by waterlink** [comment]
@ozra That is even better, when using  a type parameter. Watch out, you have a typo: `k T` => `k : T`. https://carc.in/#/r/t9r

**Comment by ozra** [comment]
Ah, didn't test it, sorry!
