### ISSUE TITLE
How to format float64 to_s?

### ISSUE THREAD

**Issue by raydf** [manastech/crystal#2220]
Hello:

In the next code

```
test = 9525365.25
puts test.to_s => 9.52537e+06
```

I would like to have a string with this format => "9525365.25"

**Comment by jhass** [comment]
Just use `String#%`:

```cr
test = 9525365.25
puts "%.2f" % test
```

https://carc.in/#/r/sz5

Please consider using StackOverflow for such questions, thanks!

**Comment by raydf** [comment]
Sorry for the misuse of the crystal github issues module. Thanks for your help.

**Comment by ysbaddaden** [comment]
I find the default Float#to_s to be rather annoying and I would love if it returned nice numbers when it can. Ruby does a better job here.

**Comment by asterite** [comment]
@ysbaddaden Me too. We just need to port [this](https://github.com/ruby/ruby/blob/trunk/util.c#L3090-L3795) from C to Crystal ;-)

**Comment by asterite** [comment]
Or we could just use it and have a wrapper for it.

**Comment by ysbaddaden** [comment]
I found an alternative to Dragon4: [Grisu3 by Florian Loitsch](http://www.cs.tufts.edu/~nr/cs257/archive/florian-loitsch/printf.pdf) which is expected to be faster yet correct in 99.5% of cases. It's apparently used in V8 and by Mozilla, and a C library is available: https://github.com/google/double-conversion
