### ISSUE TITLE
Block conversion breaks with foo yield

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#226]
I'm not sure if you intend this to be possible, but I think it would make sense.

Given
```ruby
class Foo
  def b
    with self yield
  end

  def foo
    "local"
  end
end
```

With `p Foo.new.b { foo }` we get `"local"` just as expected, but if we add a layer of indirection:

```ruby
def a(&block)
  Foo.new.b(&block)
end

p a { foo }
```

we get
```
Error in /home/jhass/projects/crystal/with.cr:18: undefined local variable or method 'foo'

p a { foo }
```

**Comment by asterite** [comment]
Block forwarding (having to use yield in these cases) is now explained in http://crystal-lang.org/docs/syntax_and_semantics/block_forwarding.html so I'll close this.
