### ISSUE TITLE
Can't deal with large array/tuple literals

### ISSUE THREAD

**Issue by Exilor** [manastech/crystal#256]
I was trying random stuff when I tried to write an array literal with all the numbers between Int16::MIN and Int16::MAX (65536 elements) and it turns out the compiler can't handle it. The "crystal" process slowly went up to ~700 mb and sat there indefinitely.
Then, I tried using a tuple with the same contents instead and my computer's RAM went up to 12 gb (out of 16) and I had to shut it down.
Next I switched back to an array and removed half of the elements and after 5 minutes it still didn't finish.
Then I removed about half of the elements again (bringing the array down to a size of 14.604) and it finished building after 15 seconds.
I switched back to a tuple with the same 14.604 elements and it took 16 seconds of building using 4.8 gb of RAM.

I assume this has to do with how the compiler deals with array/tuple literals because doing this:
```ruby
nums = [] of Int16
(Int16::MIN..Int16::MAX).each do |n|
  nums << n
end
```
takes like 0.1 seconds and the size of the resulting array is the same.

**Comment by asterite** [comment]
I'll close this. I don't know what real-life program will have such big array literals or tuples. Const arrays are another discussion.
