### ISSUE TITLE
Building with debug info fails

### ISSUE THREAD

**Issue by jtomschroeder** [manastech/crystal#257]
Building with `debug` turned on causes the build to fail:

    $> crystal build -d samples/hello_world.cr 
    Assertion failed: (GV.isGlobalVariable()), function createGlobalVariableDIE, file DwarfUnit.cpp, line 1561.
    Assertion failed: (GV.isGlobalVariable()), function createGlobalVariableDIE, file DwarfUnit.cpp, line 1561.
    Assertion failed: (GV.isGlobalVariable()), function createGlobalVariableDIE, file DwarfUnit.cpp, line 1561.
    ...
    ld: file too small (length=0) file 'hello_world.cr/main.o' for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by asterite** [comment]
It seems the metadata that we need to generate for LLVM 3.5 is a bit different than for 3.3, and that is one of the reason that it might be failing.

**Comment by waj** [comment]
The debug support is still really minimal and unusable. I'll start working on this soon, but at least now the "--debug" flag seems to work fine. Small programs seems can be run step by step using lldb.
