### ISSUE TITLE
Immutability

### ISSUE THREAD

**Issue by keleshev** [manastech/crystal#263]
I was wondering, what is your take on mutability vs. immutability for Crystal? Do you think it would be sensible to default to immutable strings, arrays and maps?

**Comment by asterite** [comment]
We can always have an `inmmutable datastructures` library if you want to.

So I'll close this.

**Comment by opensas** [comment]
I also think that having immutable collections as default would imply a far too drastic change for Crystal, but I really like the idea of having immutable collections in the standard library.
This shard: https://github.com/lucaong/immutable could be a fine starting point.
Moreover, something easier than `Immutable::Vector[1, 2, 3, 4, 5]` to define immutable structures would be welcome, perhaps a method call or a sufix, like this:
```crystal
[1, 2, 3, 4, 5].to_im
[1, 2, 3, 4, 5]_im
```
