### ISSUE TITLE
A "namespace" feature proposal

### ISSUE THREAD

**Issue by 907th** [manastech/crystal#265]
I want to know your opinion about introducing a "namespace" feature. It is better to describe it by code example (because I'm not so good in English):

Use namespace:

```ruby
# models/payment.rb
class Payment < Parent
end

# services/payment/some_service.rb
namespace Payment  # I don't use a full declaration of the Payment here
  class SomeService
  end
end
```

Instead of:

```ruby
# models/payment.rb
class Payment < Parent
end

# services/payment/some_service.rb
class Payment < Parent  # WTF? I don't want to redeclare the Payment class again and again!
  class SomeService
  end
end
```

So, using a `namespace` is just like saying: hey, put a full declaration of that const right here.
I think it could be implemented using macros, am I right?

Thank you! Cool project!

**Comment by asterite** [comment]
I'll close this for now, reopening types works as expected and there's no need to redeclare the supertype.

**Comment by 907th** [comment]
@asterite Ok. But does Crystal supports const-autoloading/const_missing?

I just want you to understand what the proposal is. There is difference between 'opening a class the first time' (aka class declaration/creation/etc) and 'reopening class'. If your language supports const autoloading you will never be sure in which order classes are loaded. So you will never be sure what happens first - class declaration or class reopening. If the reopening happens first and you don't declared the class' supertype - you will actually declare a new class with wrong inheritance information. PS. Yes, `crystal` is compiling language, so your program will just not compile in such cases, but the issue is the hell in Ruby/Rails.
