### ISSUE TITLE
On Crystal Generics

### ISSUE THREAD

**Issue by scidom** [manastech/crystal#268]
While working with struct/class generics, a few language questions on generics arose and I would like to hear what are your thoughts on them. To follow through, I will use a naive example.

1 ) The first question is this; assume you want to define an elementary `Dimensions` "parameter", which will be used as a generic parameter or as part of class hierarchy. I have 2 ways in mind to get this done:

Way 1.A (using subclasses):

```
abstract struct Dimensions
end

abstract struct TwoDimensional < Dimensions
end

abstract struct ThreeDimensional < Dimensions
end
```

Way 1.B (using type unions):

```
abstract struct TwoDimensional
end

abstract struct ThreeDimensional
end

alias Dimensions = TwoDimensional | ThreeDimensional
```

Is one of 1.A, 1.B considered better than the other in some respect?

2) Let's say now that we want to define a `Shape` struct parametrized by the shape's dimension. Is one of the following 2 approaches preferred over the other?

Way 2.A (using subclasses, `Dimensions` not used):

```
abstract struct Shape
end

abstract struct TwoDimShape < Shape
end

abstract struct ThreeDimShape < Shape
end

struct Circle < TwoDimShape
end
```

Way 2.B (using generics, `Dimensions` is the parameter-generic):

```
abstract struct Shape(D)
end

struct Circle < Shape(TwoDimensional)
end
```

3) In the case of 2.B, the following happens with generics:

```
shape = Circle.new
shape.is_a?(Shape) # returns true
shape.is_a?(Shape(TwoDimensional)) # returns false
```

Why `shape.is_a?(Shape(TwoDimensional))` returns `false` instead of `true`?

4) Would it be useful to make it possible to restrict the type of a generic? I have in mind sth along the lines

```
abstract struct Shape(D : Dimensions)
end
```

Sorry for the long discussion-issue, I hope that the above splitting into numbered sections allows the questions to be clearer.

**Comment by asterite** [comment]
I'll close this issue. I think all the questions have been answered. If you want to add ADTs to crystal please send a feature request (with a detailed proposal), but I think module inclusion / subclasses work well right now.
