### ISSUE TITLE
case enum

### ISSUE THREAD

**Issue by asterite** [manastech/crystal#285]
We have enums and you can use `case` with them:

```crystal
enum Color
  Red
  Green
  Blue
end

color = Color::Red
a = case color
    when Color::Red
      1
    when Color::Green
      2
    when Color::Blue
      3
    end
```

Enums are great because, unlike symbols, they are type-safe. They are like a group of limited and documented symbols. You can't accidentally misspell them. And you can use them as restrictions.

However, the above `case` has a few issues:

1. You have to repeat the enum's name in every branch.
2. `a`'s type is nilable, because there's an implicit `else` part with `nil`. Ideally the compiler should be smart and know there are no other possible values. This is partly because the compiler [blindly](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/semantic/normalizer.cr#L364) transforms the `case` into a series of `if-elseif`, but also, because of how our type inference works, `color` might eventually get another type.
3. There's no way to say that we want to cover all cases and, later, when we add another enum value, let the compiler know that we want a compiler error until we cover all cases again. This would be somewhat similar to [D's final switch](http://ddili.org/ders/d.en/switch_case.html#ix_switch_case.final%20switch).

I'm thinking about having something like this:

```crystal
# But with a less ugly syntax...
case color as enum Color
when Red
  ...
when Green
  ...
when Blue
  ...
end
```

Possibly with a modifier to make it `final`.

**Comment by asterite** [comment]
Now that we added enum query methods, it can be done like this:

```crystal
color = Color::Red
a = case color
    when .red?
      1
    when .green?
      2
    when .blue?
      3
    end
```

**Comment by timjs** [comment]
Could this be documented? The [book](https://crystal-lang.org/docs/syntax_and_semantics/enum.html) shows an example like this, but there isn't a clue that this is automatically derived.

Also, after this discussion I'd expect an compile error, but running this code compiles fine and prints `1 : (Int32 | Nil)` on Crystal v0.22.0.

```crystal
enum Color
  Red
  Green
  Blue
end

color = Color::Red
x = case color
  when .red?
    1
  when .green?
    2
  end

printf("%s : %s\n", x, typeof(x))
```

(Related: #1846)
