### ISSUE TITLE
Feature request: typed splats

### ISSUE THREAD

**Issue by sferik** [manastech/crystal#291]
I would like to be able to define the following methods:

```crystal
# Fetch multiple users by their IDs
def find_users(*ids : Int32)
end

# Fetch multiple users by their usernames
def find_users(*usernames : String)
end
```

such that:

```crystal
find_users(1, 2, 3) # dispatches to the first version of the method
find_users("erik") # dispatches to the second version of the method
find_users(1, "erik") # error: no overload matches 'find_users' with types Int32, String
```

Essentially, I want the ability to define a method with an *arbitrary number* of parameters of a *specific type*. Of course, this is possible with an array but it should be possible to invoke the method without square braces (e.g. `find_users([1, 2, 3])`).

Basically, I’d like a splat of type T to be syntactic sugar for Array(T) when it appears as a parameter in a method definition? Do you think that would be possible?

**Comment by asterite** [comment]
I'm reopening becuase we'll probably finally implement this

**Comment by sferik** [comment]
\o/

**Comment by vendethiel** [comment]
:+1: sounds really good :-).

**Comment by asterite** [comment]
Oh, with this I (initially) mean that you'll be able to put a type restriction, not to have overloaded splats. We have to think a bit more about the overload case, specially because of the empty-tuple case.

**Comment by asterite** [comment]
On second thought, I think we can also implement typed splats. In fact I have this in a stash :-)

The idea would be that typed splats don't match empty tuples. For the empty-tuple case use another overload. So:

```crystal
# Fetch multiple users by their IDs. Requires at least one ID.
def find_users(*ids : Int32)
end

# Fetch multiple users by their usernames. Requires as least one username.
def find_users(*usernames : String)
end

# Maybe return all of them? (just for demo)
def find_users
end

find_users(1, 2, 3)       # matches first
find_users("a", "b", "c") # matches second
first_users               # matches third
```

Of course, without the third overload the last call would give a compile-time error.

[Multi-dispatch over tuple types](https://github.com/manastech/crystal/issues/223) is still a different issue, so implementing this won't magically make #223 work (but in the future it might).

Thoughts?

**Comment by sferik** [comment]
\o/

**Comment by vendethiel** [comment]
Great :).
