### ISSUE TITLE
Linker system call quickly exceeeds MAX_ARG_STRLEN

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#300]
There's a limit on how many bytes a single argument to a program can be.

The linker command uses the `system` method to link<sup>[1]</sup>.

The system method invokes `Process.run` with `"/bin/sh", "-c", "argument_passed_to_system"`<sup>[2]</sup>. In case of the linker call, the last parameter can become very large.

`Process.run` uses `execvp` to run the command<sup>[3]</sup>, from exec(3):

>  Special semantics for execlp() and execvp()
>       The execlp(), execvp(), and execvpe() functions duplicate the actions of the shell in searching for an executable file if the specified filename does not con‐
       tain a slash (/) character.  The file is sought in the colon-separated list of directory pathnames specified in the PATH environment variable.  If this  vari‐
       able  isn't defined, the path list defaults to the current directory followed by the list of directories returned by confstr(_CS_PATH).  (This confstr(3) call
       typically returns the value "/bin:/usr/bin".)

Given the above I would suggest to add an overload of system that accepts a command and an array or tuple of strings as arguments and that overload to not call /bin/sh. Then change the linker invocation to use that overload.

To reproduce the issue, simply call `make spec` in a sufficiently deeply nested path, for me ` /home/jhass/projects/PKGBUILDs/crystal/src/crystal-0.5.4` was enough.

On a side node [this](https://github.com/manastech/crystal/blob/master/src/process/run.cr#L40) is broken, at least on Linux. The `C.exit(127)` does not cause a pid of `-1` or at least the `errno` is not available in the parent, hiding important details about the failure.

I think this is a rather critical issue, and I'd appreciate a 0.5.5 or 0.5.4.1 shortly :)

[1]: https://github.com/manastech/crystal/blob/master/src/compiler/crystal/compiler.cr#L154
[2]: https://github.com/manastech/crystal/blob/master/src/process/run.cr#L126
[3]: https://github.com/manastech/crystal/blob/master/src/process/run.cr#L36

**Comment by jhass** [comment]
acf482979977cded1dfc6ac26ad9618806bd6c44 reintroduced this.

**Comment by asterite** [comment]
@jhass Does https://github.com/manastech/crystal/commit/df716ad2e53e646ffa9b4b79da2de5f9252b208d fix it?

**Comment by jhass** [comment]
Mmmh, nope, it's the linker invocation, not launching the compiled binary.

**Comment by asterite** [comment]
Oh, I see!

So I broke `system`?

But if we do `Process.run(long_command, shell: true)` that might break too, right?

What would the best solution be? I'm thinking of splitting `long_command` into pieces and sending those to `execpv`. We can do this conditionally based on `long_command.length`.

@waj @technorama ideas?

**Comment by jhass** [comment]
I think we can do with less magic, accept `command` and `arguments`, if `shell: true` prepend `"-c"`, `command`, `"\"${@}\"` and `"--"` to `arguments`, then replace `command` with `/bin/sh`. That is invoke `/bin/sh -c 'foo "${@}" -- a b c d`.

**Comment by asterite** [comment]
Would be nice to have a regression spec for this too, so I don't break it next time.

**Comment by jhass** [comment]
Been thinking about this, but hard to do. If my last comment works, the bug is in the `system`/`Process.run` invocation, since it would still fail on `system(very_long_command)` and the proper usage for these would be `Process.run(command, arguments, shell: true)`

**Comment by jhass** [comment]
@asterite I propose the following patch to fix this for good:

```diff
diff --git a/src/compiler/crystal/compiler.cr b/src/compiler/crystal/compiler.cr
index 05dd7ea..fb0912c 100644
--- a/src/compiler/crystal/compiler.cr
+++ b/src/compiler/crystal/compiler.cr
@@ -213,8 +213,9 @@ module Crystal
       end
 
       timing("Codegen (clang)") do
-        quoted_object_names = object_names.map { |name| %("#{name}") }.join " "
-        system "#{CC} -o #{output_filename} #{quoted_object_names} #{@link_flags} #{lib_flags}"
+        arguments = ["-c", "#{CC} \"${@}\" #{@link_flags} #{lib_flags}", "--", "-o", output_filename]
+        arguments.concat object_names
+        Process.run "/bin/sh", arguments, output: true
       end
     end
 ```

Would be awesome to have a solution asap.

Furthermore I propose to change the `shell: true` interface to something like:

```diff
diff --git a/src/process/run.cr b/src/process/run.cr
index 8085c84..8fcb59b 100644
--- a/src/process/run.cr
+++ b/src/process/run.cr
@@ -56,17 +56,23 @@ class Process
   #
   # By default the process is configured without input, output or error.
   def initialize(command : String, args = nil, env = nil : Env, clear_env = false : Bool, shell = false : Bool, input = false : Stdio, output = false : Stdio, error = false : Stdio, chdir = nil : String?)
-    cmd, argv = if shell
-      raise "args not allowed with shell" if args
-      {"/bin/sh", ["/bin/sh".to_unsafe, "-c".to_unsafe, command.to_unsafe, Pointer(UInt8).null]}
-    else
-      a = [command.to_unsafe]
-      args.try &.each do |arg|
-        a << arg.to_unsafe
+    if shell
+      if command.includes?(' ')
+        raise ArgumentError.new("can't specify arguments in both, the command and `args`") if args
+        new_args = ["-c", command, "--"]
+      else
+        new_args = ["-c", "#{command} \"${@}\"", "--"]
+        new_args.concat(args) if args
       end
-      a << Pointer(UInt8).null
-      {command, a}
+      command = "/bin/sh"
+      args = new_args
+    end
+
+    argv = [command.to_unsafe]
+    args.try &.each do |arg|
+      argv << arg.to_unsafe
     end
+    argv << Pointer(UInt8).null
 
     @wait_count = 0
 
@@ -119,7 +125,7 @@ class Process
 
         Dir.chdir(chdir) if chdir
 
-        LibC.execvp(cmd, argv)
+        LibC.execvp(command, argv)
       rescue ex
         ex.inspect(STDERR)
         STDERR.flush
```

Would be nice to know if that's acceptable before I make it PR ready.

**Comment by technorama** [comment]
This is a very rare case that's probably only applicable to a compiler with lots of arguments that MAY have shell commands embedded.

My solution was going to be:
```
compiler_files = ...
expanded_linker_flags = linker_flags.map do |f|
  if f =~ /`/
    f = `echo #{f}`.split
    raise unless $?.success? 
  end
  f
end
argv = compiler_files + expanded_linker_flags.flatten
run(linker_cmd, argv) # no shell
```

The current code has very weak shell escaping of file names and may break if someone gets creative with a filename.


@asterite splitting a long command would require knowledge of where splitting is safe.
Where can this be split: \ \" ' ` " \' \' " ` ' \"?

**Comment by asterite** [comment]
For now I fixed the linker command. It basically does what the old "system" did. @jhass This should fix the problem, right?

Yesterday I changed the implementation of system and backtick because I tried these programs in Ruby:

```ruby
value = `cat`
p value
```

```ruby
value = system("cat")
p value
```

In both programs the input is inherited, so you can write to `cat`, and when you ctrl+D, in the case of the backtick, you get the output. This didn't work in the previous implementation because we specified to pipe the input and used it to send the command to "/bin/sh". This new implementation makes it work like in Ruby (and I think it's the correct behaviour).

Finally, I agree with @technorama: the cases where a system/backtick call is long is pretty rare, maybe only in compilers. And in those cases we don't need to inherit the input so we can do Process.run manually.

We can document this MAX_ARG_STRLEN limitation in both system and backtick, showing an alternative solution that doesn't have this limitation.

**Comment by jhass** [comment]
Yes, but I consider something like #1293 the proper solution.
