### ISSUE TITLE
New command line option for error checking

### ISSUE THREAD

**Issue by yaskhan** [manastech/crystal#308]
How about new command line option for error checking?
```--check```	checks the project for syntax and semantic

**Comment by asterite** [comment]
@yaskhan Right now you can do:

```
crystal build file.cr --no-build
```

That basically does parse + type check but doesn't generate an executable.

Because "build no-build" sounds strange, we just renamed "--no-build" to "--no-codegen", so (starting from the next version) doing:

```
crystal build file.cr --no-codegen
```

should be enough for your needs in this issue.
