### ISSUE TITLE
Understanding how Crystal arrays work (in comparison to Ruby ones)

### ISSUE THREAD

**Issue by scidom** [manastech/crystal#312]
I am looking at the Crystal code array in src/array.cr, comparing it with [this Ruby documentation](http://www.ruby-doc.org/core-2.1.5/Array.html), trying to learn and understand how Crystal arrays are implemented, particularly how they are initialized and allocated. A few relevant questions follow:

1) What is the difference between `@length` and `@capacity` members? The `initialize(initial_capacity = 3 : Int)` initializer sets length to 0, so does this mean that the array is then expanded every time a new item is pushed to it? Does this cause a performance penalty in comparison to the `initialize(size, value : T)` method for example?

2) How/when is memory (dedicated to arrays or tuples) freed by the garbage collector?

3) Typing `puts Array.new(3)` in Ruby returns `[nil, nil, nil]`, while typing `puts Array(Float64).new(3)` in Crystal returns `[]`. What is the most efficient way in Crystal to allocate memory for an array of say 3 uninitialized float64 elements?

**Comment by asterite** [comment]
I'll close this, the question was answered (I believe) :-)

**Comment by codenoid** [comment]
```
open = {} of String => String # < ? pwiz your correction 
open["f"] = "fa" 
open["f"]["a"] = "noob"
puts open["f"]["a"]
```
