### ISSUE TITLE
Implied Hash for trailing arguments with `=>`

### ISSUE THREAD

**Issue by trans** [manastech/crystal#322]
Noticed that Crystal can't handle trailing Hash entries in method calls like Ruby. E.g.

```ruby
    foo "a" => "x", "b" => "y", "c" => "z"
```

has to be written:

```ruby
    foo { "a" => "x", "b" => "y", "c" => "z" }
```

Can Crystal support the implicit Hash argument like Ruby? This feature is really nice for writing cleaner looking code in many places.

**Comment by blaix** [comment]
I'm very happy with crystal's decision not to support this. For the cases where you want to pass a hash as options to a method, it would be better to just use keyword arguments. And for the cases where you want to pass a hash as an object to a method, I would prefer to see the wrapping `{` `}`. It all works together to make it very clear what is intended and subtly enforce better method design in my opinion.

**Comment by trans** [comment]
@blaix That's fine if you know before hand what the keywords are. The problem is with DSLs where the user needs to provided arbitrary key-value pairs. Having to use `{` `}` adds "noise" to code making it harder to read. In fact,the lack of this noise, is probably the main reason why Ruby is so favored for DSLs.

**Comment by waterlink** [comment]
@trans You need to check out macros system, it allows to make great DSLs. Even much better than arbitrary key-value pairs ;)

**Comment by asterite** [comment]
I'll close this, we actually like to see an explicit Hash instantiation there, and to discourage using a Hash as keyword arguments (it's very inefficient).

**Comment by trans** [comment]
@waterlink Can you direct me to any tutorials for this?
