### ISSUE TITLE
crystal build from sources fails

### ISSUE THREAD

**Issue by ealmansi** [manastech/crystal#325]
after installing on ubuntu per the instructions given in [1], I tried to build from sources following [2] but the build fails right away. here is the error I'm getting: http://pastebin.com/N4MyHyzx
I'm running Ubuntu 14.10.

[1] http://crystal-lang.org/docs/installation/on_debian_and_ubuntu.html
[2] http://crystal-lang.org/docs/installation/from_source_repository.html

**Comment by ealmansi** [comment]
ok, this fixed the problem for me (on Ubuntu 14.10):
$ sudo apt-get install libgc-dev libpcre3-dev libunwind8-dev
thank you

**Comment by asterite** [comment]
Buenísimo! Feliz año nuevo! :-)
