### ISSUE TITLE
Cannot raise inside threads

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#336]
```ruby
Thread.new do
  raise Exception.new
end.join
```
```
$ ./test
Could not raise
$ echo $?
5
```

**Comment by asterite** [comment]
Oh! When in IRC you asked me about "can I raise inside a Thread" I totally forgot that this error happens.

I checked Ruby. If you raise inside a Thread but don't do join, you never find out (unless you rescue inside the Thread). If you join, any uncaught exception will be raised at that moment.

We can do it with this patch:

```diff
diff --git a/src/thread/thread.cr b/src/thread/thread.cr
index 5a17442..95b610e 100644
--- a/src/thread/thread.cr
+++ b/src/thread/thread.cr
@@ -15,11 +15,20 @@ class Thread(T, R)
 
   def join
     PThread.join(@th, out ret)
+
+    if exception = @exception
+      raise exception
+    end
+
     (ret as R*).value
   end
 
   protected def start
-    ret = Pointer(R).malloc_one(@func.call(@arg))
-    PThread.exit(ret as Void*)
+    begin
+      ret = Pointer(R).malloc_one(@func.call(@arg))
+      PThread.exit(ret as Void*)
+    rescue ex
+      @exception = ex
+    end
   end
 end
```

This works and makes the `Could not raise` error go away.

Then there's also `abort_on_exception` control in Ruby, but we can think that later.

What do you think? Should we copy Ruby's semantic here?

/cc @waj

**Comment by jhass** [comment]
Yes, let's copy the semantic until we find a reason not to ;)
