### ISSUE TITLE
Process.run should support stderr

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#345]
Process.run should provide the same semantics for stderr that are provided for stdout.

As an extra feature one could imagine that when passing `stderr: :output`, the stderr contents would be written to whatever output is pointed to.

**Comment by asterite** [comment]
Definitely!

**Comment by asterite** [comment]
@jhass Thank you, as always. We finally could implement it the way that we imagined it would be: https://github.com/manastech/crystal/commit/bbf2036d49a7b7d245852330c3697d73ff6fc2d9
