### ISSUE TITLE
Heredoc is not respected in line number calculation

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#346]
```ruby
foo = <<-DOC
a
b
c
DOC

pretending_to_be_dumb
```
```
Error in /home/jhass/projects/crystal/foo.cr:3: undefined local variable or method 'pretending_to_be_dumb'

b
^~~~~~~~~~~~~~~~~~~~~

```

Notice how Crystal thinks the error is in line 3 while it's in line 7, 4 lines added by the heredoc are not counted.

**Comment by asterite** [comment]
I'd actually like to remove heredocs from the language. Strings are already multiline and there are many ways to write them.

**Comment by asterite** [comment]
Well, heredoc is not that bad, actually. :-)

I'm just not sure we should support interpolations inside it, like in Ruby.
