### ISSUE TITLE
calling Exception#class produces a segfaulting binary

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#347]
```ruby
begin
  raise Exception.new
rescue e
  puts "#{e.class}"
end
```
```
$ crystal build tmp.cr
$ ./tmp
[1]    16583 segmentation fault (core dumped)  ./tmp
```

**Comment by asterite** [comment]
Yes! This is important and we must fix it. Another case:

```crystal
class Foo
end

class Bar < Foo
end

puts (Foo.new || Bar.new).class
```

Basically, for a type `Foo+` (in the first case, `Exception+`) we can't print its class because we don't store a class name at runtime. We need to change the way its currently done.

**Comment by asterite** [comment]
Not anymore :-)

**Comment by ysbaddaden** [comment]
great :+1:
