### ISSUE TITLE
Segmentation fault with threads on Linux 64bits

### ISSUE THREAD

**Issue by ysbaddaden** [manastech/crystal#352]
Since the change introduced in 57fa0baf626babab2b2fcb4111ca4daea356e26a (raise in threads) any attempt to join a thread on Ubuntu Trusty 64bits will segfault. The culprit is the `rescue ex` line at https://github.com/manastech/crystal/blob/master/src/thread/thread.cr#L30. If I comment it out, then threads no longer segfault.

I compiled the spec and run it through GDB:

```
Starting program: /home/github/crystal/thread_spec 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff6d0a700 (LWP 13610)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6d0a700 (LWP 13610)]
0x0000000000416b16 in *LEBReader#read_uint8<LEBReader>:UInt8 ()
```

**Comment by asterite** [comment]
Strange. I have an Ubuntu Trusty 64 bits VM.

```
$ uname -a
Linux vagrant-ubuntu-trusty-64 3.13.0-40-generic #69-Ubuntu SMP Thu Nov 13 17:53:56 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
$ bin/crystal --version
Crystal 0.5.8 [14c27e2] (Fri Jan 16 20:33:12 UTC 2015)
$ bin/crystal spec/std/thread_spec.cr 
...*

Pending:
  ConditionVariable waits and send signal

Finished in 00:00:00.0024410
4 examples, 0 failures, 0 errors, 1 pending
```

Are you with 0.5.7 or 0.5.8?

**Comment by ysbaddaden** [comment]
I'm on the master branch, using a compiled crystal:

```
$ uname -a
Linux xps 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

$ bin/crystal --version
Using compiled compiler at .build/crystal
Crystal 0.5.8 [1659435] (Mon Jan 26 14:19:10 UTC 2015)

$ bin/crystal spec/std/thread_spec.cr 
Using compiled compiler at .build/crystal
Segmentation fault (core dumped)
Program terminated abnormally with error code: 35584
```

Here is the backtrace for a basic `Thread.new {}.join` program (against current master):
![screenshot1](https://cloud.githubusercontent.com/assets/47380/5901421/be9ebd46-a572-11e4-8974-f7cfebc7ef67.png)

Using 0.5.8, I get the "Could not raise" message (since it uses 0.5.8's `src/thread.cr`).
