### ISSUE TITLE
More liberal %-literals

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#356]
Currently Crystals percent literals must use simple parenthesis as delimiter. I think adding `[]` and `{}` to that would be a good addition.

Ruby is very liberal:

> If you are using “(”, “[”, “{”, “<” you must close it with “)”, “]”, “}”, “>” respectively. You may use most other non-alphanumeric characters for percent string delimiters such as “%”, “|”, “^”, etc.

http://ruby-doc.org/core-2.2.0/doc/syntax/literals_rdoc.html#label-Percent+Strings

**Comment by zamith** [comment]
@jhass As discussed with @asterite, added support for more delimiters. Not quite as liberal as ruby, but good enough for most use cases.

**Comment by jhass** [comment]
Thanks @zamith
