### ISSUE TITLE
Recursive alias hangs compiler

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#359]
```ruby
class A
end

class B
end

alias D = A
alias D = D|B
```

Should probably error out. Or maybe we want it to even work?

**Comment by asterite** [comment]
It should give an error saying "D is already defined" (in `alias D = D|B`) and, without the previous line it should say something like "Recursive definition of D"

**Comment by asterite** [comment]
On a sidenote, should we rename `C` to `LibC`? I always forget to skip C and I get the `C is a lib` error :-P

**Comment by jhass** [comment]
Yeah me too. I think that would actually be a good move since it's also more consistent with the other bindings. And should only be a simple sed away.
