### ISSUE TITLE
Surprise with parallel assignment and operator

### ISSUE THREAD

**Issue by Exilor** [manastech/crystal#364]
```ruby
x = 1
y = 1
x, y += 1, 1
x #=> 2
y #=> 1
```
Shouldn't ```x``` and ```y``` be both ```2```?
```crystal browser``` shows this:
```ruby
x = 1
y = 1
__temp_159 = y + 1
__temp_160 = 1
x = __temp_159
y = __temp_160
```
And I expected it to be this:
```ruby
x = 1
y = 1
__temp_159 = x + 1
__temp_160 = y + 1
x = __temp_159
y = __temp_160
```
Is this expected and intended?

**Comment by asterite** [comment]
Nice find :-)

That should give a syntax error. At least in Ruby it's like that.

**Comment by Exilor** [comment]
Yes, Ruby does gives an error. But it wouldn't it be cool if it worked as you'd expect at first glance? :)

**Comment by zamith** [comment]
This is code that will confuse anyone else reading your code very fast. I think raising an error is good in this case.

Destructuring assignments should be used with extreme caution, "destructuring operations" seems a bit too much for me.
