### ISSUE TITLE
/samples/sdl/fire.cr compiler error

### ISSUE THREAD

**Issue by weskinner** [manastech/crystal#381]
When I try to compile the sdl "fire.cr" sample I get the following compiler error:

william@ubuntu:~/Downloads/crystal-0.5.8/samples/sdl$ crystal run --link-flags -lSDL fire.cr
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 0 has invalid symbol index 11
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 1 has invalid symbol index 12
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 2 has invalid symbol index 2
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 3 has invalid symbol index 2
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 4 has invalid symbol index 11
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 5 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 6 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 7 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 8 has invalid symbol index 12
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 9 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 10 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 11 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 12 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 13 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 14 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 15 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 16 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 17 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 18 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 19 has invalid symbol index 21
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_line): relocation 0 has invalid symbol index 2
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o /tmp/crystal-run-fire.ZYGacD .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/main.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/CFileIO.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Pointer40Pointer40UInt84141.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Slice40T41.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Slice40Pointer40UInt84141.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Array40String41.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/GC.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Math.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Pointer40String41.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/ArgumentError.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Pointer40UInt6441.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Pointer40ABI5858UnwindException41.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/UInt64.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Pointer40UInt841.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/String.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/StringIO.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Slice40UInt841.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/IndexOutOfBounds.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/DivisionByZero.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/StaticArray40UInt844322241.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Exception.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Int32.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/YellowColorPattern.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/MagentaColorPattern.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/CyanColorPattern.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Array40ColorPattern4341.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Pointer40ColorPattern4341.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/RainbowColorPattern.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Array40MainPoint41.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Pointer40MainPoint41.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Float64.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/MainPoint.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Points.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Array40Point4341.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Pointer40Point4341.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/SDL.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Pointer40LibSDL5858Surface41.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/SDL5858Surface.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Screen.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Array40T41.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Array40UInt3241.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/StaticArray40UInt844321241.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Pointer40UInt3241.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/File.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Array40Rectangle41.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Pointer40Rectangle41.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/CharReader.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Bool.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Char.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Errno.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Rectangle.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Array40Bool41.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Pointer40Bool41.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/UInt8.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/UInt32.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/StaticArray40UInt84432441.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/AtExitHandlers.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Exception43.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Process.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/LibSDL5858Key.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Point43.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/ColorPattern43.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/Point.o .crystal//home/william/Downloads/crystal-0.5.8/samples/sdl/fire.cr/LEBReader.o -lSDL  -lpcre -lm -lgc -lpthread -lunwind`

**Comment by ysbaddaden** [comment]
The following patch fixes the problem on Linux:

```diff
diff --git a/samples/sdl/sdl/lib_sdl.cr b/samples/sdl/sdl/lib_sdl.cr
index 4051901..19564ca 100644
--- a/samples/sdl/sdl/lib_sdl.cr
+++ b/samples/sdl/sdl/lib_sdl.cr
@@ -144,10 +144,15 @@ lib LibSDL
   fun show_cursor = SDL_ShowCursor(toggle : Int32) : Int32
   fun get_ticks = SDL_GetTicks : UInt32
   fun flip = SDL_Flip(screen : Surface*) : Int32
+  fun main = SDL_main(argc : Int32, argv : UInt8*) : Int32
 end
 
-undef main
+#undef main
 
-redefine_main(SDL_main) do |main|
-  {{main}}
+fun main(argc : Int32, argv : UInt8*)
+  return LibSDL.main(argc, argv)
 end
+
+#redefine_main(SDL_main) do |main|
+#  {{main}}
+#end
```

The `main` symbol is undefined (at this point), and thus can't be undefined or redefined.

**Comment by weskinner** [comment]
Thanks you @ysbaddaden.  That worked! Can you explain why I have to compile with the --link-flags options like:

```
crystal build  --link-flags -lSDL fire.cr
```

when 

```
 @[Link("SDL")]
  @[Link("SDLMain")]
  @[Link(framework: "Cocoa")] ifdef darwin
  lib LibSDL
```

is already telling the linker about these libraries?

**Comment by ysbaddaden** [comment]
I have the same problem on Linux too. The `-lSDL` isn't automatically added to the `cc` command. That may have something to do with calls to `pkg-config`.

I don't know enough of the internals to know better. That may be a good opportunity to dig in!

**Comment by weskinner** [comment]
So after a bit of digging I see how Crystal is building the link flags:
https://github.com/manastech/crystal/blob/master/src/compiler/crystal/codegen/link.cr#L16
```
def lib_flags
      library_path = ["/usr/lib", "/usr/local/lib"]
      has_pkg_config = nil

      String.build do |flags|
        link_attributes.reverse_each do |attr|
          if ldflags = attr.ldflags
            flags << " " << ldflags
          end

          if libname = attr.lib
            if has_pkg_config.nil?
              has_pkg_config = Process.run("which", {"pkg-config"}, output: false).success?
            end

            if has_pkg_config && (libflags = pkg_config_flags(libname, attr.static?, library_path))
              flags << " " << libflags
            elsif attr.static? && (static_lib = find_static_lib(libname, library_path))
              flags << " " << static_lib
            else
              flags << " -l" << libname
            end
          end

          if framework = attr.framework 
            flags << " -framework " << framework
          end
        end
      end
    end
```

it should be following the `if has_pkg_config && (libflags = pkg_config_flags(libname, attr.static?, library_path))` but doesn't seem to be.  

Any ideas how to debug the compiler? I guess I'll just rebuild with `puts` statements

@asterite can you chime in on this?

**Comment by asterite** [comment]
@weskinner Sure. As you can see the fix was trivial, just a couple of lines added.

The logic for how attributes are attached to nodes is [here](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/semantic/type_inference.cr) (where pretty much everything happens). The AST nodes of the programs are traversed. When an attribute is found it is [added to a list](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/semantic/type_inference.cr#L102). Then when a node, like a lib, comes, those attributes are [attached to it](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/semantic/type_inference.cr#L1465). Of course, the attributes list must be cleared at some point. We do that [after visiting an AST node](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/semantic/type_inference.cr#L108), but only in some cases, as you can see in the logic. But, there was missing the Nop case: a Nop means "nothing", and it can be an empty if branch, ifdef branch, an empty def, etc. The SDL code had an `ifdef darwin` with an empty else branch (Nop), so it was that case and the link attributes were cleared.

Of course the fix was easy because I knew where to look. From time to time I document the compiler internals [here](https://github.com/manastech/crystal/wiki/Compiler-internals), so hopefully one day all those details will be clear to everyone wanting to contribute :-)

**Comment by weskinner** [comment]
Thanks for the thorough explanation @asterite.  It all makes sense.
