### ISSUE TITLE
Can't call divisions with the dot syntax

### ISSUE THREAD

**Issue by zamith** [manastech/crystal#386]
This fails:

```crystal
4./(2)
# Syntax error in eval:3: expecting any of these tokens: IDENT, +, -, *, /, %, |, &, ^, **, <<, <, <=, ==, !=, =~, >>, >, >=, <=>, ||, &&, ===, [], []= (not 'DELIMITER_START')
```

**Comment by zamith** [comment]
@asterite You beat me to it. haha.

**Comment by asterite** [comment]
@zamith Sorry! I didn't know you was looking at this.

You can comment next time saying something like "I'l fix this" or similar. There's no rush for fixing things, so you can even say it and come with the solution several days later. And I think it's much better if you or others fix compiler bugs/enhancement, so the knowledge of how the compiler works starts to spread out :smiley:

**Comment by zamith** [comment]
@asterite No problem. I was just going over the bugs, and this is a quick fix. I'll say something next time.
