### ISSUE TITLE
Can't instantiate a generic class with initializer argument with default value

### ISSUE THREAD

**Issue by waj** [manastech/crystal#394]
The following code raises an error during compilation:
```crystal
class Foo(T)
  def initialize(x = 1)
  end
end

Foo(Int32).new
```

The error is: "undefined constant T"

**Comment by vendethiel** [comment]
What happens when T's not a numeric type, tho?

**Comment by asterite** [comment]
@vendethiel Nothing, it was a bug with default arguments and `new`. Note that `x` is not assigned to an instance variable.

**Comment by vendethiel** [comment]
Oh! My bad ><.
