### ISSUE TITLE
Vagrant box does not come with precompiled crystal

### ISSUE THREAD

**Issue by weskinner** [manastech/crystal#395]
Attempting to compile crystal in any of the vagrant boxes gives this error

`bin/crystal: line 10: crystal: command not found`

Should the latest crystal binary be included as part of the provisioning?

**Comment by asterite** [comment]
Yes. The Vagrant files are a bit outdated. Previously we used them to generate crystal binaries for linux by cross compiling, but now we have another (better) way to do it, so we don't use Vagrant at all now.

**Comment by waj** [comment]
I just updated (93aa54e) the Vagrantfile so it should work out of the box.
