### ISSUE TITLE
Support referencing constants later defined in the same lib

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#399]
I'm toying with binding generation using gobject-introspection. GI spits out the elements in alphabetical order, so it happens that among the many structs it produces, some have fields with types of structs that are later defined. Grouping by type is easy (struct, enum, object...), but resolving those inter-dependencies requires building a dependency graph to find the right ordering, and I'm not even sure there aren't any cyclic dependencies in there. So that's a huge extra effort and it would be much easier to be able to reference constants that are later defined, as a simple example:

```ruby
lib Foo
  fun foo() : Bar*
  struct Bar
  end
end
```

**Comment by asterite** [comment]
I think we could do this. But can it be "defined int he same lib" instead of "defined in the same file"? It would make things easier.

**Comment by jhass** [comment]
It seems to pretty much already work for classes actually from a quick test, so sure.
