### ISSUE TITLE
File::Stat#mtime

### ISSUE THREAD

**Issue by ysbaddaden** [manastech/crystal#405]
Trying to call File::Stat#mtime won't compile:

```
in src/file/stat.cr:140: no overload matches 'Time#initialize' with types LibC::TimeSpec
Overloads are:
 - Time#initialize(year, month, day, hour = 0, minute = 0, second = 0, millisecond = 0, kind = Kind::Unspecified)
 - Time#initialize(ticks : Int, kind = Kind::Unspecified)
 - Time#initialize()

      Time.new(@stat.st_mtimespec)
           ^~~
```

**Comment by asterite** [comment]
Thanks!

I added a TODO in the commit, not sure if the times returned by stat are always UTC. (But Time and TimeSpan are not yet finished, they are missing lots of time-zone related functionality, so...)

**Comment by ysbaddaden** [comment]
The time returned by File#mtime is UTC and is correct to my timezone (-0100). No bug, at least on Linux :-)

Now I have a problem when comparing Time.now (localtime) and File#mtime (UTC). It looks like Time#to_i returns a localtime timestamp, when it should apply the offset to return an UTC timestamp.

**Comment by ysbaddaden** [comment]
I found `Time.utc_now` which solves my problem. I understand that there are no timezone information for Time, yet. That's quite a beast to have: offsets, transformations, UTC comparisons, ...

**Comment by asterite** [comment]
@ysbaddaden Right. Time and TimeSpan are loosely (or maybe tightly :-P) based on Mono's implementation (and C#'s design, of course), so I think we should also look at how timezones are handled there. But yes, Time comparison should take into account timezones. That is, comparing a local time to UTC time should work out of the box and give the correct result.
