### ISSUE TITLE
! method only callable as !obj, not obj.!

### ISSUE THREAD

**Issue by Marand-** [manastech/crystal#412]
Negation (`!`) is a definable method, but isn't callable using standard method syntax (`obj.!`), only the syntactic sugar form of `!obj`.  Example:

```
class TestClass
  def !
    puts "!" * 10
  end
end
 
obj = TestClass.new
!obj
obj.!
```

I'm not sure why anybody would want to call it this way, but since it's a method, it should be possible to use normal method syntax.

**Comment by asterite** [comment]
This is actually important, because when writing macro you normally use the `obj.method(...)` notation and in this case it would fail to parse. Thanks!

**Comment by Marand-** [comment]
Oh nice, I just thought it was some obscure syntax parsing oddity that nobody would ever need.  Only reason I even found it is I was poking at possible methods for the `.not_nil!` RFC discussion.

Glad it was a useful find.
