### ISSUE TITLE
Crash calling a class' #object_id or #hash

### ISSUE THREAD

**Issue by Exilor** [manastech/crystal#416]
I was toying with the ```Class``` class and wondering why for example ```String == String``` returns``` false```. Then I tried to implement it in terms of the ```object_id``` of the class (I figured it would have one, being an instance of Class) and it threw an error:

```
; ModuleID = 'main_module'

%String = type { i32, i32, i32, i8 }
%CFileIO = type { i8* }
%"->" = type { i8*, i8* }
%"struct.LibABI::UnwindException" = type { i64, i64, i64, i64, i64, i32 }
%Exception = type { i32, %String*, i1, %"Array(String)"* }
%"Array(String)" = type { i32, i32, i32, %String** }
%StringIO = type { i32, i8*, i32, i32, i32 }
%ArgumentError = type { i32, %String*, i1, %"Array(String)"* }
```
and many more lines.

**Comment by asterite** [comment]
Yup. The meta-model is kind of broken right now... we still have to rethink it and fix it.

**Comment by asterite** [comment]
This is working now. There's no `object_id` for a class as its represented as a number for now, but you can invoke `crystal_type_id` on them to get some kind of id.
