### ISSUE TITLE
Another parallel assignment surprise

### ISSUE THREAD

**Issue by Exilor** [manastech/crystal#419]
```ruby
a = 1
b = 2

a, b = b, a if false

[a, b] # => [2, nil]
```
Ruby's behavior given the same code is to leave the two variables unchanged. Also, even if ```false``` is replaced with ```true```, the compiler will complain that ```b``` could be ```nil```:
```ruby
a = 1
b = 2

a, b = b, a if true

[a, b] # => [2, 1]
b.abs # => undefined method 'abs' for Nil
```

**Comment by asterite** [comment]
Thanks for letting us know :-)

I did parallel assignment very quickly so it has its bugs. We'll fix them.
