### ISSUE TITLE
Compiler tries to downcast Class

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#423]
```ruby
class Foo
  macro foo type
    def bar
      baz({{type.id}}.class)
    end
  end

  def baz type
    case type
    when String
      "hi"
    end
  end

  foo String
end

Foo.new.bar
```

I'm sure I'm doing something wrong in that code, but it would be nice if Crystal pointed out what that is ;)

**Comment by asterite** [comment]
Hmmm... what are you trying to do? I mean, what's the code you want to do, and how would you do it without macros?

Right now it crashes because you do `String.class`, and going to `Class` will always break the compiler now because the meta-metamodel is super broken :-(

**Comment by jhass** [comment]
Mmh, let me try to pseudo code it:

```ruby
class Foo
  macro wrapped_getter name, type
    def {{name.id}}
     pointer = LibSome.call
     to_crystal(pointer, type)
    end
  end

  def to_crystal pointer, type
    case type
    when String
      String.new pointer as UInt8**
    when Int32
     (ptr as Int32*).value
    end
  end

  wrapped_getter foo, String
  wrapped_getter bar, Int32
end
```

I think that should show the idea.

**Comment by asterite** [comment]
I see... well, that doesn't even work in Ruby:

```ruby
s = String
case s
when String
  puts 1
else
  puts 2
end
```

The above prints 2. String is not a String :-)

Of course, that doesn't mean we have to copy Ruby. But right now class comparison doesn't work, and less as a `when` inside a `case`.

However, what you could do, is reopen String and Int32 and add class methods to them:

```crystal
class String
  def self.my_to_crystal(pointer)
    String.new pointer as UInt8**
  end
end

class Int32
  def self.my_to_crystal(pointer)
    (pointer as Int32*).value
  end
end

class Foo
  macro wrapped_getter name, type
    def {{name.id}}
      pointer = LibSome.call
      {{type}}.my_to_crystal(pointer)
    end
  end

  wrapped_getter foo, String
  wrapped_getter bar, Int32
end
```

But... we definitely need to fix class-related functionality.

**Comment by jhass** [comment]
Ugh, right. Had a brainfart there I guess. Mmh, I'm not a big fan of patching core classes, but I guess that's the cleanest solution here, thanks.

**Comment by asterite** [comment]
Another solution is to have associated classes. So for example, MyString, MyInt32, with class methods. Then you pass `My{{type.id}}`. That way you don't patch core classes.

**Comment by asterite** [comment]
Or just a regular method: `to_crystal_{{type.id}}`

**Comment by asterite** [comment]
This doesn't crash anymore.
