### ISSUE TITLE
Macro methods for string substuition

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#425]
I think it's quite common that you do some simple conversions on a macro argument, like `.tr("-", "_")` or `.gsub(/_[a-z]/) {|m| m[1].upcase }` etc.

**Comment by asterite** [comment]
Definitely! Further, there's currently an "identify" method that works on string literals that turns a word into a valid Crystal identifier. But right now it's [too simple](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/macros/methods.cr#L179).

If you want you can try to implement some macro methods, it's not very hard. You might also find a better way to write them (right now the code is not very tidy).

**Comment by asterite** [comment]
I added `tr` and `gsub`, but `gsub` doesn't receive a block (yet), so I'll keep this open for now.

**Comment by asterite** [comment]
I'll close this. Please open another issue (or send a PR ;-)) if you need the `gsub` with a block variant.
