### ISSUE TITLE
Forward usage in aliases

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#428]
Another feature that would ease binding generation a lot.

```ruby
lib Fake
  fun foo(cb : Callback)
  alias Callback = A -> B

  struct A
  end

  enum B
    FOO
    BAR
  end
end
```

**Comment by asterite** [comment]
I think we can do this.

**Comment by jhass** [comment]
Just figured that it works if you push the aliases to the end, so don't stress it ;)

**Comment by asterite** [comment]
This is working now (if you add some member to `struct A`).
