### ISSUE TITLE
Lookup macros in parent namspaces

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#429]
I think that would provide a neat place for library internal macros

```ruby
module Foo
  macro foo
  end

  class Bar
    foo
  end
end
```

**Comment by jhass** [comment]
This is a bit related to #236 as it affects the lookup.

**Comment by asterite** [comment]
@jhass Do you think that now that you can do `Foo.foo` this takes care of this issue? I know it's not the same, but this is another way to invoke macros defined in a parent namespace, although a bit more explicitly (but maybe this is better).

**Comment by jhass** [comment]
No, I think that macro and method lookup is not interleaved is completely counter intuitive.

**Comment by asterite** [comment]
How come?

```crystal
module Foo
  def bar
  end

  def self.bar
  end

  class Baz
    bar # undefined local variable or method 'bar'
  end
end
```

It works the same way with methods, they aren't looked up in parent modules.

**Comment by jhass** [comment]
Mmmh, looking again I related this too strongly with https://github.com/manastech/crystal/issues/236#issuecomment-136515422
