### ISSUE TITLE
Remove the "block argument 'x' shadows local variable 'x'" error

### ISSUE THREAD

**Issue by asterite** [manastech/crystal#432]
Because it's annoying, and it forces you to rename and use names you wouldn't normally use. So, the following should work:

```crystal
a = 1
5.times do |a|
  puts a
end
puts a
```

**Comment by ysbaddaden** [comment]
What about a warning? It compiles, but warns that shadowing is confusing.

**Comment by asterite** [comment]
Mmm... I don't like warnings. There's two options for warnings:

1. You always print them, which is annoying
2. You print them if a flag is passed. But nobody ends up using that flag, or if you use it then you are using many libraries that didn't bother to check it, so you ignore it too.

The problem with warnings is that the say "Look, here you might have a problem", but the compiler might be wrong and you know better.

@ysbaddaden Do you find that shadowing error useful?

**Comment by ysbaddaden** [comment]
Agreed. There should eventually be a crystal lint!

**Comment by ysbaddaden** [comment]
I just stumbled along something similar, which proves to be annoying:

```crystal
macro got(klass)
  begin
  rescue ex : {{ klass.id }}}
  end
end

got(A)
got(B) # => Syntax error in expanded macro: got:3: exception variable 'ex' shadows local variable 'ex'
```

**Comment by faustinoaq** [comment]
> Agreed. There should eventually be a crystal lint!

@ysbaddaden  3 years after, Here we have [Ameba](https://github.com/veelenga/ameba/) Thanks to @veelenga!!! :tada:
