### ISSUE TITLE
Missing methods in Evented IO

### ISSUE THREAD

**Issue by ysbaddaden** [manastech/crystal#433]
I'm trying to compile Prax with -Devented (just to try) and I'm running against missing methods:

- TCPSocket (and TCPServer):
  - #fd — expected by `IO.select([server])`
  - #addr — I use it to find an available port: `TCPServer.new(0).addr.port` and debug
- IO:
  - #reopen — used by `Process.spawn` to redirect STDOUT/STDERR

There are certainly more, but I'm too tired to comment more code to find 'em all!

**Comment by waj** [comment]
TCPSocket#fd wont be implemented but you should not need it anyway, because libuv does the network polling using more efficient apis (epoll/kevent).

**Comment by ysbaddaden** [comment]
Then how can I select against different servers (many TCP, SSL, UNIX)? I should spawn many fibers and have a "blocking" accept, so that uv/fibers will handle it:

```crystal
[tcp_server, ssl_server, unix_server].each do |server|
  spawn do
    loop { handle(server.accept) }
  end
end
```

But what if I want to cleanly exit by telling a fiber/thread to exit? It's fine when they are busy (break the loop using a global state) but what if fibers are waiting for incoming connections? I can't use the classic pipe + select to message a fiber/thread anymore:

```crystal
EXIT = "exit\n"
inbox, sender = IO.pipe

spawn do
  loop do
    ios = IO.select([inbox, tcp_server, ssl_server, unix_server])
    break if ios.include?(inbox) && inbox.gets() == EXIT
    # ...
  end
end

Signal.trap(Signal::INT) { sender << EXIT }
```

How can I achieve that without `select`?

PS: I hope I don't feel stubborn, I just want Crystal to be soooo good! Maybe I have to change the way I think to be less C/UNIX?

**Comment by ysbaddaden** [comment]
IO.reopen looks hard to implement, because libuv doesn't provide any helper to access dup2 or dup3 :cry:

**Comment by waj** [comment]
I don't know how exactly the pattern would look like for this case but if we inspire in Go you would "select" on one or more channels that allow message passing between coroutines.

However for this scenario I think we could just "close" the servers from another fiber, the "accept" would return with nil or raise an error and each process could exit gracefully.

**Comment by asterite** [comment]
IO hierarchy remains the same. Closing...
