### ISSUE TITLE
String#split when separator is the last character

### ISSUE THREAD

**Issue by ysbaddaden** [manastech/crystal#441]
```crystal
# OK:
"a=b".split("=") # => ["a", "b"]

# BAD:
"a=".split("=") # => ["a"]
```

I expected `["a", ""]` instead.

**Comment by asterite** [comment]
In Ruby it's the same, we copied its logic. Basically, empty parts are removed from the split.

We could change that logic, but... why do you need that?

**Comment by vendethiel** [comment]
Probably for `a, b = x.split...`

**Comment by asterite** [comment]
However, in Ruby:

```
irb(main):001:0> "=a=b=".split("=")
=> ["", "a", "b"]
```

So there's an inconsistency there.

@bcardiff just said here: `x.split(s).join(s).should eq(x)`, but in this case it would be false.

Should we change this behaviour?

**Comment by ysbaddaden** [comment]
I was sure I tried and Ruby returned an empty string, before reporting, but just did, and yeah it skips it entirely. I guess I've been misguided by Ruby's `k, v = str.split('=')` where `v` is nil, whereas Crystal raises an out of bound exception...

**Comment by asterite** [comment]
@ysbaddaden But don't you think it makes sense to return the empty parts? That way you wouldn't get an out of bound exception, and it will also be more consistent with `join`.

**Comment by ysbaddaden** [comment]
Maybe it makes sense, and javascript for instance does just that. Yet, we'll still have out of bounds when the string format ain't for certain (eg. user data), so I'm not sure.

**Comment by asterite** [comment]
I see. So you would use `k = str.split('=').first` instead, right? That always works.

**Comment by ysbaddaden** [comment]
I expect `[0]` to always exist (in the worst case it didn't split the string), but check if `[1]` indeed exists: https://github.com/ysbaddaden/prax.cr/blob/master/src/prax/application/spawner.cr#L53-L54
