### ISSUE TITLE
"A == A" is false

### ISSUE THREAD

**Issue by ysbaddaden** [manastech/crystal#443]
I just stumbled upon this:

```crystal
class A; end

p A == A # => false
p Int32 == Int32 # => false
```

In Ruby `A == A` would return true.

**Comment by ysbaddaden** [comment]
It looks like it can be implemented this way:

```crystal
class Class
  def self.==(other : Class)
    self.to_s == other.to_s
  end
end
```

Specs: 

```crystal
require "spec"

class A
end

class B
  def to_s
    return "A"
  end
end

class C
  def self.to_s
    "A" # trying to spoof identity
  end
end

assert { Int32 == Int32 }

assert { A == A }
assert { !(A != A) }
assert { A != B }
assert { A.new != A }
assert { A.new != A.new }

assert { A != B.new }
assert { C.to_s == "A" }
assert { A != C }
```

**Comment by asterite** [comment]
`Class` is completely broken at the moment :-(

Also see: #423, #416 and #347

**Comment by ysbaddaden** [comment]
Ruby weirdness:

```ruby
A == A # => true
A === A # => false (huh?!)
```

**Comment by asterite** [comment]
Hehe. It's because A is not an A, or doesn't belong to the category of objects described by A. But... I'm not sure it makes sense.

**Comment by ysbaddaden** [comment]
A equals A but A isn't an A. Tiny difference, but (maybe) it makes a bit of send.

**Comment by jhass** [comment]
It makes sense, You're calling Module#===, which is used for case statements. So it's that way for this to work:

```ruby
case value
when String
when Hash
end
```

**Comment by asterite** [comment]
This is now working in 0.6.1. You can compare classes (equality, not order) and also get invoke `hash` on them. They even have a `name` method :-)

**Comment by ysbaddaden** [comment]
:+1: !
