### ISSUE TITLE
[Improvement] Better error message for `self is not a module, it's a class`

### ISSUE THREAD

**Issue by akaufmann** [manastech/crystal#446]
If you use a class (by mistake) instead of a module and extend it with `self`, you get an error like
`Error self is not a module, it's a class`

* You don't get a file path and a line number
* If you are new to Crystal the error message is not very helpful (you don't know what should be done)

Could this be improved?

**Comment by asterite** [comment]
Now in a code like this:

```crystal
class Foo
  extend self
end
```

You get:

```
Error in ./foo.cr:2: Foo is not a module, it's a class

  extend self
         ^
```

Is that good enough?

**Comment by akaufmann** [comment]
Yes, that's better :+1:  
Thx, asterite!
