### ISSUE TITLE
Arrays from C functions

### ISSUE THREAD

**Issue by Exilor** [manastech/crystal#465]
This is hard to explain so I'll use an example.

```ruby
lib LibGMP
  fun export = __gmpz_export(rop : Void*, countp : Int32*, order : Int32, size : Int32, endian : Int32, nails : Int32, op : MPZ*) : UInt8*
end
```
This function returns a pointer to an UInt8 that will later be used to build an array.
```ruby
struct BigInt
  def bytes
    ptr = LibGMP.export(nil, out size, -1, 1, 1, 0, self)
    array = Array(UInt8).new(size)
    array.length = size
    array.buffer.copy_from(ptr, size)
    array
  end
end
```
This is the only way to do it that I know of. The problem I see is that memory is allocated (from the function), then more memory (from the array), and then data is copied with Pointer#copy_from.

My question is: is there a way to directly use the pointer that the function returns for the array? Unless I really misunderstand how copy_from works, it seems wasteful to have these two identical allocations.

**Comment by ysbaddaden** [comment]
Isn't something like this possible, or something along those lines (ptr may already be a pointer, so no need for pointerof):

```crystal
array = pointerof(ptr) as Pointer(Array(UInt8))
array.value
```

I used pointer casting a lot when dealing with sockets and addrinfo structs.

**Comment by Exilor** [comment]
@ysbaddaden nope, that doesn't work.

**Comment by asterite** [comment]
You could do this:

```crystal
require "big_int"

class Array
  # Creates an Array backed by the given buffer.
  # This method is **unsafe**: the buffer should have been allocated
  # with Pointer.malloc, otherwise behaviour is undefined if this Array
  # needs to be resized.
  def initialize(@buffer : Pointer(T), @length : Int32)
    @capacity = @length
  end
end

struct BigInt
  def bytes
    ptr = LibGMP.export(nil, out size, -1, 1, 1, 0, self)
    Array.new(ptr, size)
  end
end

num = BigInt.new(123456)
pp num.bytes #=> [64, 226, 1]
```

We could add that method to the standard library. However, in GMP we [override the default memory allocation routines](https://github.com/manastech/crystal/blob/master/src/big_int/lib_gmp.cr#L69) to use our GC, so it's safe to do the above. In most cases the memory will be allocated by the C library and needs to be freed, so a copy will be inevitable.

Another thing you can do is do what it is said in [the docs of mpz_export](https://gmplib.org/manual/Integer-Import-and-Export.html): compute the size needed for the buffer, create an array with that initial capacity and then pass a pointer to the buffer to that C function.

**Comment by Exilor** [comment]
@asterite your first suggestion seemed like the easiest way to me but because I saw this https://github.com/manastech/crystal/blob/master/src/string.cr#L59 in String too despite taking a pointer as an arg I thought that there might be a compelling reason to copy the buffer instead of reusing it.

The second suggestion was exactly what I was looking for:
```ruby
lib LibGMP
  fun sizeinbase = __gmpz_sizeinbase(op : MPZ*, base : Int32) : Int32
  fun export = __gmpz_export(rop : Void*, countp : Int32*, order : Int32, size : Int32, endian : Int32, nails : Int32, op : MPZ*) : UInt8*
end

struct BigInt
  def bytesize
    LibGMP.sizeinbase(self, 256)
  end
  
  def bytes
    size = bytesize
    bytes = Array(UInt8).new(size)
    bytes.length = size
    LibGMP.export(bytes.buffer as Void*, nil, -1, 1, 1, 0, self)
    bytes
  end
end

BigInt.new(1234567890).bytes # => [210, 2, 150, 73]
```
Thanks :)

**Comment by asterite** [comment]
This operation, creating an Array with a given length and doing something with the buffer, is something that I found is very common so far. So maybe we can add a method for that. And then we can also remove the method `#length=`.

I was thinking about something like this (Array has already many constructors and this one is avaialble... in this way you can also specify the length but maybe allocate a bigger buffer if you know it's probable that the array will grow):

```crystal
class Array
  def initialize(length : Int, capacity : Int)
    @length = length.to_i
    @capacity = capacity.to_i
    @buffer = Pointer(T).malloc(capacity)
    yield @buffer
  end
end
```

Your code would become:

```crystal
lib LibGMP
  fun sizeinbase = __gmpz_sizeinbase(op : MPZ*, base : Int32) : Int32
  fun export = __gmpz_export(rop : Void*, countp : Int32*, order : Int32, size : Int32, endian : Int32, nails : Int32, op : MPZ*) : UInt8*
end

struct BigInt
  def bytesize
    LibGMP.sizeinbase(self, 256)
  end

  def bytes
    size = bytesize
    Array(UInt8).new(size, size) do |buffer|
      LibGMP.export(buffer as Void*, nil, -1, 1, 1, 0, self)
    end
  end
end

BigInt.new(1234567890).bytes # => [210, 2, 150, 73]
```

In fact, right now when you write `[1, 2, 3]` the compiler translates it to this (for maximum efficiency):

```crystal
ary = Array(typeof(1, 2, 3)).new(3)
ary.length = 3
buffer = ary.buffer
buffer[0] = 1
buffer[1] = 2
buffer[2] = 3
```

But with this change it could be rewritten to:

```crystal
Array(typeof(1, 2, 3)).new(3, 3) do |buffer|
  buffer[0] = 1
  buffer[1] = 2
  buffer[2] = 3
end
```

So `#length=`, the ugly unsafe method, is removed, and the only two unsafe methods are this new one (to manipulate the buffer in an efficient way) and `to_unsafe` (we could remove `buffer` so the unsafeness is more explicit.)

What do you think?

/cc @waj

**Comment by Exilor** [comment]
I think it looks great. Code that uses this would look cleaner.
What about taking it one step further and yield the index too? This way this:
```ruby
struct Number
  def self.[](*nums)
    ary = Array(self).new(nums.length)
    ary.length = nums.length
    nums.each_with_index do |num, i|
      ary.buffer[i] = cast(num)
    end
    ary
  end
end
```
can be written as:
```ruby
struct Number
  def self.[](*nums)
    Array(self).new(nums.length, nums.length) do |buffer, index|
      buffer[index] = cast nums[index]
    end
  end
end
```
And the yielded index can be ignored if you don't need it.
But maybe that's taking it too far :P

**Comment by asterite** [comment]
Ah, but in my version the buffer was yielded and you could do whatever you want with it, it doesn't yield once for each index. You couldn't implement BigInt#bytes like that.

I'll add it :-)

**Comment by asterite** [comment]
@Exilor note that I renamed the method. If you were using it, please update :-)
