### ISSUE TITLE
Argument 'name' of 'LibC#getaddrinfo' must be Pointer(UInt8), not String?

### ISSUE THREAD

**Issue by Odaeus** [manastech/crystal#468]
Hello!

I was trying out a simple HTTP request but came across this problem:
```crystal
require "http/client"

uri = URI.parse("http://www.example.com")

HTTP::Client.new(uri.host) do |client|
  client.get("/")
end
```

Resulting in a stacktrace:
```...
instantiating 'TCPSocket#initialize(String?, Int32)'

in /opt/crystal/src/socket/sync/tcp_socket.cr:5: instantiating 'getaddrinfo(String?, Int32, Nil, Int32, Int32)'

    getaddrinfo(host, port, nil, LibC::SOCK_STREAM, LibC::IPPROTO_TCP) do |ai|
    ^~~~~~~~~~~

in /opt/crystal/src/socket/sync/ip_socket.cr:38: argument 'name' of 'LibC#getaddrinfo' must be Pointer(UInt8), not String?

    ret = LibC.getaddrinfo(host, port.to_s, pointerof(hints), out addrinfo)
```

It works if I use a literal string in place of `URI#host` so I'm not sure what's going on. Have I misunderstood something about the language?

**Comment by Exilor** [comment]
The compiler is anticipating that #host might return nil (probably because of this https://github.com/manastech/crystal/blob/master/src/uri.cr#L8). In such cases you can use #not_nil! (if you're really sure it won't be nil).

```ruby
require "http/client"

uri = URI.parse("http://www.example.com")

HTTP::Client.new(uri.host.not_nil!) do |client|
  client.get("/")
end
```

**Comment by jhass** [comment]
Maybe we should add `host!` etc properties for convenience, although the host part in an URI is in fact optional.

**Comment by Odaeus** [comment]
Ah I see. Thank you! Out of interest, which bit of the error message implies the type ambiguity?

**Comment by jhass** [comment]
`String?` is the shortcut notation for the union `String|Nil`.

**Comment by Odaeus** [comment]
Thanks @jhass! I like the idea of the convenience methods, if I call `host!` then it's because I need a host value to be present so I don't think it affects the idea that a host is optional in a URI. The curse of nil!

**Comment by asterite** [comment]
If you want to add `host!`, etc., please send a separate pull request. I'll close this issue for now.
