### ISSUE TITLE
Two symbols that should work without quotes but don't

### ISSUE THREAD

**Issue by Exilor** [manastech/crystal#479]
```
:[]? # => unexpected token: EOF (or whatever comes after it)
:[]= # => unexpected token: =
```
Which is weird because there are tests for both of them.

**Comment by asterite** [comment]
Yes, I was surprised too!

But the problem was that they lexed well but the lexer's cursor was left in a wrong place. It needed to avance one more char.

I'll later add specs for all the symbols in the parser so we make sure the all work.

Thanks!

**Comment by Exilor** [comment]
While we're on the topic of symbols.
Do you want me to add this kind of symbols to ```Symbol::needs_quotes?``` ? That method has been outdated ever since you expanded the number of symbols that don't need quotes.
Shouldn't ```Symbol``` include ```Comparable```? Like:
```ruby
struct Symbol
  include Comparable(Symbol)

  def <=>(other : Symbol)
    to_s <=> other.to_s
  end
end
```
that's how Ruby does it.

**Comment by asterite** [comment]
Yes, please, that would be fantastic!

And in fact `Symbol::needs_quotes?` is [used by the compiler](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/syntax/to_s.cr#L50) when you interpolate a symbol in a macro, so it won't work for these ones.
