### ISSUE TITLE
Underscore prefixed classes are not allowed

### ISSUE THREAD

**Issue by bcardiff** [manastech/crystal#490]
```
$ crystal eval 'class _A;end'
Syntax error in eval:1: expecting token 'CONST', not '_A'
```

I think const should be allowed to begin with underscore(s).

**Comment by jhass** [comment]
I disagree, this is a local variable. Both, constants and local variables may contain the same set of characters. Constants are defined by starting with an uppercase letter, there's no uppercase `_` thus it must be a local variable.

**Comment by asterite** [comment]
@jhass is right. In Ruby it's an error too:

```ruby
class _Foo
end

# class/module name must be CONSTANT
```

If you are generating code you can always put the underscore at the end :-)

**Comment by bcardiff** [comment]
Ok. In my eagerness I missed to double check against Ruby.

I was thinking of `_A` could be const while `_a` could be local. But ugly corner cases appears like `_3g` `_3G`. 

Closing this.
