### ISSUE TITLE
`crystal` command crashes Ubuntu 12.04

### ISSUE THREAD

**Issue by rhysd** [manastech/crystal#493]
I cloned current master branch and executed `make`, but the result had never returned.  After a while, all applications were killed and the system went shutdown.

How to reproduce is below:

```sh
$ git clone https://github.com/manastech/crystal.git
$ cd crystal
$ make # this yields ./bin/crystal build
```

The environment was:

- Ubuntu 12.04 (32bit)
- llvm 3.4 (installed from LLVM apt repository)
- Crystal b73b155c0cd4f1b2b11c146149c197613f6873c3

**Comment by asterite** [comment]
Oh, you need llvm 3.5. Can you try with that one?

**Comment by rhysd** [comment]
OK, I'll do that.

**Comment by rhysd** [comment]
I installed llvm 3.5 with `apt-get install llvm-3.5` and executed `make` again.  However, it didn't resolve this issue...

**Comment by alex-guenther** [comment]
I had simmilar issues when i tried to compile crystal without having a crystal executeable in my path. The wrapper script starts calling itself until the whole system crashes. When you look at the running processes and see hundreds of crystal processes just hit `ctrl+c`. You need a workink current crystal compiler from tar.gz or package to compile crystal itself.
See: http://crystal-lang.org/docs/installation/README.html

**Comment by jhass** [comment]
@alex-guenther Good catch, I did some improvements in #495.

**Comment by rhysd** [comment]
@alex-guenther 

Thank you! I'll do that.

@jhass 

Thank you for your patch.  But it doesn't resolve this issue...

**Comment by jhass** [comment]
What's your output of `echo $PATH`?

**Comment by rhysd** [comment]
I checked my (confushed) `$PATH` and confimed `path/to/crystal/bin` is included in it.

The result of `command -v crystal` shows `path/to/crystal/bin/crystal` correctly.

**Comment by jhass** [comment]
Sorry, what do you mean by `path/to/crystal/bin/crystal`? The wrapper script in the repository?

**Comment by rhysd** [comment]
Sorry for making you confused.  I executed `path/to/crystal` is a crystal repository and `path/to/crystal/bin/crystal` is the wrapper script.

**Comment by jhass** [comment]
Ah, so you put it into your PATH, I see the issue now.

**Comment by rhysd** [comment]
Oh, I said `correctly` but it was wrong.

`make` yields `./bin/crystal` and `./bin/crystal` uses itself...

**Comment by rhysd** [comment]
OK I'd removed `./bin/crystal` from `$PATH` and confirmed the message "You need to have a crystal executable in your path!".  Thank you, everybody!
