### ISSUE TITLE
crystal docs crashes

### ISSUE THREAD

**Issue by alex-guenther** [manastech/crystal#494]
Hi, 

I tryed to generate crystal docs and it told me to open an issue, so I'm not sure if and what is broken.

I ran `crystal docs` on a hello sqlite3 project and it complained that it's not a git repository. So I made a git repository out of it and `crystal docs` crashed

* I created a new git repository. 
* Added a Projectfile (only crystal-sqlite3)
* Added the example code for crystal-sqlite3
* And finaly run `crystal docs`

```
➜  fun git:(master) ✗ crystal docs
Using compiled compiler at .build/crystal
Nil assertion failed
*Exception#initialize<Exception, String, Nil>:Array(String) +21 [71874560]
*Exception::new<String>:Exception +120 [71874560]
*raise<String>:NoReturn +6 [71874560]
*Nil#!<Nil>:Bool +0 [71874560]
*Crystal::Doc::Generator#compute_repository<Crystal::Doc::Generator>:Array(String)? +512 [71874560]
*Crystal::Doc::Generator#initialize<Crystal::Doc::Generator, Crystal::Program, Array(String), String>:Array(String)? +131 [71874560]
*Crystal::Doc::Generator::new<Crystal::Program, Array(String), String>:Crystal::Doc::Generator +158 [71874560]
*Crystal::Doc::Generator::new<Crystal::Program, Array(String)>:Crystal::Doc::Generator +16 [71874560]
*Crystal::generate_docs<Crystal::Program, Array(String)>:File +27 [71874560]
*Crystal::Command::docs<Array(String)>:File +677 [71874560]
*Crystal::Command::run<Array(String)>:(Crystal::Compiler::Result | File | Bool | CFileIO | Nil) +794 [71874560]
*Crystal::Command::run:(Crystal::Compiler::Result | File | Bool | CFileIO | Nil) +37 [71874560]
__crystal_main +11333 [71874560]
main +40 [71874560]
__libc_start_main +240 [71874560]
_start +41 [71874560]
 +41 [71874560]

Error: you've found a bug in the Crystal compiler. Please open an issue: https://github.com/manastech/crystal/issues
```
I use ArchLinux with a compiler from the sources (compiled using the tar.gz compiler).

```
crystal --version
Using compiled compiler at .build/crystal
Crystal 0.5.6 [d8f8826] (Thu Mar 19 21:02:03 UTC 2015)
```

**Comment by jhass** [comment]
Can you please try the latest version? It's nicely packaged up for you in the AUR ;)

**Comment by alex-guenther** [comment]
The funny thing is, that I used the current master version as indicated by the hash `[d8f8826]` and this is what makes me whonder why it displays the version `0.5.6 ...`

Installed the aur package und used it results:
```
➜  fun git:(master) ✗ /usr/bin/crystal docs
[1]    3931 segmentation fault (core dumped)  /usr/bin/crystal docs
```

**Comment by jhass** [comment]
Oh right, maybe you never fetched the tags for a while, try `git fetch` in your repo. Anyway, ignore my previous comment then :P

**Comment by asterite** [comment]
It seems it's a bug in the compiler. I can reproduce it with this program:

```crystal
def foo
  while false
    yield
  end
  3
end

z = foo do
  break 10
end
puts z #=> doesn't print 10
```

If you look at [the method](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/tools/doc/generator.cr#L232) in this issue's backtrace you will see it's a block that always breaks, so it has something to do with it. The code we are generating is wrong. That explains the segfault or random behaviour.

**Comment by asterite** [comment]
I mean, it should print 3, of course.

**Comment by asterite** [comment]
Fixed! You can try compiling a new compiler and using that one for the docs

**Comment by alex-guenther** [comment]
Thanks for the fast response!

It works, and produces an empty documentation because there are no methods or classes... now I see why it crashed. But as soon I have a class I see it's docs. :)
