### ISSUE TITLE
bug of Enumerable#sum

### ISSUE THREAD

**Issue by And3s** [manastech/crystal#497]
Crystal 0.6.1 [0d09e33] (Fri Mar 20 14:14:13 UTC 2015)

crystal eval 'p (1..100000).inject {|s,e| s + e }'
crystal eval 'p (1..100000).sum'

output:

705082704   

# the ans: 5000050000

**Comment by asterite** [comment]
This works:

```crystal
require "big_int"

p (1.to_big_i .. 100000).inject {|s,e| s + e }
p (1.to_big_i .. 100000).sum(0.to_big_i)
```

Integers in Crystal don't automagically convert to BigInt. If you expect big numbers, use BigInt.

Alternatively, you can use Int64:

```crystal
p (1_i64 .. 100000).inject {|s,e| s + e }
p (1_i64 .. 100000).sum(0_i64)
```

Note that in the second call I pass `0.to_big_i` or `0_i64`, because sum by default receives `0` (Int32), but we want BigInt or Int64.

**Comment by bcardiff** [comment]
Or UInt64

```
p (1_u64 .. 100000_u64).sum(0_u64)
```

NB: with Crystal 0.6.1 you will need to specify both begin and end with the same type.

**Comment by asterite** [comment]
Maybe `sum` is not very intuitive like it is now. Maybe we can make the "initial" parameter be always required, so that the type is the correct one. For example right now if you do `[1.5, 2.5].sum` that gives an `Int32 | Float64`, very ugly. Or do the same as inject: raise if the enumerable is empty.

**Comment by bcardiff** [comment]
Or we can add a `default(T)`

**Comment by asterite** [comment]
Yes, I thought of that. What's a `default(Int32 | Float64)`? Or a `default(Int32 | BigInt)`?

**Comment by bcardiff** [comment]
you don't need to deal with unions. `enumerable(T)` will be expanded and `def sum(initial = default(T));...;end` should not generate a union type on a enumerable instance.

**Comment by asterite** [comment]
T can be a union. For example: `[1, 1.5] # Array(Int32 | Float64)`

**Comment by asterite** [comment]
Maybe we can have `default(A | B)` be `default(A) as A | B`, because you want a default value from that union, and that can be the default of any type in the union. I mean, if you have `Array(Int32 | Float64)` and you sum it and you get `0` or `0.0`, because either are `Int32 | Float64` it's the same. For non-primitive types the default would be to invoke `new` on the type, I guess, so `default(BigInt)` would be `BigInt.new` and so on.

**Comment by bcardiff** [comment]
Not in most cases. Either way `default(T1 | ... | T_n) can be default(T1)` if we define a canonical order for `T_i`. Or just complain about no default(T) for union types I think is fine to do that.

**Comment by asterite** [comment]
I also remember @waj wanted to have `default(T)` in the language, [similar to C#](https://msdn.microsoft.com/en-us/library/xwth0h0d.aspx), but I don't remember why right now...

For unions where Nil is involved, `nil` would be the default, I guess.

**Comment by asterite** [comment]
Ah, one reason is to be able to do `StaticArray(Int32, 8).new` and have that initialized to zero. Right now it's not possible because there's no `default`, so you have to do `StaticArray(Int32, 8).new(0)`.

**Comment by asterite** [comment]
There's something better that we can do, more generic. We can allow invoking methods on a union class type. For example:

```crystal
def foo(x : T)
  T.zero
end

a = 1 == 1 ? 1 : 1.5 #:: Int32 | Float64
foo(a)               #=> 0 :: Int32 | Float64
```

Here `T` is the type `Int32 | Float64` (not just one of them, it's `(Int32 | Float64):Class`). The compiler then checks if both `Int32.zero` and `Float64.zero` exist. If so, the compiler types the call as the union of those calls (in this case it will be `Int32 | Float64`) but it just generates a call for the first type in the union: `Int32`. So the call will evaluate to `0` casted to a union.

If one class in the union doesn't have a `zero` method, you get a compile error.

With this we can implement `default(T)` very easily: just define a class method named `default` in your types and that's it. The compiler always guarantees that if `Nil` is part of a union, it will be the first member of it, so a default of Nil and some other type will always be nil.

The good thing is that this doesn't need any new syntax. And we'll be able to make `sum` more intuitive and correct, by using `T.zero` as the initial value.

**Comment by bcardiff** [comment]
Well, you still need the grammar rules for:

```ruby
class Foo(T)
  def foo(x = default(T))
   ...
  end
end
```

unless we are able to write calls to class methods (IDK):

```ruby
class Foo(T)
  def foo(x = T.default)
   # ...
  end
end
```

which will still be awesome.

**Comment by asterite** [comment]
You can already do the second one

**Comment by bcardiff** [comment]
great :-). No new syntax then.

Just lets not throw a compiler error if the Enumerable is instantiated in a class without default. Lets just throw the error when the `.sum` method is called without an initial value.

**Comment by asterite** [comment]
Right now `sum` returns the correct type after we added `T.zero` and others, so I'll close this. You still have to use the correct type (BigInt, Float32, etc.) though!
