### ISSUE TITLE
`Class#superclass` - will it be possible at some point?

### ISSUE THREAD

**Issue by waterlink** [manastech/crystal#503]
And friends:
- `Class#===`
- `Class#<` and `Class#<=`

**Comment by asterite** [comment]
I think we can add these. You already have `superclass` at compile-time, maybe you can make use of it. What's your use case?

**Comment by waterlink** [comment]
Given I have some sort of `value` of some type. And I have a list of transformations:

```crystal
TRANSFORMATIONS = {
  Int => TransformationA,
  Float => TransformationB,
  String => TransformationC,
}

# ...

def transform(value)
  # Will find first type that value is derived from
  transform = TRANSFORMATIONS.find { |key, t| key === value }
  if transform
    # and apply transformation stored in value
    TRANSFORMATIONS[transform].apply(value)
  end
  value
end
```

Might be to dynamical for systems static language :) And actually perfectly solvable with multiple dispatch:

```crystal
def transform_strategy(value : Int) TransformationA end
def transform_strategy(value : Float) TransformationB end
def transform_strategy(value : String) TransformationC end
def transform_strategy(value) DefaultTransformation end

def transform(value)
  transform_strategy(value).apply(value)
end
```

So in the end I have avoided the need to use these features of `Class` and it rendered to be more concise and pretty code.

**Comment by asterite** [comment]
Good!

You can also write it like this:

```crystal
def transform_strategy(value)
  case value
  when Int    then TransformationA
  when Float  then TransformationB
  when String then TransformationC
  else             DefaultTransformation
  end
end
```

**Comment by bcardiff** [comment]
At least for this class based case overload fits very nicely. Also the plain case variant.

If on the future, given a `class C`, `C` itself is member of `Class(C)` instead of just `Class` we could write things like:

```
def transform_strategy(_ : Class(String)) TransformationC end
```

just to go a bit further.

**Comment by waterlink** [comment]
I think multiple dispatch is better here, since we have class reopen available in our arsenal (at compile time), which means, that the list of strategies can be extended elsewhere without modification of original code. Am I right?

**Comment by asterite** [comment]
@waterlink You are right!

@bcardiff I'm not sure this is what you mean, but you can do `def transform_strategy(x : String.class)` and x will match the class String or any of its subclasses.

**Comment by bcardiff** [comment]
Yeap I meant that @asterite but then `String.class` should return, well, `String.class` :-P instead of `Class`. Otherwise there is something not so tidy...

**Comment by waterlink** [comment]
@asterite Hmm, I think even if you do `def transform_strategy(x: String)` it will already match `String` and all subclasses. At least it works with `Int` -> it matches all `IntXX` types.

**Comment by bcardiff** [comment]
@waterlink  I was thing of calling `transform_strategy` with `value.class` and not just `value` so it is clear that the dependency is with the type and not the value. And that was what I was trying to express before.

**Comment by waterlink** [comment]
I think this can be closed now.
