### ISSUE TITLE
Custom functions in lib declaration?

### ISSUE THREAD

**Issue by ic5y** [manastech/crystal#521]
Is there any way to declare custom functions in a lib declaration?
like: 
```
lib LibA
    # linking to C functions
    ...
    
    def customFun() : Int32
        # something
    end
end
```

**Comment by asterite** [comment]
No, at least not yet. Why do you need it?

**Comment by ic5y** [comment]
There are some functions in the library that's not declared but #define-d. E.g.: 

Void func_a();
#define func_b func_a

So, there is no symbol for func_b in the library only for func_a. So to stay true for the lib, I wanted to add a Crystal function to the lib with def func_b which calls func_a from the imported library

**Comment by asterite** [comment]
I see. If you really want to provide an alias, you can do this:

```crystal
lib LibC
  # Make sure to use the same signature as the aliased function
  fun bye = exit(status : Int32) : NoReturn
end

LibC.bye(0)
```

That's a way.

However, the idea of a `lib` declaration is to define the minimum necessary code to interface with C. After that's done, you should write a Crystal wrapper for it. The wrapper uses the `lib`. Users of your library should never have to deal with the `lib` type.

**Comment by asterite** [comment]
With the above I mean that the alias will only be useful for end-users, but your wrapper will be the only end-user, so you can do just fine without that alias.

**Comment by ic5y** [comment]
Thanks, with "aliasing" I could fix my problem
