### ISSUE TITLE
Crystal is first-class citizen in Atom now.

### ISSUE THREAD

**Issue by k2b6s9j** [manastech/crystal#523]
I've been working on a couple of plugins to ensure that Crystal is, more or less, a first-class citizen in Atom. First I created a [proper grammar for the language](https://atom.io/packages/language-crystal-actual), which the text editor uses for syntax highlighting, because the last guy who tried abandoned [his package](https://atom.io/packages/language-crystal). I've sent a report to the guys at Atom.io about the abandonware status of the other guy's package, so hopefully some time soon they will remove his package and resolve the confusion caused by having `language-crystal` and `language-crystal-actual` packages in the directory.

As well, I've created a [linter package for Crystal](https://atom.io/packages/linter-crystal) which runs the file currently being edited through the Crystal compiler, and if the compiler returns any errors the editor will display them on screen. 

However, there is a small issue with the linter package where I cannot properly work around the terminal bolding characters. If it isn't too much trouble I'd like to request a command-line parameter for the compiler which removes the bolding, and displays errors in plain-text.

Sorry about the ranty not-really-an-issue issue. Just thought I'd drop in and tell you guys about the advances I've made with Atom and Crystal.

**Comment by k2b6s9j** [comment]
Just thought I'd also add real quick that my grammar brings the possibility of having proper syntax highlight on GitHub. I'll look more into this soon.

**Comment by asterite** [comment]
What rant? This is AWESOME!! :smiley: :grinning: :smile: :smiley_cat:

We really need a good grammar for text editors. For Sublime Text we are using a modified grammar based on Ruby, but it would be nice to have a real grammar for Crystal and apply it in Atom, Sublime Text, Vim, GitHub and others. For example macros are what, right now, break most text files. This is [one example](https://github.com/manastech/crystal/blob/master/src/struct.cr).

I agree with you about the no-color option. I checked how clang and rustc do it. In clang it's an option called `-fno-color-diagnostics`. In rustc they have a flag `--color` which can be auto, always or never. "auto" is the default, and it means coloring is on if the output is a tty. But @jhass thinks, and I agree with him, that this might not be a good default: what if you are editing code from an ssh terminal? I'd like colors there too.

So, we can have colors on by default, and add an option `--no-colors`. What do you think?

**Comment by asterite** [comment]
I'm also curious, how did you create the grammar?

**Comment by jhass** [comment]
+1 to `--no-colors`.

**Comment by k2b6s9j** [comment]
I love the `--no-colors` parameter. Having colors on by default and turning it off when need to parse sounds fantastic. When I made the Swift Linter for Atom I remember telling the compiler to run without colors.

In terms of grammar the creation for Atom was semi simple. I started by forking their Ruby Grammar and stripping what didn't apply, and slowly adding what greatness was added that makes Crystal the language it is. Things like `enum` and `lib` were almost trivial, but the new method definitions and function definition were a little more complicated, but not impossible. For those I based some of it off of the Atom Scala grammar. Some of the work I did in the past little bit I haven't posted yet, but I will post it bit by bit.

Remarkable some of the more confusing grammar was the documentation grammar. I wasn't sure if I should keep the Yarddoc stuff. But I'm thinking I'll experiment with replacing the Yarddoc implementation with a new Markdown based documentation stuff.

But yeah. More rant writing. Gotta love it. Can't wait to see what you guys think about what happens, I think Atom is a very promising and capable editor that can go a very long way.

**Comment by asterite** [comment]
I finally chose `--no-color` as the name (a bit shorter). Feel free to reopen this issue if you need anything else (or open another one).

**Comment by k2b6s9j** [comment]
Fantastic! Thanks. I'll update the linter when I get my hands on the updated compiler.

**Comment by k2b6s9j** [comment]
My Atom grammar, has about reached the point now where most Crystal files can be read and edited without a lot of funkiness now. Even though there may be some funkiness with method definitions, due to the way the Atom guys originally did Ruby definitions. But the method issues are not too jarring, just a slight discoloration.

**Comment by asterite** [comment]
@k2b6s9j I just tried your pakcage and it looks great! :-)

I also installed the linter but when I have errors nothing happens. Where can I see them? Do I need to configure something in Atom? (First time using it)

**Comment by k2b6s9j** [comment]
Did you install `linter-crystal` and the central `linter` package. Atom doesn't currently install packages dependencies from apm for you, it does do npm though.

There's a slight issue with the linter ignoring line number right now. I'm going to go in and look at that later today.

**Comment by k2b6s9j** [comment]
Oh, and thanks! :smile: I was a little worried that some of the Ruby language artifacts would completely screw up some of the Crystal stuff, but it's looking like right now I just need to do some general tuning and cleaning.
