### ISSUE TITLE
Respect CC?

### ISSUE THREAD

**Issue by kirbyfan64** [manastech/crystal#525]
It would be great to build using a custom C compiler. As far as I know, Crystal currently ignores the CC environment variable.

**Comment by asterite** [comment]
Sounds good. Right now we are using `cc`. I checked `ENV["CC"]` and it's empty in my case. Is the "CC" environment variable usually used for this?

**Comment by kirbyfan64** [comment]
@asterite Yes. Most builds will check the CC variable and fail to whatever they want the default to be (in this case, `cc`).

**Comment by jhass** [comment]
Note that our `cc` call is just for invoking the linker, we already compiled all object files at this stage.

**Comment by asterite** [comment]
@jhass Right, I totally forgot about that. So I think it doesn't matter what linker we use, right?

**Comment by jhass** [comment]
I'd say it does, you still may have it in a location that's not on your  `$PATH`, for whatever strange reason, or want to point it to a wrapper script that adds some flags in a generic way. It can't harm to respect the `$CC` convention.
