### ISSUE TITLE
Is crystal going to support better functional programming features than Ruby and concurrency models fot multithreading such as Actors or STM?

### ISSUE THREAD

**Issue by mrkaspa** [manastech/crystal#526]

**Comment by jhass** [comment]
Please note that we have a [mailing list](https://groups.google.com/forum/?fromgroups#!forum/crystal-lang) ;)

**Comment by asterite** [comment]
I'm closing this because I already answered [here](https://groups.google.com/forum/?fromgroups#!topic/crystal-lang/Bx7L-5I8-eg).
