### ISSUE TITLE
Compiler Bug: Missing hash value: rray

### ISSUE THREAD

**Issue by ruhlio** [manastech/crystal#527]
When trying to print a C union out using the string interpolation error the compiler barfs. I assume this has something to do with trying to print the union as a whole instead of specifying one of the members.

https://gist.github.com/ruhlio/6aac3db6481a1c652000

**Comment by asterite** [comment]
Thanks for reporting! We had a spec for this for C struct but not for unions, and it seems it broked. Now there's a spec :-)

Note that for C unions only their name is printed, not any of its fields.
