### ISSUE TITLE
Structs in C bindings don't work

### ISSUE THREAD

**Issue by asterite** [manastech/crystal#536]
[Related discussion](https://groups.google.com/forum/#!msg/crystal-lang/1c8Co0FbgYI/x0NwUR0cYfwJ)

Many APIs pass structs as arguments: clang, tcod, csfml.

**Comment by asterite** [comment]
This is fixed in HEAD now. The X86_64 and X86 ABIs have been implemented. I tried this with libtcod and csfml and now they seem to work fine :smiley_cat:

**Comment by jhass** [comment]
:+1:

**Comment by asterite** [comment]
@jhass I was actually going to comment the relevant commit with a :heart: :-P . it's so nice to see this finally solved. I remember we also had some issues with bindings to clang because they also return big structs, and we did some custom logic to handle that, kind of a hack. Now it's finally correct :-)

I still have to see if libtcod and csfml work in 32 bits, specs pass but I didn't try it. If you have a 32 bits machine nearby, could you try running this code and see if it shows a blank window?

```crystal
@[Link("csfml-window")]

lib CSFMLWindow
  struct VideoMode
    width: Int32
    height: Int32
    bits_per_pixel: Int32
  end

  struct ContextSettings
    depthBits: Int32
    stencilBits: Int32
    antialiasingLevel: Int32
    majorVersion: Int32
    minorVersion: Int32
  end

  type Window = Void*

  fun window_create = sfWindow_create(
    mode: VideoMode, title: UInt8*,
    style: Int32, settings: ContextSettings*
  ): Window

  fun window_is_open = sfWindow_isOpen(window : Window) : Int32
end


mode = CSFMLWindow::VideoMode.new width: 800, height: 600, bits_per_pixel: 32

window = CSFMLWindow.window_create(mode, "CSFML works!", 7, nil)

while CSFMLWindow.window_is_open(window) != 0
end
```

You can also try [this one for libtcod](https://github.com/Arcnor/crystal-libtcod) and check that a window with a white '@' appears (and not some other color).

**Comment by jhass** [comment]
Seems to work on 32bit. I get a window with the CSFML example, though it doesn't refresh. The tcod example works. Good work!

**Comment by asterite** [comment]
Yay! Thanks for trying it out. My CSFML sample doesn't refresh the window either (I just put the bare minimum code to show it), but previously it crashed.
