### ISSUE TITLE
compiler segfault

### ISSUE THREAD

**Issue by datanoise** [manastech/crystal#539]
the following code segfaults the compiler:

```crystal
def m1(a, b)
  p a, b
end

m1 1
m1 1, 2
```

**Comment by asterite** [comment]
If I try this the compiler says:

```
Error in ./foo.cr:5: wrong number of arguments for 'm1' (1 for 2)

m1 1
^~
```

What version of the compiler you are using? What OS? How did you install Crystal?

**Comment by datanoise** [comment]
For some reason when I rebuilt the compiler in the release mode, the problem disappeared.
