### ISSUE TITLE
Compiler just dies on include Comparable(T)

### ISSUE THREAD

**Issue by alex-fedorov** [manastech/crystal#544]
```crystal
struct Int
  struct Null < Int
    include Comparable(T)

    def to_s(io)
      io << ""
    end
  end
end
```

renders:

```
/usr/local/bin/crystal: line 6: 64408 Segmentation fault: 11  "$INSTALL_DIR/embedded/bin/crystal" "$@"
```

**Comment by datanoise** [comment]
works for me. Make sure that you are not using buggy llvm version. For reference, see #540.

**Comment by asterite** [comment]
Yes, must probably be the buggy llvm version, it doesn't crashes for me either.

**Comment by asterite** [comment]
@alex-fedorov Could you confirm if this was because of the buggy llvm version?

**Comment by jhass** [comment]
No response in months, closing this for now. Please reopen if you can still reproduce this issue.

**Comment by waterlink** [comment]
Yeah, this was already resolved, sorry for not closing..
