### ISSUE TITLE
Unable to use Hash#to_a in certain case

### ISSUE THREAD

**Issue by waterlink** [manastech/crystal#545]
```
in /opt/crystal/src/hash.cr:190: no overload matches 'Array({String+, Int32})#<<' with types {String, Int32}
Overloads are:
 - Array({String+, Int32})#<<(value : {String+, Int32})

      ary << {key, value}
          ^~

```

**Comment by waterlink** [comment]
I don't understand, why `{String, Int32}` doesn't count as `{String+, Int32}`..

**Comment by asterite** [comment]
@waterlink It's because of [this bug](https://github.com/manastech/crystal/issues/357). You can use the workaround of using `record` in the meantime until we implement it :-)

**Comment by waterlink** [comment]
I see. But in that case tuple is formed by `Hash#to_a`, so I have no control over it..

**Comment by waterlink** [comment]
I'm using workaround with `Hash#each` and accumulating in local variable (yuck).

**Comment by waterlink** [comment]
I'm closing this because it is a duplicate
