### ISSUE TITLE
String#to_i (and related) should raise on overflow/underflow

### ISSUE THREAD

**Issue by asterite** [manastech/crystal#547]
Because right now:

```crystal
puts "1234567891234".to_i #=> 1912277282
```

The same applies to `to_i64` and others. Also, the parsing should support underscores, like in Ruby.

Additionally, it would be nice to have a method somewhere that strictly parses an integer and raises if it's not (in Ruby it's the `Integer` method, but we don't have methods that start with uppercase).

Some days ago I was thinking that we could have a generalized mechanism for converting between types given that we have overloads. For example:

```crystal
class String
  # These overloads match against types, not instances (because of .class)
  def to(type : Int32.class)
    # convert self to Int32
  end

  def to(type : Int64.class)
    # convert self to Int64
  end
end

"123".to(Int32) #=> 123
```

Of course we can leave `to_i` because it's short and convenient. But with this generalized `to` method anyone can define a way to convert a String to some other type by reopening it, without fearing that the method name is already taken (well, someone could have defined a way to convert to that same type already, but you should do that for your library types, not others').

As you can see, the `type` argument is not used inside the method, it's just for selecting an overload. In this way you could have, for example, `String#to(JSON)` (if we really wanted that), and that would only mean "convert it to JSON", not necessarily convert it to an instance of the JSON type.

This also allows you to do a dispatch at runtime:

```crystal
target_type = some_condition ? Int32 : Int64
"hello".to(target_type)
```

Otherwise you'd have to repeat the invocation (there's no `send`).

Then maybe we can have `String#to!` to make a strict parsing like Ruby's `Integer`.

Comments? Ideas?

**Comment by kirbyfan64** [comment]
I would some way to disable overflow checks in release mode for speed reasons. Other than that, this seems great.

**Comment by Exilor** [comment]
I think ```123.to_u64``` looks better (and it's shorter) than ```123.to(UInt64)```.
As for strict parsing... I'd enable it with an optional boolean argument for ```to_i```.

**Comment by unixlife** [comment]
At first I found to(JSON) and to(Int32) confusing because the first one would presumably return a string suitable for use in a JSON document, whereas the second is returning a string as a different type. str.to(JSON) reads nice though.

**Comment by ssvb** [comment]
@kirbyfan64 The overflow check chould be relatively cheap, considering that it is already a slow string handling operation. If we apply the very similar reasoning, bounds checking should be also disabled for speed reasons on indexing arrays (there it negatively impacts perfromance for real). But in the case of arrays, it is possible to workaround the issue by getting access to the buffer pointer instead. IMHO the Ruby compatible way of doing things should preferably keep safeguards against runtime failures. And the "to_i" method is originating from Ruby, where in fact no overflows are possible because integers can be arbitrarily large. The other Crystal-specific and less safe methods can probably omit bounds checking for performance reasons.

@asterite What about also adding a new conversion function, which could return the (Int32 | Nil) union? Something like this:
```
class String
  def to_i?
    # Fix me to provide a performance optimized implementation here
    tmp = to_i64
    if tmp < -0x80000000 || tmp >= 0x80000000
      nil
    else
      tmp.to_i32
    end
  end
end

def inspect_conversion_result(str)
  puts "Original string before conversion: '#{str}'"
  val = str.to_i?
  puts "The value before branching: '#{val}' is #{typeof(val)}"
  if val
    puts "In the true branch: '#{val}' is #{typeof(val)}"
  else
    puts "In the false branch: '#{val}' is #{typeof(val)}"
  end
  puts
end

inspect_conversion_result("1234567891234")
inspect_conversion_result("123")
```
The output of this test program:
```
Original string before conversion: '1234567891234'
The value before branching: '' is (Int32 | Nil)
In the false branch: '' is Nil

Original string before conversion: '123'
The value before branching: '123' is (Int32 | Nil)
In the true branch: '123' is Int32
```
If I understand it correctly, if the user actually checks the returned value before using it, then there should be no performance problems (in the 'true' branch, the compiler can see that the value is Int32 and not a union anymore).

**Comment by ssvb** [comment]
Hmm, I was a bit too slow to realize that the array indexing does not only have somewhat similar performance considerations, but in fact has exactly the same semantics and even introduces the []? operator (with the same '?' suffix). So if the "to_i", "to_i32", "to_i64", etc. methods get changed to raise an exception when the value does not fit and the new "to_i?", "to_i32?", "to_i64?" methods get introduced to return a union of (Nil | Int), (Nil | Int32), (Nil | Int64), then this behavior is perfectly consistent with the way of handling arrays indexing. If @asterite and the others do not have any objections, I can try to implement this code myself.

**Comment by ssvb** [comment]
@Exilor 
> As for strict parsing... I'd enable it with an optional boolean argument for to_i.

IMHO it would be preferable to have the default "to_i" behaviour to raise an exception on bad input (similar to how array indexing raises an exception when the index is out of range). This should simplify porting the existing code from Ruby and ensure that the bugs are caught early and we are not passing the incorrectly converted numbers further.

I have had a bit of troubles with handling Int64 integers when converting Ruby code to Crystal, starting with the use of "to_i" method which silently returns incorrect data for the numbers that are too big to fit into Int32 type. And finally the #558, #568 issues when trying to store Int64 numbers in arrays (and sometimes mixing them with Int32 numbers) and the #567 issue on mixed Int64 / Int32 arithmetics. Hopefully this all can be improved.

**Comment by asterite** [comment]
@ssvb Yes. In fact I'd also like `to_i` to raise an exception for things like `"hello".to_i`, where Ruby (and C) would return 0. Raising is not harmful because in the normal code path you would get a valid integer, and I think you do want to know when you get an invalid number. Then we can have `to_i?` and others, so the user can choose if she wants an exception or to explicitly deal with that error. I think I like that we have both options in many cases: "I prefer an exception here" or "I prefer to deal with this right now".

If you want to implement this, please do so! It's a nice small task/exercise, and you'll help Crystal and everyone using it :-)

Some advice/considerations to do it:
1. Use the string's internal buffer (`to_unsafe` or `cstr`) and `bytesize` to move from left to right. I think you can go byte by byte instead of char by char (using a `CharReader`) because numbers and underscore in UTF-8 are represented with a byte that's less than 128, so you'd stop in the first non-number non-underscore byte.
2. Leading whitespaces are OK, and also trailing non-numbers. "  123  ".to_i and "123hello" should give 123 as a result.
3. Support underscores. "123_456" should give 123456 as a result.
4. I think I would implement `to_i64?` or `to_u64?` first and then for `to_i32` and smaller sizes check if the value fits. The non `?` methods just raise on nil. I guess the trickiest part is to check the biggest integer overflow/underflow cases. Crystal's lexer has code to deal with this, maybe you can get some inspiration from there.
5. Specs for everything ;-)
6. Optional: compare the performance with Ruby's to_i. If it's the same performance or faster, we are good. Ruby definitely must be doing more work than us.

**Comment by ssvb** [comment]
@asterite Thanks for all the hints, they are very helpful. I think that I will have time for doing this exercise on the weekend :-)

**Comment by asterite** [comment]
@ssvb I finally decided to implement this. There's a slight difference from Ruby: when doing `"hello".to_i` Ruby gives zero, but I decided to raise in that case. There's also `"hello".to_i?` for getting `nil` back, and also `"hello".to_i { 0 }` (or just `"hello".to_i? || 0`) for getting Ruby's behaviour. It always bugged me that `0` is returned for invalid numbers because then you can't know if you got a zero or an invalid number.

**Comment by jhass** [comment]
Just as an aside, the Ruby version for a raising conversion is `Integer(str)`, see `Kernel#Integer`.

**Comment by asterite** [comment]
@jhass Yes, I know about `Integer()`, but it has a slightly different semantic. For example `Integer("123hello")` raises, while `"123hello".to_i` returns 123. But then you have `Integer("0x123") #=> 291` and `"0x123".to_i #=> 0`. It seems there's no consistency.

In fact, maybe I'd like `to_i` to behave exactly like `Integer`, but without the "0x" and other suffixes (maybe with an optional boolean to enable this). In what cases you want "123hello" to be valid? That's maybe asking for trouble.

In Python it raises. In D it raises. I tried to convert a string to integer in Rust but couldn't find how to do it (I found something about `from_str` in Google but it didn't compile), but it probably returns None for the "123hello" case.

Would it be bad if we changed the semantic there to also raise, like every other language out there?

**Comment by jhass** [comment]
No, I would welcome that in fact. I was just mentioning that for completeness.

**Comment by asterite** [comment]
@jhass Cool! I'll check with @waj, and if nobody oposes, I'll change the semantic. I do, however, like that leading and trailing whitespaces don't trigger an exception (for example it's useful for interpreting lines of a file as numbers without having to remove the `\n` char, or accidental leading spaces).

**Comment by jhass** [comment]
I disagree, either it's "try to be smart" or "this is a string or nothing, call `String#strip` yourself".

**Comment by asterite** [comment]
Oh... but `String#strip` allocates memory.

What if we have options?

```crystal
def to_i(base = 10, ignore_whitespace = true, allow_prefixes = false, allow_underscores = false)
```

* `ignore_whitespace` would be for leading and trailing, I don't think it's worth having two options here
* `allow_prefixes`: for checking `0x`, `0b`, etc.
* `allow_underscores`: the obvious meaning

For the usual case it works with the whitespace tolerance (for example Python does this), but then you can get more strict or liberal with the other options, if that's what you want. Or we can have the default to be very strict, but I think the whitespace thing is pretty common to want.

**Comment by jhass** [comment]
Well, can't say much against choice I guess ;)

**Comment by asterite** [comment]
:-)

It always bothers me to find in some library that there's a method that *almost* does what I need. Then I have to reimplement it with that tweak, or just do it in another, less efficient way. So having many choices here I think is good. Like `Int#to_s` where you can choose lowercase or uppercase letters.

I'll make the changes soon.
