### ISSUE TITLE
strange is_a? behavior 

### ISSUE THREAD

**Issue by datanoise** [manastech/crystal#548]
The following code:

```crystal
class A; end
class B; end
class C; end

a = A.new
c = C.new

if a.is_a?(A|B)
  puts "ok"
end

if c.is_a?(A|B)
  puts "not ok"
end
```
prints:

```
ok
```

but if we add a common superclass:

```crystal
class Base; end
class A < Base; end
class B < Base; end
class C < Base; end

a = A.new
c = C.new

if a.is_a?(A|B)
  puts "ok"
end

if c.is_a?(A|B)
  puts "not ok"
end
```
it prints:

```
ok
not ok
```

**Comment by asterite** [comment]
Bug indeed. The problem is that the type of `A | B` becomes `Base+` (means: Base or any of its subclasses), but in that case (`is_a?`) the compiler shouldn't merge the types. I'll fix it soon :-)
