### ISSUE TITLE
Strange behavior of the "while" expression

### ISSUE THREAD

**Issue by ssvb** [manastech/crystal#549]
Executing the following snippet as Crystal code differs from Ruby:
```
   # Trying to implement https://code.google.com/codejam/contest/544101/dashboard

   original = [
     "BB.",
     "RBR",
     "RBR",
   ]

   transformed = original.map {|l|
     new_l = l.chars.select {|ch| ch != '.' }
 #    if new_l.size < l.size
      new_l = ['.'] + new_l while new_l.size < l.size
 #    end
     new_l
   }

   transformed.each {|l| p l.join }
```

Ruby result (correct):
```
".BB"
"RBR"
"RBR"
```

Crystal result (incorrect):
```
".BB"
".RBR"
".RBR"
```

Reproducible with both Crystal 0.6.1 and the current git.

**Comment by asterite** [comment]
It's not a bug, it just behaves different than Ruby in this case.

In Ruby if you do:

```ruby
puts 1 while false
```

Nothing is printed. However, if you do this:

```ruby
begin
  puts 1
end while false
```

then 1 is printed. We think that's inconsistent: a trailing `while` executes its body once, or not, depending if you surround the expressions with `begin ... end`. Imagine you start with one expression and then you refactor it to add more expressions, the semantic changes.

In Crystal, a trailing while always means "execute the body at least once".

Here are the [docs](http://crystal-lang.org/docs/syntax_and_semantics/while.html). And also see [this](http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-core/6745).

**Comment by jhass** [comment]
Well, Matz says there he'd like to remove the behavior where it executes once, not make both versions run once. And I have to agree that's the more expected and consistent behavior, it's in line with modifier-if/modifier-unless.

Can't we tell people to do the
```ruby
loop do
  body
  break if cond
end
```
for a do-while loop?

**Comment by ssvb** [comment]
@asterite Thanks for explaining, it makes sense from this point of view. But I'm still not sure it was a very good idea.

So far I'm very much impressed with Crystal and converting Ruby code to Crystal turned out to be much easier than I expected. Basically, it's mostly just a matter of running the compiler and fixing the reported compilation errors by adding type annotations, converting arrays with mixed data types to tuples, etc. This whole process is reasonably straightforward and the modifications are very logical and clearly justified. And then the code typically happens to work correctly.

The subtle difference in the "while" expression handling between Crystal and Ruby was an unpleasant surpriese though. At the end of the day, it is kind of like the Jonathan Swift's "big endian" vs. "little endian" struggle, in the sense that you can come up with reasons in favour of either of these solutions and none of them seems clearly superior. However the Ruby's behaviour has been around for a much longer time and a lot of people are already used to it, so with everything else more or less equal, I wouls be in faviour of better compatibility. I'm particularly worried that there is no automatic error or warning for this type of construct, which happens to be syntaxically valid for both Crustal and Ruby, but has different behaviour. This seems to be a rather nasty trap for the people trying to convert their existing Ruby code to Crystal.

As @jhass mentioned, the Ruby way of handling the one-liner variants of "while/unless" is consistent with the one-liner variant of "if". The "while" expression may be also seen as a more persistent variant of "if" and one may sometimes change between the if and while keyword when refactoring code.

The Ruby's one-liner if/while variants are kind of like the syntax sugar of curly brackets removal in the C code to make it more compact and readable:

```
    if (<cond>) {
        <code>;
    }
    while (<cond>) {
        <code>;
    }
```
vs.
```
    if (<cond>)
        <code>;
    while (<cond>)
        <code>;
```

The "begin \<code\> end while \<cond\>" loop variant in Ruby is more like the following loop variant in C:
```
    do {
        <code>;
   } while (<cond>);
```
And in my experiance, this seems to be a rather rarely used construct. I can totally see why Matz would want to get rid of "begin \<code\> end while \<cond\>". How common is the "begin <code> end while <cond>" loop variant anyway? By quickly grepping the Crystal compiler code itself, I don't see it being massively used anywhere, one occurence seems to be only https://github.com/manastech/crystal/blob/master/spec/compiler/codegen/while_spec.cr#L17 (which is just the test for this functionality).

IMHO it would be great if Crystal and Ruby remained as much compatible as possible and avoided the dangerous "same syntax, different behaviour" stuff. Just for the sake of following the http://en.wikipedia.org/wiki/Principle_of_least_astonishment

**Comment by asterite** [comment]
@jhass @ssvb Definitely. I think removing the trailing `while` and leaving an error saying to use the `loop ... break end` construct would be the best option. I also find the trailing `while` to be rarely used, both in the one-liner form and in the begin/end form. I think I always have to stop and think "wait, was this executed at least once or not?".

If we remove it and leave the error, porting Ruby code to Crystal won't give unexpected results, only compile-time errors you will need to correct.

I'll ask waj the next week.

**Comment by mverzilli** [comment]
This is pretty common in natural languages: http://en.wikipedia.org/wiki/False_friend.

"No false friends for rubyists" would be a great goal to add to Crystal's design goals :)

**Comment by ssvb** [comment]
@asterite Thanks! Removing these trailing "while" variants (including the one-liner) at least for some grace period also seems like the best option to me. Changing the behaviour of the one-liner "while" from one to another may potentially wreak havok and cause unexpected regressions for the users. But removing it altogether should be relatively safe.

I myself have been using the one-liner "while" variant (the Ruby style), got used to it and don't see anything wrong with it. But replacing it in my code is not a big deal as long as the compiler just rejects it.

@mverzilli Indeed, that's a good link :)

**Comment by ssvb** [comment]
This can be resolved with a relatively [simple patch](https://github.com/ssvb/crystal/commit/cd63433157275ad15008f9b88d750d19f1ce998b) for the parser (which is not very clean though). Only [one place](https://github.com/ssvb/crystal/blob/512650e1a34023678d56ef61e4c631a0ecd128fe/src/compiler/crystal/syntax/parser.cr#L64) in the current Crystal code ever uses the ```"begin <code> end until <cond>"``` construct. And the single-line variant of while/until is never used at all.

**Comment by ysbaddaden** [comment]
Actually, I feel the opposite:

- I like trailing while/until because they spell very nicely, like `work until done` compared to `until done; work; end`
- Crystal's behavior is inconsistent: `work if false` and `work while false` are legitimately expected to behave the same: ie. to never invoke `work` because the condition is false

To be fair, having `begin; end while false` run the body once in Ruby *is* inconsistent with said behavior, and that shouldn't be reproduced (or even used at all). I think there are better alternatives (eg: loop + break).

**Comment by jhass** [comment]
To clarify, I'm with @ysbaddaden here, while I rarely use the modifier while, I use a do-while loop even less in Ruby due to the better alternatives provided in its standard library. So my vote goes for

* Make `begin; expression end while condition` invalid and a parse error.
* Change `expression while condition`s behaviour to never run expression if condition is false initially, that is rewrite it to `while condition; expression; end;`

**Comment by jessedoyle** [comment]
I recently encountered this difference while working on a previous pull request.

Coming from Ruby, the result from a suffix-while/until loop surprised me and I believe the difference in execution is significant enough to cause considerable headaches for anyone new to Crystal (as code executes where the developer may not expect it to).

Furthermore, I do believe that there are situations where a `while` or `until` suffix makes code more readable.

Therefore, I agree with @ysbaddaden and @jhass that the `begin; end while condition` variant should be a parse error, and that the expression is not executed once when the condition is `false`.

I'd be happy to throw together a pull request if we can come to an agreement about the implementation!

**Comment by ozra** [comment]
Regarding the multiline variant - +1, ditch it! Using break instead.
Regarding the one liner: changing the operation from "run once" to the prefix-variant - "run zero" is _very surprising_ to _a lot_ of coders from different languages. I vote ditch both suffix variants of `while`! I know some langs that has already taken this route, and I haven't missed them there.

**Comment by ssvb** [comment]
I guess, the best course of action is just to submit a pull request. We all know that the required changes in the compiler code are rather simple. Then the pull request is either accepted or rejected. And it is not like we can reach any consensus just discussing this issue here any time soon :)

**Comment by BlaXpirit** [comment]
I agree with @jhass and @ysbaddaden 

While we're at it, this should not parse either:

```crystal
begin
end if expr
```

**Comment by asterite** [comment]
Why not remove the suffix `while`? That's the easiest thing to do. They are so uncommon that using `loop { ... break if ... }` doesn't hurt, in my opinion.

**Comment by jessedoyle** [comment]
@asterite : I would prefer the removal of the suffixes over the current behaviour.

With that begin said, I think the syntax is common enough that you'll see issues/pull requests in the future regarding the "lack of functionality".

But I think removal is the best option now - after looking into a pull request to fix the functionality, I discovered this code:
``` crystal
i = 0

while true
  i += 1
  break
end while false

puts i #=> 1
```
 which actually compiles. Removal of the suffixes doesn't let terrible code like above compile.

**Comment by asterite** [comment]
I added the reasons of the removal to the [FAQ](https://github.com/manastech/crystal/wiki/FAQ#why-trailing-whileuntil-is-not-supported-unlike-ruby).

**Comment by ytti** [comment]
I'd like to see trailing while make come back. I just wanted to use it in simple scenario

def run_loop
  loop do
    process_beat @ch.receive while ! @ch.empty?
    do_something_else
  end
end

I would want body to be never ran, if condition is false. 

To me this is not about being more ruby like, to me it's about removing useless decorations in simple cases.

**Comment by ozra** [comment]
@ytti, I agree the expected behaviour - in my eyes - is for suffix variants to behave exactly _as if_ they had been expressed as regular prefixed constructs. But not ruby, and the Crystal motto seems to be that if something looks like Ruby but acts a different way - it will be a source of confusion and bugs.

**Comment by jhass** [comment]
As already stated here a couple of times, Ruby **does** have that behavior, just not in `begin; body; end while condition`.

**Comment by ozra** [comment]
My mistake of confusing the subject. It's the suffix-if's that does not.

**Comment by jhass** [comment]
modifier-if behaves almost exactly like a regular if in Ruby too, the differences are completely negligible. In Crystal they're just the same.

**Comment by kirbyfan64** [comment]
@jhass

> modifier-if behaves almost exactly like a regular if in Ruby too, the differences are completely negligible. In Crystal they're **just the same.**

*cough*

```crystal
if something

```

**Comment by jhass** [comment]
Yes, how is that different from
```cr
if something
  a = 1
end
if a
  puts a.abs
end
```
in Crystal?

**Comment by kirbyfan64** [comment]
@jhass Wait...wasn't there a point that that (or something similar) would be a type error because of the way suffix ifs mixed with type inference? Was it fixed and I didn't realize it?

**Comment by jhass** [comment]
I don't remember anything ...

**Comment by ytti** [comment]
So how do we decide? Or is @asterite against it, so no discussion is necessary?

I would vote to enable it for both use-cases and never evaluate unless while is true. 

My rationale is, I want Crystal to feel like high-level language, even with cost of parser complexity.

**Comment by asterite** [comment]
@ytti This issue is closed, we already decided to remove trailing `while`. Please see the [FAQ](https://github.com/manastech/crystal/wiki/FAQ#why-trailing-whileuntil-is-not-supported-unlike-ruby).

**Comment by ErikAGriffin** [comment]
I realize you have closed the issue and outlined the reasons in the FAQ. However if this issue ever becomes reopened I would like to express my desire for Option 3 as outlined in the [FAQ](https://github.com/manastech/crystal/wiki/FAQ#why-trailing-whileuntil-is-not-supported-unlike-ruby) to be the choice forward.

I understand that `puts "hello" while false` may be confusing to newcomers, but since it is the behavior in ruby I don't think its too much to ask for people to become familiar with it.  Personally I just think it so much easier and cleaner to have that single line of code rather than
```
while false
  puts "hello"
end``` 

Having the option there, especially after neither has been accepted, will not be very confusing to newcomers or people currently using the code base.  If they choose to use it now, they will know that `puts "hello" while false` will not print out hello, and any new code added intending for that to be so will quickly discover the issue and then find this thread.

**Comment by LevitatingBusinessMan** [comment]
I am a couple of years late to the party, but I agree with @ErikAGriffin here. Maybe a new issue should be opened for it.
Option 3 was the better option by far.

I have been trying to port some code from Ruby to Crystal, and I actually use `<code> while <condition>` a _lot_. And my code wouldn't look the same if I used 3 lines for it instead.
