### ISSUE TITLE
`crystal doc` shouldn't recursively delete

### ISSUE THREAD

**Issue by BlaXpirit** [manastech/crystal#554]
First of all, people can lose files by putting them in the *doc* folder.

[generator.cr#L10](https://github.com/manastech/crystal/blob/6f3037e6dd4cd6933d3433f63011f77c8d0107e9/src/compiler/crystal/tools/doc/generator.cr#L10)
Don't know what kind of interpolation is used here, but it looks scary.

This also disables the workflow of having a copy of the repo with *gh-pages* branch as the *doc* folder.

I think files shouldn't be deleted at all. Leftover files are a rare occurence anyway, and they are never harmful. If someone wants to clean the folder, they can easily delete it themselves.

I suggest simply overwriting files without specifically deleting anything.

**Comment by asterite** [comment]
You are right.

I wonder how can we make it easy to generate docs and put them immediately in the `gh-pages`...

**Comment by BlaXpirit** [comment]
> how can we make it easy to generate docs and put them immediately in the gh-pages

So let me describe
> the workflow of having a copy of the repo with gh-pages branch as the doc folder.

(Prerequisites: doc folder does not exist in your project)

As mentioned, you copy your project's repository inside itself, naming the folder "doc". Go to it and `checkout gh-pages`.

Now `crystal doc` will generate docs right into the folder with *gh-pages*, ready to commit.

Optional: delete *gh-pages* branch in main and non-*gh-pages* branches in *doc*.

**Comment by jhass** [comment]
There's also a nice script which couples the two .git repos stronger. Make sure `doc` does not yet exit and run: `/usr/share/git/workdir/git-new-workdir . doc origin/gh-pages`

**Comment by waterlink** [comment]
I don't have such script on Ubuntu 14.04..

--
Best Regards,
Alexey Fedorov,
Sr Ruby Developer, Clojure Developer, Rust Developer,
+49 15757 486 476

2015-04-19 17:56 GMT+03:00 Jonne Haß <notifications@github.com>:

**Comment by jhass** [comment]
Debian probably split it into its own package or something, look out for git-contrib or something.

**Comment by waterlink** [comment]
heh, looks like building them from source.. I can't find package and all
google results tell about building it from source..

--
Best Regards,
Alexey Fedorov,
Sr Ruby Developer, Clojure Developer, Rust Developer,
+49 15757 486 476

2015-04-19 20:53 GMT+03:00 Jonne Haß <notifications@github.com>:

**Comment by jhass** [comment]
It's [a simple script](https://github.com/git/git/blob/master/contrib/workdir/git-new-workdir), could always just vendor that in I guess.

**Comment by waterlink** [comment]
Makes sense. Will there be any problems with licensing? Git has LGPL-2.1..

--
Best Regards,
Alexey Fedorov,
Sr Ruby Developer, Clojure Developer, Rust Developer,
+49 15757 486 476

2015-04-19 22:03 GMT+03:00 Jonne Haß <notifications@github.com>:

**Comment by jhass** [comment]
I doubt anyone would complain if we keep the license note at the top of the file, after all it would just be shipped with crystal, not built into the binary or something.

**Comment by waterlink** [comment]
Yes, you are right, and it will not be used by end-user apps/libraries
built with crystal.

--
Best Regards,
Alexey Fedorov,
Sr Ruby Developer, Clojure Developer, Rust Developer,
+49 15757 486 476

2015-04-19 22:29 GMT+03:00 Jonne Haß <notifications@github.com>:
