### ISSUE TITLE
crystal deps install should do a shallow clone

### ISSUE THREAD

**Issue by Arcnor** [manastech/crystal#555]
It doesn't seem that dependencies are cloned using shallow clones (at least the github ones). Unless there is a good reason not to, we don't need the full history of the repo when getting dependencies, do we?

**Comment by jhass** [comment]
With Git 1.9 this is indeed feasible. However prior to that shallow clones do not support fetch or pull, making updating them impossible.

**Comment by asterite** [comment]
We can always clone again in the case of an update if shallow clones don't support fetch or pull.

**Comment by Arcnor** [comment]
Yes, I was thinking the same (but forgot to reply, it seems), although that
poses a problem if the repo itself is very big, but I'm guessing libraries
are going to be small and not full of resources?

**Comment by ysbaddaden** [comment]
I recently saw this commit for Bower that is related: https://github.com/bower/bower/pull/1628

**Comment by jhass** [comment]
I think we can close this in favour of #1357 and/or a specific issue at https://github.com/ysbaddaden/shards too.

**Comment by asterite** [comment]
@jhass Definitely! Feel free to close any issues related to the package manager, the discussion can continue in #1357 or in shards itself.
