### ISSUE TITLE
lib - incorrect struct matching?

### ISSUE THREAD

**Issue by ic5y** [manastech/crystal#562]
So, I was trying to make a SDL2 wrapper, but I found something interesting when linking to SDL2 library. SDL's [events are a C unions](http://hg.libsdl.org/SDL/file/704a0bfecf75/include/SDL_events.h#l498), so I made a struct Event in Crystal, and put each type of event in the struct, so it's look exactly like in SDL, with the same types, names, order.

When I wanted to process a Keyboard event, it filled the events whose comes before KeyDown event(CommonEvent, WindowEvent) with the Keyboard events data. So e.g. WindowEvent's padding1 member contained KeyboardEvent's state member.

I suppose it's because the WindowEvent and CommontEvents are null on a KeyboardEvent, so it (SDL I think) thinks that the first byte to write is happens to be CommonEvent's data.

I hope I could properly write down the problem

**Comment by jhass** [comment]
Use a union to bind a union: http://crystal-lang.org/docs/syntax_and_semantics/c_bindings/union.html

* https://github.com/weskinner/crystal-sdl2/blob/master/src/lib_sdl2.cr#L158
* https://github.com/TheBlueCrane/SDL2-Crystal/blob/master/src/lib_sdl2.cr#L195
* https://github.com/farleyknight/crystal-sdl/blob/master/lib/sdl_main.cr#L149
* https://github.com/Arcnor/crystal-raw-sdl2/blob/master/src/libsdl2.cr#L911

**Comment by ic5y** [comment]
Thanks, I totally forgot about union type.
