### ISSUE TITLE
Fix Array#+ for mixed element types

### ISSUE THREAD

**Issue by ssvb** [manastech/crystal#568]
This fixes a runtime failure in following testcase:
```
a = [1, 2, 3]
a += [4294967296]
p a
```
In the case if we are adding together two arrays of different types and the type of the resulting array changes (to a union), elements need to be copied one by one instead of memcpy'ing raw memory buffers.

Some things still can be improved. For example, when adding Array(Int32) and Array(Int64) together, it might be better to return Array(Int64) instead of Array((Int32 | Int64))

**Comment by asterite** [comment]
You are right! I think at one point we had Pointer#copy_from and others implemented in Crystal itself, copying value by value. I think changing that to use llvm intrinsics wasn't a good decision. I think I'll change it back, LLVM should still be able to optimize these loops.

**Comment by ssvb** [comment]
@asterite 
> I think changing that to use llvm intrinsics wasn't a good decision. I think I'll change it
> back, LLVM should still be able to optimize these loops.

Looks like using the llvm intrinsics was actually a good decision. For example, it is possible to use the following test program as a benchmark:
```ruby
require "benchmark"
Benchmark.bm { |x|
  x.report("unshift") {
    a = [0] ; 80000.times { |i| a.push(i) }
    # This is unreasonably slow in Crystal because of actually moving
    # the whole buffer in memory for every "shift" method call!
    while a.size > 0
      a.shift
    end
  }
}
```

== before (with 93e5d321e16ae0d84fedc7cc45478a8cad7f8730) ==
```
$ ./crystal run shiftperf.cr 
              user     system      total        real
unshift   0.003799   0.000000   0.003799 (  2.495777)

$ ./crystal run --release shiftperf.cr 
              user     system      total        real
unshift   0.003799   0.000000   0.003799 (  2.492066)

```
== after (with bf2912d56478154ddf8fa7a02c879ad1048bf57a) ==
```
$ ./crystal run shiftperf.cr 
              user     system      total        real
unshift   0.066483   0.000000   0.066483 (  43.612190)

$ ./crystal run --release shiftperf.cr 
              user     system      total        real
unshift   0.004654   0.000000   0.004654 (  3.056545)
```

Before the fix, shifting data in the array was using the SSE2 optimized memmove function from glibc, which is always faster than the one by one copy loop:
```
$ perf record ./shiftperf
# perf report
    99.44%  shiftperf  libc-2.20.so       [.] _wordcopy_fwd_dest_aligned      
     0.11%  shiftperf  libc-2.20.so       [.] __memmove_sse2                  
     0.05%  shiftperf  libgc.so.1.0.3     [.] 0x0000000000011c9e              
     0.04%  shiftperf  [kernel.kallsyms]  [k] debug_smp_processor_id          
     0.04%  shiftperf  libc-2.20.so       [.] __memcpy_sse2_unaligned         
     0.03%  shiftperf  [kernel.kallsyms]  [k] apic_timer_interrupt            
```

**Comment by ssvb** [comment]
I was originally trying to implement the fix in the following way (nothing particularly spectacular there), but somehow it just got reported as a bug instead of a pull request: https://github.com/ssvb/crystal/commit/f47eb714071fb262ed1e13bfcbd79eb44b5d00a5

But if the llvm buffer copy is kept, there could be indeed potentially other regressions similar to Array#+. Maybe Array#concat, Array#replace and some other places.

**Comment by ssvb** [comment]
BTW, thanks for taking care of the crasher problem. It is always better to have something that is slow and correct than fast and buggy :-) I have submitted a new bug for the performance issue, so that it can be tracked there.
