### ISSUE TITLE
Array of generic class issue

### ISSUE THREAD

**Issue by Exilor** [manastech/crystal#578]
```crystal
arrays = [] of Array
arrays << [1, 2, 3]
arrays[0][0].abs # => undefined method 'abs' for String
```
```crystal
arrays = [] of Array(Int32)
arrays << [1, 2, 3]
arrays[0][0].abs # => works
```

This example is super weird:
```crystal
array = [] of Matrix
array << Matrix.identity(5)
0 + array[0][0] # => 1 (works)
```
```crystal
array = [] of Matrix
array << Matrix.identity(5)
Matrix.new(2, 2) { |i, r, c| {r, c} } # note the {Int32, Int32}
0 + array[0][0] # => no overload matches 'Int32#+' with types (Int32 | {Int32, Int32})
```

**Comment by asterite** [comment]
The problem is that `[] of Array` is an array of *any* array, including arrays of strings, bool, etc, so it will never work.

Why do you need an array of a generic class without knowing its type?

**Comment by Exilor** [comment]
I don't need it. I'm reporting this issue because it strikes me as anomalous behavior. In my opinion if ```[] of Array``` would never work it should throw an error right there, not later when I'm retrieving an element and calling a method on it.
Especially in the second example where the type of an unrelated matrix seems to affect the array of matrices.
