### ISSUE TITLE
HTTP::Headers forced to be unique by name

### ISSUE THREAD

**Issue by porras** [manastech/crystal#581]
While testing [crul](http://github.com/porras/crul), I found something weird. HTTP response headers are not forced to be unique (in fact the [standard](http://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html#sec6.2) is not very explicit about it, but it also *doesn't* say they must be unique). It will be generally the case, but there is at least one use case where it makes sense to have several headers with the same name: cookies.

Example with curl:

```
$ curl -v "http://httpbin.org/cookies/set?cookie1=1&cookie2=2"
> GET /cookies/set?cookie1=1&cookie2=2 HTTP/1.1
< HTTP/1.1 302 FOUND
< Date: Sun, 26 Apr 2015 20:14:28 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 223
< Set-Cookie: cookie1=1; Path=/
< Set-Cookie: cookie2=2; Path=/
...
```

The same with crul:

```
$ crul "http://httpbin.org/cookies/set?cookie1=1&cookie2=2"
HTTP/1.1 302 FOUND
Server: nginx
Content-type: text/html; charset=utf-8
Content-length: 223
Set-cookie: cookie2=2; Path=/
...
```

Only the second one is shown. This is because internally `HTTP::Headers` is a [`Hash(String, String)`](https://github.com/manastech/crystal/blob/1dcabc4db47793dc3564d4f06f21f01fdeab7d0f/src/http/headers.cr#L3) so the second one *overwrites* the first.

I had a look to what Ruby does, and it is really weird. It acknowledges the fact that the headers don't need to be unique by storing them in a `Hash(String, Array(String))` ([example](https://github.com/ruby/ruby/blob/69ba9302c5cc6a0edc2cd6e38ee233ac3b5df2d3/lib/net/http/header.rb#L59-63)), but then the access methods always return strings, and just concatenates the multiple values ([example 1](https://github.com/ruby/ruby/blob/69ba9302c5cc6a0edc2cd6e38ee233ac3b5df2d3/lib/net/http/header.rb#L101), [example 2](https://github.com/ruby/ruby/blob/69ba9302c5cc6a0edc2cd6e38ee233ac3b5df2d3/lib/net/http/header.rb#L31)). Confusing:

```
$ ruby -r net/http -e "Net::HTTP.get_response(URI.parse('http://httpbin.org/cookies/set?cookie1=1&cookie2=2')).each { |k, v| p [k, v]}"
["server", "nginx"]
["date", "Sun, 26 Apr 2015 20:31:07 GMT"]
["content-type", "text/html; charset=utf-8"]
["content-length", "223"]
["connection", "keep-alive"]
["location", "/cookies"]
["set-cookie", "cookie1=1; Path=/, cookie2=2; Path=/"]
["access-control-allow-origin", "*"]
["access-control-allow-credentials", "true"]
```

I thought that that's because Ruby's net/http is confusing in general, but I also checked a couple gems in Ruby (Faraday, Excon), and they do the same (maybe for compatibility reasons?). Typhoeus returns arrays instead (but it's based on libcurl).

So I was ready to start writing a pull request with a fix, but I don't see a clear solution (as every solution would require API changes). The internal representation would be a `Hash(String, Array(String))` (or maybe an `Array(Tuple(String, String))`), but how would be the external access?

A possible solution is to do the same Ruby does, but I find it ugly and not especially useful.

Another solution would be have all the fetching methods that currently return a `String` (`[]`but also `each`) returning `Array(String)`, but that would break all existing code for a small use case.

So I decided to just report it instead :laughing:. If I can get some thoughts on what would be the right solution, I can code it :dancer:. It can also be ignored :laughing:

**Comment by ysbaddaden** [comment]
Yes, in the HTTP protocol, a header may be repeated with different values, but the values may also be concatenated in a comma separated list. This happens regularly with cookies, and far less frequently with other headers.

It's nevertheless recommended to not store HTTP headers as a Hash. In [Prax](https://github.com/ysbaddaden/prax.cr/tree/master/src/prax/parser) i'm using a Header class that can receive many values, and then have `headers = [] of Header` in requests and responses.

**Comment by dhruvrajvanshi** [comment]
If this gets accepted, it would make my life so much easier.

**Comment by asterite** [comment]
I didn't know you could have repeated headers. Every day you learn something new :-)

I'll rewrite HTTP::Headers to take that into account. I think I'd still like it to be hash-like, so it has `[]`, for example to easily get the "Content-Length" or any header without it being O(n). The values of the hash will be `Array(String)`, and I'll probably add a method to get a key assuming it has a single value (most common case) and maybe additional getters like `content_length` and `host`. What do you think?

**Comment by asterite** [comment]
This will probably break many things, but that's why we are still on `0.x` ;-)

**Comment by porras** [comment]
@asterite that makes sense. On top of the access by name methods, it'd be nice to have an `#each` method (and make the class `Enumerable`) that wouldn't yield the `name => [values]` map but the duplicated names, something like this example naive implementation (I didn't include the method you mention to get a value assuming it's unique, but it sounds very sensible):

```crystal
class Headers
  def initialize
    @headers = Hash(String, Array(String)).new
  end

  def []=(key, value)
    @headers[key] ||= [] of String
    @headers[key] << value
  end

  def [](key)
    @headers.fetch(key, nil)
  end

  def each
    @headers.each do |key, values|
      values.each do |value|
        yield key, value
      end
    end
  end
end

h = Headers.new
h["Content-Type"] = "application/json"
h["Set-Cookie"] = "a=1"
h["Set-Cookie"] = "b=2"

puts h["Content-Type"]
# ["application/json"]

h.each do |k, v|
  puts "#{k}: #{v}"
end
# Content-Type: application/json
# Set-Cookie: a=1
# Set-Cookie: b=2
```

How does it look?

**Comment by asterite** [comment]
So, as you can see in the commit, I changed HTTP::Headers to be a wrapper around `Hash(String, Array(String))`. I preserved backwards compatibility, so doing `headers#[key]` will always give you a String. If there are many values, the are joined with commas.

Now, this comma-joining is not always correct because for example `Set-Cookie` doesn't allow that. However, most headers have only single values, so it's better that the API be comfortable for that use case. Then with `#get` and `#get?` you can get the internal arrays in case you need them.

@porras Finally, `#each` yields the key and the array of values, always, so in your case you'd had to do this:

```crystal
h.each do |k, values|
  values.each do |v|
    puts "#{k}: #{v}"
  end
end
```

I did it that way because it's easy to iterate the values, but it's hard to group them back again if they were yielded separately (maybe someone needs that).

What do you think?

Later we can in fact optimize things so each header doesn't get an array, for example we can have it be `Hash(String, String | Array(String))` and treat it differently. And then have `#each_header` or something like that that yields header/value pairs, even if duplicated. I think that will improve memory usage a bit, but I'm not sure it'll be significant.
