### ISSUE TITLE
Is there a way to execute system commands?

### ISSUE THREAD

**Issue by phortx** [manastech/crystal#586]
Like `system`, `exec` or the backticks in ruby?

**Comment by jhass** [comment]
Yes, see https://github.com/manastech/crystal/blob/master/src/process/run.cr which defines `system`, the backtick method and a general interface for both as `Process.run`.

**Comment by phortx** [comment]
Thanks. There is no chapter in the documentation, isn't it? I'll write one and open a PR, ok?

**Comment by jhass** [comment]
I see nothing at http://crystal-lang.org/docs/ too, correct, whether that's the best place to document them I'm not sure.

But there are no [inline docs](http://crystal-lang.org/api/toplevel.html#system%28command%20%3A%20String%29-class-method) for them yet too, and those are most definitely a welcome contribution!

**Comment by ssvb** [comment]
There is also http://crystal-lang.org/api/

**Comment by asterite** [comment]
@ssvb http://crystal-lang.org/api/ is generated from the inline comments in the code (using Markdown)

**Comment by gerrywastaken** [comment]
For anybody ending up here in 2020, this is the documentation page you want:
https://crystal-lang.org/reference/syntax_and_semantics/literals/command.html

Or the keyword to search for if things get moved around again is: "Command literal"
