### ISSUE TITLE
Unintentional override of Hash.fetch(key)?

### ISSUE THREAD

**Issue by regexident** [manastech/crystal#587]
While looking through the implementation of `Hash` I noticed the redundant definition of `def fetch(key)`.
From my understanding that's effectively an override of the former, so I'm assuming that this is not intentional and therefore a bug?

Lines in question:
https://github.com/manastech/crystal/blob/master/src/hash.cr#L82-99

**Comment by Exilor** [comment]
Those are overloads. One method for fetch that returns the given value if the key is missing, one that runs the block if the key is missing, and one that raises if the key is missing.

**Comment by regexident** [comment]
Sure, but isn't …

```crystal
def fetch(key)
  entry = find_entry(key)
  entry ? entry.value : yield key
end
```

… effectively redefining ("overriding") …

```crystal
def fetch(key)
  entry = @set.fetch(key) do
    if block = @block
      block.call(self, key)
    else
      raise MissingKey.new "Missing hash value: #{key}"
    end
  end
  entry ? entry.value : yield key
end
```

… as they have the very same signature (vs. "overloading" of different signatures)?

**Comment by jhass** [comment]
I can't find the second method you pasted anywhere in the source.

**Comment by regexident** [comment]
My bad, had copied the snippet from the wrong file (a refactoring of mine). Corrected my message. My questions remains the same though, I guess.

**Comment by jhass** [comment]
The second method has no yield, which counts into the method signature, thus it's an overload.

```crystal
{}.fetch(:a) { :b } # calls the first method you pasted
{}.fetch(:a) # calls the second method you pasted

**Comment by Exilor** [comment]
Maybe you're mistaking that ```@block``` variable for a block supplied to the method?

**Comment by regexident** [comment]
@jhass: Ah okay, thanks for clearing that up.
@Elixor: No, I was simply missed the effect of `yield` on the method signature

Having to scan the function's body for occurrences of `yield` to figure out the true signature may become quite tedious and error-prone for longer ones like `def delete(key)`, no? Possibly even resulting in unwanted overloads/overrides. Just a thought.

Anyway, thanks guys. Closing.
