### ISSUE TITLE
"<<" Operator for String concatenation, array push etc

### ISSUE THREAD

**Issue by phortx** [manastech/crystal#589]
Like the `<<` operator known from ruby. It seems it doesn't exist in crystal.

Is it just not yet implemented or don't you wan't to support that operator?

**Comment by jhass** [comment]
It's defined for Array, String is immutable so it makes no sense. It's defined for Int too.

**Comment by asterite** [comment]
Yes, to build a String use `StringIO`.

**Comment by ssvb** [comment]
Maybe it would be a good idea to make the compiler provide such hints to users at compile time? Like something inspired by http://clang.llvm.org/docs/LanguageExtensions.html#messages-on-deprecated-and-unavailable-attributes

**Comment by phortx** [comment]
Ok, thx :)

**Comment by phortx** [comment]
Since my question is answered, I'll close that issue.

@ssvb I encourage you to open a new issue for your suggestion :)
