### ISSUE TITLE
Typecasting seems to break creation of new instances

### ISSUE THREAD

**Issue by yyyc514** [manastech/crystal#590]
```
class B
	def initialize()
	end
end

a = [] of Tuple

a << {B, nil}

b_again = a.first[0] as B
b_again.new
```

Results in: (running compiler from master as of a day or so ago)
```
Error in ./test.cr:17: undefined method 'new' for B
```

**Comment by yyyc514** [comment]
N/m I need B.class to get the class back.

**Comment by asterite** [comment]
This is also similar to #578, it's not very convenient to use a generic type as a generic type argument. We added that for completeness, but I'm more and more convinced that it shouldn't be possible to use generic types as type arguments.
