### ISSUE TITLE
Are classes allowed inside blocks or not?

### ISSUE THREAD

**Issue by yyyc514** [manastech/crystal#595]
Invalid:

```
def blah(&block)
	with self yield
end

blah do
    class B
    end
    B.new
end

# in ./test2.cr:11: can't declare class inside block
```

Valid: 

```
def blah(&block)
    block.call
end

blah do
    class B
    end
    B.new
end

```

I'm sure it has something to do with `with self yield` but it seems either this should be allowed or not... or at the very least the error needs to be improve to explain when you can and can't declare classes inside blocks.

**Comment by yyyc514** [comment]
This same bug applies when including a module.  It's allowed when calling a block, but not when using `with x yield`.

**Comment by yyyc514** [comment]
This currently allows for some cool abuses to make up for lack of instance eval:

```
macro get(url, &block)
	{% klass = "Klass#{url.id.gsub(%r{[/:]},"")}".id %}
	route :get, "{{url.id}}" do |request|
		class {{ klass.id }} < Moonshine::Controller
			def action
	 			{{block.body}}
	 		end
	 	end
	 	c = {{klass}}.new(request)
	 	c.action
	 	c.return_response
	end
end

get "/dogs/:more" do |request|
    redirect_to "/cats"
end
```

I'm not sure if this insane or not yet, but it seems to work just fine.

**Comment by kirbyfan64** [comment]
\*reads post about making of for instead eval, coughs, and dies*

**Comment by asterite** [comment]
Classes inside method blocks should give error, this is a bug.

**Comment by yyyc514** [comment]
> *reads post about making of for instance eval, coughs, and dies*

For some cases like this it's a neat idea... for places where really you could argue (and some Ruby frameworks do) that a class is what is needed in the first place (for each action)... in that case this is just syntactic sugar (in the form of macros) to turn a block into a full class with methods, context, etc.

Of course since this behavior is a bug I'll have to rethinking this. :-)
