### ISSUE TITLE
Protected methods and yield

### ISSUE THREAD

**Issue by Exilor** [manastech/crystal#598]
It's not mentioned in the changelog so I don't know if it's on purpose:
```crystal
class Foo
  def initialize
    @bar = [] of Int32
  end

  def self.new
    with new yield
  end

  protected def baz(value : Int32)
    @bar << value
  end
end

Foo.new { baz 134 } # => protected method 'baz' called for Foo
```

**Comment by Exilor** [comment]
The same thing happens with a plain ```yield```
```crystal
class Foo
  def initialize
    @bar = [] of Int32
  end

  def self.new
    yield new
  end

  protected def baz(value : Int32)
    @bar << value
  end
end

Foo.new { |f| f.baz 134 }
```

**Comment by asterite** [comment]
@Exilor Only public methods are callable with `with ... yield`.

**Comment by Exilor** [comment]
It worked with protected methods before the version that was released the day I opened this issue. But because there was no mention of the change in the changelog, I didn't know if it was intended or a side effect of some change in the compiler.
I'll close the issue if it was indeed intended.
