### ISSUE TITLE
HTTP::Server#listen_fork

### ISSUE THREAD

**Issue by will** [manastech/crystal#600]
On Crystal 0.7, given 

```
def fib(n)
  if n == 0
    return 0
  elsif n == 1
    return 1
  else
    return fib(n-1) + fib(n-2)
  end
end

server = HTTP::Server.new 8080, do |request|
  i = request.path[1..-1].to_i
  HTTP::Response.ok "text/plain", fib(i).to_s
end

puts "Listening on http://0.0.0.0:8080"
server.listen_fork
```

we get 
```
Listening on http://0.0.0.0:8080
[warn] kevent: Bad file descriptor
[PCL] Stale coroutine called: curr=0x10834a000  exitto=0x7f9e92801200  caller=0x7f9e92801200
[warn] kevent: Bad file descriptor
[PCL] Stale coroutine called: curr=0x10834a000  exitto=0x7f9e92801200  caller=0x7f9e92801200
[warn] kevent: Bad file descriptor
[PCL] Stale coroutine called: curr=0x10834a000  exitto=0x7f9e92801200  caller=0x7f9e92801200
[warn] kevent: Bad file descriptor
[PCL] Stale coroutine called: curr=0x10834a000  exitto=0x7f9e92801200  caller=0x7f9e92801200
[warn] kevent: Bad file descriptor
[PCL] Stale coroutine called: curr=0x10834a000  exitto=0x7f9e92801200  caller=0x7f9e92801200
[warn] kevent: Bad file descriptor
[PCL] Stale coroutine called: curr=0x10834a000  exitto=0x7f9e92801200  caller=0x7f9e92801200
Ready
[warn] kevent: Bad file descriptor
[PCL] Stale coroutine called: curr=0x10834a000  exitto=0x7f9e92801200  caller=0x7f9e92801200
[warn] kevent: Bad file descriptor
[PCL] Stale coroutine called: curr=0x10834a000  exitto=0x7f9e92801200  caller=0x7f9e92801200
```
and it does not serve requests.

Even setting the number of workers to 1 `server.listen_fork(1)` is no help
```
Listening on http://0.0.0.0:8080
Ready
[warn] kevent: Bad file descriptor
[PCL] Stale coroutine called: curr=0x10f0f3000  exitto=0x7ff333801200  caller=0x7ff333801200
```

Instead of fork, we also tried to use threads in a similar way to the listen_fork:
```
class HTTP::Server
  def listen_thread(workers = 8)
    server = TCPServer.new(@port)
    workers.times do
      t = Thread.new do
        puts "starting worker"
          loop {
            puts "before handle_client"
            spawn handle_client(server.accept)
            puts "after handle_client"
          }
      end
    end

    puts "Ready"
    gets
  end
end 
```
which gives
```
Listening on http://0.0.0.0:8080
starting worker
before handle_client
starting worker
before handle_client
starting worker
before handle_client
starting worker
before handle_client
starting worker
before handle_client
starting worker
before handle_client
starting worker
before handle_client
starting worker
before handle_client
Ready
```

By adding a call to t.join we can see a stacktrace 
```
Listening on http://0.0.0.0:8080
starting worker
before handle_client
Could not get the current fiber (Exception)
*Exception#initialize<Exception, String, Nil>:Array(String) +21 [4352266693]
*Exception::new<String>:Exception +111 [4352266639]
*raise<String>:NoReturn +6 [4352237734]
*Fiber::current:Fiber +59 [4352269371]
*TCPServer#accept<TCPServer>:TCPSocket +145 [4352290065]
~fun_literal_12 +125 [4352240557]
~fun_literal_11 +49 [4352240417]
*Thread(Nil, NoReturn)@Thread(T, R)#start<Thread(Nil, NoReturn)>:Exception+ +100 [4352292084]
~fun_literal_9 +6 [4352240294]
GC_inner_start_routine +117 [4352690741]
GC_call_with_stack_base +59 [4352671835]
GC_start_routine +31 [4352697887]
_pthread_body +138 [140735574333593]
_pthread_struct_init +0 [140735574333226]
Program terminated abnormally with error code: 256
```

We also poked around by adding a fiber manually in the thread, but that did not help.

cc @fdr who looked into this with me earlier today

**Comment by asterite** [comment]
I think we'll remove that method now that `#listen` spawns and doesn't block. Can you use `#listen` instead?

**Comment by fdr** [comment]
I don't think that can use multiple threads.  @will and I were interested in trying out Crystal using multiple processors and seeing how that went.

**Comment by ysbaddaden** [comment]
Confirmed with Prax: it seems we can't spawn threads and have IO calls inside them anymore.

I guess we are in-between 2 solutions where the long term goal of Crystal is to have a multithreaded event loop (hence the choice of libevent over libuv), which is now limited to a single thread.

**Comment by ysbaddaden** [comment]
@waj I'm porting Prax to use the event loop (it works great). Yet, I'd like to keep some operations in their own thread, in order to not affect the main loop with something unrelated. For instance the monitor that kills unused spawned apps periodically, but I can't since just calling `sleep` will crash the thread (same error as above).

I can get rid of the thread and spawn a coroutine instead, but what if the operation was very CPU-bound and I really wanted to have it running on it's own to avoid blocking the loop?

**Comment by dbackeus** [comment]
So would the end goal here be for #listen to use multiple cores?

Really interested to see how that would look performance wise. Is there any way to getting something like that to work right now?

(I'm not knowledgeable enough to understand if this was already answered by @ysbaddaden mentioning the "event loop" above)

**Comment by bararchy** [comment]
@dbackeus it seems that the end goal is to have a "Fiber pool" where a few Threads will handle, which will means you have Thread safety + Multi-core operations.

**Comment by ysbaddaden** [comment]
It looks like calling IO within a fork is also broken. I'm more annoyed by this problem than the lack of threads (no global process forking childs for never downtime).

I'm also having problems in signal handlers. They can happen when any thread (that crystal ran, like GC) is running, so handlers may fail randomly, and we can't use use a channel to postpone signal handling, since we can't call IO within a signal handler safely...

**Comment by waj** [comment]
I think I'll just remove this method. I added it way before we think about what concurrency model was desired in Crystal.

**Comment by asterite** [comment]
@waj :+1:

I'm also thinking maybe `fork` is out of place in Crystal. I know Ruby tends to be very close to unix: errno, fork, etc., but most popular programming languages (for example: Java, C#, Go) tend to abstract that away, which I think makes sense. Programmers shouldn't have to deal with all those complexities.

**Comment by strcmp** [comment]
in Java/Go/Objective-C runtime I don't think their implementations allow for fork, definitely true for JVM/ObjC runtime. why not remove when it's a problem? :)

**Comment by ysbaddaden** [comment]
Could `fork` create a new event loop? We obviously can't access it once we forked, but I guess we can create a new loop, can't we?

**Comment by waj** [comment]
I didn't any research on the problem yet, but this seems to be related: http://www.wangafu.net/~nickm/libevent-book/Ref2_eventbase.html#_reinitializing_an_event_base_after_fork

**Comment by waj** [comment]
I just did a quick fix to solve this issue. Still, I think the `listen_fork` method should go away. Specially once the scheduler supports multiple threads.

**Comment by waj** [comment]
@ysbaddaden Still is not possible to create new threads and use IO inside them. So try to use `spawn` everywhere. Even though the performance will be far from ideal, eventually once we improve the scheduler, everything will start to perform better.

Although creating custom threads should be possible, the scheduler should be smart enough to continue processing IO on other threads while one is blocked in some CPU intensive task.

**Comment by ysbaddaden** [comment]
I'm not ranting on IO inside threads. This may either be fixed by multithreaded loop (I'm not sure) or not required anymore since there would be a better interface :)

I'm glad to see `fork`fixed! and yes, `listen_fork` should be removed. It's not monitoring child processes for instance, and it doesn't fit into the stdlib.

**Comment by ysbaddaden** [comment]
I'm just wondering about signals. How to react correctly to a SIGHUP or SIGTERM when they may happen anytime, like outside the main thread, which can't do any IO?

Maybe I should open another issue about this.

**Comment by waj** [comment]
Yes please, open another issue and describe what's the problem with the signals, including an example if possible. I'm not sure to understand why signal handling might be problematic.
