### ISSUE TITLE
Reason for extremely slow regex-dna benchmark

### ISSUE THREAD

**Issue by gottlike** [manastech/crystal#604]
I was looking into Crystal today and I really like what I see! Ruby's syntax is most beautiful and efficient, imho. I was hoping that JRuby (with Truffle) will be able to deliver performance that makes me not want to resort to io.js/node.js for when I really need a fast implementation, but it seems Crystal could do that too.

The only thing that seems to be really slow is Regex (which I usually use a lot): https://github.com/kostya/crystal-benchmarks-game#regexdna

Do you know why it's that slow and if there is a way (and plans) to fix it?

**Comment by ssvb** [comment]
https://github.com/manastech/crystal/releases/tag/0.7.0 lists "Improved Regex performance" among other things. How slow is it running for you now? I'm getting the following results:
```
Crystal 0.6.1 : 21.87s, 59.3Mb
Crystal 0.7.1 :  6.70s, 50.6Mb
C             :  3.62s, 12.4Mb
Ruby          :  3.67s, 17.9Mb
```
Which is probably still not perfect, but shows that things are getting better.

**Comment by waj** [comment]
I just did a quick check and found that we’re not using the function pcre_study that allows some performance improvements in the regex execution. I quickly added that call and the numbers now are much more close to C and Ruby.

I’ll make the change and commit for the next version ;-)

**Comment by gottlike** [comment]
@ssvb : I get similar performance on my machine. Roughly double the time for crystal, compared with C and Ruby. Much better than 0.6.1, but could be better still.

@waj: Awesome, thanks! :)

**Comment by waj** [comment]
Calls to `gsub` seems to still be the bottleneck in this benchmark, but the Regex numbers are much better now.

**Comment by gottlike** [comment]
Okay, cool. Feel free to close the issue, if you consider this solved :)

**Comment by asterite** [comment]
It can also be sped up if you do this:

```crystal
# {
# 'B' => "(c|g|t)", 'D' => "(a|g|t)", 'H' => "(a|c|t)", 'K' => "(g|t)",
# 'M' => "(a|c)", 'N' => "(a|c|g|t)", 'R' => "(a|g)", 'S' => "(c|t)",
# 'V' => "(a|c|g)", 'W' => "(a|t)", 'Y' => "(c|t)"
# }.each { |f,r| seq = seq.gsub(f, r) }

hash = {
  "B" => "(c|g|t)",
  "D" => "(a|g|t)",
  "H" => "(a|c|t)",
  "K" => "(g|t)",
  "M" => "(a|c)",
  "N" => "(a|c|g|t)",
  "R" => "(a|g)",
  "S" => "(c|t)",
  "V" => "(a|c|g)",
  "W" => "(a|t)",
  "Y" => "(c|t)"
}

seq = seq.gsub(/B|D|H|K|M|N|R|S|V|W|Y/, hash)
```

because now we have `String#gsub(String, Hash(String, String)`. The times now give me: C: 1.7s, Crystal: 1.81s, Ruby: 1.92s.

**Comment by gottlike** [comment]
:+1:

**Comment by waj** [comment]
Wonderful! We can close the issue now :-)
