### ISSUE TITLE
Crystal fmt

### ISSUE THREAD

**Issue by Vikaton** [manastech/crystal#606]
These are just Ideas I've had for a little bit, but could Crystal implement something like Gofmt (https://blog.golang.org/go-fmt-your-code)

Also, for abstract methods, would it be any different writing it like

EDIT: found out about the abstract keyword

**Comment by asterite** [comment]
Also see this: https://github.com/manastech/crystal/issues/309

I think it's doable and maybe very easy to do, but we don't consider it a high priority right now. I also feel Ruby/Crystal allows for more flexibility when you write code, specially because of blocks.

**Comment by asterite** [comment]
(I'm closing because it's a duplicate)
