### ISSUE TITLE
Travis failures

### ISSUE THREAD

**Issue by kirbyfan64** [manastech/crystal#607]
The error:

    cat: stdin: resource temporarily unavailable

I'm guessing it's from [this test](https://github.com/manastech/crystal/blob/77475dd3769ce35458bd9d120c5f9b2f12a116f0/spec/std/process/run_spec.cr#L41).

This might be related to [this bug in the Fish shell](https://github.com/maxfl/fish-shell/commit/437b4397b9cf273922ce7b414bf6626845f15ad0). My guess is that `stdin` should be initialized as non-blocking if the mode is `r`; right now [it always blocks](https://github.com/manastech/crystal/blob/c142140e18ed0132eb6a0beb246b81b207ddced2/src/file.cr#L20).

Of course, this is just a guess, and I don't have a Mac. Still, it'd be nice to see the build actually succeed. Maybe someone who does have a Mac could experiment with that?

**Comment by asterite** [comment]
`STDIN` is actually a [CFileIO](https://github.com/manastech/crystal/blob/master/src/io/c_file_io.cr#L112). We don't know why travis fails, sometimes you hit the "rebuild" button and it works.

**Comment by kirbyfan64** [comment]
Should be fixed by #679!!!!
