### ISSUE TITLE
If `rescue` doesn't fire, `else` section should know everything succeeded

### ISSUE THREAD

**Issue by BlaXpirit** [manastech/crystal#610]
```crystal
begin
  a = 5
rescue
else
  p a.to_f
end
```

    undefined method 'to_f' for Nil (did you mean 'to_i'?)

Here `a` can never be `nil`, but the compiler doesn't know it.

**Comment by asterite** [comment]
You are right, the compiler should be smarter here.

**Comment by asterite** [comment]
@BlaXpirit If you can use HEAD and see if it works in your apps, that would be great :-)
