### ISSUE TITLE
Compiler error when calling type .to_i

### ISSUE THREAD

**Issue by Arcnor** [manastech/crystal#614]
I don't exactly know how to reproduce this one without lots of code, but basically:

```crystal
lib Test
type K = Int32
end

def func(k : Test::K) : Int32
  k.to_i
end
```

If you call `func`, the compiler will freak out because of the `to_i`. This is the last part of the stack I got:

```
alloca:

entry:                                            ; No predecessors!
}

attributes #0 = { nounwind }
Bug: codegen_cast called from Test::K to Int32
```

Let me know if you need more info, and I'll try uploading my code somewhere (the stack it's very big right now)

**Comment by asterite** [comment]
Yes, seems to be a bug.

As a workaround for now you can use an alias:

```crystal
lib Test
  alias K = Int32
end
```

**Comment by Arcnor** [comment]
Man, you're fast :D. Thanks!

**Comment by asterite** [comment]
Let me know if it doesn't work, typedefs are a beast... I'm actually not sure now that they are such a good idea, maybe `alias` is enough.

**Comment by Arcnor** [comment]
I will test later and let you know.

About typedefs, I was asking me the same the other day while working on my binding generator. Right now I generate `type` for everything instead of `alias` because I think it gives you a bit more safety even if you're just passing `Int32` around in a bunch of cases. But maybe the "safety" is not worth the complexity it might add to the compiler? Open to discussion I guess :smile:
