### ISSUE TITLE
Unable to set instance hash outside class methods

### ISSUE THREAD

**Issue by dhruvrajvanshi** [manastech/crystal#615]
```
class Moonshine::Controller
	@router = {
			"GET /.*" =>
				->(req : Request) { get(req) },
			"POST /.*" =>
				->(req : Request) { post(req) }
	} of Request => (Request -> Response)
     ...
end
```
Gives an error 
```
Error in ./src/moonshine/controller.cr:7: undefined constant Request

	} of Request => (Request -> Response)

```
Request and Response are classes defined in another file. This file has access to them because putting the definition inside the initialize method works just fine. Is it a bug or am I missing something?

**Comment by asterite** [comment]
Make sure `Request` and `Response` are defined before that controller class.

I just checked and [here](https://github.com/dhruvrajvanshi/Moonshine/blob/master/src/moonshine.cr) you are doing:

```crystal
require "./moonshine/**"
```

This requires the files in alphabetic order, and `controller.cr` comes before `http.cr`. In that case, add `require "./http"` to `controller.cr` to make it work.

Also, when you think you've found a bug in the compiler (either a crash or a semantic issue) try to reduce the code to something we can copy/paste and see.

Let us know if requiring that extra file fixes the issue.

Thanks!

**Comment by dhruvrajvanshi** [comment]
Yes the "issue" is fixed now. This will save me a lot of headache in the future. Thanks a lot!

**Comment by asterite** [comment]
Awesome! Then I'm closing this :-)
