### ISSUE TITLE
`when` clause ignores nil check

### ISSUE THREAD

**Issue by rhysd** [manastech/crystal#616]
In Crystal, `nil` checks for nilable object are detected automatically if it is checked with `if` or `unless` expression.  However `case ... when` expression doesn't.  Is this a bug? Or is there any reasons that `case ... when` expression can't detect `nil` check?

- `unless` expression example

```ruby
foo = "blah blah blah" as String?

unless foo
  puts "nil!"
else
  puts foo.size
end

# => Size of foo was shown correctly
```

- `case ... when` expression example

```ruby
foo = "blah blah blah" as String?

case foo
when nil then puts "nil!"
else          puts foo.size
end

# => Oops, 'undefined method 'size' for Nil' error occurred
```

Thanks in advance :dog:

**Comment by Exilor** [comment]
Try ```when Nil``` (capital N).

**Comment by rhysd** [comment]
@Exilor 

Thanks.  Yes, I know it works.  But `if` and `unless` expression checks value `nil`.  Why `when` clause can't detect the check by value?

**Comment by Exilor** [comment]
I guess it's because ```when``` calls the ```#===``` method whose result is not known at compile time.

**Comment by asterite** [comment]
It's because of what @Exilor says. However, since `when` has some specific rules (for example, if you do `when Foo` the compiler rewrites that to an `is_a?(...)` we can also make `when nil` work, I think. It's a very simple and small rule to add.

**Comment by rhysd** [comment]
@Exilor @asterite 

Thank you for discussion!
I got the point by @Exilor 's explanation, but accepting check by value is also reasonable, I think.

**Comment by rhysd** [comment]
Thanks a lot!
