### ISSUE TITLE
Incomplete doc

### ISSUE THREAD

**Issue by michelboaventura** [manastech/crystal#617]
Hi all!

I've just met Crystal and my mind just blow! The project is awesome, thank you for the great job!

I've installed it from source following [the main doc](http://crystal-lang.org/docs/installation/from_source_repository.html) and everythink went smooth. But, when I tried to compile a simple script I got two missing dependencies: ``libpcl`` and ``bdwgc``. I think we should update the doc to reflect this need. I tried to write a PR fixing it, but couldn't find where this doc is.

Btw, I'm using Gentoo Linux 64 bits.

**Comment by asterite** [comment]
Now there's [Contributing.md](https://github.com/manastech/crystal/blob/master/Contributing.md) and [All required libraries](https://github.com/manastech/crystal/wiki/All-required-libraries).
