### ISSUE TITLE
IndexOutOfBounds on Array

### ISSUE THREAD

**Issue by michelboaventura** [manastech/crystal#618]
Hi,

Running this:
```Crystal
my_array = [] of Int32
my_array[0] = 0
```
causes this:
```
Index out of bounds (IndexOutOfBounds)
*Exception@Exception#initialize<IndexOutOfBounds, String>:Array(String) +46 [140721379311496]
*IndexOutOfBounds#initialize<IndexOutOfBounds, String>:Array(String) +6 [140721379311496]
*IndexOutOfBounds::new<String>:IndexOutOfBounds +97 [140721379311496]
*IndexOutOfBounds::new:IndexOutOfBounds +16 [140721379311496]
*Array(Int32)@Array(T)#check_index_out_of_bounds<Array(Int32), Int32>:Int32 +98 [140721379311496]
*Array(Int32)@Array(T)#[]=<Array(Int32), Int32, Int32>:Int32 +39 [140721379311496]
__crystal_main +467 [140721379311496]
main +32 [140721379311496]
__libc_start_main +240 [140721379311496]
_start +41 [140721379311496]
 +41 [140721379311496]
Program terminated abnormally with error code: 256
```

I'm using this version:
```
crystal --version
Using compiled compiler at .build/crystal
Crystal 0.7.1 [c816cfa] (Seg Mai  4 01:39:52 UTC 2015)
```

Thanks!

**Comment by Exilor** [comment]
That ```IndexOutOfBounds``` exceptions is raised on purpose. Your example is the one case where it wouldn't apply, but if you did ```my_array[1] = 0``` what would be the 0th element? You can't have ```nil``` in that array, which is what you would have in Ruby (```[nil, 0]```). Basically you're setting an element which doesn't exist yet to 0 and Crystal doesn't allow it.

**Comment by michelboaventura** [comment]
Hum, now that you've explained it to me, makes perfect sense :smile:

So it is not possible to write on a random position of a empty array. Where can I find Crystal's documentation? I would like to add this caveat to it (if it is not there), with a PR.

Thanks!

**Comment by michelboaventura** [comment]
And about the ``You can't have nil in that array, which is what you would have in Ruby ([nil, 0])`` part you wrote, the real problem is that ``Array``doesn't have a default value to represent emptiness. Because, even if I do: ``my_array = [] of (Int32 | Nil)`` I still can't write to any position.

**Comment by yyyc514** [comment]
> I still can't write to any position.

You could if you pre-filled the array.  Also might be other ways, I haven't looked at the Array code closely.

**Comment by Exilor** [comment]
@michelboaventura Documentation can be found [here](http://crystal-lang.org/docs/) and [here](http://crystal-lang.org/api/). Both are still fairly incomplete.
When I said ```You can't have nil in that array``` I meant in *that* specific array :laughing: . You can do what @yyyc514 suggested: ```Array(Nil | Int32).new(5, nil) # => [nil, nil, nil, nil, nil]```.

**Comment by asterite** [comment]
In our experience assigning to an arbitrary index is almost always a bug. If you need arbitrary indexing of Int32 => Something the best thing to do is to use a Hash.

In the original code instead of doing `my_array[0] = 0` you can simply do `my_array.push 0`.

**Comment by michelboaventura** [comment]
Thank you all for the explanations, it all makes sense.

What I was trying to accomplish was to port a ruby code to crystal. On this code I speak with a device via serial port and it sends me a pair of integers, which represents x and y for a molecular distribution. The hardware sends all possible xs between 0 and N, but each time N is different and unknown. So, on ruby I did (more or less):
```Ruby
@vector = []
...
def update_vector(x, y)
  @vector[x] = y
end
```

To do it on Crystal I would have to do something like this:
```Crystal
@vector = [] of Int32

def update_vector(x, y)
  delta = x - @vector.size
  if delta > 0
    @vector.enlarge_by(delta, default: 0)
  end
  @vector[x] = y
end
```
How do I do the "enlarge_by" part on Crystal?

**Comment by yyyc514** [comment]
`resize_to_capacity`

Reading the class source files is often very helpful.  `array.cr` in this case.

**Comment by yyyc514** [comment]
Of course you probably want to still read the source to see how to use that method reliably. :-)

**Comment by yyyc514** [comment]
Of course you could also write your own class (with a backing Array) to make this all transparent.

**Comment by michelboaventura** [comment]
Sadly this is a private method. I couldn't find a easy way to do this, at least not one that doesn't involve allocate another array and do a concat.

**Comment by ysbaddaden** [comment]
If you know the maximum x, you could allocate a prefilled `vec = StaticArray(Int32).new(size, 0)` and then set the values with `vec[x] = y`.

You could have a Int32 | Nil and prefill with the nil, but with Crystal you're happier when you don't have to deal with nils.

**Comment by michelboaventura** [comment]
I don't know the maximum x, that's the problem.

**Comment by asterite** [comment]
@michelboaventura Here's one way to do it:

```crystal
def update_vector(vector, x, y)
  while vector.length <= x
    vector.push 0
  end
  vector[x] = y
end

vector = [] of Int32
update_vector vector, 3, 1
puts vector
update_vector vector, 1, 2
puts vector
update_vector vector, 2, 3
puts vector
update_vector vector, 6, 4
puts vector
```

However, I'm a bit concerned about the API that serial port provides:

* You don't know N, so there's no way to make the receiver allocate a buffer of size N for efficiency.
* How do you know when you received all N values? Do you have to count them?

On the other hand, you could perfectly use a `Hash(Int32, Int32)` in this case. It might be slightly slower, depending on the value of N, but that API doesn't seem to be designed for efficiency anyway, so... :-)

**Comment by michelboaventura** [comment]
@asterite, nice code! About the API, I did a simplification of the problem while explain it. Actually I receive packages well defined by a protocol. The first and last are header and tail, so I know when it is over.

I'm planning to port all of my code to Crystal to force the language and learn more about it, but I must confess that I will miss Ruby's ``vector[n] = 1``, it is used all over the code :smile_cat:
