### ISSUE TITLE
upcase X in StringFormatter blows up

### ISSUE THREAD

**Issue by yyyc514** [manastech/crystal#622]
```
puts "%%%X" % 23
```

This works in Ruby.  Any reason we don't want to support uppercase?  If this is simply an omission I can likely work up a patch.

**Comment by asterite** [comment]
It's missing because we didn't have time to implement it yet. A pull request would be awesome :smile_cat:

**Comment by yyyc514** [comment]
https://github.com/manastech/crystal/pull/631

**Comment by asterite** [comment]
Fixed by 69a19c0
