### ISSUE TITLE
Ruby Int#to_s differs from Crystal Int#to_s

### ISSUE THREAD

**Issue by yyyc514** [manastech/crystal#623]
Ruby:

`31.to_s(16) => 1f`

Crystal:

`31.to_s(16) => 1F`

Seems in Ruby the result is lowercase while in Crystal it's upper... Found this while researching the other issue I filed. #622

**Comment by yyyc514** [comment]
#626 solves

**Comment by asterite** [comment]
This is on purpose. One of the usages we found for that is [percent encoding](https://tools.ietf.org/html/rfc3986#section-2.1) and there it says one should prefer uppercase letters. And since upper and lower are the same, but upper are preferred, we chose that so we can reuse that logic in many places.

Do you need it to be lower case?

**Comment by asterite** [comment]
You are right. I think the best thing to do is to provide an extra argument in `Int#to_s`, say `16.to_s(upcase: true)` so that we have both logics in one place.

**Comment by yyyc514** [comment]
Is any real reason `16.to_s(upcase: true)` trumps `16.to_s.upcase`?

**Comment by asterite** [comment]
`16.to_s.upcase` involves two string allocations, while `16.to_s(upcase: true)` just one. And if you are writing directly to an IO, no allocations are needed at all:

```crystal
# write 16 in base 16 to STDOUT without memory being allocated
16.to_s(STDOUT, upcase: true)
```

Well, the truth is `Int#to_s` does allocate, I see a StringIO there, but I think that's not needed and we can use a StaticArray.

In any case, the standard library should provide ways to do things without allocating unneeded memory. There's a GC, but allocating less memory is always good.

**Comment by yyyc514** [comment]
Gotcha.  I'll take a swing at adding the upcase flag and leave refactoring out the StringIO for someone else.

**Comment by asterite** [comment]
Ah, but when I made that comment I had it implemented already (and I updated your code :-))

I now remember the StringIO is there because it's hard to know how many digits you will need as maximum with an arbitrary base. For base 2 it can be a very long string :-)

**Comment by yyyc514** [comment]
Nice.
