### ISSUE TITLE
build err:  Cannot allocate memory

### ISSUE THREAD

**Issue by kolyan1981by** [manastech/crystal#635]
Error executing system command '/bin/sh': Cannot allocate memory
*Errno::new<String>:Errno +433 [0]
*system<String>:Bool +1327 [0]
*Crystal::Compiler#system<Crystal::Compiler, String>:Bool +131 [0]
*Crystal::Compiler#build<Crystal::Compiler, Crystal::Program, Crystal::Expressions, Array(Crystal::Compiler::Source), String>:(Nil | Bool) +12069 [0]
*Crystal::Compiler#compile<Crystal::Compiler, Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result +4992 [0]
*Crystal::Command::run<Array(String)>:(Nil | CFileIO | File | Bool | Crystal::Compiler::Result | Array(Crystal::Init::View+:Class)) +1538 [0]
main +15883 [0]
__libc_start_main +240 [0]
_start +41 [0]

**Comment by asterite** [comment]
@kolyan1981by Doing what? Please provides the steps to reproduce this.

**Comment by kolyan1981by** [comment]
i have 4gb memory , i tried install from aur and got a error, when compiling

**Comment by jhass** [comment]
Do you use an AUR helper that builds in `/tmp`? Peak memory usage for the package build here is `2538553344 = 2.36G`, the build directory occupies `252284 = 247M` after the build.

**Comment by kolyan1981by** [comment]
yes, /tmp, seems not enough memory

**Comment by asterite** [comment]
@kolyan1981by Was you able to finally build it? Was it a memory issue?

**Comment by jhass** [comment]
In any case I setup a binary repository for Archlinux, see https://wiki.archlinux.org/index.php/Crystal

I think we can close this.

**Comment by asterite** [comment]
@jhass Good, thanks
