### ISSUE TITLE
Show Regex modifiers when doing Regex#to_s

### ISSUE THREAD

**Issue by jeromegn** [manastech/crystal#638]
Right now this is what's happening:

```crystal
/abc/imx.to_s # => "/abc/"
```

It would be useful to see the modifiers when inspecting a regex.

Even more useful would be to have a method to access those, like Ruby's `Regex#options`: http://ruby-doc.org/core-2.1.1/Regexp.html#method-i-options

**Comment by asterite** [comment]
Good :-)

We'll probably use an enum for the options.
