### ISSUE TITLE
Array of subset of type invalid for overload

### ISSUE THREAD

**Issue by jeromegn** [manastech/crystal#639]
I'm writing a BSON library (making heavy use of libbson) and I've stumbled upon a small issue with types.

I've inspired from JSON::Type and created a BSON::Type which looks like:

```crystal
module BSON
  alias Type = String | Time | Int32 | Int64 | Float64 | Document | Bool | Array(Type) | Hash(String | Symbol, Type)
end
```

Given:

```crystal
class BSON::Document
  def initialize(data : Hash(String | Symbol, Type))
  end
end
```

It's not possible to do this:

```crystal
BSON::Document.new({key: ["str2", 1234]})
```

I get:

```
no overload matches 'BSON::Document#initialize' with types Hash(Symbol, Array((String | Int32)))
Overloads are:
 - BSON::Document#initialize(data : Hash(String | Symbol, Type))
```

I'm not sure if this is a bug, a limitation or intended. Is my Type definition a bit too ambitious?

This works in my program:

```crystal
arr = [] of BSON::Type
arr << "str"
arr << 123
BSON::Document.new({key: arr})
```

However, if I run the same exact code as specs, I get a segfault error:

```
/usr/local/bin/crystal: line 6:  2015 Segmentation fault: 11  "$INSTALL_DIR/embedded/bin/crystal" "$@"
```

**Comment by asterite** [comment]
It's not a bug (the first one), because `{key: ["str2", 1234]}` is deduced by the compiler to be `Hash(Symbol, Array(String | Int32))`, which is not your BSON type.

This works (there's no other way):

```crystal
BSON::Document.new({key: ["str2", 1234] of BSON::Type})
```

Can you point to the spec file that gives you the segfault? Are you on Mac OSX?

As a side note, I wouldn't use Symbol and String interchangeably. BSON documents you will get from the C API will be strings, never symbols, and there's no way to convert a string to a symbol. And the union will make things a bit slower. Plus, you can use strings in hash keys (this is different than Ruby):

```crystal
{"foo": 1} #:: Hash(String, Int32)
```

The grammar for BSON is cute: http://bsonspec.org/spec.html . I think doing it pure Crystal could be fun (both to read and write docs) :-)

**Comment by jeromegn** [comment]
Yes I'm on Mac OSX (Yosemite, 10.10.3). Here's the segfaulting spec: https://github.com/jeromegn/bson.cr/blob/master/spec/bson/iterator_spec.cr#L98-L109

Alright, got it. It's a limitation of the language, I'm cool with that.

Concerning the symbol and keys, I'm doing the conversion in the library in multiple places. Basically, it's like a HashWithIndifferentAccess from ActiveSupport in Rails. When I get a key, be it a Symbol or String, I just `.to_s` on it for my next operation. The wrapper code is really simple if you want to take a look: https://github.com/jeromegn/bson.cr/blob/master/src/bson/document.cr I'd love feedback on it.

The reason I went with a wrapper instead of implementing the spec is because I want to create a way to use MongoDB with Crystal. That meant either implementing the whole driver spec or just using wrapping the C driver. I thought the latter would be simpler, but it does work with bson types provided by the C BSON implementation. Therefore I created a simple wrapper for that :)

**Comment by asterite** [comment]
Thanks for the link! I was able to reproduce it and fix it :-)

As I said before, I don't think there's a real need for symbols in your code. It bloats a bit the code and you still convert symbols to strings anyway for comparing stuff. I wouldn't like to see a HashWithIndifferentAccess in my life in Crystal. Strings are immutable here and constant strings go into the data section of the binary, so there's absolutely no cost of using strings (except maybe they are one char longer, and maybe a symbol looks cool :-P).

It seems @datanoise published a MongoDB client: https://github.com/datanoise/mongo.cr, maybe you can join forces :-)

**Comment by jeromegn** [comment]
Haha, I had not seen that. Looks like we have been working on it concurrently! I just replied to his message on the google group.
