### ISSUE TITLE
Exit code not working properly?

### ISSUE THREAD

**Issue by sardaukar** [manastech/crystal#640]
``exit 1`` gives me

<pre>
Program terminated abnormally with error code: 256
</pre>

and ``exit -1`` gives me

<pre>
Program terminated abnormally with error code: 65280
</pre>

What am I doing wrong?

**Comment by jhass** [comment]
`crystal run` modifies the exit code/doesn't correctly relay it iirc, try `crystal build` and executing the binary directly.
