### ISSUE TITLE
Crystal build filename output message could be better

### ISSUE THREAD

**Issue by sardaukar** [manastech/crystal#650]
If I try to build a binary for "app.cr" and I have an "app" subfolder present, I get 
`
ld: can't open output file for writing: app, errno=21 for architecture x86_64
`
`
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by kirbyfan64** [comment]
This isn't a Crystal bug. You can't have a file and a directory with the same name on UNIX-y systems.

**Comment by sardaukar** [comment]
Yes, I know that ;) but don't you think the message could be a bit better? I've omitted the wall of text with the full clang compiler invocation line (sorry, was not too explicit in the issue text)

**Comment by kirbyfan64** [comment]
Well, you have to remember it's the linker giving this issue.

Also, you can't really accurately test for the ability to write to an output file on a multi-threaded system.

**Comment by sardaukar** [comment]
OK, just thought the message could be a bit better :/
