### ISSUE TITLE
gets.chomp wont compile

### ISSUE THREAD

**Issue by bararchy** [manastech/crystal#652]
Code:

```ruby
puts "num1: "
a = gets.chomp
puts a
```

Error:
```
crystal build test.cr 
Error in ./test.cr:2: undefined method 'chomp' for Nil

a = gets.chomp
         ^~~~~

================================================================================

Nil trace:

  /usr/lib/crystal/io.cr:394

    def gets(delimiter = '\n' : Char)


  /usr/lib/crystal/io.cr:395

      STDIN.gets(delimiter)
            ^~~~

  /usr/lib/crystal/io/c_file_io.cr:72

      def gets(delimiter = '\n' : Char)
          ^~~~

  /usr/lib/crystal/io/c_file_io.cr:74

          return super
                 ^~~~~

  /usr/lib/crystal/io.cr:268

      def gets(delimiter = '\n' : Char)
          ^~~~

  /usr/lib/crystal/io.cr:272

            return buffer.empty? ? nil : buffer.to_s
                                   ^

```

**Comment by ysbaddaden** [comment]
This happening because `gets` may return a `nil`, and there is no NilClass#chomp method. This is a feature of Crystal's compiler which is annoying at first but ends up being very powerful: no more NoMethodError at runtime on a production server: the compiler got them already in development.

You may instead:

```crystal
if input = gets
  a = input.chomp
  puts a
end
```

Or:

```crystal
a = gets.to_s.chomp
puts a
```

**Comment by bararchy** [comment]
Oh, I see, ok, I get the idea :)

**Comment by Exilor** [comment]
Maybe gets should return at least an empty string instead of nil.

**Comment by bararchy** [comment]
Well, it is "get string" so It does make sense

**Comment by ysbaddaden** [comment]
It seems to mimick [Ruby's behavior](http://ruby-doc.org/core-2.1.5/IO.html#method-i-gets), where `nil` means `EOF`, so that one can:

```crystal
while input = gets
  # process line
end

# done
```

**Comment by asterite** [comment]
There's also `read_line`, which reads a line or raises an exception instead of returning nil. Or you can just do `gets.not_nil!.
