### ISSUE TITLE
Compiling using multiple cores 

### ISSUE THREAD

**Issue by bararchy** [manastech/crystal#657]
Is there a way to tell the compiler to use more then a single core ? like "make -j" does ?

**Comment by asterite** [comment]
The compiler already uses multiple cores... well, at least in the codegen phase it forks 8 processes and use that for the compilation.

You can specify the number of "threads" (forks, really) with `--threads N`, like this:

```
crystal build foo.cr --threads 4
```

But I don't think you can improve the performance as the default is 8. And the type inference phase is done sequentially, no parallelism there.

**Comment by asterite** [comment]
@bararchy is the compiler slow for you?

**Comment by bararchy** [comment]
@asterite , not for my small projects, by it is for crystal (the whole project) for example, I just forked the repo to add Thread.current, and built with "make spec", it took like 2.5 min, which maybe is not that allot of time now that I'm looking at it....
So I guess no, its not slow :)

**Comment by asterite** [comment]
@bararchy `make spec` compiles the specs and runs them, which in my machine takes 2:13 minutes. But note that this needs to compile the compiler and associated specs, which are 5820 right now. To just compile the specs and see how it long it takes:

```
# specs
time bin/crystal build spec/all_spec.cr -s

# compiler
time bin/crystal build src/compiler/crystal.cr -s
```

For me it's 34 seconds and 15 seconds respectively. It went up from the last time (about 10 seconds), I'll have to investigate why...

Also, if you are just trying an addition to a type in the standard library, there's no need to run all specs. You can just do, for example:

```
bin/crystal spec/std/thread_spec.cr 
```

Or run a spec in a specific line:

```
bin/crystal spec spec/std/thread_spec.cr:11
```

That takes 0.3s for me. Once you are done with changes in that class you can run all specs and go do something else for a minute or two. Or just leave that job to the CI server (but we usually run all specs locally just in case).
