### ISSUE TITLE
Adding Thread.current to Thread class

### ISSUE THREAD

**Issue by bararchy** [manastech/crystal#660]
So, I'm working on adding the Thread.current method to the Thread class.
(my C abilties are below nothing), looking at libpthread I understood the right place to look is the .self function.

So adding this to LibPThread:
```ruby
fun current = pthread_self() : Thread*
```

And adding this to the Thread class:

```ruby
  def current
    LibPThread.current
  end
```

Now, trying both Int64 and Thread* as the return value for pthread_self show a long int or a pointer (no surprise there), how would I return a thread class instead though ? populated with the right values to be the current thread.

**Comment by ysbaddaden** [comment]
Here is a patch that I did some months ago that implemented `Thread.current` using a `@[ThreadLocal]` global variable: https://gist.github.com/ysbaddaden/a24270c1ac6f23655f34

I'm not sure the finalizer will garbage collect the global variable, thought.

**Comment by bararchy** [comment]
An integral part of a project I work on relies on Thread.current (for logging).
Is there a way you can create a PR for your patch ?

**Comment by ysbaddaden** [comment]
I'm not sure this is a correct solution (it relies on a global variable). You may monkey patch Thread in your application for the time being.

Also, be careful with threads, they are broken since v0.7: any IO operation inside a thread will segfault the process.

**Comment by bararchy** [comment]
Oh... it does ? then I'll just wait as the logging is indeed an IO operation.
Oh well...

**Comment by asterite** [comment]
Sorry about not replying to this... but as @ysbaddaden, Thread is currently kind of broken. Eventually you won't even have to use Thread as lightweight processes will be managed in multiple threads by the runtime scheduler.
