### ISSUE TITLE
 Exception handling

### ISSUE THREAD

**Issue by bararchy** [manastech/crystal#661]
I see this part of the Docs isn't written, I tried 

```ruby
begin 
 ...
rescue Exception => e
  puts e
end
```

but the "=>" doesn't play nice, what is the crystal way to do it ?

**Comment by bararchy** [comment]
So I got my answer from @jhass  on the IRC, so 

```ruby
begin
  ...
rescue e : Exception
  puts e
end
```

**Comment by asterite** [comment]
Yes. I've been finishing the docs lately, and exception handling and generics are the two missing bits. I'll finish them during the next week, and maybe I'll add a section that talks about the compiler's command line and some FAQ.

**Comment by bararchy** [comment]
@asterite Thanks :)
