### ISSUE TITLE
unless and if are not treated the same way

### ISSUE THREAD

**Issue by bararchy** [manastech/crystal#662]
This code compiles:
```ruby
require "openssl"
require "socket"

begin
  tcp_socket = TCPSocket.new("google.com", 443)
rescue e : Exception
  puts "Error in socket: #{e}"
end

puts tcp_socket

context = OpenSSL::SSL::Context.default

puts context
if tcp_socket
  ssl_socket = OpenSSL::SSL::Socket.new(tcp_socket, mode = :client, context)
  puts ssl_socket
  ssl_socket.close
end

tcp_socket.close
```

But this one wont:

```ruby
require "openssl"
require "socket"

begin
  tcp_socket = TCPSocket.new("google.com", 443)
rescue e : Exception
  puts "Error in socket: #{e}"
end

puts tcp_socket

context = OpenSSL::SSL::Context.default

puts context
unless tcp_socket == nil
  ssl_socket = OpenSSL::SSL::Socket.new(tcp_socket, mode = :client, context)
  puts ssl_socket
  ssl_socket.close
end

tcp_socket.close
```

**Comment by bararchy** [comment]
it seems that the issue is with negative condition ? 
this wont compile too

```ruby
if tcp_socket != nil
   ...
end
```

**Comment by asterite** [comment]
The thing is, `==` and `!=` can be defined by you so the compiler can't really know that if something equals nil then it's nil. The same goes for `!=`. (well, technically it could, the compiler has access to all the source code, but there would be more things to analyze, probably not worth it)

The only way the compiler can know something is not nil is by doing `if var` where `var` is a variable, like explained [here](http://crystal-lang.org/docs/syntax_and_semantics/if_var.html).

In the rare case where you have a union of Nil and Bool and you want to explicitly check for nil and not false, you do use `if var.is_a?(Nil)`, as explained [here](http://crystal-lang.org/docs/syntax_and_semantics/if_varis_a.html).

I also found, while programming in Ruby, that `if var == nil`, `if var != nil`, `unless var == nil`, etc., are more verbose and redundant than just `if var` in like 99% of the cases. So Crystal, in a way, forces you to use the short notation, which is the convention.

**Comment by jhass** [comment]
How about adding `Object#nil?` and `Nil#nil?` that Ruby has? As a nice shortcut to `.is_a? Nil`.

**Comment by bararchy** [comment]
Well, just things to get used too I guess, I'll close the issue as it is apparently not a bug :)

**Comment by strcmp** [comment]
:+1: to adding a .nil? predicate.

**Comment by bararchy** [comment]
:+1:  for this too, I would love .nil?

**Comment by asterite** [comment]
I'm not sure about `nil?`, `.is_a?(Nil)` is just a bit longer and works, and you rarely need it. Let's try to keep the language rules short and simple :-)

**Comment by bararchy** [comment]
TBH I usually just do if somthing.to_s.empty ? 
This saves the trouble of checking both nil and empty

Closing issue.

**Comment by asterite** [comment]
@bararchy please don't do `to_s.empty?` for nil checks if you care about performance. A nil check is super fast, probably one or two cpu instructions, while converting something to a string and then checking for emptiness allocates memory and generates much longer code. I know premature optimization is the root of all evil, but...
