### ISSUE TITLE
OpenSSL key is missing optional password field

### ISSUE THREAD

**Issue by bararchy** [manastech/crystal#663]
https://github.com/manastech/crystal/blob/0df531ede12efc4417519f8baf355a9d0e649f03/src/openssl/ssl/context.cr#L18

This should accept an optional field for password.

**Comment by asterite** [comment]
Is it in https://github.com/datanoise/openssl.cr ? If so, we can close this.

**Comment by bararchy** [comment]
reported against crystal , can be closed.
