### ISSUE TITLE
<Type> doesn't implement lookup_instance_var

### ISSUE THREAD

**Issue by PuerkitoBio** [manastech/crystal#665]
I had the following message when trying to run my program (crystal version Crystal 0.7.1 (Fri May  1 22:39:55 UTC 2015) on Arch Linux 64-bit):

```
% crystal run src/trouve.cr
Bug: Trouve::CircularBuffer(T) doesn't implement lookup_instance_var
_init +194110 [0]
_init +1861825 [0]
_init +1838412 [0]
_init +1575444 [0]
_init +1597158 [0]
_init +1649161 [0]
_init +1597158 [0]
_init +2306235 [0]
_init +238636 [0]
_init +226429 [0]
_init +210723 [0]
__libc_start_main +240 [0]
_init +191969 [0]
 +191969 [0]

Error: you've found a bug in the Crystal compiler. Please open an issue: https://github.com/manastech/crystal/issues
```

You can find the source code here: https://github.com/PuerkitoBio/trouve, commit cd04f26ad876f031225873eb072112fbda92a4db

Let me know if you need more details.

Martin

**Comment by PuerkitoBio** [comment]
I can reproduce with this minimal code:

```
class SomeType(T)
  @x = 0
end
```

Removing the generic (T) type makes the error message disappear. Hope that helps.

**Comment by waterlink** [comment]
If you actually try to use `@x` in class method you will get an error:

```ruby
class SomeType
  @x = 0

  def self.x_plus_one
    @x + 1
  end
end
```

Does not compile:

```
in line 4: @instance_vars are not yet allowed in metaclasses: use
@@class_vars instead
```

So instead, just use `@@x` - it works just fine.



--
Best Regards,
Alexey Fedorov,
Sr Ruby Developer, Clojure Developer, Rust Developer,
+49 15757 486 476

2015-05-18 2:48 GMT+03:00 Martin Angers <notifications@github.com>:

**Comment by PuerkitoBio** [comment]
As far as I know, @@x is a class variable, while @x is an instance variable, so that change , while it may compile, is not the intended code. In any case, I'm not arguing that the original code is good code (though I believe it should compile?), but it still shouldn't cause such an error message (the message explicitly asked to create an issue), so that is why I created this.

**Comment by asterite** [comment]
@waterlink Check [this](http://crystal-lang.org/docs/syntax_and_semantics/instance_variables_type_inference.html) (near the bottom). `@x = 0` at a class level defines an instance variable initializer. This is different from Ruby, but it's useful to avoid the `Nil` type when reopening classes and adding instance variables.
