### ISSUE TITLE
String Range

### ISSUE THREAD

**Issue by bararchy** [manastech/crystal#668]
I would really like to see something like the Ruby string range implemented 
```ruby
("0000".."9999")
```
which creates 
["0000","0001",....]

What do you guys think ?

**Comment by Exilor** [comment]
It's a matter of implementing ```String#succ```. You can use [this](https://gist.github.com/Exilor/50b2efb1ab1994febd10) (adapted from Rubinius) if you need it now.

**Comment by asterite** [comment]
Yes, `String#succ` would be nice to have. I wonder how Ruby does it, though. For example:

```ruby
"あ".succ #=> "ぃ"
```

and then it also realizes when you reach the last Hiragana character:

```ruby
"ゖ".succ #=> "ぁぁ"
```

We can use @Exilor's code as a base. If somebody wants to send a pull request (with specs) we'll gladly accept it :-)

**Comment by asterite** [comment]
Fixed by #1053
