### ISSUE TITLE
Noexec flag for tmp folder breaks things

### ISSUE THREAD

**Issue by ujifgc** [manastech/crystal#676]
```
~$ crystal init app test
      create  test/.gitignore
      create  test/LICENSE
      create  test/README.md
      create  test/.travis.yml
      create  test/Projectfile
      create  test/src/test.cr
      create  test/src/test/version.cr
      create  test/spec/spec_helper.cr
      create  test/spec/test_spec.cr
Initialized empty Git repository in ~/test/.git/
~$ cd test
~/test$ crystal spec
sh: 1: /tmp/crystal-run-spec.LdTVjk: Permission denied
Program terminated abnormally with error code: 32256
```

OS is Debian 8.0.
`/tmp` folder is mounted with noexec for security reasons.
Is there a project-wide config file where I can put `TMPDIR=./tmp` so crystal would apply it without needing to write `TMPDIR=./tmp crystal spec` every time?

**Comment by asterite** [comment]
@ujifgc I changed it to use the `.crystal` directory, which we are already using for temporary files. To test this you'll have to wait until the next release or [compile a compiler](https://github.com/manastech/crystal/blob/master/Contributing.md#user-content-contributing-to-the-compiler-itself). Please reopen if this didn't work for you or there's something missing. Thanks!
