### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by Codcore** [manastech/crystal#680]
Spec that couses compile errors can be find at 
https://github.com/Codcore/facets/blob/bug-in-the-Crystal-compiler/spec/http/request_spec.cr

**Comment by Codcore** [comment]
Code is in file https://github.com/Codcore/facets/blob/bug-in-the-Crystal-compiler/src/facets/http/request.cr

**Comment by Codcore** [comment]
I have forgot colon before symbol, now it works. But it doesn't matter, Crystal have to display an error, but instead it failed

**Comment by asterite** [comment]
Thanks, I was able to reduce it to this:

```crystal
class Foo
  def initialize(@method)
  end

  def method
    @method
  end
end

class Bar < Foo
  def initialize
    super(method)
  end
end

Bar.new
```
