### ISSUE TITLE
`loop` method seems to be broken

### ISSUE THREAD

**Issue by rhysd** [manastech/crystal#685]
```crystal
def foo(n)
  loop do
    return case n
      when 0
        return
      else
        n -= 1
        next
      end
  end
end

p foo(42)
```

I noticed that above `foo(42)` yields infinite loop.  And if I executed above code by Ruby, `foo(42)` returns `nil` correctly.

Using `while true` instead of `loop do` also returns `nil` correctly.

- Environment
  - Crystal 0.7.1
  - OS X 10.9.5

**Comment by jhass** [comment]
Related to #420

**Comment by rhysd** [comment]
@jhass 

Thanks.  I don't likely understand `yield` in Crystal.

Definition of `loop` is

```crystal
def loop
  while true
    yield
  end
end
```

so I supposed that `loop do ... end` would be expanded to `while true ... end`.  But it seems that simple while loop and `do ... end` block have difference in terms of loop control expression such as `break`.

**Comment by rhysd** [comment]
OK, I'll try it with debug build `crystal`.

**Comment by rhysd** [comment]
I've found that the latest `crystal` (6219f8f) doesn't reproduce this issue.  `foo(42)` returns `nil` correctly.

**Comment by asterite** [comment]
@rhysd Yes, I believe it's the same issue as this one: https://github.com/manastech/crystal/issues/659 (which is fixed now)

**Comment by rhysd** [comment]
@asterite 

Thanks!  It's just the same bug I faced.
