### ISSUE TITLE
It is possible to avoid generics?

### ISSUE THREAD

**Issue by sergey-kucher** [manastech/crystal#690]
My first impression about Crystal - it's awesome! Expressiveness of Ruby and speed of C is something  unique. I think it can attract many programmers (not only rubyists) and Crystal can become one of mainstream languages. But I think it's only possible if Crystal will preserve it's expressiveness (not necessary in ruby way).

In my opinion, in the long term, generics (i.e. parametrized classes) it's totally antiexpressive thing.
While generic definition looks like:
```ruby
MyBox(Int32)
```
It's ok.

But then project is really big, programmers have to define very complicated classes. And definition of class can looks like this:
```ruby
GenericClass1(AnotherGeneric1(CustomClass1(String, Int32), CustomClass2(Int64, ComplexClass(Int32, Int32, String, String), Init64, String)))
```
Or similar but even larger. On half of screen for example.

I'm already seen such generics in Java. Actually they was one of the reasons why I'm leave Java in favour of Ruby.

So my question is. It is possible to fully avoid generics in Crystal?

**Comment by jhass** [comment]
I don't think fully ever, but for an amazing already, they can be inferred, like `Array.new(5) { Array.new(5, 0) }` works, and I think inference will and can be improved. In some distant point maybe even for (some) cases like `a = []; a << 1`.

**Comment by asterite** [comment]
@sergey-kucher We can't get rid of generics. In the beginnings we didn't have them and compile times were exponential relative to the code size. With generics it became linear.

I don't think you'll ever have to write that long generic type. One reason is what @jhass said, the type inference is pretty good (although not perfect) so you generally don't have to write all that down. Second, you don't have to annotate types in methods and vars, so fewer locations. And generic types aren't really that common. To be honest, I've never seen a long generic declaration in Java either.

Take for example this Crystal code:

```crystal
iter = (1..10).each.map { |x| x * 2 }.take(3)
puts iter.class
```

The above prints ```Iterator(T)::Take(Iterator(T)::Map(Range(B, E)::ItemIterator(Int32, Int32), Int32, Int32), Int32)```. Well, that's surely a long name. But you didn't have to write it, the compiler figured it out.

I believe we can always improve things, but right now we are in a sweet spot where you almost never have to write types and the compiler is pretty fast.

**Comment by asterite** [comment]
I'll close this, generics are here to stay.
