### ISSUE TITLE
Crystal IDE support

### ISSUE THREAD

**Issue by Codcore** [manastech/crystal#693]
Is there IDEs supporting Crystal projects? (except Vim)

**Comment by bararchy** [comment]
@Codcore 
Sublime --> https://github.com/manastech/sublime-crystal

**Comment by sergey-kucher** [comment]
:+1:

**Comment by Codcore** [comment]
Thanks! I hope InteliJIDEA plugin will be introduced soon

**Comment by jhass** [comment]
Related:

* https://groups.google.com/forum/#!topic/crystal-lang/VBcUdJNUM-s
* https://groups.google.com/forum/#!topic/crystal-lang/YqrG_zPkfkA
* #523 
* #308 
* #65

**Comment by bararchy** [comment]
Me too, I'm working with RubyMine regularly, would be awesome to have CrystalMine :)

**Comment by adrianvoica** [comment]
Crystal support in RubyMine would suffice. Most of the syntax work is already there.

**Comment by idchlife** [comment]
So, best IDE for crystal?

**Comment by mverzilli** [comment]
@idchlife Probably Sublime. The plugin is hooked to the formatter on save which saves you lots of keystrokes for the sake of indenting. Atom is also a thing. I honestly don't see anyone changing their choice of editors based on Crystal support. What editor do you use in general?

**Comment by idchlife** [comment]
@mverzilli in general I'm using JetBrains IDEs, PHPStorm, WebStorm for main work, VS Code for C#.

Right now using Vim with crystal-lang plugin for syntax. Going to stick with this for now, because I'm just starting with crystal, maybe change my editor in future.

**Comment by mverzilli** [comment]
Cool! I use VS Code for everything these days (including Crystal). It'd be cool to explore implementing the language server protocol. In fact @kofno started some work on that direction here: https://github.com/kofno/crystal-ide. Would be lovely to see it grow.

**Comment by drhuffman12** [comment]
An IntelliJIDEA plugin would be great! Rubymine :+1

**Comment by samueleaton** [comment]
An IDE will be brittle until Crystals APIs/implementations are stabilized. An IDE should happen naturally after 1.0, right?

**Comment by keplersj** [comment]
@drhuffman12 I've started some work on a Crystal IntelliJ plugin, but am having difficulty building the syntax. If you're interested I can put the, currently small, codebase I have on GitHub.

**Comment by drhuffman12** [comment]
@keplersj, I'll be glad to help you test your plugin.

**Comment by keplersj** [comment]
It's small, and largely unimplemented, but it is a start. https://github.com/intellij-crystal/intellij-crystal

**Comment by elorest** [comment]
Vim seems to work well for crystal. Sublime's format on change by default is pretty cool though.

**Comment by keplersj** [comment]
https://github.com/crystal-lang-tools

**Comment by Extrapolator214** [comment]
Feature request for RubyMine is already created: https://youtrack.jetbrains.com/issue/RUBY-17225
If everyone upvotes it, then they might consider implementing it. You know, your vote matters :)

**Comment by 0xb0bee** [comment]
Thank you. I hope intellij won't create a community plugin, make programmers migrate to their system and eventually kill the community edition and making only a commercial version just like they did it with the golang plugin.

**Comment by idchlife** [comment]
@0xb0bee yes they can do this, but they need to be fully commercial interested in Crystal community. Even so, the thing is - they already loosing some part of popular languages community thanks to wonderful developers creating opensource language servers! Example: python - jedi. I'm conding my python in vscode, because jedi is really awesome and I don't need bloated pycharm to be in my way. Same with typescript and even javascript nowadays.

I think Crystall will have powerful opensource language server overtime. And it will be at some point when opensource based language server usage will have too much developers to jump to jetbrains ide (because they are not fully investing in languages that are not enought hyped at the moment)
