### ISSUE TITLE
instance variable  was not initialized in all of the 'initialize' methods, rendering it nilable

### ISSUE THREAD

**Issue by Codcore** [manastech/crystal#696]
I have such code:
```crystal
class SomeClass
  
  def func1
    @var1 = 6
  end
  
  def func2
    @var2 = 3
    puts @var1  
    puts @var2
  end
end

obj = SomeClass.new
obj.func1()
obj.func2()
```
It is works fine and output is:
```
6
3
```
But, when I change it to next, I get error:
```crystal
class SomeClass
  
  def func1
    @var1 = 6
  end
  
  def func2
    @var2 = 3
    puts @var1
    puts @var2
    puts @var1 - @var2
  end
end

obj = SomeClass.new
obj.func1()
obj.func2()
```
Output (http://carc.in/#/r/h5):
```
Error in line 17: instantiating 'SomeClass#func2()'

in line 11: undefined method '-' for Nil

================================================================================

Error: instance variable '@var1' of SomeClass was not initialized in all of the 'initialize' methods, rendering it nilable
```
Can you explain what happens, and how can I avoid this error(without initializing instance variables in "initialize" method)?

**Comment by ysbaddaden** [comment]
You can puts a nil, because Nil#to_s is defined, but you can't have math operations, because Nil#- isn't defined. Crystal requires most instance vars be:

- defined in #initialize
- defined to memoize values in getter methods (using @var ||= 0) and use the getters, not the ivars.

**Comment by Codcore** [comment]
@ysbaddaden Thanks, everything fell into place!

**Comment by jhass** [comment]
Another way around this is to use local variables: http://carc.in/#/r/i9
