### ISSUE TITLE
Eval method

### ISSUE THREAD

**Issue by Codcore** [manastech/crystal#698]
Does Crystal have method like Ruby's eval()?

**Comment by jhass** [comment]
No, we use macros for that.

**Comment by Codcore** [comment]
@jhass, could you show an example,please?

**Comment by jhass** [comment]
Do you have a usecase?

**Comment by Codcore** [comment]
@jhass, yes: I have variable with class name in and want to call "new" method on this class.

**Comment by waterlink** [comment]
This will not work with macroses.

You need to have a `Hash of String => Class` for that somewhere in constant. And then you just do this: `FACTORIES.fetch(klass_name_string) { fail "Unknown klass name string" }.new`

**Comment by jhass** [comment]
http://carc.in/#/r/k1 that needs neither macros in Crystal, nor eval in Ruby.

**Comment by asterite** [comment]
@Codcore where do you get that name from?

**Comment by Codcore** [comment]
@asterite actually, from URL
@waterlink your approach doesn't work http://carc.in/#/r/k4

**Comment by waterlink** [comment]
@Codcore, sorry, I thought it was obvious, that you need to define `FACTORIES` yourself:

```ruby
FACTORIES = {
  "ClassA" => ClassA,
  "ClassB" => ClassB,
  # .. etc ..
}
```

**Comment by asterite** [comment]
@Codcore This works: http://carc.in/#/r/k7

However, note that for that to work the array/hash of classes has to be of some specific class or module. You can't have `[] of Class`, because the compiler wouldn't know what can you do with it.

**Comment by Codcore** [comment]
@asterite, @waterlink , @jhass thank you all. I am a beginner at Crystal, so sorry for stupid questions

**Comment by jhass** [comment]
No worries, btw we have an [IRC channel](http://webchat.freenode.net/?channels=#crystal-lang) if you seek a bit more direct feedback ;)

**Comment by waterlink** [comment]
@asterite or you can just have a proper `Factory` class and you will have an instance of `Hash<String, Factory>`

**Comment by waterlink** [comment]
Though you can have a hash like that `{} of ClassA|ClassB|ClassC|...` if I don't miss anything?
