### ISSUE TITLE
Pointer without a value

### ISSUE THREAD

**Issue by bararchy** [manastech/crystal#700]
Shouldn't that just return a false (or nil) ? 
```crystal
ptr = Pointer(String).malloc(5)
puts ptr.value
ptr.value = "Testing"
puts ptr.value
```
output is : Program terminated abnormally with error code: 139

example : http://carc.in/#/r/l2

reference : http://crystal-lang.org/api/Pointer.html
"Note that a pointer is falsey if it's null (if it's address is zero)."

**Comment by jhass** [comment]
Look at all the metadata that's setup when you make a string: https://github.com/manastech/crystal/blob/master/src/string.cr#L195

In your case all that data is set to a bunch of 0's, and 5 bytes is probably not even enough to fit it, so you get accesses to uninitialized memory.

**Comment by bararchy** [comment]
@jhass not relevant, you can change it to 1024 and it still returns the same error.

**Comment by jhass** [comment]
It is relevant, you don't setup the metadata of the String, it is not just a bunch of raw bytes.

**Comment by bararchy** [comment]
Going with your theory, why then , when removing line 2, the code executes ?

**Comment by jhass** [comment]
Because there you copy the sane header from another string into the buffer (and beyond, possibly corrupting other stuff) before calling any code that expects it to be properly set up.

**Comment by bararchy** [comment]
hm..... Then I guess it makes sense.
Thanks.
