### ISSUE TITLE
Bug in Crystal when SomeClass is tested to be a Class

### ISSUE THREAD

**Issue by Codcore** [manastech/crystal#701]
The code that causes failure is here: http://carc.in/#/r/re
```crystal
require "spec"
class BaseController
end

hash = {} of String => Class

hash["BaseController"] = BaseController

hash["BaseController"].should be_a Class
```

**Comment by ysbaddaden** [comment]
{} of String => Class means the hash will have instances of Class, or derivates, but instances nonetheless.

You want {} of String => BaseController.class and then the hash will contain classes of BaseController and derivates like PostsController < BaseController.

**Comment by Codcore** [comment]
@ysbaddaden, I already understood that, bit compiler says bug was found, so I opened this issue.

**Comment by asterite** [comment]
@Codcore You are right. We'll fix that (for now) by disallowing Class as a generic type. That will make that the above code won't compile (because that uses a generic type, BeAExpectation), but you can workaround it by doing `.is_a?(Class).should be_true`.
