### ISSUE TITLE
File::Stat#mode question

### ISSUE THREAD

**Issue by datanoise** [manastech/crystal#703]
What is the point of converting File::Stat#mode to a form that makes the decimal representation look like octal form? I ran into a bug where I assumed that this fields returns exactly the value from C API.

That makes it quite difficult to do binary operations to extract the individual permissions, e.g. to check if a group has write permission: `stat.mode & (1 << 4) != 0`

Btw, Ruby's File::Stat returns the correct value.

**Comment by asterite** [comment]
Hm, File::Stat came from a big pull request, apparently I didn't see that method... it should just return the underlying value.

**Comment by asterite** [comment]
@datanoise Kind of offtopic, but can I include [this](https://github.com/datanoise/mongo.cr/blob/master/src/shims/time.cr) in the standard library?

**Comment by datanoise** [comment]
that would be nice, thank you!
