### ISSUE TITLE
High CPU load on Darwin (Crystal 0.7.2)

### ISSUE THREAD

**Issue by Nightforge** [manastech/crystal#706]
Hello!

Issue with crystal compiler 0.7.2 on OS X - high CPU load
Test code is:
```crystal
puts "Hello from Crystal language!"
sleep 60
```
I test the same code on os x with 0.7.1 - has no issues. Crystal compiler for linux (0.7.1 and 0.7.2) also has no this issue.
![screen shot 2015-05-29 at 18 18 12](https://cloud.githubusercontent.com/assets/583081/7883485/44040360-0630-11e5-80b0-62d9b3b7e03a.png)

**Comment by tommasop** [comment]
Same issue here with the simple http server code.


100% cpu loading


------------------------------------

IN OBSCURO MIRANDA RELUCENT

**Comment by asterite** [comment]
Seems it has something to do with the change to STDOUT (and others) from CFileIO to FileDescriptorIO and non-blocking IO for that. Not sure yet why it's happening.

**Comment by waj** [comment]
The problem is that libevent is raising the "write" event for the STDOUT all the time, even though the event is registered with the ET (edge triggered) flag: https://github.com/manastech/crystal/blob/master/src/concurrent/scheduler.cr#L24

I'll investigate this further to find a solution. Thanks for reporting!

**Comment by asterite** [comment]
In IRC @jhass confirmed this doesn't happen in linux, so maybe it's a bug in libevent for mac, but we'll have to investigate.

**Comment by waj** [comment]
The solution could be more elegant... but it works for now. @Nightforge, @tommasop could you confirm if this fixes the issue?

**Comment by Nightforge** [comment]
Confirmed!

**Comment by tommasop** [comment]
Confirmed!
