### ISSUE TITLE
Strange Array behaviour

### ISSUE THREAD

**Issue by baltavay** [manastech/crystal#711]
Strange array behaviour
```crystal
class Foo
  def hello
    puts "hello world"
  end
end
test = [[Foo.new,Foo.new,"bar"]]
test.each do |val|
  foo1,foo2,bar = val
  foo1.hello
end
```
I get `undefined method 'hello' for String`.

**Comment by bcardiff** [comment]
It's because the inner array is of `Foo|String`. The assignment can't deal with that.
But it works if you use tuples.

http://play.crystal-lang.org/#/r/ym

```crystal
class Foo
  def say_hello
    puts "hello world"
  end
end

arr = [[Foo.new,Foo.new,"bar"]]
puts typeof(arr) # => Array(Array((String | Foo)))

tup = [{Foo.new,Foo.new,"bar"}]
puts typeof(tup) # => Array({Foo, Foo, String})

tup.each do |val|
  foo1,foo2,bar = val
  foo1.say_hello # => hello world
end
```

**Comment by asterite** [comment]
@baltavay As @bcardiff says, arrays mix their types so when you access one of their elements the compiler doesn't know what type you'll get.
