### ISSUE TITLE
gets() only allows char as delimiter

### ISSUE THREAD

**Issue by bararchy** [manastech/crystal#713]
I really don't get this decision, lets say I want to read from User\Socket until I get "\r\n\r\n" or "\0\0\0\0" or even "ENDEND" why does it forces a char ? what's the point ?

**Comment by bararchy** [comment]
Goes also for chomp which allows only a char.

**Comment by asterite** [comment]
@bararchy What's not in the standard library might be because we didn't have time to do it, or we didn't need it. I think Ruby has that functionality because it lacks a Char type, so they are forced to handle the general String case. But in C, for example, there's `getdelim` which only accepts a char. Of course there's no need that we do the same, I'll try to implement it for IO, should be simple.

As for chomp, it removes the last `\n`, `\r` or `\r\n`... oh, wait, now I see that it accepts a string parameter. I didn't know that. I wonder what's that useful for :-) (but I'll try to do it too).

Of course, you can always try to implement these things and send a pull request :-)

**Comment by bararchy** [comment]
@asterite Just wanted to say sorry about the aggressive way this issue is written in.
It was uncalled for and it was my own frustration while working over hours spilling towards the wrong people.

It would be great  if you could add that, if not, that's totally fine too.

Real world usage:

I have an HTTP proxy written in Ruby which I was tasked with converting to Crystal,  this proxy reads from Server and Client and manipulates the data, to know how much to read from the server or client I read in ruby using this:

```ruby
http_response[:http_headers] = socket.gets(/\r?\n\r?\n/)
```

This is for cases like IIS or other weird server's who uses \r\n\r\n instead of the \n\n for header body separation, after I know the content length or if this is a chunked data or a file etc.. I know how to handle and read the remaining data. 

Without gets having this functionality I need to create a loop which will read char by char and checks for \r or \n, then start filling a buffer until I get \r\n\r\n or \n\n and then it should build a buffer.
This could work, but I rather change as little as possible the code base which I know is working.

Again, sorry and I hope you manage to add that :) 

Thanks for the great work until now !

**Comment by asterite** [comment]
@bararchy No worries, we all have bad days :-)

Mmm... does that `socket.gets(/\r?\n\r?\n/)` line in Ruby works? As far as I know `gets` can receive a string or an integer, but not a Regex. I just tried it with File and StringIO and it doesn't work.

**Comment by bararchy** [comment]
Yeha, this line works :) it's not documented, or at lest I can't find the documentations.
But you could try it using a simple

```ruby
require 'socket'
s = TCPServer.new(8888)
client = s.accept
message = client.gets(/\r?\n\r?\n/)
puts message
```
you can use telnet to fill it up with data until you send \n\n or \r\n\r\n

**Comment by bararchy** [comment]
Now that I tried that, I get an error that gets is not String or Int, maybe this is because that my Socket in the proxy is SSLSocket ? maybe it work differently ?

**Comment by asterite** [comment]
Do you have a program with `gets(Regex)` in Ruby that works? The documentation doesn't say that Regex is a valid argument to gets, and checking the source code I can't find it either.

How can you implement this on an IO? You would have to consume an arbitrary sequence of bytes and then check if the regex matches. If the argument is a String it's easier: once the first char matches you continue checking the next chars, but with Regex I find that near impossible to do (at least efficiently and without reading too much from the IO).

**Comment by bararchy** [comment]
Yeha, just got it to work, apperently this only works for an SSLSocket (SSLServer)

server_code: 

```ruby
require 'socket'
require 'openssl'
s = TCPServer.new(8888)
context = OpenSSL::SSL::SSLContext.new
context.cert = OpenSSL::X509::Certificate.new(File.open("/home/unshadow/Desktop/git-projects/Zakif/Cert/cert.pem"))
context.key = OpenSSL::PKey::RSA.new(File.open("/home/unshadow/Desktop/git-projects/Zakif/Cert/key.pem"), "1234")
s_socket = OpenSSL::SSL::SSLServer.new(s, context)
client = s_socket.accept
message = client.gets(/\r?\n\r?\n/)
puts message
```

client code:

```
require 'openssl'
require 'socket'

s = TCPSocket.new("127.0.0.1", 8888)
sslContext = OpenSSL::SSL::SSLContext.new
sslContext.verify_mode = OpenSSL::SSL::VERIFY_NONE
ssl_s = OpenSSL::SSL::SSLSocket.new(s, sslContext)
ssl_s.connect
ssl_s.write "blablablabla"
ssl_s.write "\r\n\r\n"

```

Running both right now gives the output:

```
┌─( unshadow ) - ( ~ )
└──┤ ruby tester.rb 
blablablabla
```

Version: ```ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]```

**Comment by bararchy** [comment]
btw, because SSL has to read at least some number of bytes or the SSL Frame will be malformed maybe this is how it is possible, TBH I thought that it was a regular thing.

The string is the only thing I really need, the Regex is a nice addition, but not a necessity.
