### ISSUE TITLE
Module#=== incompatibility between Ruby/Crystal.

### ISSUE THREAD

**Issue by strcmp** [manastech/crystal#714]
In Ruby this is true, in Crystal it's false.
```ruby
Array === [1,2,3]
```
Although, case works the same in Ruby and Crystal.
```ruby
case [1,2,3]
when Array
  puts "O, so you're an array, that's cool."
end
```

**Comment by ysbaddaden** [comment]
The `when Array` statement is interpreted as `when [1, 2, 3].is_a?(Array)` at compile time (this is merely a developer convenience). The `===` method is thus never invoked at runtime.

That doesn't explain why `===` behaves differently thought. There must be another reason.

**Comment by asterite** [comment]
It's not yet implemented because it's not that simple. Maybe we can just do:

```crystal
class Class
  def ===(other)
    self == other.class
  end
end
```

Or maybe:

```crystal
class Class
  def ===(other)
    other.is_a?(self)
  end
end
```

I'll try one of these. In any case, it's not as useful as the `case ... when` or `is_a?` because the compiler doesn't restrict the types.

@strcmp Do you need this for a reason, or just have it for completeness?

**Comment by strcmp** [comment]
@asterite Yeah, nothing specific that would require me to use === instead of is_a?, so just for completeness. I thought about sending a pull request that would have used your second example(other.is_a?(self)), but in the end I didn't. It came up on IRC while talking with @jhass and unshadow. No real code involved. :smile: 
@ysbaddaden Thanks for the extra bit of information.
