### ISSUE TITLE
failed running crystal browser

### ISSUE THREAD

**Issue by datanoise** [manastech/crystal#715]
Here is the error:

```
Browser open at http://0.0.0.0:4000
invalid UInt64:
*Exception@Exception#initialize<ArgumentError, String>:Array(String) +46 [4303493006]
*ArgumentError#initialize<ArgumentError, String>:Array(String) +6 [4303492950]
*ArgumentError::new<String>:ArgumentError +92 [4303492908]
*String#to_u64<String, Int32, Bool, Bool, Bool, Bool>:UInt64 +255 [4303556927]
*String#to_u64<String>:UInt64 +32 [4303556656]
*Crystal::Browser#handle<Crystal::Browser, String>:String +97 [4314551617]
*Crystal::Browser::open<Crystal::ASTNode+>:NoReturn +417 [4314550913]
*Crystal::Command::browser<Array(String)>:NoReturn +102 [4303746134]
*Crystal::Command::run<Array(String)>:(Nil | File | Bool | AutoflushBufferedIO(FileDescriptorIO+) | Crystal::Compiler::Result | Array(Crystal::Init::View+:Class)) +732 [4303734188]
*Crystal::Command::run:(Nil | File | Bool | AutoflushBufferedIO(FileDescriptorIO+) | Crystal::Compiler::Result | Array(Crystal::Init::View+:Class)) +37 [4303733365]
__crystal_main +33993 [4303453849]
main +40 [4303456568]

Error: you've found a bug in the Crystal compiler. Please open an issue: https://github.com/manastech/crystal/issues
```

Here is the diff that fixes it:

```diff
diff --git a/src/compiler/crystal/tools/browser.cr b/src/compiler/crystal/tools/browser.cr
index 7180173..34f81ca 100644
--- a/src/compiler/crystal/tools/browser.cr
+++ b/src/compiler/crystal/tools/browser.cr
@@ -32,7 +32,7 @@ class Crystal::Browser
   end

   def handle(path)
-    object_id = path[1 .. -1].to_u64
+    object_id = path[1 .. -1].to_u64 { 0_u64 }
     case object_id
     when 0
       render_html @node
```

**Comment by asterite** [comment]
@datanoise Thanks! I'll apply that patch soon.

Do you use browser? It was something fun we did in the beginning, I don't use it anymore and I don't find it useful, maybe we should remove it until we do something decent with it. What do you think?

**Comment by datanoise** [comment]
I ran it because I thought it would show me the exact method signatures along with all Type annotations, but was disappointed that it's not there. It could be very useful addition, considering that `crystal hierarchy` doesn't display methods.

**Comment by asterite** [comment]
Well, you can click on the calls to see the instantiated methods, but it looks really ugly right now in my opinion (not only because of the colors, but the code you see is like the expanded form used by the compiler).

But what do you mean with "exact method signatures"? Would you like to see method instantiations? To see the methods you can also use `crystal doc` or just see the source code, but instance variables are something that can't be easily seen.

**Comment by veelenga** [comment]
Just pointed in the same error. What was the purpose of `browser` command ?

**Comment by datanoise** [comment]
@asterite I was referring to method instantiations.
I just realized that I can see them via the browser but unfortunately they are shown without return types.
