### ISSUE TITLE
Union type instance variable is not checked by compiler

### ISSUE THREAD

**Issue by rhysd** [manastech/crystal#717]
Crystal compiler's type check is almost always awesome but compiler fails type check for instance variables as below.

Is it possible to check instance variable like normal variable?  I avoided this issue by `case x = @x` and using `x`...

- Code

```crystal
class X
  def initialize(@x)
  end

  def add_one
    case @x
      when Nil
        raise Exception.new
      else
        @x + 1 # Compiler reports that nil + 1 is not defined
      end
  end
end

X.new(rand(2) % 2 == 0 ? 42 : nil).add_one
```

- Error

```
Error in line 15: instantiating 'X#add_one()'

in line 10: undefined method '+' for Nil

================================================================================

Nil trace:

  eval:2



  eval:2



  eval:2
```

**Comment by jhass** [comment]
This is intentional, see #477

**Comment by rhysd** [comment]
Oh, I've got it.  It's a problem of thread safety.  Thanks.

**Comment by rhysd** [comment]
It seems that normal variable has the same problem.

```crystal
require "thread"

x = 42 as Int32 | Nil

t = Thread.new do
  x = nil
end

if x.is_a? Int32
  sleep 0.1
  puts x
else
  puts "oops"
end

t.join
```

http://carc.in/#/r/13p

Is it intended?

**Comment by jhass** [comment]
Well, I hope so, it's closured into a thread, so it is affected in this case from the same problem and you can see the same solution works: http://carc.in/#/r/13q

**Comment by rhysd** [comment]
Ah, `x` can took `nil` so that the `then` clause of `if` didn't occur an error.  Thanks a lot.

**Comment by asterite** [comment]
@rhysd In the second case it's because of a [closured variable](http://crystal-lang.org/docs/syntax_and_semantics/closures.html#type-of-closured-variables). We need to improve the error message for these cases.

About the `x = @x`, there's no other way around. I found it annoying at first, but now I'm used to it. You can always find shorter ways to write these things:

```crystal
if x = @x
  x + 1
else
  raise ...
end
```

Or:

```crystal
@x.try { |x| x + 1 } || raise ...
```

Or just:

```crystal
@x.not_nil! + 1
```

but that has a generic exception message.

**Comment by rhysd** [comment]
@asterite 

Thank you for your advice!

`try` is one of the most favorite methods in Ruby.  I'll use it in Crystal.
