### ISSUE TITLE
Crystal bug when implementing Singleton class

### ISSUE THREAD

**Issue by Codcore** [manastech/crystal#718]
Was trying to implement Singleton pattern in Crystal:
```crystal
class Singleton
  getter :msg

  @@instance = new
  
  def initialize
    @msg = "Hello"
  end
  
  def self.get_instance
    return @@instance
  end
end
    
a = Singleton.get_instance
b = Singleton.get_instance
c = Singleton.new

p a
p b
b.msg #----->>here Crystal bug message appears
p c
```
You can find error output and code at http://play.crystal-lang.org/#/r/13n

**Comment by Codcore** [comment]
Following works:
http://play.crystal-lang.org/#/r/184
```crystal
class Singleton
  getter :msg
  
  def initialize
    @msg ="hello"
  end
  
  def self.instance
    @@instance ||= new
  end
end

p Singleton.instance
a = Singleton.instance
p a.msg
```
```
#<Singleton:0x8854fd0 @msg="hello">
"hello"
```
But I can't find how to make "new" private. Approach suggested by @jhass , doesn't work too:
http://play.crystal-lang.org/#/r/183
```crystal
class Singleton
  getter :msg
  
  private def self.new
    super
  end
  
  def initialize
    @msg ="hello"
  end
  
  def self.instance
    @@instance ||= new
  end
end

p Singleton.instance
p Singleton.instance
a = Singleton.instance
a.msg
```

**Comment by asterite** [comment]
Interesting, I'll fix these.

A simpler way to make a singleton is to use a constant:

```crystal
class Singleton
  INSTANCE = new

  def self.instance
    INSTANCE
  end
end
```

The first snippet works if you move the `@@instance` to the bottom. The "problem" is that `new` gets called, the default constructor is invoked, but then an `initialize` is defined. In fact, if you try it in Ruby and then output the `@msg` variable you will get nil:

```ruby
class Singleton
  attr_reader :msg

  @@instance = new

  def initialize
    @msg = "Hello"
  end

  def self.get_instance
    return @@instance
  end
end

b = Singleton.get_instance
p b.msg #=> nil
```

But, if you move `@@instance` to the bottom it works OK.

Apparently the compiler gets confused by this redefinition and crashes.

As to how to define private constructors, I still don't know. Maybe we can use `private def initialize`.

**Comment by ony** [comment]
Use of `@@instance` is broken with generic classes (see #3719 ). Hacky work-around:

```crystal
class Singleton
  def self.instance
    (INSTANCES[self.hash] ||= new).as(self)
  end
  private def self.new; super; end
  private INSTANCES = {} of typeof(self.hash) => self
end
  
class Dummy(T) < Singleton
end
    
describe Dummy do
  it { Dummy(Bool).instance.should_not be_nil }
  it { "#{Dummy(Bool).instance}".should contain("#{Bool}") }
  it { "#{typeof(Dummy(Bool).instance)}".should contain("#{Bool}") }
  it { Dummy(Bool).instance.should be(Dummy(Bool).instance) }
  it { Dummy(Bool).instance.should_not be(Dummy(Nil).instance) }
end
```
With #2733 it should be possible to get rid of base class by using something like:
```crystal
module SingletonModule
  macro extended
    def self.instance
      (INSTANCES[self.hash] ||= new).as(self)
    end
    private def self.new; super; end
    private INSTANCES = {} of typeof(self.hash) => Object
  end
end
```

**Comment by asterite** [comment]
I wouldn't try to hack around the language. There won't be a way to have singleton generic types, there will be just one class var for all generic types of a single type, once that's fixed.

**Comment by ony** [comment]
@asterite does it make sense to re-open this issue #3719 or create a new one?
P.S. See my comment in that issue for class var regarding it being broken in 0.24.2.
Thank you for maintaining this repo. I just recently discovered this language and so far I like it.

**Comment by asterite** [comment]
@ony Um, I just checked the code, it seems I fixed it in the past. So I don't know what we are discussing :-P

**Comment by asterite** [comment]
Also #3719 is closed because it's fixed. So what's the issue?

**Comment by ony** [comment]
@asterite , yes it is marked as closed. But [here is sample](https://play.crystal-lang.org/#/r/4gpb) that gives:
```
cast from Crystal::GenericClassInstanceType to Crystal::ClassVarContainer failed, at /build/crystal/src/crystal-0.25.0/src/compiler/crystal/semantic/semantic_visitor.cr:502:5:502
```
Same for 0.24.2.

**Comment by asterite** [comment]
@ony Here's the fix https://github.com/crystal-lang/crystal/pull/6348 . It should be available in the next release.

**Comment by wontruefree** [comment]
I dont know if this is expected behavior but I have been looking into the example from this issue and it seems like new does not return the singleton instance.

```crystal
class Singleton
 
  property :msg
 
 
 
  @@instance = new
 
  
 
  def initialize
 
    @msg = "Hello"
 
  end
 
  
 
  def self.get_instance
 
    return @@instance
 
  end
 
end
 
    
 
a = Singleton.get_instance
 
b = Singleton.get_instance
 
c = Singleton.new
 
 
 
 
 
p a
p b
p c
 
c.msg = "FOO"
 
p a
p b
p c
 
a.msg = "BAR"
 
p a
p b
p c
```

https://play.crystal-lang.org/#/r/9ymg

**Comment by straight-shoota** [comment]
Why would it return the singleton? `Singleton.new` is just the standard constructor which initializes a new instance.

**Comment by docelic** [comment]
(@wontruefree I think this particular case with `c = Singleton.new` works as expected, because `new` wasn't overriden anywhere in the example so it just results in creating and returning a new object, as usual.)

**Comment by wontruefree** [comment]
I guess I would have expected new to use the singleton instance.  That might not be the correct expectation.

**Comment by Blacksmoke16** [comment]
@wontruefree You'd have to overload `self.new` to return `@@instance`.  Otherwise there isn't anything to tell Crystal that it shouldn't be instantiated normally.
