### ISSUE TITLE
Document needed packages/libraries to run crystal spec

### ISSUE THREAD

**Issue by PragTob** [manastech/crystal#720]
Hi there,

at first thanks for all your work and passion with crystal! It is shaping up quite nicely :)

To get started today I just wanted to compile from source and do `bin/crystal spec` - I'm a test driven person :) I'm on Linux Mint 17.1 (which has Ubuntu 14.04 as a package base, so fairly common) with already lots of the common "Ruby developer" packages/libs installed. Getting to `make` and compile crystal is fairly simple.

However, to get `bin/crystal spec` to run quite a few more libraries are needed - it'd be nice if those were documented somewhere (wiki/README) with a nice sudo apt-get command to follow along. I know right now it's probably still changing a lot, just saying.

for reference, here is what I installed today after llvm et. al.:

```
 install libbsd-dev:amd64 <none> 0.6.0-2ubuntu1
 install libedit-dev:amd64 <none> 3.1-20130712-2
 install libevent-core-2.0-5:amd64 <none> 2.0.21-stable-1ubuntu1.14.04.1
 install libevent-extra-2.0-5:amd64 <none> 2.0.21-stable-1ubuntu1.14.04.1
 install libevent-openssl-2.0-5:amd64 <none> 2.0.21-stable-1ubuntu1.14.04.1
 install libevent-pthreads-2.0-5:amd64 <none> 2.0.21-stable-1ubuntu1.14.04.1
 install libevent-dev:amd64 <none> 2.0.21-stable-1ubuntu1.14.04.1
 install libgc-dev:amd64 <none> 1:7.2d-5ubuntu2
 install libpcl1:amd64 <none> 1.6-1ubuntu1
 install libpcl1-dev:amd64 <none> 1.6-1ubuntu1
 install libunwind8:amd64 <none> 1.1-2.2ubuntu3
 install libunwind8-dev:amd64 <none> 1.1-2.2ubuntu3
 install libgmpxx4ldbl:amd64 <none> 2:5.1.3+dfsg-1ubuntu1
 install libgmp-dev:amd64 <none> 2:5.1.3+dfsg-1ubuntu1
2015-05-31 20:29:54 install libxml2-dev:amd64 <none> 2.9.1+dfsg1-3ubuntu4.4
```

Also note that that as shown in #524 a newer libpcl version than in the ubuntu repositories is needed.

Also for reference:

```
tobi@tobi-desktop ~ $ uname -a
Linux tobi-desktop 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

All that said, error reporting is actually quite nice so doing these installations is rather easy (although annoying) :+1: 

Keep it up, thanks and hoping to ship in some documentation or so in the future!
Tobi

**Comment by asterite** [comment]
Thanks!

I added this wiki page: https://github.com/manastech/crystal/wiki/All-required-libraries

I also added a link to it here: https://github.com/manastech/crystal/blob/master/Contributing.md
