### ISSUE TITLE
for loops in Crystal

### ISSUE THREAD

**Issue by kerkomen** [manastech/crystal#725]
Not sure how to rewrite such constructs from Ruby in Crystal:

```ruby
for i in 1..10
    puts i
end
```

Crystal reports the following (which doesn't help):

```
Syntax error in eval:3: expecting token 'EOF', not 'end'
```

And there seems to be no information on *for loops* in the docs.

**Comment by asterite** [comment]
Use this:

```crystal
(1..10).each do |i|
  puts i
end
```

We didn't bring the `for` loop from Ruby because it's not very used and you can do everything with regular methods and blocks.

**Comment by kerkomen** [comment]
Thanks for the quick response!

**Comment by jhass** [comment]
Another variant

```crystal
1.upto(10) do |i|
  puts i
end

1.to(10) do |i|
  puts i
end

# Or if you don't need the 1-indexd i
10.times do |i|
  puts i
end
````

**Comment by kerkomen** [comment]
Thanks!

P. S. Since there are different variants listed, one may also use a `while` loop for that:

```
i = 0
while i < 10
  puts i
  i += 1
end
```

**Comment by daneb** [comment]
Ruby supports "for" and I understand we have "iterators". Are we making an intentional design decision to not support it?

**Comment by rdp** [comment]
startlingly neither "iterating" nor "for loops" seem to be mentioned anywhere in the docu: https://crystal-lang.org/docs/ or perhaps I'm missing it :)
