### ISSUE TITLE
Array from range

### ISSUE THREAD

**Issue by kerkomen** [manastech/crystal#727]
The task is to construct an array from the range.

There are several ways to do that in Ruby (some of them are listed [here](http://stackoverflow.com/questions/191329/correct-way-to-populate-an-array-with-a-range-in-ruby)):

```ruby
values =*(1..10)       #=> [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
values = Array(1..10)  #=> [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
values = (1..10).to_a  #=> [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
```

Neither of these ways works in Crystal. The following code does work:

```ruby
values = 1.upto(10)
values = 1.to(10)   # only in Crystal
```

But the latter ways to construct an array seem weird to me.

Are there any other ways?

P. S. By the way, what's the prospect of having both `upto` and `to` in Crystal?

**Comment by jhass** [comment]
I think adding `Range#to_a` should be uncontroversial, how about sending a PR? :)

Another non-optimal solution, just for the sake of it:
```crystal
start = 1
end = 10
values = Array.new(end) {|i| i + start }
```

**Comment by jhass** [comment]
That said I actually very rarely need that, curious about your real world usecase :)

**Comment by kerkomen** [comment]
Oops, `Range#to_a` [is actually working](http://play.crystal-lang.org/#/r/1fu). Sorry for that.
I agree, it's actually rare in the real world, though sometimes might be helpful when working with numbers and ranges or while playing with code.

And what's about keeping both `upto` and `to` constructs?

// I also noticed that Ruby prints every element of the Array on a new line while Crystal prints the array itself (which is more logical). Nice!

**Comment by jhass** [comment]
I think they're both useful, `to` is useful if you're unsure if you want to iterate upwards or downwards, but if you know it `upto` and `downto` should fail your logic in a less subtle manner.

**Comment by kerkomen** [comment]
That's reasonable. Thanks!
