### ISSUE TITLE
Case statement not correctly return results

### ISSUE THREAD

**Issue by zamith** [manastech/crystal#730]
I bumped into this strange bug, which I would love to try to fix, but don't really now where it is happening. The thing is that this works:

```crystal
def method
  case
  when true
    [1,2]
  end
end

p method
```

But this doesn't:

```crystal
def method
  case
  when true
    [1,2]
  end
end

p method.first
```

It fails with:

```
Error in ./case_bug.cr:8: undefined method 'first' for Nil

p method.first
         ^~~~~

================================================================================

Nil trace:

  ./case_bug.cr:1

    def method
        ^~~~~~

  ./case_bug.cr:2

      case
      ^
```

However, if save the result of the case statement branch that gets run, it works:

```crystal
def method
  res = [] of Int32
  case
  when true
    res = [1,2]
  end
  res
end

p method.first
```

This is a really odd behavior, but I don't quite understand how the expressions are evaluated, to know if it a bug or not.

**Comment by kirbyfan64** [comment]
Read up on Crystal's `Nil` checking. Basically, Crystal knows that the case may never be matched, so it's type is an array of numbers *or* `Nil`.

**Comment by jhass** [comment]
Yes, what's not apparent here is that Crystal doesn't track that you'll always runs in the condition, so the first example is closer to
```ruby
def method
  res = nil
  if true
    res = [1, 2]
  end
  res
end

**Comment by zamith** [comment]
Totally forgot about the way Crystal handles grouping types...

So, I can fix it with:

```crystal
def method
  case
  when true
    [1,2]
  else
    [] of Int32
  end
end

p method.first
```

Is there a better way?

**Comment by jhass** [comment]
Depends on the real code I guess.

**Comment by zamith** [comment]
[This](https://github.com/zamith/holmes/blob/master/src/selector_parser/css.cr#L7) is the actual code.

**Comment by waterlink** [comment]
If you are sure, that the thing you return is never `nil`, you can call `not_nil!` on it:

```crystal
def method
  case
  when true
    [1, 2]
  end.not_nil!
end

p method.first
```

link: http://carc.in/#/r/1ik

**Comment by jhass** [comment]
Mh, I don't think you'll get much better. I'd use an `if/else` personally until I need to add more branches. You may consider returning an empty tuple (`Tuple.new`) since that's mostly  API compatible, close to a null object for Array in fact, but should be completely gone in the generated binary.

**Comment by zamith** [comment]
Oh, cool. Thanks. Didn't know about that. @waterlink.

@jhass I think I'll stick with the Array, because `Tuple.new` does not respond with `nil` to `.first`, it responds with index out of bounds. But thanks for that.

**Comment by Exilor** [comment]
@zamith if it helps, ```#first?``` does return ```nil``` on an [empty tuple](http://play.crystal-lang.org/#/r/1j3).
