### ISSUE TITLE
`combination` and `repeated_permutation`

### ISSUE THREAD

**Issue by kerkomen** [manastech/crystal#733]
Ruby's `Array#combination` and `Array#repeated_permutation` cannot be found in Crystal. Are there any (simple) replacements? Are there reasons they are not implemented?
Sorry, if I've missed something, but I really couldn't find these methods.

**Comment by kostya** [comment]
i implemented it for topaz here https://github.com/topazproject/topaz/blob/master/lib-topaz/topaz/array.rb
i think it can be easy copied.

**Comment by asterite** [comment]
@kerkomen No reason, just nobody needed them for now, the language is still young (we are at 0.7.2), etc. Pull requests are welcome :-)

**Comment by jalyna** [comment]
I would like to tackle this issue :)

**Comment by kerkomen** [comment]
There's also a bunch of methods that lack from `Array#` in [Crystal](https://github.com/manastech/crystal/blob/master/src/array.cr) when comparing to [Ruby](https://github.com/ruby/ruby/blob/f8fb526ad9e9f31453bffbc908b6a986736e21a7/array.c):
`flat` and `flat!`,  `combination`, `repeated_combination`, `permutation`, `repeated_permutation`.

**Comment by jalyna** [comment]
@kerkomen Did you mean `flatten` and `flatten!`? I will then try those first. Thank you!

**Comment by asterite** [comment]
@kostya implemented the rest of these in #1190
