### ISSUE TITLE
Additions for Process

### ISSUE THREAD

**Issue by bararchy** [manastech/crystal#734]
Hi,

I needed to add some things to Process for a project I'm working on and I thought I should share the changes, they are too small for PR but maybe someone would like to use them, Those changes add ```Process.kill(pid, signal)``` and ```Process.getpgid(pid)```

* Add to LibC

```crystal
lib LibC
 fun getpgid(pid : Int32) : Int32
 fun kill(pid : Int32, signal : Int32) : Int32
end
```
* Add to process.cr

```crystal
module Process
  def self.getpgid(pid : Int32)
    if LibC.getpgid(pid) == 0
      return 0
    else
      raise "ESRCH"
    end
  end

  def self.kill(pid : Int32, signal : Int32)
    LibC.kill(pid, signal)
  end
end
```

Usage for kill is:

```crystal
pid = 1514
status = Process.kill(pid, 0)
if status == 0
  puts "Process is up!"    
else
  puts "No such Process id !"      
end
```
Or

```crystal
pid = 1443
puts "I hate process #{pid} !, I wish he was dead !"
status = Process.kill(pid, 9)
if status == 0
  puts "good riddance !"
else
  puts "process #{pid}, you won once more :("
end
```

**Comment by jhass** [comment]
There's no such thing as a too small PR ;)

**Comment by bararchy** [comment]
@jhass but...but... OK :(
I'll fork and PR.

**Comment by dziulius** [comment]
This method seems weird to me:

```crystal
 def self.getpgid(pid : Int32)
    if LibC.getpgid(pid) == 0
      return 0
    else
      raise "ESRCH"
    end
  end
```
Isn't it supposed to return process group id? Now it seems to return 0 or raise error (unless I'm blind).

**Comment by bararchy** [comment]
@dziulius , you are right, this isn't right, I'll fix it before the PR

**Comment by bararchy** [comment]
https://github.com/manastech/crystal/pull/735
Done.
