### ISSUE TITLE
Installation without homebrew

### ISSUE THREAD

**Issue by cuyler** [manastech/crystal#737]
Is there a way ( documented or not ) to install without the use of Homebrew, short of dissecting the Makefile? Some folks are weird and don't really want to use that tool but are interested in the work.

**Comment by asterite** [comment]
There's a pkg file in the release:

https://github.com/manastech/crystal/releases/tag/0.7.2

But in any way you will need a compiler binary because this is a self-hosted compiler.

**Comment by asterite** [comment]
I'll close this. Reopen if you need so.
