### ISSUE TITLE
Octal prefix is incosistent.

### ISSUE THREAD

**Issue by omeid** [manastech/crystal#740]
Just looking through the docs it seems like `0b` is used for binary, `0x` is used for hex, then why just `0` for Octal? wouldn't `0o` makes more sense?

**Comment by jhass** [comment]
Well, that's a common scheme that you can find in many languages.

**Comment by omeid** [comment]
The `0` comes from the old Unix days it seems.
Yes but later versions of Perl, Python, and ES have moved away from `0` only to Haskell like `0O`/`0o`. Ruby also at least as of version 2 supports the `0o` notation.

**Comment by asterite** [comment]
I think I'd like to only have the `0o` notation, as @omeid suggests. I dislike the `0` prefix to mean octal, like in C/Ruby, it's not very intuitive. Right now it's like that because we ported it from Ruby, but we can remove it. Thoughts?

/cc @waj @bcardiff

**Comment by waterlink** [comment]
+1 from me on leaving only consistent `0o` version

--
Best Regards,
Alexey Fedorov,
Sr Ruby Developer, Clojure Developer, Rust Developer,
+49 15757 486 476

2015-06-06 17:57 GMT+03:00 Ary Borenszweig <notifications@github.com>:

**Comment by bcardiff** [comment]
+1 for `0o`

**Comment by ozra** [comment]
Yeay!

**Comment by omeid** [comment]
Thanks a lot for accepting this improvement suggestion.
