### ISSUE TITLE
Improve the Sieve of Eratosthenes

### ISSUE THREAD

**Issue by mrjbq7** [manastech/crystal#750]
The homepage has an example of the [Sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes).

Given that Crystal seems interested in performance, I think you should at least change it to follow the "optimized" (start from squares) pseudocode on Wikipedia:

```crystal
# Compute prime numbers up to 100 with the Sieve of Eratosthenes
max = 100

sieve = Array.new(max + 1, true)
sieve[0] = false
sieve[1] = false

2.step(Math.sqrt(max)) do |i|
  if sieve[i]
    (i * i).step(max, i) do |j|
      sieve[j] = false
    end
  end
end

sieve.each_with_index do |prime, number|
  if prime
    puts number
  end
end
```

Obviously there are other faster sieves, bit-arrays to reduce memory usage, iterating over odd numbers only, wheel factorization, etc., but I think having a basically optimized version would be better than what is there currently.

It's not as elegant as checking every number excessively using ``(2..max).each``, but it's 30% faster.

**Comment by kirbyfan64** [comment]
It also shows off a little more of the language...

**Comment by mrjbq7** [comment]
The diff is pretty small:

```diff
< (2..max).each do |i|
> 2.step(Math.sqrt(max)) do |i|

<     (2 * i).step(max, i) do |j|
>     (i * i).step(max, i) do |j|
```

**Comment by asterite** [comment]
Thanks! But just some minutes ago I changed the sample and now it's a small HTTP server. The example was long and hard to read, and maybe this new one is more attractive.

@mrjbq7 A few minutes after I made the change I saw your issue, I didn't change it because of it. Just pure coincidence.

**Comment by mrjbq7** [comment]
Hah, nice timing!

One suggestion, if its easy, is to rotate examples on the front page randomly when it is loaded.

Close this issue anytime you want.

**Comment by kirbyfan64** [comment]
I hate those rotating examples. That's actually been a major criticism of Nim's website!

**Comment by mrjbq7** [comment]
Haha okay :-)
