### ISSUE TITLE
Ugly exception on String#[](regex, group)

### ISSUE THREAD

**Issue by tomas** [manastech/crystal#755]
On Ruby, this returns nil:

`"hello world"[/foo/, 1]`

On Crystal, this is what happens:

`"hello world"[/foo/, 1]`

```
Nil assertion failed (Exception)
*Exception#initialize<Exception, String, Nil>:Array(String) +46 [0]
*Exception::new<String>:Exception +149 [0]
*raise<String>:NoReturn +34 [0]
*IO::Error::new<String>:IO::Error +0 [0]
*String#[]<String, Regex, Int32>:String +129 [0]
__crystal_main +2111 [0]
main +76 [0]
__libc_start_main +247 [0]
_start +33 [0]
Program terminated abnormally with error code: 256
```

Is this the expected behaviour?

(Kudos for the work, by the way!)

**Comment by asterite** [comment]
Yes, it's expected behavior. Methods that usually return nil on "missing element" in Ruby raise an exception in Crystal. But, we usually provide a "question" method that returns nil in those cases:

```crystal
p "hello world"[/foo/, 1]? #=> nil
```

Same goes with:

```crystal
[1, 2, 3][4] # raises
[1, 2, 3][4]? # nil
```

Or

```crystal
([] of String).first # raises
([] of String).first? # nil
```

**Comment by tomas** [comment]
Cool. What's the suggested way of getting an array of matches for a string, then? `#scan`? I like Ruby's `String#[]` because it lets you quickly get a matching value or nil (e.g. for scraping/parsing third party content), e.g.:

```rb
if val = string[/regex/, 1]
 # use val for something
end
```

I also noticed that `"hello world"["foo"]` raises a Nil assertion failed exception. What's the proper/quickest way of checking whether a string is contained in another?

**Comment by datanoise** [comment]
The Ruby's equivalent is:

```crystal
if val = string[/regex/, 1]?
...
end
```

if you just want just to check if a substring is included in another:

```crystal
if string.includes?(substring)
...
end
```

**Comment by tomas** [comment]
Perfect. Thanks for the clarification!
