### ISSUE TITLE
Extending Macros

### ISSUE THREAD

**Issue by Vikaton** [manastech/crystal#760]
I want to propose a more flexible approach of using Macros in Crystal.

Let's take this code for example:
```Ruby
macro and(y,x) 
	{{y}} && {{x}}
end

	
puts and(7>5,2<5)
```

This returns `true`, but `and(7>5,2<5)` could be used in a different way which is what I'm proposing

```Crystal
macro and(y,x) 
	{{y}} && {{x}}
end

	
puts 7>5 and 2<5
```

This would also return true.

This is also similar to how Nim templates work.

```Nimrod
template `&&`(y,x): expr =
  y and x
```

**Comment by jhass** [comment]
What are the rules? You want to allow `argument1 name argument2` for all macros that take two arguments or...?

**Comment by ysbaddaden** [comment]
Notice the `expr = y and x` of Nim templates, they indicate the rule. The proposed Crystal syntax, however, doesn't define such an expression, which make them impossible to distinguish from regular Crystal macros —unless they are limited to a set of keywords, like the `def x=(value) end` and `def [](key) end` methods.

**Comment by Vikaton** [comment]
I guess we could use something similar to `macro and(x,y): expr`

**Comment by kirbyfan64** [comment]
Or Haskell backticks for infix operators? Before any macros are expanded, the compiler could rewrite ``a `x` b`` as `x(a, b)`.

**Comment by asterite** [comment]
But

```crystal
foo bar baz
```

is already

```crystal
foo(bar(baz))
```

There's no way we can distinguish both cases.

**Comment by Vikaton** [comment]
in this case it would bar(foo,baz)

**Comment by kirbyfan64** [comment]
@asterite But I'm referring to using backticks.

**Comment by asterite** [comment]
@kirbyfan64 Always?

**Comment by kirbyfan64** [comment]
@kirbyfan64 Wait, there might be a misunderstanding. I'm referring to using backticks to represent an infix operator, e.g. ``a `b` c`` meaning `b(a, c)`.

**Comment by asterite** [comment]
@kirbyfan64 But backticks are command execution in Crystal (and Ruby).

@Vikaton Any other infix use case? Having `&&` and `and` is redundant, why create new syntax for something that already exists and works well? Users have to learn more for no need.

**Comment by Vikaton** [comment]
@asterite It's just an option for people who want to extend the language on their own, it's a simple concept and adding flexibility to Crystal is a good thing IMO

**Comment by asterite** [comment]
I'll close this for now, all variants of this proposal go against language rules we have.

In my opinion extending the language with arbitrary syntax is not a good thing.
