### ISSUE TITLE
A compiler release for windows

### ISSUE THREAD

**Issue by nabeelomer** [manastech/crystal#762]
When are you planning to release a compiler for windows?

**Comment by asterite** [comment]
There's currently no one in the core team working on this, sorry. Also read this: https://groups.google.com/forum/?fromgroups#!topic/crystal-lang/grBVugVCHm0

**Comment by nabeelomer** [comment]
@asterite Can I make the compiler output ASM?

**Comment by asterite** [comment]
@nabeelomer Yes, do `--emit asm`

**Comment by nabeelomer** [comment]
@asterite Somebody working on a Windows release?

**Comment by asterite** [comment]
@nabeelomer Not really. There's [this](https://github.com/xwanderer/crystal/tree/win32), but we never merged it or tested it well, plus it's missing a lot of things.

**Comment by nabeelomer** [comment]
@asterite  I read issue https://github.com/manastech/crystal/issues/26. If you can give me some kind of a _'compiler frontend'_ for Crystal, I think I will be able to make it work.

**Comment by stephan-nordnes-eriksen** [comment]
@asterite You say I can run "`--emit asm`". Where can I do this? If I am able to get the asm, I might be able to convert that into an .exe and boostrap the compiler somehow.

**Comment by jhass** [comment]
This is really not about [crosscompiling](http://crystal-lang.org/docs/syntax_and_semantics/cross-compilation.html) but about getting stdlib compatible.

**Comment by stephan-nordnes-eriksen** [comment]
@jhass Maybe I am just naive, but how is it not about cross compiling? Wouldn't it be solved by something like mingw?

**Comment by kirbyfan64** [comment]
@stephan-nordnes-eriksen I issue is simply that the Crystal standard library doesn't work on Windows. So, it couldn't even possibly compile.

**Comment by jhass** [comment]
@stephan-nordnes-eriksen cross compiling is there, did you follow my link? stdlib is not there.

**Comment by nabeelomer** [comment]
@jhass You could release only the compiler and not the library for Windows (we'll call the Windows API for every thing).

**Comment by jhass** [comment]
@nabeelomer no, the compiler itself heavily relies on stdlib.

**Comment by ozra** [comment]
I'll just add a direct link here for reference: https://github.com/xwanderer/crystal/tree/win32/win32
Doesn't seem to have been touched for a few months though.
@nabeelomer - maybe you want to pick up the port? B-)

**Comment by svnpenn** [comment]
#5430
#6170
