### ISSUE TITLE
all_spec.cr takes an infeasibly long time to build in --release mode

### ISSUE THREAD

**Issue by asb** [manastech/crystal#768]
Pull request #766 enables passing flags when building the spec target. Although there's no real need to build the all_spec with `--release`, it seemed worth trying anyway. The result for me (core I5-3210M, 16GiB RAM) was a compile time of over 1 hour before my system started hitting the disk like crazy and I had to kill it. The spec suite is only a couple of tens of thousands of lines of code, so this does seem to represent a scalability issue in crystal compilation.

**Comment by kirbyfan64** [comment]
To me, it more lies inside the fact that the specs instantiates every single function in the library *and* the compiler.

**Comment by asb** [comment]
It's definitely a stress test. I'm filing the issue as it seems a reasonable medium-term goal that Crystal can compile its own spec suite in release mode.

**Comment by asterite** [comment]
On my machine parse + type inference + generate llvm IR code takes about 14 seconds for all specs. That isn't much, I think, given that there are **a lot** of specs. Then the bulk of time is spent optimizing LLVM code. I don't know what can be done about that.

One note is that with `--release` we only generate one LLVM module so we can't parallelize those. Maybe we can try parallelizing but maybe inlining optimizations aren't that effective, we'll have to try. There's also LTO (link time optimization) but I know nothing about that.

Another note is that I noticed LLVM becomes really slow when optimizing code involving array types (StaticArray in our case). I have no idea why.

**Comment by asterite** [comment]
With the above changes, compiling all_spec.cr in release mode takes less than 5 minutes. We expect that this time can still be improved a bit more.

**Comment by ysbaddaden** [comment]
All that time because the block was inlined? Crazy.

**Comment by asterite** [comment]
@ysbaddaden The main issue is that both `describe` and `it` weren't capturing the block, so all the code was inlined at the top-level. In this way, all the code for all the specs went into a single LLVM function and LLVM has a really hard time optimizing big functions with lots of variables.

One solution that we have in mind is to split top-level code into functions, one for each file, and from the main function call these functions. This will work and we could go back to non-captured blocks for specs. However, I thought a bit more about this and capturing blocks will allow us to, for example, run specs in a random order, or run them in parallel. So I think this is a good change :-)
