### ISSUE TITLE
Namespace pattern

### ISSUE THREAD

**Issue by yegortimoshenko** [manastech/crystal#78]
There are `CharReader`, `StringBuilder`, `StringScanner`, but still there are `String::Buffer` and `String::Formatter`.

There should be a common pattern, so it is better to choose the convention for these Classes, one or another.

I personally love `::` namespacing style more, since you can use it in class methods without writing `String::` at all:

```ruby
class String
  def self.new_from_buffer(capacity = 16)
    buffer = Buffer.new(capacity)
    yield buffer
    buffer.to_s
  end
end
```

and you should if you use `StringBuffer`, for example:

```ruby
class String
  def self.new_from_buffer(capacity = 16)
    buffer = StringBuffer.new(capacity)
    yield buffer
    buffer.to_s
  end
end
```

And it is more logical for me, since (e.g.) string buffer exists to produce strings and there won’t be `StringBuffer` without strings. Though, @asterite mentioned that it is easier to type without `::`, and it is true, so maybe `StringBuffer` style is better...

**Comment by asterite** [comment]
We already renamed some of this, like CharReader -> Char::Reader, StringBuilder -> String::Builder. If you'd like to propose more, send issues with specific name changes. Thanks!
