### ISSUE TITLE
bug with right while

### ISSUE THREAD

**Issue by kostya** [manastech/crystal#785]
crystal eval 'x = 0; x += 1 while x < 0; p x'
1
expected 0

**Comment by kerkomen** [comment]
The same for `until`:

```ruby
x = 0 
x += 1 until x >= 0
p x  #=> 1
```

It executes the body at least once.

This behavior is documented: [for `while`](http://crystal-lang.org/docs/syntax_and_semantics/while.html), [for `until`](http://crystal-lang.org/docs/syntax_and_semantics/until.html).
There is also [an issue](https://github.com/manastech/crystal/issues/549) about that.

**Comment by asterite** [comment]
Yes, this is a duplicate.

My vote is to remove `while` and `until` as suffix expressions. I think they are quite confusing and just save a few keystrokes. You can

**Comment by kostya** [comment]
suffix `while` imho is nice, but for one liners.
`x = 0; x += 1 while x < 0; p x`
1

reads like suffix `if`
`x = 0; x += 1 if x < 0; p x`
0

but result different, this is unexpected for me.

but this:
```ruby
begin
  ...
  ...
end while x < 0
```

and this imho bad:
```ruby
begin
  ...
  ...
end if x < 0
```

**Comment by jhass** [comment]
Can we continue discussion in #549 so it doesn't get split?

@asterite can you close duplicates and maybe even lock them so discussion focuses in the original?
