### ISSUE TITLE
http example memory leak ???

### ISSUE THREAD

**Issue by funny-falcon** [manastech/crystal#788]
I setup crystal 0.7.3 from debian repository.
Then compile "classic" http examle from main page with `crystal build --release http.cr`

````ruby
# A very basic HTTP server
require "http/server"

server = HTTP::Server.new(8080) do |request|
  HTTP::Response.ok "text/plain", "Hello world!"
end

puts "Listening on http://0.0.0.0:8080"
server.listen
````

It runs reasonably well under `ab` load and uses 14MB of resident memory.
I didn't shutdown `http`, and leave it idle for a couple of hours.
Then I'd run `ab` again and seen (in the `top) that `http` were using > 200MB of resident memory and 900MB of virtual memory.

Why it's memory usage increased despite it were idle?

**Comment by netroby** [comment]
This issue may be the same 
https://github.com/manastech/crystal/issues/773

**Comment by funny-falcon** [comment]
And may be not the same, so I created separate.

**Comment by asterite** [comment]
I wasn't able to reproduce this. I tried on a Mac and on a ubuntu precise64 VM.

**Comment by kostya** [comment]
confirm on ubuntu 14.04
i doing some `ab`, after that process have 211100 rss, after 5 minutes of idling, 340032 rss, and growing. strace shows only `epoll_wait(3,`, ltrace too.

**Comment by netroby** [comment]
Thanks @kostya

**Comment by asterite** [comment]
Yesterday @waj was able to reproduce the problem. If I understood correctly, the problem is that each `spawn` calls `malloc` to allocate the Fiber's stack and the OS assigns that memory to the process. Eventually the process is given to the process and it starts to go up (as far as I understood). One solution would be to use `mmap`, but that's all I know for now :-)

**Comment by waj** [comment]
I was able to reproduce the problem with just this small C code:

```c
#include <stdlib.h>
#include <stdio.h>

int main() {
  int i, j;
  char *m;
  for (i = 0; i < 10000; i++) {
    m = malloc(8 * 1024 * 1024);
    for (j = 0; j < 4096; j++) {
      m[j] = 123;
    }
  }

  getchar();
  return 0;
}
```

Seems like the OS keeps assigning memory pages before the process actually uses the blocks.
I also tried with mmap already but with the same behaviour.

**Comment by waj** [comment]
I reopen this issue because I'd like you guys to test this change

**Comment by kostya** [comment]
seems fixed, memory now 45~60Mb

**Comment by ysbaddaden** [comment]
I tested Artanis, which had the memory leak under 0.7.3, and this patch fixed it! Memory goes up, then it's regularly being reclaimed by the OS.
