### ISSUE TITLE
sleep in corountine hangs forever

### ISSUE THREAD

**Issue by ysbaddaden** [manastech/crystal#794]
Either I'm missing something, or there is a problem:

```crystal
spawn do
  puts "A"
  sleep 1 # locks the coroutine: the fiber will never be resumed
end

loop do
  puts "loop"
  sleep 1 # ok
end
```

Running this script generates the following output:

```
loop
A
loop
loop
loop
...
loop
```

If I remove the call to sleep in the coroutine, then it prints `A` continuously to the screen, but whenever I enable it back, the fiber will never be resumed.

Am I missing something about preventing the process to exit when there are coroutines running?

**Comment by waj** [comment]
I don't see why you expect the coroutine to continue running. There is no loop in your example.

If I run this:
```crystal
spawn do
  loop do
    puts "A"
    sleep 1
  end
end

loop do
  puts "loop"
  sleep 1
end
```

I get the expected output:
```
loop
A
loop
A
loop
A
...
```

**Comment by ysbaddaden** [comment]
Facepalm... I tried to reduce a failing example where introducing a sleep would hang. Indeed it works, and I can't reproduce the initial problem.
