### ISSUE TITLE
Recursion bug in compiler

### ISSUE THREAD

**Issue by wmoxam** [manastech/crystal#795]
def nil_tree(depth)
        if depth > 0
            [nil_tree(depth - 1), nil_tree(depth - 1)]
        else
            [nil, nil]
        end
    end
 
    tree = nil_tree(2)

When compiling I get:

    /usr/local/bin/crystal: line 6: 68933 Segmentation fault: 11  "$INSTALL_DIR/embedded/bin/crystal" "$@"

**Comment by asterite** [comment]
Thank you! Yesterday I also added #793, which is supposedly a reduced case for the above, but we'll see.

**Comment by asterite** [comment]
This is indeed a duplicate of #793
