### ISSUE TITLE
Inconsistence with >= <=

### ISSUE THREAD

**Issue by bararchy** [manastech/crystal#796]
This is valid:
```crystal
1 >= 2
```
this is not:
```crystal
1 => 2
```

this is valid:
```crystal
1 <= 2
```
this is not:
```crystal
1 =< 2
```

This is inconsistent.

**Comment by jhass** [comment]
Care to elaborate? How's `operator modifier` being allowed inconsistent with disallowing `modifier operator`?

**Comment by bararchy** [comment]
well, I expected that the same order of the operator will result in similar behavior
as in 
1 >= 2
one is bigger or equal to two.
1 =< 2
one is smaller to equal to two.

it looks the same.

but, because this "rocket" shape => is for hashes and other operators it is not allowed to be used in the mathematical expressions.
So i guessed this one <= wont be used as well (or at least be an alias to =< ) 

Is this just my OCD ?

**Comment by asterite** [comment]
Both `=>` and `=<` look weird to me, probably because almost no language uses that (I know [Erlang](http://erlang.org/doc/reference_manual/expressions.html#id78689) has some that always confuse me).

Chances of adding `=>` and `=<` as comparison operators are %0, sorry. There's nothing to win here except having to learn new syntax.

**Comment by jhass** [comment]
I  don't follow your reasoning

````
              1  > =  2                
              ^       ^                
              |  ^ ^  |                
  +-----------+  | |  +-------------+  
  |              | |                |  
  +          +---+ +----+           +  
[one] is [bigger] or [equal] than [two]


              1  < =  2               
              ^       ^               
              |  ^ ^  |               
  +-----------+  | |  +-------------+ 
  |              | |                | 
  +          +---+ +----+           + 
[one] is [lower] or [equal] than [two]

**Comment by bararchy** [comment]
@jhass you are right, when saying it it sounds better, when looking at it it looks weird... 
It's a nonsense discussion, I also saw that Ruby does the same.

I'll close the issue, ignore it ;)
