### ISSUE TITLE
Convert the idea behind Thread pool to Fibers/spawn

### ISSUE THREAD

**Issue by bararchy** [manastech/crystal#807]
I'm having some hard time learning the idea behind Fibers\coroutines and the implementation in Crystal.

I hope this is the right place to ask this, I'll totally accept a "not here" answer :) 

This is my usual way of handling multi-threading in Ruby:

```ruby
threads = []
max_threads = 10

loop do
  begin
    threads << Thread.new do
      helper_method(1,2,3,4)
    end
  rescue Exception => e
    puts "Error Starting thread"
  end

  begin
    threads = threads.select { |t| t.alive? ? true : (t.join; false) }
    while threads.size >= max_threads
      puts 'Got Maximum threads'
      sleep 1
      threads = threads.select { |t| t.alive? ? true : (t.join; false) }
    end
  rescue Exception => e
    puts e
  end
end
```
This way I open a new Thread, usually of a incoming connection or some other thing, add the Thread to a threads array, and then check that I don't have more threads then what I wanted.

What would be a good way to implement something similar in Crystal  using spawn\channels\fibers etc.. ?

**Comment by ysbaddaden** [comment]
You'll may want to start populating the #crystal-lang tag on stackoverflow.

The example in #802 is a good start. It explains how to spawn coroutines and have some communication throught channels. That being said, in order to keep a pool, you can't just duplicate the way it works for threads: `spawn` doesn't return a coroutine object, and there ain't no way to `join` coroutines.

That being said, this should work (maybe, I wrote this out of my mind):

```crystal
def worker(&block)
  result = UnbufferedChannel(Exception?).new

  ::spawn do
    begin
      yield
    rescue ex
      result.send(ex)
    else
      result.send(nil)
    end
  end

  result
end

def pool(size, &block)
  counter = 0
  results = [] of UnbufferedChannel(Exception?).new

  loop do
    counter += 1

    while counter < size
      results << worker { yield }
    end

    result = Channel.select(*results)
    if ex = result.receive
      puts "ERROR: #{ex.message}\n#{ex.backtrace.join("\n")}"
      counter -= 1
      results.delete(result)
    end
  end
end

pool(5) { helper_method(1, 2, 3, 4) }
```

**Comment by bararchy** [comment]
This looks interesting, I'll open the same question on SO, it's nice to spread to use of it.

**Comment by kirbyfan64** [comment]
@bararchy Good! If the tag goes entirely unused for six months, it will be deleted!

**Comment by bararchy** [comment]
Done --> http://stackoverflow.com/questions/30853566/crystal-convert-the-idea-behind-thread-pool-to-fibers-spawn
