### ISSUE TITLE
Integrating h2o Server?

### ISSUE THREAD

**Issue by pyros2097** [manastech/crystal#811]
Is it possible to use the [h2o](https://github.com/h2o/h2o) webserver instead of the default `http/Server`? Would making C bindings to it cause an overhead and reduce its performance?

**Comment by waj** [comment]
C bindings doesn't have any special overhead. At runtime they are just function calls.
The only overhead I can think is every time a string is returned by the library, to use in Crystal an memory allocation and copy is needed.
The `http/server` implementation is pure Crystal so it doesn't have those issues. But that doesn't mean it has to be faster than h2o.

**Comment by asterite** [comment]
I think the current HTTP Server (written in Crystal) is pretty fast. As @waj says, it's probably not the fastest one but we can always optimize it later. Having it written in pure Crystal means the code is easier to understand (maybe), we need less dependencies (I see h2o uses libuv) and integrates nicely with the rest of the standard library (we have HTTP::Request, URI, etc.).

@pyros2097 Can I close this? You can always provide bindings to h2o in a separate library (shard).

**Comment by pyros2097** [comment]
@asterite Yeah. If I get some time I'll try to create some bindings and benchmark it and see if we can make some performance improvements in the standard one. Less dependencies is always a lot better.
