### ISSUE TITLE
Omit curly braces in method call if last argument is a Hash

### ISSUE THREAD

**Issue by Codcore** [manastech/crystal#812]
Is it possible that someday we can omit curly braces  in method call if last argument is a Hash, like in Ruby? Or this is impossible for some reasons?
```crystal
def method(s : String, to : Hash)
  p s
  p hash
end

# now it works  next way
method "bacon",  { :key => "key" }

# ruby way
method "bacon",  :key => "key" 

# or even
method "bacon",  key: "key" 
```

It is pretty cool feature, as it allows to create more clear-looking DSL's

**Comment by ysbaddaden** [comment]
No. This is due to the way keyword arguments are handled in Crystal. See #322 and #560

**Comment by Codcore** [comment]
@ysbaddaden Thanks!

**Comment by Codcore** [comment]
[This link](http://crystal-lang.org/docs/syntax_and_semantics/default_and_named_arguments.html) helped me. It is really better approach then passing Hashes, and code looks clear as well.
