### ISSUE TITLE
Passing Slice to BufferedIO#read terminates at 8192nd character

### ISSUE THREAD

**Issue by lpm11** [manastech/crystal#813]
Hi all,

I'm new to Crystal and I really like it. Great work!

I have a question about BufferedIO. If I call BufferedIO#read without slice, it read whole buffer. On the other hand, passing Slice to BufferedIO#read makes different behavior: terminated at 8192nd character even if I pass an adequate size of Slice (FYI, 8192 is the same as BufferedIO::BUFFER_SIZE).

```crystal
text = "a" * 20_000 + "b"

io = BufferedIO.new(StringIO.new(text))
puts io.read[-1] # => b

io = BufferedIO.new(StringIO.new(text))
slice = Slice(UInt8).new(30000)
count = io.read(slice, 30000)
_text = String.new(slice)
puts _text[-1]    # => a
puts _text.length # => 8192
puts count        # => 8192
```

May I ask whether it is intentional or not?

**Comment by asterite** [comment]
This was definitely something to improve, thank you for letting us know!

**Comment by lpm11** [comment]
Great! Many thanks!
