### ISSUE TITLE
Installing on Lubuntu (and Ubuntu in general)

### ISSUE THREAD

**Issue by deathbeam** [manastech/crystal#818]
So, first, I want to introduce myselft. My name is Thomas and this project looks super interesting to me. I am right now working on game engine in Java, but as I saw this language and because I simply love style of Ruby, I decided that I will maybe switch to Crystal (currently using Java + C + LuaJIT in my engine).

And now, actual issue. I am running latest Lubuntu 15.04. I tried to follow this [guide](http://crystal-lang.org/docs/installation/on_debian_and_ubuntu.html) to install `crystal` CLI. So I ran

```
curl http://dist.crystal-lang.org/apt/setup.sh | sudo bash
```

and output was fine. But when I tried to install `crystal` with `sudo apt-get install crystal`, output said that it was not able to find `crystal` package.

**Comment by ysbaddaden** [comment]
I don't think there are packages for vivid but only for precise and trusty. What release does the apt repository in `/etc/apt/sourcea.list.d/` points to?

**Comment by bararchy** [comment]
1) make sure you did a full apt-get update.

2) you can just download the deb package and install it manually with dpkg -i crystal.deb

**Comment by kostya** [comment]
i usually download from here, unpack, and add to PATH bin dir. works fine.

**Comment by deathbeam** [comment]
@ysbaddaden I have there crystal.list files with contents:

```
deb http://dist.crystal-lang.org/apt crystal main
```

@bararchy
1) I did
2) Okay then, I can live with it :smile:

**Comment by jney** [comment]
same problem here due to `keyserver timed out`

```

Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.EKwuK2ND66 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/neovim-ppa_ubuntu_unstable.gpg --keyring /etc/apt/trusted.gpg.d/webupd8team_ubuntu_atom.gpg --keyserver keys.gnupg.net --recv-keys 09617FD37CC06B54
gpg: requesting key 7CC06B54 from hkp server keys.gnupg.net
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
```

**Comment by jhass** [comment]
keys.gnupg.net is a DNS round robin pool, just wait a bit or try another (specific) keyserver.
