### ISSUE TITLE
Using @ in non-constructor parameters crashes compiler.

### ISSUE THREAD

**Issue by booch** [manastech/crystal#82]
I was cargo-culting a bit, and didn't think about the `@` in front of a parameter name when I moved it from `initialize` to a class method. So code like this:

```
class X
  def self.y(@z)
  end
end
X.y(1)
```

crashes the compiler with:

```
bin/crystal: line 75: 31701 Segmentation fault: 11  "$DEPS_DIR/crystal" "$@"
```

If I understand correctly, it doesn't make sense to use `@` there, but we should get an error message instead of crashing.

**Comment by asterite** [comment]
Since classes don't have instance vars, I'll close this for now. If later we decide to have them, we'll just do it.
