### ISSUE TITLE
Recognize nil? as an is_a? ::Nil type check?

### ISSUE THREAD

**Issue by PragTob** [manastech/crystal#820]
Hi everyone,

I don't know if this is possible - I was just wondering if for type checking purposes it was possible to have `.nil?` have the same effect as `.is_a?(::Nil)`.

Point in case:

Given this `Option` class:

```
class Option
  def find(n : Int32) : String?
    if n % 2 == 0
      "strike"
    else
      nil
    end
  end
end
```

I want both

```
result = Option.new.find(2)
if result.nil?
  puts result
else
  puts result.upcase
end
```

and

```
result = Option.new.find(2)
if result.is_a?(::Nil)
  puts result
else
  puts result.upcase
end
```

to compile. Currently only the latter compiles while the first one gives a `Nil` trace :)

**Comment by jhass** [comment]
It's worth noting that the following program is usually equivalent:

```cr
result = Option.new.find(2)
if result
  puts result.upcase
else
  puts result
end
```

As well as
```cr
puts Option.new.find(2).try &.upcase
```

**Comment by bcardiff** [comment]
@PragTob Since each class may define `#nil?`, is seems not feasible right now to make the type inference narrow the type of the receiver object to not be nil.

The logic is wired to `#is_a?` and the `if` @jhass shows. For now that is the way it's supported.

**Comment by PragTob** [comment]
ah sure how could I forget about `if result` - I'm just so used to `if @result` but that doesn't work in crystal that I completely let it go :)

It's a super minor thing then - do we want to keep the issue open for further thoughts of maybe doing it in the future far ahead or rather close it?

**Comment by bcardiff** [comment]
This keeps coming from time to time. Rubyist are used to `#nil?` unless either that method is fixed on the compiler it seems unlikely to be supported for type restriction.

I think we can close this issue for now.

Thanks!

**Comment by asterite** [comment]
I think we can close it. If you see `@jhass` alternative solutions, they are all shorter than using `.nil?`: less to type, less to read. Not having `nil?` forces you to write a shorter solution, and I think that's something good (and makes code consistent between programmers).
