### ISSUE TITLE
Using HTTP Client?

### ISSUE THREAD

**Issue by pyros2097** [manastech/crystal#822]
I'm trying to use the http/client library any running into errors?
```ruby
client = HTTP::Client.new("playlyfe.com", 80, true)
client.get("/login")
```
And I'm getting these errors,
```ruby
Nil assertion failed (Exception)
*Exception#initialize<Exception, String, Nil>:Array(String) +21 [0]
*Exception::new<String>:Exception +111 [0]
*raise<String>:NoReturn +6 [0]
*Nil@Value#==<Nil, String>:Bool +0 [0]
*HTTP::Response::from_io<(OpenSSL::SSL::Socket | TCPSocket)>:HTTP::Response +183 [0]
*HTTP::Client#exec<HTTP::Client, HTTP::Request>:HTTP::Response +54 [0]
*HTTP::Client#exec<HTTP::Client, String, String, HTTP::Headers, Nil>:HTTP::Response +46 [0]
*HTTP::Client#get<HTTP::Client, String, HTTP::Headers, Nil>:HTTP::Response +48 [0]
*HTTP::Client#get<HTTP::Client, String, HTTP::Headers>:HTTP::Response +23 [0]
*Playlyfe#initialize<Playlyfe, String, String>:Int32 +163 [0]
*Playlyfe::new<String, String>:Playlyfe +107 [0]
__crystal_main +22848 [0]
main +35 [0]
__libc_start_main +245 [0]
_start +41 [0]
 +41 [0]
Program terminated abnormally with error code: 256
```

If  I get this working. I'll try adding some docs for it :smile:

**Comment by asterite** [comment]
Hi!

I made a small fix for this, it now raises an exception with "unexpected end of http response".

The problem with your code is that you are trying to connect to https via the port 80, but it should be 443. If you try that in a browser (https://playlyfe.com:80) you'll get an error too.

The solution is to use named arguments:

```crystal
require "http/client"

client = HTTP::Client.new("playlyfe.com", ssl: true)
response = client.get("/login")
response.to_io(STDOUT)
```

Please close if this works for you. Thanks!

**Comment by pyros2097** [comment]
Yes it works. Thanks. Now to port [playlyfe-ruby-sdk](https://github.com/playlyfe/playlyfe-ruby-sdk) to [playlyfe-crystal-sdk](https://github.com/pyros2097/playlyfe-crystal-sdk).
