### ISSUE TITLE
Support for SliceIO

### ISSUE THREAD

**Issue by benoist** [manastech/crystal#825]
Hey guys,

A few days ago we talked about support for SliceIO. Is this still a useful addition to the standard lib?

Cheers,
Benoist

**Comment by asterite** [comment]
We will probably want SliceIO, yes.

**Comment by jreinert** [comment]
I wrote a simple SliceIO in #1603 for specs. What should it be able to do otherwise? I think a constructor with type restriction `Enumerable(UInt8)` would make sense.

**Comment by benoist** [comment]
I had to create one for testing purposes as well, but have recently removed it from the library as it wasn't the right place and I didn't need it anymore. You can find my implementation here:

https://github.com/benoist/msgpack-crystal/blob/436ce7aa3ae046b3d7cd1a35b63b079b8c06c3fb/src/slice_io.cr

I don't know how correct this though.

**Comment by jreinert** [comment]
i've created a pr #1608 but i need some help getting the last two specs to pass. I'm clueless to what is happening there...

**Comment by jhass** [comment]
Given StringIO was renamed to MemoryIO, do we still want this? Related to #1681, we need clearer guidelines on this stuff from the language designers.

**Comment by benoist** [comment]
Will it work the same as SliceIO would then?

**Comment by asterite** [comment]
`MemoryIO` (formerly StringiO) lets you write to it and when with `to_s` you get a String, with `to_slice` you get a Slice. MemoryIO is growable. @benoist Does this fit your use cases? If so, please close this issue.

**Comment by benoist** [comment]
Just checked and it does.
