### ISSUE TITLE
HTTP::Server: performance drop + listening socket gets closed

### ISSUE THREAD

**Issue by ysbaddaden** [manastech/crystal#834]
While testing artanis for #788 (fixed) with wrk, I noticed 2 problems:

- a huge performance drop: from 70k/s requests to merely 23k/s.
- the listening TCP socket being closed :fearful: 

The app won't stop or fail or raise, but the listening socket gets closed. wrk can't connect anymore and lsof won't list the socket after the first wrk run. I can reproduce this every time on my ubuntu trusty laptop with current master. I cherry-picked the patch for #788 over 0.7.3 but everything is fine then: memory leak is fixed, 70k/s and the listening socket is kept opened.

I tried the HTTP::Server example against the current master, and got a bunch of `Unhandled exception: Error writing file: Broken pipe` when wrk finishes, with the same behavior: slow requests (37k/s) and the listening socket being closed.

**Comment by waj** [comment]
Can you try with a889171? It should fix the closed socket. The performance dropdown is due to the socket being not buffered by default after the IO refactor. It should be fixed for 0.7.4 anyway.

**Comment by waj** [comment]
I reopen until we do more testing

**Comment by waj** [comment]
@ysbaddaden can you try again? a9b00cc should fix the closed socket issue and 82e63bc should improve the performance

**Comment by ysbaddaden** [comment]
I confirm that both are fixed. The socket is kept open, and I even get better benchmarks (80k requests/s)! And memory is kept low & reclaimed. HTTP::Server rocks :-)

**Comment by waj** [comment]
Thanks @ysbaddaden! And we still have more improvements coming, yay! ;-)

**Comment by Codcore** [comment]
@waj nice work, thanks!
