### ISSUE TITLE
Bug: `"string".gsub(/\0*\s*/, "")` is just eating CPU

### ISSUE THREAD

**Issue by y8** [manastech/crystal#841]
You can try this:

`crystal eval 'puts "Parsing"; "string".gsub(/\0*\s*/, ""); puts "Done" '`

You will see `Parsing` and 100% CPU load from compiled program.

Crystal 0.7.3 [bf72b07] (Sun Jun  7 16:17:59 UTC 2015)
Darwin Kernel Version 15.0.0: Wed May 27 20:17:31 PDT 2015; root:xnu-3216.0.0.1.13~1/RELEASE_X86_64 x86_64

**Comment by y8** [comment]
Seems like it's related to the #787

**Comment by y8** [comment]
Seems like `*` (zero-or-more) is breaking it.

**Comment by asterite** [comment]
This is fixed in HEAD. You can check this using the latest standard library. Just clone the repo and from that directory do:

```
bin/crystal eval 'puts "Parsing"; "string".gsub(/\0*\s*/, ""); puts "Done" '
```

It should work fine. Note that for this you don't need to compile a new compiler, `bin/crystal` will pick the new standard library.
