### ISSUE TITLE
can I somehow get all @type.methods from first class-level macro call, not placing it in the end of class definition?

### ISSUE THREAD

**Issue by Codcore** [manastech/crystal#842]
Here is the code:
http://play.crystal-lang.org/#/r/4ro
```crystal
macro visible_methods
  {% a = @type.methods.map { |m| {{p m.name.stringify}} } %}
  "Visible methods:"
  {{debug()}}
  end

class A
  
visible_methods

def a
  visible_methods
end
  
visible_methods
  
def b
  visible_methods
end
  
visible_methods
  
def c
  visible_methods
end
  
visible_methods
  
end

a = A.new
a.a
a.b
a.c
```

Output is:
```
"Visible methods:"
  
  
"a"
  "Visible methods:"
  
  
"a"
"b"
  "Visible methods:"
  
  
"a"
"b"
"c"
  "Visible methods:"
  
  
"a"
"b"
"c"
  "Visible methods:"
  
  
"a"
"b"
"c"
  "Visible methods:"
  
  
"a"
"b"
"c"
  "Visible methods:"
  
```
All I need, it is to be able to be all class methods available at very first call of macro at class-level. Is it a way to say to interpreter not to call this macro while all Def's will not be setted to ```@type.methods```. I don't understand the whole picture what happens, so I can't figure out how to achieve this behavior.

**Comment by asterite** [comment]
It's pretty simple: code is read and interpreted by the compiler sequentially. If it's not sequential then it becomes confusing for the programmer.

But, imagine we say "let's first define all defs and then evaluate macros". Then you have this:

```crystal
class Foo
  visible_methods

  getter name

  def bar
  end
end
```

Because `getter name` defines a method, but it's a macro, in the `visible_methods` macro call you will only get `bar`. As you can see, it's not that simple.

The question is: why can't you place `visible_methods` at the end of the class definition?

**Comment by Codcore** [comment]
@asterite for aesthetics and practical reasons. Actually, I'm trying to implement analogue of Rails ```action_before```, it is will be confusing if  we will place it in the end of some thick controller.

**Comment by Codcore** [comment]
@asterite this makes sense, but in my case it is useful: I don't wanna no macro-defined def's, only that defined by user. So, there no way to bypass this behavior?

**Comment by asterite** [comment]
I'll have to see some real code to understand what you want to do. But one thing I know is that Crystal isn't 100% Ruby, so probably some (many) things will have to be done in a different way.

**Comment by Codcore** [comment]
@asterite here is the commit with simple macro implementation:
https://github.com/Codcore/Amethyst/commit/2b745c1c7d44d34f52ff19444712c7210659718f
what I need to do, is:
```before_action :authenticate, only: [:index, :profile]```
It sets callbacks from methods for actions. So, when we call ```index``` or ```profile``` action, ```authenticate``` will be called first. Current version works well, but it requires to implicitly specify ```only:``` option to list methods that callback will applied for. 
By default, if no ```only``` array implicitly passed to the macro, I want to set callbacks for all methods, expect those created by macros ```register_before_action_hooks```(it isn't inappropriate name, I know). So, I want to parse ```@types.methods``` and filter those methods I don't need, and then set ```only``` array from it.

**Comment by Codcore** [comment]
@asterite I realize that Crystal is not Ruby :wink: . I just try to make main approaches as familiar to newcomers from Rails as possible.

**Comment by asterite** [comment]
I think we'll probably need more features for this. One idea we had for a long time is to be able to mark methods with user-defined attributes and then at compile-time check these. That way you could mark some methods to execute before some other methods. We'd only need an "after" macro hook to execute after a class definition or after the initial semantic phase finishes. But right now what you want to do is kind of hard.

I actually don't see a big problem requiring the `before_action` to happen afterwards. In Ruby you can't invoke a method before you define it, so this would be consistent with this.

**Comment by Codcore** [comment]
@asterite  thank you for your time, maybe I will use some little hack for this so far.

**Comment by asterite** [comment]
I'll close this. I don't think it's doable because of how things must be done in some order.
