### ISSUE TITLE
Allow number after capital letter for type vars

### ISSUE THREAD

**Issue by ozra** [manastech/crystal#847]
```crystal
class SomeCls(T1, T2, T3) < OtherCls
end
```
Feels very natural, and it seems unlikely that anyone would name a type as `T1`.

**Comment by ysbaddaden** [comment]
For reference: it was decided in #487 and more specifically in [this comment](https://github.com/manastech/crystal/issues/487#issuecomment-81665690) that generics were to be denoted with a single letter.

**Comment by asterite** [comment]
I think using numbers is OK in this case. This is still better than having to invent a syntax for free/bound type vars.

**Comment by ozra** [comment]
Wow - that is fast dev'ing! :-)
