### ISSUE TITLE
Compiler eats all avaialbe memory and crashes with a recursive macro

### ISSUE THREAD

**Issue by veelenga** [manastech/crystal#849]
```sh
$ cat runner.cr
macro runner
  {{ run("./source.cr") }}
end
runner

$ cat source.cr
require "./runner"

$ crystal build runner.cr
```

Compiler starts eating cpu and memory:

![htop](https://cloud.githubusercontent.com/assets/3624712/8325432/4ec613e2-1a62-11e5-8d51-c367958d60aa.png)

Finally, it crashes when free memory not available anymore:
```
Error executing system command '/bin/sh': Cannot allocate memory
_init +170337 [80]
_init +2399237 [80]
_init +2421599 [80]
_init +2420152 [80]
....
_init +193658 [80]
_init +189991 [80]
__libc_start_main +240 [80]
_init +164313 [80]
 +164313 [80]

Error: you've found a bug in the Crystal compiler. Please open an issue: https://github.com/manastech/crystal/issues
```

Does it possible to detect such situation and warn ? It could be hard to understand what's going on in a large project.

**Comment by veelenga** [comment]
Or a bit simpler:

```crystal
# runner.cr
macro runner
  {{ run("./runner.cr") }}
end
runner
```

**Comment by asterite** [comment]
I'm afraid that would (probably) be [impossible](https://en.wikipedia.org/wiki/Halting_problem).

Did this happen to you accidentally, or you tried to crash the compiler on purpose?

**Comment by veelenga** [comment]
Accidentally. Bad side of this is editor/ide freezing(if this editor/ide is doing recompilation of a source automatically) and a chance of losing a source code updates. That happen to me with [vim syntastic](https://github.com/scrooloose/syntastic) plugin. But that's because I didn't understand how macro works.

In general, compile time recursion could be a powerful feature. Just now noticed few examples in C++.

Seems, this issue does not makes sense now. You may close it if do not plan updates.

Thanks!

**Comment by vyp** [comment]
Isn't syntastic just a syntax checker?

**Comment by veelenga** [comment]
Yes it is. And it uses a following command to check a syntax:

````
$ crystal run --no-build --no-color {source.cr}
````

**Comment by vyp** [comment]
Yes I just [saw](https://github.com/rhysd/vim-crystal/blob/77536d821380f49b9b7553b156fecf3186088e95/syntax_checkers/crystal/crystal.vim#L18), you're correct. Still, this is because vim doesn't allow async ops. I'm presuming an IDE will not have this problem. Vim does not have async *by design*, so you can't really blame it either.

**Comment by veelenga** [comment]
IDE will not freeze, but compiler will consume all memory.

**Comment by jhass** [comment]
I have to agree that this is most likely impossible to handle. If somebody can prove me wrong please comment or open a new issue! But I see no benefit in keeping this open :)
