### ISSUE TITLE
Time Parser consumes more numbers than required

### ISSUE THREAD

**Issue by benoist** [manastech/crystal#853]
Hi,

Time.parse("20150624", "%Y%m%d") raises an error expecting a number.
I can see that the parser consumes all digits when parsing %Y, however %Y should only consume 4 digits. This is the same for all number patterns with a fixed size.

Should the pattern.cr tell the parser how many digits it's allowed to consume per pattern?

```crystal
private def check_char(reader, char)
  case char
  when '%'
    case char = reader.next_char
    when 'y'
      year_modulo_100(2)
    when 'Y'
      year(4)
    when 'm'
      month_zero_padded(2)
    when 'M'
      minute(2)
    end
  end
end
```

**Comment by asterite** [comment]
@benoist Definitely! Nice catch!
