### ISSUE TITLE
Segfault in Hash/Array

### ISSUE THREAD

**Issue by Kilobyte22** [manastech/crystal#855]
When working with crystal yesterday i encountered an interesting bug.
Under some circumstances Arrays and Hashes can segfault when used inside an instance variable.

Code examples: [Array](http://carc.in/#/r/534) and [Hash](http://carc.in/#/r/53c)

**Comment by jhass** [comment]
Note this is a regression from 0.7.4, both examples work fine on 0.7.3.

**Comment by asterite** [comment]
@Kilobyte22 Thanks for reporting! And @jhass thanks for noting that it was a regression, it helped me figure out why it broke.

Basically, instance variables initializers didn't go through the second semantic phase. In 0.7.3 that didn't happen either (the bug predates that), but before [this commit](https://github.com/manastech/crystal/commit/702df90b57c01c272f567cf7e518ef0639a1b2af) some of that was also handled in the codegen phase (kind of ugly). It's kind of hard to explain (all the details), but a more complex code would break it both in 0.7.3 and 0.7.4.

But, now there are specs in place and I also put more "shouldn't reach this" bug checks :-)

**Comment by Kilobyte22** [comment]
Awesome! Also mad props for resolving the issue that quickly. Now I can go on with my life (read: code)

**Comment by asterite** [comment]
@Kilobyte22 You can, of course, initialize te variable in all of your initialize methods as a workaround until the next release.

**Comment by Kilobyte22** [comment]
For most part I run the self compiled version from git anyways
