### ISSUE TITLE
Type inference for conditions?

### ISSUE THREAD

**Issue by pyros2097** [manastech/crystal#865]
I Have a constructor like this,
```ruby
class Playlyfe
   def initialize(@client_id, @client_secret, @store = nil)
       unless @store
          @store = ->(token : Hash(String, JSON::Type)) { puts "Storing Token" }
       end
   end
   
  def get_access_token
      token = {} of String => String
      @store.call token
  end
end
```

```
in ./playlyfe.cr:83: instantiating 'get_access_token()'

      token = get_access_token()
              ^~~~~~~~~~~~~~~~

in ./playlyfe.cr:67: undefined method 'call' for Nil

    @store.call token
           ^~~~


```
But I get this compile error shouldn't the compiler know that @store will never be nil.

Anyway I tried this
```ruby
def initialize(@client_id, @client_secret, @store = ->(token : Hash(String, JSON::Type)) { puts "Storing Token" })
end
```

But then this gives this this error
```
in ./playlyfe.cr:67: undefined method 'call' for String

    @store.call token
           ^~~~
```

And is there an easier way to alias this `{} of String => String`
I tried `alias ReqQuery = Hash of String => String` But that doesn't seem to work.

**Comment by jhass** [comment]
The alias should just be `alias ReqQuery = Hash(String, String)`. For the other question see #477.

**Comment by pyros2097** [comment]
Thanks got that alias thing working. But now when I create an empty hash parameter with this alias
```
def api(method, route, query = {} of ReqQuery)
end
```
it gives me this error 
```
x error in ./playlyfe.cr:93: expecting token '=>', not ','

  def api(method, route, query = {} of ReqQuery, body = Object.new, raw = false)                                          ^
```
Is this not possible or is there some other syntax because I have a lot of methods with this and don't want to redefine the types.

**Comment by jhass** [comment]
Simply do `query = ReqQuery.new`

**Comment by pyros2097** [comment]
Thanks that works.. Need to learn more on crystal.
