### ISSUE TITLE
Compiler crash with redefined new and instance variable access

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#867]
```cr
class Foo
  def self.new
    super
  end
  
  def initialize
    @msg = 1
  end
  
  def foo
    @msg
  end
end

Foo.new.foo
```

slightly reduced from http://carc.in/#/r/5j9

**Comment by jhass** [comment]
Still present in 0.7.6 http://carc.in/#/r/dfk

**Comment by greyblake** [comment]
@jhass @asterite Looks like it's alrady fixed in 0.10.0 and 0.11.0:

INPUT:
```crystal
class Singleton
  getter :msg

  private def self.new
    super
  end

  def initialize
    @msg ="hello"
  end

  def self.instance
    @@instance ||= new
  end
end

p Singleton.instance
p Singleton.instance
a = Singleton.instance
a.msg
```


OUTPUT:
```
Using compiled compiler at .build/crystal
Error in ./crash.cr:17: instantiating 'Singleton:Class#instance()'

p Singleton.instance
            ^~~~~~~~

in ./crash.cr:13: instantiating 'new()'

    @@instance ||= new
                   ^~~

in ./crash.cr:5: undefined method 'new'

    super
    ^~~~~

```

So the issue can be closed

**Comment by jhass** [comment]
It no longer crashes the compiler indeed https://carc.in/#/r/qno

Not too sure if the error makes sense though, @asterite what do you think?

**Comment by asterite** [comment]
I don't know what this is meant to do:

```crystal
  def self.new
    super
  end

  def initialize
    @msg = 1
  end
```

I mean, `initialize` and `new` conflict. We should just decide what happens in this case.

**Comment by jhass** [comment]
I guess the intent was to make new private, any way to do that?

**Comment by asterite** [comment]
`private def initialize`

**Comment by asterite** [comment]
But it's something kind of recent, introduced in 0.8.0 (this issue was created before that)

**Comment by jhass** [comment]
Alright then.
