### ISSUE TITLE
"\n".strip => negative index exception

### ISSUE THREAD

**Issue by ysbaddaden** [manastech/crystal#873]
Trying to build Prax against 0.7.4 I noticed exceptions with String#split which I reduced to this simple case:

```crystal
puts "\n".strip
```

```
negative count (ArgumentError)
*Exception@Exception#initialize<ArgumentError, String>:Array(String) +46 [3467824627879784480]
*ArgumentError#initialize<ArgumentError, String>:Array(String) +6 [3467824627879784480]
*ArgumentError::new<String>:ArgumentError +97 [3467824627879784480]
*String#byte_slice<String, Int32, Int32>:String +794 [3467824627879784480]
*String#strip<String>:String +231 [3467824627879784480]
```

Git bisect outlines this commit 6edd2f4df7bbaff0dc37cbe3f42326edf366f340 (Fixed `String#[]` and `Array#[]` semantic for some border cases.)

**Comment by asterite** [comment]
Thanks! It seems strip was "broken" before that but because byte_slice was too permissive it worked fine.

**Comment by kubakrzempek** [comment]
Hi @asterite, do you have any plan to release a new crystal with the fix? I'm asking because I don't know if I'd rather install some older version or wait for the release.
Thanks!

**Comment by asterite** [comment]
@kubakrzempek Not in at least a week, because right now we are at [curry on](http://www.curry-on.org/) / [ecoop](http://2015.ecoop.org/), so, Prague, and we have very little time.

In the meantime you can try to compile the compiler and use that, by simply using `path_to_crystal/bin/crystal your_app.cr`.

**Comment by kirbyfan64** [comment]
@asterite Is the Crystal talk at curry on going to be available online soon?

**Comment by asterite** [comment]
@kirbyfan64 Yes! According to the organizers they will be online in two or three weeks. There were two tracks so we of course missed half of them, they were all really good so we are also eager to see them :-)
