### ISSUE TITLE
crash in loop do

### ISSUE THREAD

**Issue by bararchy** [manastech/crystal#879]
I got the error with this:
http://carc.in/#/r/5ou
```crystal
require "base64"
require "secure_random"

pool = {} of String => Hash
pool["Session_ID"] = {cookie: "bar", username: "admin", password: "secret"}


loop do
  sid = Base64.urlsafe_encode64(SecureRandom.random_bytes(128))
  break unless pool.has_key?(sid)
end
```

I managed to minimize it to this:
http://carc.in/#/r/5ov
```crystal
require "base64"
require "secure_random"

loop do
  sid = Base64.urlsafe_encode64(SecureRandom.random_bytes(128))
end
```

**Comment by asterite** [comment]
Does it crash anywhere else carc.in? I tried it on a mac and on a linux vm and it doesn't crash.

Also, please specify next crash what crashes: the prorgam or the compiler?

**Comment by jhass** [comment]
I think the random number generator is broken/disallowed in the sandbox for now.

**Comment by bararchy** [comment]
Oh... now testing against HEAD, it seems to build and run at my environment... 
Sorry about it.

**Comment by jhass** [comment]
@bararchy the issue was that the sandbox had no access to `/dev/random` and `/dev/urandom` and thus OpenSSL failed to seed the PRNG for us, it's fixed now http://carc.in/#/r/5rf

**Comment by jhass** [comment]
What would've been helpful in debugging this is if crystal would call SSL_load_error_strings if OpenSSL was loaded, though I guess @datanoise's version already does that?

**Comment by bararchy** [comment]
@jhass for now (https://github.com/datanoise/openssl.cr/commit/5e945c67ace0bf3100fcc2c7f52a72d1fc3d1ae1) only checking for errors on sockets.
I'll send a PR with additional checks for this.
Thanks :)
