### ISSUE TITLE
Descrepancy for hash-literals passed to function

### ISSUE THREAD

**Issue by ozra** [manastech/crystal#891]
Unsure if it's a bug, or I've missed some rule regarding hash-literals.

Works:
```crystal
do_stuff({
    foo: "blargh"
    bar: "klorkh"
})
```

Doesn't:
```crystal
do_stuff {
    foo: "blargh"
    bar: "klorkh"
}
```

**Comment by jhass** [comment]
The ambiguity is the one to the block literal:

```cr
foo.tap {
  puts "Hello World"
}
```

**Comment by ozra** [comment]
Ok, they're "competing" for the brace. Perhaps distinction should be clarified somehow?

**Comment by jhass** [comment]
Ruby "solves" this by making the braces of the hash literal optional if it's the last argument.

```rb
foo foo: "blah", bar: "blub"
foo {
  puts "hi"
}
foo(foo: "blah", bar: "blub") {
  puts "hi"
}

foo foo: "blah", bar: "blub" do
  puts "hi"
end
```

**Comment by ozra** [comment]
It works good with the parens so that's all good anyway :)

The open hash literal seems like it could cause more ambiguity problems than solve (Livescript and coffeescript comes to mind).

What's the precedence for the `{` parsing, including other potentially conflicting uses?

**Comment by jhass** [comment]
Uh, let's see

```cr
Constant { initial data }, Set {1, 2, 3}, HTTP::Headers {"Foo" => "bar"}
method { block  }, map {|i| i*2 }
method this_method_receives_the_block { block }, puts map {i| i*2 }
this_method_receives_the_block method do block; end, 1.upto limit do |i| puts i; end
variable = {hash literal}, foo = {bar: "baz"}, foo = {:bar => "baz"}
```

mmh, not sure I catched all

**Comment by ozra** [comment]
Thanks a lot for the run down! :)

**Comment by jhass** [comment]
Hey @ozra still with us? :) Got any ideas on what doc to improve?

**Comment by ozra** [comment]
Hey @jhass, sorry time has filled up quite a bit, so no doc fixes :-/ Am using Crystal full on for a project though :) I'll just close this.
