### ISSUE TITLE
macro templating in asm() block space sensitivity

### ISSUE THREAD

**Issue by aktowns** [manastech/crystal#895]
Not quite sure if this a bug or I'm missing something obvious but I have the following

``` crystal
macro test(nap)
  asm("
    .asciz \"{{ nap }}\"
    .asciz \" {{ nap }} \"
  ")
  {{debug()}}
end

test(hello)
```
which gives me the following output
```crystal
  asm("
    .asciz \"{{ nap }}\"
    .asciz \" hello \"
  ")
```
Is there a whitespace insensitive way to insert the template variables?

**Comment by aktowns** [comment]
A similar case is 
```crystal 
macro test(*args)
  asm("
    .asciz \" {% for x, i in args %}{{x}}{{i}}{% end %}\"
  ")
  {{debug()}}
end

test(hello, there)
```
which  gives me 

```
Syntax error in eval:1: unterminated macro
````

but if i unbalance the speech marks with 
```crystal
  asm("
    .asciz \" {% for x, i in args %}{{x}}{{i}}{% end %}\\"
  ")
```
[it compiles](http://play.crystal-lang.org/#/r/5st)

**Comment by asterite** [comment]
These are definitely bugs, we'll fix them.
