### ISSUE TITLE
Compiler crash (or quiet allowance) on assignment to `self` within a multiple assignment

### ISSUE THREAD

**Issue by Perelandric** [manastech/crystal#908]
A multiple assignment that assigns to `self` either crashes the compiler or fails to error.

Given the following code, the compiler with crash:

```
struct TypeA
  def initialize()
  end 
  def bar(other)
    self, other = other, self
  end 
end

struct TypeB
  def initialize
  end 
end

a = TypeA.new
b = TypeB.new

puts(a.bar b)
```

Changing the following code so that the types are the same will result in no crash, but no error:
```
a = TypeA.new
b = TypeA.new
```

In either case, if we replace the multiple assignment with a temp variable, we get the expected `can't change the value of self` error:

```
    t = self
    self = other
    other = t
```

> crystal --version
> Crystal 0.7.4 [42efdbf] (Wed Jun 24 01:08:36 UTC 2015)

**Comment by asterite** [comment]
@Perelandric Thanks for reporting this!
