### ISSUE TITLE
Class macros

### ISSUE THREAD

**Issue by booch** [manastech/crystal#92]
If I define a class macro:

~~~
class X
  macro self.let(name, value)"
    def #{name}
      #{value}
    end
  "end
end
~~~

I can use it like this:

~~~
class X
  let :x, 1
end
~~~

but not like this:

~~~
X.let :x, 1
~~~

That gives `undefined method 'let' for X:Class`.

But they're effectively equivalent code, and it would help write better DSLs to allow the second form as well as the first.

**Comment by asterite** [comment]
Hey! We finally implemented this? There's no need to use the `self` keyword (yet... in the future we'll probably want to distinguish this).
