### ISSUE TITLE
Can't create proc from instance method at class scope

### ISSUE THREAD

**Issue by Codcore** [manastech/crystal#924]
http://play.crystal-lang.org/#/r/6cx
```crystal
class My

  def hello
    9
  end

  @@hello = ->hello
end
```
Output:
```
Error in line 7: undefined local variable or method 'hello'
```
It works as intended? Is there any way to bypass this behavior?

**Comment by jhass** [comment]
Which instance would you expect the call to happen upon?

**Comment by Codcore** [comment]
@jhass sorry, didn't understand your question. I just wanna to save proc in class variable. Then I planned to pass this proc to the instance of other class.

**Comment by jhass** [comment]
Well, if your method doesn't depend on an instance, simply don't make it an instance method and it starts working: http://play.crystal-lang.org/#/r/6ds

**Comment by Codcore** [comment]
@jhass it sounds reasonable. Thanks!
