### ISSUE TITLE
Overloading Float64 fails, iff type constraining arg with generic class

### ISSUE THREAD

**Issue by ozra** [manastech/crystal#935]
It can be worked around by dropping the type constraint for now.

Works:
```crystal
class Foo
end

struct Float64
    def /(other: Foo)
    end
end
```

Fails with ` Bug: called Bar(_).is_restriction_of?(Int8)`:
```crystal
class Bar(T)
end

struct Float64
    def /(other: Bar(_))
    end
end
```

**Comment by ozra** [comment]
God damn @asterite! You must be one of the fastest developers I've seen swish by! :)

**Comment by asterite** [comment]
@ozra Thanks! If the fix is easy it's better to do it quickly, otherwise bugs accumulate and later it's (mentally) harder to do it. You can also see the commit is very short, the spec is larger than the fix. But... I don't fix all of them that quickly :-)

**Comment by ozra** [comment]
@asterite Know what you mean, easier to climb a hill than a mountain :)
