### ISSUE TITLE
Alternative if / ternary syntax

### ISSUE THREAD

**Issue by ozra** [manastech/crystal#937]
Not too unlikely, this will be frowned upon as 'not Ruby', but in any event:

In issue #406 it was touched upon the possibility of changing the ternary operator `foo = condition ? true_expr : false_expr`, for example to: `foo = condition ?? true_expr :: false_expr`

A proposition, from a construct I've been toying with for some time that is starting to grow on me more and more is:
```
foo = if condition ? true_expr : false_expr
````
That is: the good ole' ternary, simply with `if` prefixed, as a syntactic requirement.

"Why the hell" you ask?

**From the `ternary` perspective:**
- `If` before it is almost as short.
- Disambiguates the `?` and makes parsing even more clear.
- Visually easier to distinguish for the reader

**When seen from the `if-expression` perspective:**
- Easier way of making if-expression with two one-expression branches (common one liner used _instead_ of ternary)
- The question mark comes in a reasonable semantic place, when the 'ternary-if' is chosen (which by then of course isn't a ternary, but you catch the drift).
- The regular way (if no `?` after condition) is available as usual for blocks, or when explicit `end` is wanted despite one line usage, or simply by stylistic choice.

Note: I've used the ternary _a lot_, also in a language which only has the ternary for logic ops, so this is not about me being alien to that construct. It objectively (?) simply isn't good enough to cut it into the next era of programming.
(The idea came from my dislike with the current situation of constructing _clear_ one-liner conditional expressions, and from the, imo, misplaced, but very cool idea of `is_a?` [ending question marks]).

**Comment by pkorotkov** [comment]
In context of discussion of ternary-if modifications I dare propose my version of replacement for the current ternary operator:
```
foo = true_expr if condition else false_expr
```
Essential part of this syntax is actually already [in the language](http://crystal-lang.org/docs/syntax_and_semantics/as_a_suffix.html) and seems not a deal to be extended with else clause.
Factoring out other benefits from removing additional usages of symbols `?` and `:`, I believe that such syntax makes code much more readable and encourages using better constructions. Just compare:
```
x = a ? "a" : b ? "b" : "c"
VS
x = "a" if a else "b" if b else "c"
```

**Comment by alex-fedorov** [comment]
@pkorotkov Last code example is totally unreadable in both cases actually. If you have such complicated ternary operation usage, I would advice not to use them at all. Just extract simpler methods with guard clauses (`return ... if ...`).

"You see here one method, I see here 3 classes" (c).

**Comment by alex-fedorov** [comment]
Following this up, I would ask tricky question: "Is it worth to have ternary operator at all?".

**Comment by pkorotkov** [comment]
@alex-fedorov Well, I'd agree that ternary-if is not worth at all. Others may not. As to my code snippets, these two lines are equally bad styled (allusions to [this PR](https://github.com/manastech/crystal/pull/1055)) but the the first one is dramatically less readable as compared to the second.

**Comment by alex-fedorov** [comment]
Probably. For my small brain, they are both off limits and my brain refuses to process them :P 

Even the comment from @asterite to this PR says such a thing: https://github.com/manastech/crystal/pull/1055#issuecomment-126167673

**Comment by stugol** [comment]
I use ternary-if quite a lot, and think it should remain in the language. Chained ternaries, on the other hand, are mind-bending. Use ```case``` instead for complex situations.

**Comment by asterite** [comment]
I'll close this. The current `if` and ternary operators are fine.
