### ISSUE TITLE
Weird minimal case with finalize and class-var of self type(?) crashes compiler.

### ISSUE THREAD

**Issue by ozra** [manastech/crystal#941]
```crystal
class Cls
    @@current–instance = Cls.new
    def finalize()
    end
end
```

**Comment by asterite** [comment]
Workaround (for now): define the `@@current-instance` variable after the finalize method.

After the trip we have a plan to enhance the semantic so that first methods are declared and then "top-level" code is type checked. This way you won't get these errors anymore. A related discussion is #911.

**Comment by ozra** [comment]
Ok, good to know. I went with a global mean while. I'll read the discussions for a better picture.
