### ISSUE TITLE
Convert string to symbol

### ISSUE THREAD

**Issue by michelboaventura** [manastech/crystal#943]
Is it possible to convert a string to a symbol? I've searched on docs and source and didn't find anything like that.

I'm porting some ruby code to crystal and it has something like this:

```Ruby
def method_missing(name, *args)
  @callbacks[name].call
end
```

I've ported the method_missing as a macro, but ``name`` on ruby is a symbol, but on Crystal is a String.

**Comment by bcardiff** [comment]
@michelboaventura Symbols are translated to numbers in compile time. There is a symbol_table in the compiled program but used to get string representation of the symbol. There is no way AFAIK to get symbols from strings. Notice that possible symbols are bound to symbols using during compilation.

But, regarding your snippet, what is the problem of @callbacks been a Hash from String to proc?

This works http://play.crystal-lang.org/#/r/6jk 
```crystal
class ObjWithCallbacks
  def initialize
    @callbacks = {} of String => (->)
  end

  def add(name, &callback)
    @callbacks[name.to_s] = callback
  end

  macro method_missing(name, arg, block)
    @callbacks[{{name}}].call
  end
end

o = ObjWithCallbacks.new
o.add :foo do
  puts "this is foo"
end
o.add :bar do
  puts "this is bar"
end

o.foo
o.bar
```

And here is another example that build a proxy, here the name in method_missing is used to forward the message to another object, without translating to string. http://play.crystal-lang.org/#/r/6jl
```crystal
class Real
  def bar
    42
  end

  def foo(x)
    x
  end
end

class Proxy(T)
  def initialize(@inner : T)
  end

  macro method_missing(name, arg, block)
    puts "proxy call to {{name.id}}"
    @inner.{{name.id}}({{*arg}})
  end
end

p = Proxy.new(Real.new)
puts p.bar
puts p.foo(31)
```

**Comment by michelboaventura** [comment]
Hi @bcardiff, nice codes :) Your idea of storing keys as string but accepting user to call it by symbol will work for me, thanks!

I have nothing agains using strings instead of symbols, it's just I'm so used to use symbols as keys (being a ruby programmer for like a decade),

I will try your approach, thank you again!

**Comment by bcardiff** [comment]
@michelboaventura If you are not expecting to get string from the outside world you can actually store them by symbols

http://play.crystal-lang.org/#/r/6k1

```crystal
class ObjWithCallbacks
  def initialize
    @callbacks = {} of Symbol => (->)
  end

  def add(name, &callback)
    @callbacks[name] = callback
  end

  macro method_missing(name, arg, block)
    @callbacks[:{{name.id}}].call
  end
end

o = ObjWithCallbacks.new
o.add :foo do
  puts "this is foo"
end
o.add :bar do
  puts "this is bar"
end

o.foo
o.bar
```

happy coding!

**Comment by Djok39** [comment]
i found that way for myself, looks ok.
but not sure how much this efficient
```
require "kemal"

modes = Set{:manual, :auto}
prevId = -1
modes.each{|s| 
  raise "sequence is broken" if (prevId >= s.to_i)
  prevId = s.to_i 
}

get "/" do |env|
  s = modes.find{|x| x.to_s == env.params.query["mode"] }
  s.inspect
end

Kemal.config.port = 80
Kemal.run
```
