### ISSUE TITLE
Suspected erronous octal nums in io.cr because of #770

### ISSUE THREAD

**Issue by ozra** [manastech/crystal#947]
I just stumbled upon this when rumbling around the source, and it looks a tad "suspicious". I'm not sure, but figured it was better to post an issue just in case - otherwise just close it.

Random snippet from io.cr:
```
...
  S_IRWXU    = 0000700         # RWX mask for owner
  S_IRUSR    = 0000400         # R for owner
  S_IWUSR    = 0000200         # W for owner
  S_IXUSR    = 0000100         # X for owner
...
```
These looks much like intended octal numbers, which they also where before #770. Is it a left over? Perhaps the lexer should produce warnings on numbers beginning with zeros that are "suspected" "octal mistakes"?

**Comment by jhass** [comment]
Uh, #770 wasn't merged yet and does update those constants.

**Comment by ozra** [comment]
Ah, ok. :-)
