### ISSUE TITLE
Mistake in docs

### ISSUE THREAD

**Issue by yavora** [manastech/crystal#948]
In first example 
"hello".succ #=> "hell**p**"

http://crystal-lang.org/2015/04/01/auto.html

**Comment by bjmllr** [comment]
Crystal doesn't actually have `String#succ`. Ruby does, though:

```ruby
[1] pry(main)> "hello".succ
=> "hellp"
```

**Comment by yavora** [comment]
Yeaa, i actually read comments finally :D
Nevermind.
