### ISSUE TITLE
Create class instances dynamically

### ISSUE THREAD

**Issue by hugoabonizio** [manastech/crystal#949]
I couldn't find a way to do something like this http://stackoverflow.com/questions/2556193/reflection-in-ruby-instantiate-an-object-by-given-class-name 

Maybe we need a Object.const_get implementation or is there another way?

**Comment by jhass** [comment]
There are some workarounds, it depends largely on the why and where the class name would come from.

**Comment by asterite** [comment]
@hugoabonizio What's your specific use case? We usually tend to add features to the language if we find a few good use cases for them.

**Comment by hugoabonizio** [comment]
My idea is declare routes like get "/", "welcome#index" (for example),instantiate WelcomeController class and call index method.

**Comment by waterlink** [comment]
"railsy" :)

Why not `get "/", WelcomeController.index`, where `get` is a macro, that
accepts `CallASTNode`? something along these lines:

```crystal
macro get(route, mapping)
  Route.get({{route}}) do |request|
    {{mapping.receiver}}.new(request).{{mapping.name}}
  end
end
```


--
Best Regards,
Alexey Fedorov,
Sr Ruby Developer, Clojure Developer, Rust Developer,
+49 15757 486 476

2015-07-08 2:09 GMT+03:00 Hugo Abonizio <notifications@github.com>:

**Comment by kostya** [comment]
```ruby
class A
  def bla
    p :bla
  end
end

macro make_proc(name)
  {% a = name.split("#") %}
  cl = {{a[0].capitalize.id}}.new
  ->cl.{{a[1].id}}
end

make_proc("a#bla").call
```

**Comment by asterite** [comment]
@waterlink and @kostya have the key to it.

(I started writing this while @waterlink and @kostya answered, they are too fast!)

I see. Well, my advice is to forget about such dynamic capabilities that Ruby offers you and then think about how you could do it in some other way... preferrably at compile time.

So in Ruby you write that code, then you instantiate the WelcomeController at runtime and if it doesn't exist, boom, crash. If you rename the index method, boom, runtime crash. You don't want those things to happen. I know they don't *usually* happen, and they are easy to fix, but they also involve a runtime cost (but probably that can't be fully avoided).

So, you can do a simple thing (but definitely not routing) like [this](http://play.crystal-lang.org/#/r/6m7). It's basically building `WelcomeController.new.index` at compile time. Use it wrong, [your program won't compile](http://play.crystal-lang.org/#/r/6m8).

Now, dealing with macros and thinking about all of this at compile time is definitely not simple, and our macro language isn't very powerful (yet), and we don't have all patterns for this (yet), so we'll have to figure them out together :-)

**Comment by asterite** [comment]
And now I read @waterlink and @kostya answers and they are brilliant and pretty simple :-)

**Comment by asterite** [comment]
So, I think I just found a pattern that might work. Right now macros can only be invoked without a receiver, so `foo` could be a macro call, but `Foo.bar` can never be. But with have `with ... yield` (just realized it's not documented -_-), so we can do something like [this](http://play.crystal-lang.org/#/r/6m9). So, basically, the `get` works because it's now looked up in the context of the `Routes` class. Of course I wouldn't model it *exactly* like that, but for a start it could be good.

An interesting idea is that after the `with self yield` line, you could analyze the routes and store them in a way that's efficient to process requests. I think Aaron Patterson did that for [journey](https://github.com/rails/journey). Then you get type safety and performance, with only two type annotations (the block signature and the array type) :-)

**Comment by hugoabonizio** [comment]
Thank you guys, you're awesome! I'm not confortable with macros yet, but I can see that make this at compile time makes more sense. :)

**Comment by bcardiff** [comment]
This keeps coming once and again :-)

I've just created https://github.com/bcardiff/crystal-routing to experiment with a routing dsl for routing strings or http request.

I think there is enough value to have routing on it's own besides http routing. For example:
* how the dsl is able to play with routes orders/priority. 
* how to extract context information from patterns `/foo/:id` 

Really initial stages but worth the sharing I hope. And lots of macro ;-)

**Comment by jhass** [comment]
You can try something like

```cr
macro get(path, target)
  routes[path] = ->(request : Request) { {{target.split("#").first.capitalize.id}}Controller.new(request).{{target.split("#").last.id}} }
end
```

**Comment by Codcore** [comment]
@hugoabonizio You can look how I implemented Rails-like routing in Amethyst https://github.com/Codcore/Amethyst

**Comment by asterite** [comment]
@Codcore I believe the way you do it is by manually registering controllers in a big hash and then looking them up at runtime. It works, but I wouldn't say it's the "Crystal Way ®" to do things.

The good thing is that the way you did it can be probably evolved to something more efficient and type-safe.

**Comment by Codcore** [comment]
@asterite yes, I understand and will try to do this in "Crystal Way" :)

**Comment by asterite** [comment]
I don't think we'll implement this any time soon (we want to avoid dynamic aspects for now)
