### ISSUE TITLE
Empty typeof generated fails at runtime

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#951]
Just found this one while skipping through the submissions: http://carc.in/#/r/6if

**Comment by bcardiff** [comment]
The problem seems to be the expansion `%w()` http://play.crystal-lang.org/#/r/6pg

**Comment by jhass** [comment]
Oh, good catch

**Comment by bcardiff** [comment]
drilled down. `ArrayLiteral` does not keep the `klass` when there are no elements. But there no single type information assignment in the parser to an `ASTNode` (yet?).

https://github.com/manastech/crystal/blob/master/src/compiler/crystal/syntax/parser.cr#L1663

**Comment by asterite** [comment]
@bcardiff AWESOME!! Do you want to try to fix it? Shouldn't be terribly hard. A global String Path should be hardcoded in that array literal (or Symbol in the case of %i, but maybe we should remove that other feature). Of course add specs ;-)
