### ISSUE TITLE
Select public or private methods inside a macro

### ISSUE THREAD

**Issue by Codcore** [manastech/crystal#953]
Is there a way select all public or all private methods from ```@type.methods``` inside a macro ? For example
```crystal
macro public_methods
  {% public_methods = @type.methods.public.map(&.name.stringify) %} 
  {{ public_methods }}
end

**Comment by ysbaddaden** [comment]
No, we may only access these methods: https://github.com/manastech/crystal/blob/master/src/compiler/crystal/macros/methods.cr#L620

I agree it would be nice to access the `visibility` attribute of Def types.

**Comment by Codcore** [comment]
@ysbaddaden it would be good if someone implemented that. I don't have enough knowledge and experience for this. Maybe you could?

**Comment by asterite** [comment]
@Codcore @ysbaddaden We'll do. Ideally you should be able to reflect on all attributes of AST nodes, but we add them slowly as we need them.

**Comment by Codcore** [comment]
@asterite good news. But what is priority of ```visibility``` attribute for ```Defs```? Maybe leave this opened until it will be done?

**Comment by ysbaddaden** [comment]
OK, I'll try!

**Comment by Codcore** [comment]
@ysbaddaden oh, it would be cool :+1:

**Comment by bcardiff** [comment]
Probably it should be something similar to https://github.com/manastech/crystal/commit/1842ba1e2df9f71245484a0586bed2e3f0373c59 and https://github.com/manastech/crystal/commit/5bfee485b20f456aa9f8f0e7a367b72e95b730ee

Happy coding!

**Comment by asterite** [comment]
This is now implemented
