### ISSUE TITLE
Crash on, peculiar case, hinting towards need for compile phase changes

### ISSUE THREAD

**Issue by ozra** [manastech/crystal#962]
Oboy, took some time to find a small case, here we go: This crashes the compiler. Removing _either_ of the commented lines makes it compile.

```crystal
class ClsB(T) end   # forward declaration to make it compile

class ClsA
    @c :: ClsB(Int32)    # remove me and it compiles
    def initialize
        @c = ClsB(Int32).new
    end
end

class ClsB(T)
    @pos = 0i64    # or, remove me and it compiles
end

fooA = ClsA.new()
```

A range of bugs stumbled upon the last days hints further towards the compile phases having to be split up further, as also mentioned by @asterite in some other issues.

**Comment by asterite** [comment]
Thanks for these bug reports!

They are actually all related to instance variables specifiers/initializers for generic types. It's a bit more complicated than it seems.

The good thing is that the workaround is easy: don't use them for now, and initialize them in initialize.

**Comment by asterite** [comment]
I'm also not sure why you need the forward declaration, can't you declare ClsB before ClsA?

**Comment by asterite** [comment]
In any case, you are right that this is because of the order of the declarations: `ClsB(Int32)` is instantiated before `@pos` is defined, so that doesn't get initialized. With a two-phase type inference, one that declares classes and methods, and one that checks types, this would be solved, so I'll leave this issue for later.

**Comment by ozra** [comment]
Yeah, I realize most probably stem from the same reasons (they all arise in the same code base I'm working on), but I figure it's worth taking the time trying to reduce them to reports rather than not :)

I've defined classes mostly in an order which makes it natural (for my brain) to navigate them and read it much like a book index, which isn't always in dependency order (and there are also some mutual type recursions)

I've used the initializer workaround, so it ain't no show stopper :)
