### ISSUE TITLE
URI.parse do not allow for inheritance

### ISSUE THREAD

**Issue by luislavena** [manastech/crystal#964]
Use case: Extend `URI` to provide database-related responses, like extending with `database` to be extracted from `path` or other options (like `encoding` or `pool` from `query` options)

However, `URI.parse` explicitly does `URI.new`, making impossible to do perform the following:

```crystal
require "uri"

class MyURI < URI
  def database
    File.basename(@path)
  end
end

db_uri = MyURI.parse("scheme://server/db_name")
pp db_uri.database # => Error
```

Is there a particular reason to force `URI` from `parse`?

Reference:
https://github.com/manastech/crystal/blob/master/src/uri.cr#L87

Thank you.

**Comment by jhass** [comment]
Are the regular URI methods really useful for that usecase? Can't you use composition?

```cr
struct MyURI
  def self.parse(url)
    new URI.parse(url)
  end

  def initialize(@uri)
  end

  def database
    File.basename(@uri.path)
  end
end

**Comment by luislavena** [comment]
@jhass but that doesn't behave like URI, so I cannot do `.host` or `.userinfo` on it, unless using `method_missing` macro.

Wanted to know if there was a particular reason *why not* as I'm already using a workaround.

Thank you.

**Comment by jhass** [comment]
or you delegate those explicitly with the `delegate` macro.

**Comment by asterite** [comment]
I think this is one of the nice things about `new`: that it's virtual (unlike other languages). So we decided to do the change.

**Comment by luislavena** [comment]
@jhass thank you for the recommendations. I was more curious on the *why* than the workarounds.

@asterite thank you for the commit :heart: :heart: :heart:
