### ISSUE TITLE
Syntax error: can't reassign to constant

### ISSUE THREAD

**Issue by hugoabonizio** [manastech/crystal#974]
I'm trying to set a constant value with ||= to avoid reassignment (to have a default value)

```crystal
module M
  A = 1
  # ...
  A ||= 2
end
```
But it's resulting in a syntax error http://play.crystal-lang.org/#/r/6wn

**Comment by asterite** [comment]
Mmm... constants are constant. What's your use case again? I don't understand.

**Comment by hugoabonizio** [comment]
I want to access a constant that constains a path in a macro, but I have a relative path in spec/ folder and it's path have be different.

**Comment by hugoabonizio** [comment]
I was trying to use ENV vars, but seems I can't access them http://play.crystal-lang.org/#/r/6x4

**Comment by bcardiff** [comment]
@hugoabonizio not sure if I get the scenario, but you should be able to reopen classes for testing purposes and redefine some methods. https://github.com/manastech/webmock.cr does that to stub http requests.

**Comment by asterite** [comment]
@hugoabonizio `ENV["a"] = ...` will happen at runtime, the `env` you read in the macro happens at compile time. That will never work the way I think you expect it.

Instead of describing possible solutions to a problem you have, could you describe the problem?

**Comment by hugoabonizio** [comment]
I solved my problem setting a VIEWS_PATH in spec_helper.cr, but it would be nice to have an #ifndef condition or some way to know if a constant was setted before.

```
module M
  ifndef VIEWS_PATH
    VIEWS_PATH = "#{__DIR__}/views"
  endif
end
```

**Comment by jhass** [comment]
I gather this is a won't fix?

**Comment by asterite** [comment]
Yes, we can close this. A separate issue, if somebody wants to open it, is to check if a constant is defined at compile time (we could do this with a macro method). @jhass Thanks for all the cleanup you are doing!
