### ISSUE TITLE
\x support in String

### ISSUE THREAD

**Issue by chendo** [manastech/crystal#992]
Is there any particular reason why `\x` isn't supported in Strings? I use it to define byte arrays in Ruby and it took me a while to figure out that it wasn't working cause it's being parsed as is.

If not, I'm happy to have a crack at implementing it.

**Comment by Exilor** [comment]
Crystal uses ```\u``` instead of ```\x```. [Take a look at this](http://crystal-lang.org/docs/syntax_and_semantics/literals/string.html).

**Comment by jhass** [comment]
Well, not really instead. Strings are meant for a sequence of characters and not bytes as in Ruby. Byte sequences are better handled with Slice, StaticArray and the like.

**Comment by chendo** [comment]
@Exilor Yeah, I tried that as well, but just seems slightly more annoying than `\x` cause you need the brackets for 2 hex characters. It's minor, though.

**Comment by jhass** [comment]
I'd vote to close this as a won't fix. Supporting `\x` escapes in strings suggests that we recommend them for handling non-text data, like in Ruby, which is not true.

**Comment by asterite** [comment]
Yes, strings are for text.
