### ISSUE TITLE
Casting from byte array to Struct

### ISSUE THREAD

**Issue by chendo** [manastech/crystal#993]
It took me a while to figure out how to take a byte array and cast it to a C struct for the purposes of implementing a binary protocol.

This is what I've got so far, but it feels like there's a nicer way somewhere:

```
lib C
  @[Packed]
  struct Message
    msg_size : UInt16
    descriptor : UInt16
    source : UInt32
    target : UInt8[8]
    site : UInt8[6]
    options : UInt8
    sequence : UInt8
    at_time : UInt64
    type_id : UInt16
    _reserved : UInt16
  end
end

def decode(data)  
  ptr = Pointer(UInt8).malloc(36)
  data.each_with_index do |v, i|
    ptr[i] = v
  end
  msg_ptr = ptr as C::Message*
  msg_ptr.value
end

data = [0x25, 0x00, 0x00, 0x34, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0xcb, 0x00, 0x00, 0x00, 0x01].map { |i| i.to_u8 }
p decode(data) #=> C::Message(@msg_size=37, @descriptor=13312, @source=0, @target=[0, 0, 0, 0, 0, 0, 0, 0], @site=[0, 0, 0, 0, 0, 0], @options=0, @sequence=0, @at_time=0, @type_id=203, @_reserved=0)
```

Issues I ran into along the way:

* (resolved) Can't do `[0x25, ...] as UInt8` because `0x25` is still treated as a `Int32`
* I naively assumed `pointerof(Array(UInt8))` would give a raw byte array

Is there a better way to do this?

**Comment by Exilor** [comment]
You can do ```data = UInt8[0x25, ...]``` and you'll have an array of UInt8.

**Comment by chendo** [comment]
Oh cool, that helps. Thanks!

**Comment by Exilor** [comment]
Also in ```decode``` I think you could cast ```data```'s buffer directly instead of allocating more memory:
```crystal
(data.buffer as C::Message*).value
```

**Comment by chendo** [comment]
Awesome, I didn't know about `buffer`. That's pretty much all I need I think, thanks! Closing.
