### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by benoist** [manastech/crystal#998]
Hi,

I'm using the http client to perform some requests, but there is no option yet to make the request timeout after a certain amount of seconds.
I was looking at ruby's timeout function as a more general timeout mechanism but that implementation is done with threads and probably doesn't fit the crystal way.

I came up with something like this using channels

```crystal
class Timeout(T)
  class TimeoutException < Exception
  end

  def self.timeout(sec, &block: -> T)
    timeout = Channel(Bool).new
    result :: T
    spawn do
      sleep sec
      timeout.send true
    end

    spawn do
      result = block.call
      timeout.send false
    end

    if timeout.receive
      raise TimeoutException.new("Timeout after #{sec} seconds")
    else
      result
    end
  end
end
```

Which enables something like

```crystal
result = Timeout(Int32).timeout(5) do
  count = 0
  10.times do
    count += 1
    puts count
    sleep 1
  end
  count
end
puts result
```

However this doesn't work for jobs that are stuck doing calculations for example:

```crystal
result = Timeout(Int32).timeout(5) do
  count = 0
  loop do
    count += 1
  end
  count
end
puts result
```

Is there a way to make that case timeout as well or do we have to wait for the multiple event loops?

**Comment by jhass** [comment]
Stopping a blocking process of whatever kind concurrently from the outside is inherently flawed and unsafe, only the blocking process can unblock with leaving consistent state and no trash. For this reason for example Java deprecated `Thread.stop` the version after its introduction, Ruby's `Timeout` is [highly discouraged](http://blog.headius.com/2008/02/ruby-threadraise-threadkill-timeoutrb.html) too (Yes, that's 7 years old and still valid).

The proper way is to code your blocking processes in a way that they support an optional timeout. Pretty much all system level blocking operations I've seen either support a timeout or have a variant that does not block.

**Comment by benoist** [comment]
Yes I agree that its a bad idea to just kill the blocking process. The never ending counter is off course something flawed already.
For the project I'm working on now I'd only need to timeout a web request, how would I go about that? Because the Timeout class now only gives the ability to do something else after a given time, but doesn't actually stop the spawned block. This could lead to unlimited http connections waiting for a response that might never come and ultimately will never be used as the raised TimeoutException ignores any result from the block.

**Comment by jhass** [comment]
Yes, it needs support from the HTTP::Client lib to do properly.

**Comment by waj** [comment]
Every IO operation should have a timeout. We could do this either by call (adding a timeout parameter to IO#read and IO#write) or by IO instance.

**Comment by benoist** [comment]
I'm pretty stuck on this issue. Browsing through the code I get the feeling it might take some work to implement the timeout setting. Do you think there's a workaround that I can use in the mean time?

**Comment by bararchy** [comment]
Having read(4096, 5) when 5 is timeout in sec sounds amazing, also, IO.select has this implemented in Ruby
```ruby
IO.select(readable, writable, error, timeout)
```

**Comment by jpellerin** [comment]
If I wanted to start working on this, where would be a good place to begin?

**Comment by asterite** [comment]
@jpellerin The way we think we'll do it is:

* Allow setting a timeout when you create a TCPSocket. This is for the connection phase.
* Allow setting a timeout for IO operations. Because we are using libevent we probably need to tell it to notify us where there's data on the IO or when the timeout is reached, and in the later case raise an exception.

We have to sit down with @waj and code it (he believes maybe more things will be involved in this), but of course you could try to do it too :-)

**Comment by benoist** [comment]
Can we close this one or are there still parts missing?

**Comment by jhass** [comment]
If you consider your usecase fixed we can close it, yeah.

**Comment by rdp** [comment]
Was anything like this ever implemented (ability to set socket timeouts/keepalive's on HTTP client/Server?)
